sprite $Amazon_Aurora [150x150/16z] {
pDAr0O105C1GNBB_m5n7Wvuc4xmltBUNRNi89Gib2oKB9Gib2oKB9Gib2oKB9Gib2oKB9Gib2oKB9Gib2oKB9Gib2oKB9GibYmAiTGWbiIZ0MhlG7bsaYhAg
FL95MTKUgUBnf_ekbFHRHFQmfxFgAfmg3Ag3MJjHTXI7eJ0iovQryFxlErH8Hi1rY4-wwRh_xFjNh1BJsaKgxn8HDV-HjTOghRMr6rMcmlIkKaKlxi5xLAwr
qCTOx1-gjD9ifTa_KRaKEbIuIjQOwLZLlBRMRb79wUAnDxS0KyRcGBZAIvuQzRZAJV94ovqgesTjyljMPzggDwaILJhmEBKAiN2LqoC1d_B6s-6zILLfhNon
LRS7o-vHFL0UWRC4E5YWIcbDltjLCn4nCCs3ga3BSyWJ4ogkwhJctx4ghG4gy5ZL-8PbTAFgMzQ68c2QHrN47c12My24YghMAkJgXMvMvN0I4-NOSwygA-qp
R3SqF6mEJFEOoZbbBE-76PNz22rwxpqOeKpxk8hesdF1KEtIkD0-yRXFPQzdkrMQhtIFk5k5xHD5BDR6ggjf7bVbjLokrwxkfxFlMBWgruRA9nopYDhmclJC
rEvIPQvh1yj8bIm3LWn01PIgP0aHyIzH9QlzBbMaYdw9Abdr5wcILMXDVuSgMV2UVxyglEFxzFsgg5SJ5RxZn7Urqx6YhVwNL1fVLOwgJbliOClu39951kuJ
1-IMegfbeFgIrUZHyL0zf0ohbh6A9B2qqDRnK6qFKeLLoq05kWu3zU5yolRlAxXgEQcoflZYHOT_ZpzFhE2gvOSg9-FQBIxJbgIsKp6jzV-V3uQhbhCgj1od
O1sEWCVfkRgcQhlAytSBhafMFjixqp5cbbULEJtv0I1Lkh-H6NtlBAy6Rnnh1LkyKcLvk-GVmQgruNlGXEbZjVjvRZzzRUhWYsV9ZghCUkFBlIjpMOlmSlxY
AnXhsJLGPQOYZLzL4L6DSLP-lXqgn5hsZLHuurSM8zVMSkXlgFeG5Lw02N0vziSgRuawvjj9B8Qhbf4AVqMNHFsSJ0LNBP1gV3Ye-ENttAAmQlbQvK9RxNgk
NsEzNNN-rALNSiwNmTqgwvLcluTtUiLDvrKTKjdnBSqwTvTcB5CgXSPG1as33wusey9s7DfLDEQoHhjqNaKAx3NOmV9AXnnGKOkfL6G_aR9FBOrRt5hhZgZM
ciTiddEOpErdfIdsPCXgdpFv_iGK_toWk4Suh6h0ZYDCzNZFwzKpD2y_MBKOKyPjJ3DvJQcd_wnS3LxKunciMdyxs76QF6kd7KTFfwYEKUU7FwnQy_aTHmxZ
yP3Lyq1bg6hB-ioE8nwPro5BnzCWhDeQxZZNLzo8PUzkJrXrNCXCH0u_CDFiUYwGArG6gRAOptZjnSfR81V4KP0g0xyXvqdqFATNJrT8bM6gT72UqSin159b
kCfBNbh-SGY1L1ci2ijpo0by5wJA85K-vUlhJvQu3b9bi2huUTxAr6mxeuhlMB9N-NR1zyazu5hbjDOMb9MEupDUIpuZhXkfiktYH5dvsVY8BFChqwNAdgyn
bALqlgmhFVF0MCkWzffE49Rnpw40N4oIjLomgFaigpCbAaifnbg6TNfMph0XgT4pjj7oK6A-L0rotWzr5cFMUVQIyL3S0YXLevHFuvrqCukDPMOgmapPU7sS
NiEpL0spHlEL_lvPuG6Lgd6XSp1kTls_nr7MyYdljLoBzCChg0IQBrDPbyPyuh28-SIBaGDkmGfx18s1zMuLFfqshdQxAeix-w_PEH00000040Iml-yQHL1a
Ax8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6j0G
}

