sprite $Amazon_DynamoDB_light_bg [150x150/16z] {
xPk9akGe34I5Z43m__-xLyNYy6R9GqMJxTu9NXnprV5QicN8iVl_dCrcizbiDflDPhFPRBnOLaroabIp5M_z6QgftA6vVhDQpIepf5pxD-5PFY5xvrEIN50r
AtvIp5JbGYhVw9Io-Srfa5K6YTd8fcTVIki_0nzAjVyOghom_eFm3vqyfgz3vI_K-oHPOhGjBPL-z3F4bBu8axzedxKRMNreveMbahhoiDAFIfNZustjmUwp
BuxRFNpNMUcNIrKND12EbEJpfU8r48zVcouLiu5uLjbSgSWDn7CzrubIaHg8LlbKEqgRB1KsSB6LzPfaa0xp5fQArq2qwhseN53DPjLVGAaO3KIh-zr4WbAH
6eXMBp4LGGgKYjD0j1guQGfBHMuWMXKhVU3LJ5MXL743rK_MMUMu5b0gRE2LlCnAxhfmNoh30t7Hgg-X5POge82LBraXEwp-Wb9DxZ3MxIQAsdofRlN5MJil
V4dn0L-gjr-kOnptVIGf_D9aVVuSuqbXAR9FRWADBjMk0x3Cd6CrV55Pkicvf6h5Vv4pKAHmChnF8CtzxGznKAHmYaRhAttRxyAKmfoXveHMU7LXI-6LfjMi
DrQ7Y2XACNOJui7_cA30kveKaEBd3BYKyWafSiw0lKfqASmPxXa28CMnciy_QYZ5pHdc1xl3cShF6Mu7EqezaJFWOB-NukSCxjLXi8CKFMT0AWnsaABd30WC
TX-xVO2LCm073FOKBJtvESEWZC4-iHwcvmmus56gM0UuEGCETfGIj2Bd33ZOKIgm8kOCEDXH2gtuEGCEzaF6Rti9Zdbope0hzdoH2afCpHbmnOvIqZe1dxk_
vEK2KjW_Tiw0AtQGGYjApb3lLknZZpMae8Eid45pyM2mb_z89TmXyNE6uY_-VTbnbKe5jfEqd04PPzv5AlleltM0cZCC3xrATGzMGiIS0PUXxPGQiAsatTwP
ESwt83bYMUd4O7__EcLPpLm70obN2QtuEKDzBsLtx-Nd33Qam8bgTNyTRB37gbc4R9KLRkM5e_tmqx6SIgeqA-i5heC1RaUwt5qBLioS8Masyt_eBRZZLmjr
YjeNxeu6AtRE4AFPyVtyd24cgJcy_wcSGLJLh7hm_kToXlZzv9o1O4NE6VXMUCSlvWnpD7akPuZHntA66DUdSuRubeBs-1CAw2Jr-QSvS7tb_V4dNt1z1Iz_
v2aXozVr5PFmVeQ1CPweuZzzzloJUWhdnUDFDHeOFVu4QF_Ts6mscyrcizbiDflDvay
}

