sprite $Amazon_RDS_on_VMware_light_bg [150x150/16z] {
xPgBigii34P3J33a_T_tlphVs1wn1mtRdfciVRyOLe468lNl9qcI94cI94cI94cKtl6Bq3lgbw5vLlI3Lcab7eW4M8LhIU08IfnKZ9L4Qct1xbjvd1P21LWX
LfXKX1MYHKd5M25UZ5IK5I96I0LPXMWXGAGLeWP81LeXRe1Kd1KYLxz0XLIubSkzlfAtk548IS2buTIuI-TZjkh6QkRFioeNUgEmFgbM5-gor2VBiZxb0IzZ
siCRhx_q7wQXwKNDNdHDbwUq_c-uYFaX9WNfV3xDDpwlFdLVCzJgix1TWePK7zrP5I8ndq3bhHLOaJRlqcJNLpRfIRaMUXaqPALsg8HCzbe5bjK3QVnUhX8e
Ywu6jsQhBeK0-dc3BJvV2cBIRxARanlgCV1hF5WndL9WzVhOE3A9mmbMtgGhnhKPhDwyYjsNsbffdLtgginlGeiQhZoUdnOpVFLyx-m6tXxFSMuj8LBc7QiE
VIktWBbL8HLZ1QtgDoYG2hA2rjskKkzOYPyYlSRrPcSjtPb97nR2jcM1xWWiVfb-Zz36OU5WohJHxyLxLjQtsYWigjN-OLKLr3nzAvjlrUVSoYPPLQOJM6Rs
LUt-1Vie09RQJjgkzwou_nn4t6Qgp8m2JDJQXnufzx9xHMV5PL54lGvzOMwFNmUnYkcqFKFrKzP3A_jFYaCgz_N8YgGvw2mvXwf4BMOlkZYuK7c1xTTHMsIC
rt7bvU2WyWAL81LM39PwRyMf1IL022XzjLsjl9gMyDDYAqUrixVANIKn8rYj2tvl7WUcHFrSUHNMjRtcAo5S7enYHCOhBzicmAHxHSl5t5w8kFeacdLtNkUv
lKhpYOpUWVookxLXQI3-pdR9Ku214vCyNHevYLCwHPyvjQGFF7B2EzzAI6PQpN_bW33BGOop-FDVPS7OIysqWfGCRHBhFAjnAG8oosfOgj8ERlGFYBNx760r
BcNE1EAj1gM4SE0c4wt6f7Y_MLWdMerBuL-DPrcDI2s__AjCieBKjTry9Q8bFZCCIFdHJQLMrMEjEb81hGHOYN-XrPu_oogjz06hO9wtIgkqIgj1liqghPI6
KVz-aYH9aYH9aYH9akHl
}

