sprite $Amazon_RDS_light_bg [150x150/16z] {
xCv14aG04CNG6O2-_u4j8JlfilevGEhLhPHIIYcbb59AQTzGoNppZvNensP_yIeMrGUggPhQBWrMHPPl-caLMHxbL1DORQZflQh0QaELK87LXZ8giBfGIWLM
4qghoF8ehIBBexoAB8tIAiyYogiqYoYlujEZl8fNYsfMrQHK1tVceHin389XJ01Ztl-1UrM2HAi4-HBR7PzsnzqlDbZzlnDLjw177jJl_prgEo6o1oZPJw1g
lmOLHeG08ikFwgk4S07IpoXh13c5cws6e0EsfUWNPx7eYptPXQDRKMqT3Gv8sdaAR71WwzY_4wib27gJMGMyADhdPizNjIa8KbHLE_uZg2fGP58TYAf0kqH1
j1lfZDeaKHMWf9fA37SQdvG41vkhSZRHB0UZAcThDWA1dH0O4C6DkUf1PM-BJiZ9SRMruOdjuGs21OUvKKy_25uqBf1InE35QU-K4Tv3FPsUbH4kGD7JATZF
VFnS52SplGflCP8GYQicixaylTM96ofHbG8lhY9L7iKKcerLvMMYsYtGBJrObSkw_sI2Da7La-KIFhd-bNQ6W9rIRXfBaf3i2zSAdoI2vTvaLp8p9gD9x319
qAAzJKay3mwosWcnlAQprzjaoGkHukk4BnC58cdC9RmVqP0pLLLkAnFiwCwvgl5nPMPDjhmxtush-pbeEqsP4ClNxjnivsuEtgzNri7eUkKXFKMLr_Rsc_gW
Bz_qJsQ6VBxg30gPCL-PmCL1eMknQmGJPj5iRj_Paa-kNigIkNtuZkEWhmw1Lhqv9plEd7qmKX29TxoWEgFtGUTgTtOF9M2oEq-wCrYZ0Wc5r98xmwIRZBre
GdYgwBZLdDragCsyNvcZoanuGCogvioxNqLTzskxkfqctqMjW-GkEe7EXj-I6_BFNRPz5Lq4TRm2LFIqNGOSqDMrbk2WsJeKlxqkEU5roTsy4eOEo5QJNcjd
LQUFzktY260OY69ecFelEDSmnzPuz2hO--fVqHr-UFs6VufPML2Ab3bAlGCjdQ1L6BIWWzQ6q38JMh52Yrze7OqjoVdLFN-Xm5zpy9Sl_9LGDVoWIduJvrNy
1UZSjslPRgKVPYH9aYH96W4
}

