sprite $Amazon_DynamoDB_Items_light_bg [100x100/16z] {
xPZ50SGm4CJsFVttUnTcJioQCEfZakrEY6xbxlknCc1SBnpzuKg-PQYDGuR6k69e6ZSCpUE28N-CySmLexrsmbZ-roN3Cc78AMDswRfSkIsxooJQbhXl4vUG
HFkeunGwze6HQF0F6FW7_e5_6Fw1VwJgpcEi4F_0F_0F6FW7vGh_m3_mZ-JcaF4F_4Db-GV-WNymzi4_o1y
}

