sprite $Amazon_Timestream [150x150/16z] {
pCwn0G0H002nzZ_x3sm2AhXC47F_MT-2P4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMmRoT9Jclmc0O_XWaXDZ_Vaz2jrNs
ALS3SgW_Rm_NJoO5PV2oohbFitGrOKenuF-5c7EHJx5qfK8HVvUerEVDgoedp9MuFatdAYTII4JbScj9AJd702lBVfLoC13B7u_4aWqVosPL2Ryaaea1KN90
BybELJRIxDmwRcxUfggXctXndEREoZjKXgB5AM-kj4UL00HHTR0OhtY7ghnHLTN5AdYrGvK0LBKSrnPlKDbzoiSAGDgZOlMp4X3sgBBwMG707XNKpH9ikwwG
tAm08EvH-La1ErK8uc0ni5S5fBh8AX5RLHn-NBB0uXzJojjKHGczG7MALJ9wWUjEbTPqEeh-oH9A-2tNkbUbMZEiI5JCPacX774KgDRTgXudN8hl4iLt0UT2
bbgtgwoI0qP5achjLbc5KiHj8MOsqNxLJL8AlKinqxjYzxH_eXhtdIhzJfL-fqg_KwNVgTBlLEdtg9YewD7Ng290Uc7HDwcCLIXplIRvfuUgx5LflQlWfuUg
v5RfHXLaIPNZKQgTnV4Tcoh6ZwX2NL55MA6gBM0mLWtFLJrPLXcBSSI6-f0ALATLJB-5DulmAbFkB4E5eQgDL0cl0g_Fgu2Vs5wDF50bnZXGjO5A6BrSPrN6
CfInEggEQwqDL2hH5eLfbR5OrLZ5K1EgDb2fbcXhAfKPbR5OrLY6cbEraKgrP5Wn4fLIhyj5kL5fvVCuDTIagerKutVYo5Ht6QhmWgeDLEDtBTEVAZrG02-e
saXbrK8fXcLLHmamnsf7aofBIh7aT6-Nh4T2LaST0qB6yyfQL5qpbG3fGE5IiBcL0SogsaTK0PrrYpBMYgfzGjKjwK25yxb6ZRMaQXzG7IpJgTLP4iEggZrN
6IiPwjJiMRHT-u3AM8OwvLErvofZMLdqEYropckgzb1rmqg0g5LbPOfQZrKIvCnArqCs8tbKxQfYpxtzn4heYQ60v56rH_jWzsJzOHdAM88PLhlhhCAJAPew
Ilh_-DiCgzrsLgMdppXYrnYix56ramhP--niA6DPx50P2xqeEkh-96CeLJhgFbQVgXsgO6lNdEgS6ChY7vIgJzL-LIMYkyIXKf6xGodhEv-g7LEKqGii4wfX
rVPmdwhPRC_s7XlNeMe-dweTAgq4An9B_OXAVQfsg6nFXHLVPIBAyLNtHCmMZVL4PR28-xmgVQQoXEzfKLKSAls0oX9XUXLV9Nh5HLIrbib4rVAg_1KYrb4-
LLDt14GTvbErpIhrgTfcbVfKRRDAVQgsMQK-LTkiKf-gRLRfcegQdnLMLgHvLGAWRbPPMYTrMYK0efSbU5LrlbbLoszMTR4Abj_XdrLfn2jUPzLakwI3rQPO
WTTObMoJTB7QiEFR77MQ9HczeklDgfgzvyLrWYNspPUgdamrZ0DioP6_H7Jwbf0wCzKuIR1Y8XQfPuq8NRzHLTMVgIPIJfWh5tsMgUQIyJVrMFHvjQqcnMwi
Sp5cageVglbIbLCEpHPLqwtzr-mS200000080jZVTuqYAB8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaQm
}

