sprite $Amazon_Quantum_Ledger_Database_QLDB [150x150/16z] {
pCv10K1G042nA-iVM040_BS4ist-rhH3iYNPacn9jYHRaYt9bcHBiYNPacn9jYHRaYt9bcHBiYNPacn9jYHRaYt9bcHBiYNPacn9jboni6iVEgwiC1Z7Fmp6
ODx_VQy63H6Z2rdmMNBgNpNQabyQPOX43aGEhnoH3r5-cYgnTvZcV92FgyHZ8Hy_g4eF4dbcbhl8xCcPONQL4EvSY39-owSO27SkdbTb3zIyvD6FkoGur4WE
gwIHrWQ8zbhpKLL4DQMDSIlWoXzK2G3GLw_nq1MEgJ80yFue7m50JgcueNPP0e1EgHn0sjf-4TCX5G1H6mk0d5EnsbW0-9oArCIAPrKG2olXx2i8n7rMSiTL
27cJnS1v5LpSOGdXk2gWkZWligB3bJ-hakHGyr_3SlH0BUR3AjLuk-1yJ3efnU1mnpcVLzskHgEwF4utHaIOFNK_lqpdLRKS71PoNZH_IjNUDUwzY9DUVKxL
aiX4m3EYmFsY_kEgLfQxf8C-eBBqQwhqrrJftwNwf_gdqbzEnSn9zPGgw0_roPsN3CeLCVn9JGRPLECjJd8O5LKJXgMS8qQvz7qxBuTnIJ4f9uoZRzjvPKmI
cVw4fzvfPQwwO-sIuIUpgNJu4nuzBV9ULTwe-7RbpwlAN9KIeKQS7ofnQF5JnMYv-5G5j9migCfSzTXviJILe2lqAaPNx5KUNRAWAbFLyxZ4DPL7N-vKw7ET
Ag7FhwZAL5NBaN3bcmg0bngtsynDnLBphziUeAg8hv_GagfCLIq91EvKtC-MkEidp_wvUoh2igfCLNrsbTfKvTTK5RMhMlzNjSogyeizLwrVKrMMLEEH0HYE
3Bsg_SHjgigAQZoACiz6KK-NoZAAllfAbOmpZgf7LzfJbGNL-zdP3MTdrTtP-Tc2oh2IqLThAvaf2q0ye5ARgh40U6rzUeKyPM7uu1t6PSKaDUmcogYNYhvX
vwKQCShb7LLZON94dwv6krILGJhRlwQyhIfD1KGzKNvVcLHLheqxcxLdpymginI04Aeh95qfnOtBEJPL0P0q0ZTCz6rPWWFokahjgiS6Zq9COn1xGYrigDIk
keeUNKJ4hUvRVWQLsbMr7FtQaPTkgTIkQgKO2BCen6ovU6bJ5NsMKkH0NPwvZG8MbTfKHLUogzIcAeTLQbELmogrgSfXbTfKvR1ARQfoMAKsLJciqYsL51Ch
RwjqMUK0AYOM0yYwrwgA0KGBAm4WtMrHfG30-oo1xGnlJLK402ZliNA0zGXlJLKYha9UPsN6bLTJQwgIKFEonae1DLPZQwgY0QW5qSQQaXngbDJSWggMg5-s
Zrb9c1xNX-ojg6eve8iySqntaJay5ku-wG_ML0j9m48-wZVKL4lb66ZXgshVn2ex9Qchzav353ZEG7PMCQI7iwdEi_vhTWu4000000G1xE-xHX4KsOfiHROY
Mv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHRO6
}

