sprite $Amazon_DynamoDB_Item_light_bg [100x100/16z] {
xTX55i8040JHMVVz3ym6fv5vhuTOrGf9ykDMdKYj-iFt3OpwfNkZViaO6BeqPUYX4KFFnGsviePy6UEPC5ypXja2KuRRZJE69wec33-O0eOXHWsFv8nQoAZ3
6HWA6rhIMEHybJ_lQl7hHz-G8_BNypBVX-zBjdP_vP61-rqZf0oly8mJC0xqV8wnvdX_XS4xCWmC30mC30mC30mC30pUaM5qeXC
}

