sprite $Amazon_ElastiCache_For_Memcached_light_bg [100x100/16z] {
xTX9LWD130JHNCVz3ymEEf_Sb2orF5QiG3LyPcphVTlj6Cs8gKh6DdHzmM16S8C98Xg452VtZjnC65xYd7wRCdHinj0pZTKeiUbf1ZC61WmPW9ouqZ1aoj0j
GnSR2eQqCBoC8TpGXA6SOTTvGMeP_5FHi4Wawrw3P7K3yjMCn9V4AXXdjvzB3KEBwaOG4ahDKBA6eNIl_NdCVpzo390tuh_4fHCt0JKZKbWD8rFVI4jg698I
W9GqF9zocc-tqeONxxxMy8e6Xye6nuB1zGQlO1mHN8n36ePTmQb1nl2SZ4QujsVuEmysc3AOCdJ3yCd2IFp0oy3b0xTyY-U1J1hC6eSHimR1lDBucp5j88pi
6V66KuE6GJJ0HTlSVNdsT0fT0nve7CTwS-Fscor30XAFqDg_Wsj31MCRsqXKDvZPBJLUowWYD3Rc4I2tfuPuYSK2aa_bnWHl3F0QG8_IvxVR_G
}

