sprite $Amazon_ElastiCache_Cache_Node_light_bg [100x100/16z] {
xTf5TWDH44FH6cl_2yuaK3dFRAa3bcOVhzrCyq0QcNC0GKIHW4WX9Cnh5fM1BIX0444fXu0m1SO4KkEX5H8XzipdZNEmP3Aaxt-KzNluFdnSCKW8gyvYx5cN
WNeQWrmpAExwnutpX53lDaQItvWpnhYDFGMDbLLwob3QcB3n4Vlw48WrKSwGoI0Y2JFP3E4aOpXU0S75Y-6u2uJ6s0pMilvwQ0HIeqQD6eRKg56ZHeqQDMhK
g56ZHeqQl_6zMWs521toRZk0W30Z98xzPc8K2kW84LQ6oHFNqxm1
}

