sprite $Amazon_Aurora_light_bg [150x150/16z] {
xPhhclCg24OH0T7xl-2TRqxlRjfQ4xMTW-k_C-iHH4WjWrWi5el5Oh5OB1QBnS9vu_jPqKQPnhAQdrEqmHlVQP_0Dx9QLfvKXHceckToHLPLeGtTAFF8IPdk
mMB-_3EO9D13sFo9LYbIAq7pSwnqjqlCKO4mqoNHaLkpSifsoPFl704cmBbC9JDz42ILEcu8j3sbw8YN9em_5qoN2bRQoVAHNMKMYCQ9g6kPWz06UpcCqZ_o
lAqAvm-kpiigBwTW8kB1tNn_PLPO3RuThICv8crCiKhd3xZJ52lyQJbVvwPqyuvBxTpLEQL3nNLpoCi2JRR2DNZKQRuLMeOw6Kq3ux-Ew-PXbHbch2dVRsC4
kqJcSyzWASxqVpYg-aRvHtPtKs48VLmriwqsNAWTjbAUOhMHf54fr_ypklb-AsHE1TPqR3_whQ1sFTGmgtf-j3QxJxC2_aRpseocTe1L_rhSGlpjhFJRMj6t
iuhVqeffmx-R5IRBRsILC4z_8oiPzdtKEYSlAe3UiK5MwVoKIjUTF8-8uEbpOxju1Vh0-wtE_A5z5a5InsoMexKy0fhNowrwT_L1Ll1gTu8Ljgha8Plb12IL
5h850cXYDZu3goEi8dqIpKiL5yRk4gpugoOWJpkjIWe4M6-gPLTX0lAn5gMB4KeUO8Nlme2PzHDX3dI9PAn5VS6soQ0RnoLG8snO2ocxI34TTW-wCZr4x6hj
xbPEaEosmknrLutLyesPZ_UPfD3gigh_R1bLpRrUk_9rtRS-g_5N5YEtNc5baBgX9Q-n4aW1J1R4_dmh3_IFu1LXVR9LbdgNfmJdPrbbfNVauStF_YGhVEfA
fGBZCfXjvIOezCq_QBFwh1d7SKktXaO8D6zQEdHE-9WJ3WNmyJCEWVQpbUM45NBsS3YyUGqurBTBQS9LDOO3BoqKFYogTdIQa5nQoUXSjQ7uRmJnipDEj4Of
90ksgxPHdCvKKJamuoYJ866gESb8lpDMnRdwzclVfUxUrrWr2jPnE_kD6KVkpJXfLxhblbJix6Ho-unZMCxG0l2r4JEECJqasgv5XnP8A9cpPnnaN4qBuUFX
CuwhAd-Xgkxrli16IS6gxsMxxGi4G-g5tv3bSYACa7gL5NABBoBghxSgZ3inG-hLLeuOGl3bLiK-2xaZc2-tmkzT0V5xXHKc4QGJ3thibpi-Kdp52kVG0qmx
w4XEHad7PdLj5V0J3GVktt1hR2WTT7mxGJlcbS6a3pd-Aem9KW2c8p0wCecOt9i73K7jPjSUHzsRtUkzjE4zPH-9T-sTchlZjKnIPIPmUtn4HpCA5sedsFrQ
aSjOh4sCnMldfep7BOQwKIr0YcGVHFkhiBeLb-du6uVgVIpV3k7efOd5Oh5OB1QBnMAnM2p-0m
}

