sprite $Amazon_Redshift_light_bg [150x150/16z] {
xTlPhlCg38RX3uEDyVrVyAQh226qEqM2e5z-JjVGLyH9w6J_2EUSSyuvvvnpJeKJ4J0YIYnwLn1Jm1k1M3SN9S9NAEqgAodW1s57cCvJ59b51y8Svz_9-vf2
4hMNLCOb9RLr4j0aAVPHaU4FR1N2KypsjHpnHCMMm1CN-qb9U5guKj5-Lo8UQ46Ku27R9HaFicYfr2xIHOk5YkqoHhMcIkqoNLSbTfcigmfsMLXMTVrIM0Zh
gYgvUFZMLe7qmYrzPLL3OZ-G0Aoj8ZHHYdsXI4IpSDgDqL4IjJTK4g5ZMrXb9SqxKL6TSbJctMWgjhIg4iB_8i9W6iFLLPKAuKl4QhQygik9FXQbRDtogaup
9mh0B53YhDPihkhqGPX57wpPLhNkxxrAzRWg8LGaHrKbDEcWgeGk7LELCSYdL4LKRCQeuYbLBQfbdLIbLkatLLuL-u0TDUqnPpfgsXK3FQNA61tR0LLp5jj1
LHaF8HKxgQgVV2TL5LJfdYgjtenLkQEAXt6U1G1aDrGH6denwt935Q6Z5xE-lqema1UplhsAMetCYwKHJxgnwlM-Rjwms_QgUGT5h7CKqarLsQgCXf8KnK3l
gQ8sO9EepzcA-wiIAXAPegOzwEwgWW77-S3fJNSSGIUFIaaqLzd-AWj3LACt7y5MCBzJ4M-UTajzSWPtNnbilb0USHLbLFhXTQljLNrRDzCsMxQxIeKZAZde
rTf2QEoSAaMdvrG5TE6OAXxVTkDJgW8gRGSod5BLppr1TLALzgbNNwiFSnMAMGadpHNZ8SMppa73m5xpQ_luQHpIizvBLOx4wkyxxwxoAg_ATbbULqLs6Qsh
Ghw-L6kg4XwINSBjZnSj5eBQpqh07rkWu8dqueTOYwsWQ0BRrpYWKLkZq6_VIDBKaq35bX4CGfHYBnI90GEnfHYJG9Ja8SkVH1GmOLik4tv2sVR8T5fIKuG-
5acnEnHvzIdMHK7xEUUSSyuvvvnp_m4
}

