sprite $Amazon_ElastiCache [150x150/16z] {
pCwn0G0H002nzZ_x3sm2AhXC47F_MT-2P4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs1hTskYKX2eDXE2mX
y77_zpirdHQFZhGnqpZB-xFMfrRY4KnAz4BfeQhIAzLdAg5NAlyRLLdvbIzU5P6iOaaWluho6XOJULG8f9KLh49QQ0zLZRF26i1qAbrTrbesNbRraJFNfwhn
Jye0_QLwTLcpNiRqALRlYXE8A5ofvEgoPhqi4b6epQigzCcXCbp6pQsININO6ghzihO_cxGjmsLhLNYkAdvLNgCAH9JSgagVqk-hqhZGeIhwvVnzbIuSx52L
G5z5_BwgHTBueQeHQMs5geQ_DVM52hiAPjLWYKV53HRLg6ctgayvU5NGx2hOLDe2bNMmULarwstLLKsOKmn4Uo4cPcc7NbHLJe6cXSJrTLNDWMuBITvKbK36
GdbB9GVJrzTex-kBDd6jLEKTnD8m-nNijFnhgZfL9TAIt1sGbN7JvIhPLdlJSM8PXyXhLK5VF6vhMgPFORLg7EO_OhsX4ZnWbRTKLEsiIg-fA3SZY-abbPO4
jzL4j5QroOwh7AQraWADDiLgbHOYbxEjIc4L-LNTeU98TDPz5-XKP9Ugtwluf1BKHAQIG4wgr4ogVgCwjkaWTnDMo0N0K8sCgkvIwMIG8bqKqvWc_AhkKesg
28z418VygkvGMVAhjAcAQK_SAgXYBvbKVQQYtr7XfA9gKlN5AfnKObFrnIhuL7sgggTlUsmmryButRIjHwfkLH4L62k1XWe-LJ-epgbkFyh3RKrDu_KTCwkw
JQMbds6r9DBygZEhtQYqa5Zg1KZ6AEDLJLZv1rMcOp76p5_b62CTIp-eKZEgEdvENs69P2fm4rMDcgLkPXtNmSRndbG1d5NmgRf1fGcd2IsCKUQWqdogVgUg
X-SGOURu7VC-oCzKyAcwGMLege9FrHUhu5FrnIhuL7sn2ZvLNwo2JzNdgeG7fOaAFbMVgYXM6AkHPYeuL3CMQRcQJ8aqF6JrXopQ2dUmoe6sS9rFrQSgRQmh
fvfmej5S1P-gNweYQPgECKN-Z8-dmCQDCSkdwbUgsZ8PIsEIcUHJzSd_LKa6Kcd0ZGe-LRzMwMGUYEQZ33xTg-1JzObAgyASnboimumeoAY2JzKNh3Y7VAg-
M0MVgYzMmQVgYrNmgVfY5Nog_l1Ct8XjAdXKWnMViNGL233aK_N36LvO6cTuOScdKbOcBGjkaaHQWYsVQcTfaIiiEmTWpQTILZtkiiZCTIJ2d8-xB0JsV2fb
eKGo5WeUvLFrPxjtAfxcKtLirNAtqmcULELdAOrJZ4HxKNU5mPrFrR4uX-eTrX_Dpe400000W220_NtNA88YMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfi
HROYMv6jo5PaAx8LsOfiHROYMv6jo5PaQm
}

