sprite $Amazon_Neptune_light_bg [150x150/16z] {
xPkBZkig34KtEpQO-VyFlfKy2WaQTD9GIgx4Eky7rT80Zet3p_-KnMAnM2mMYyLYiLWip5J8W0E153MR9HI5G1jA_BPQt729BKvKcY-cE46AHZiGLKYSq6yw
KLF-QP2JybjU5ehHXQLinIpOk0K59sY-EYHhW3DgUOb_FD_y_4WV9oE_Kd70oFjat-Vt1diioOFcJ-QCRXC0yFvm0WYVjyABT7zumeinLjOHwiPPnOuTFCug
T2pBKLOzovqOQ0NcMx6E66RbQ4UYCSuAuTtdOC1eAqViSfWIE0EjCejOV4k9UPpLQJeG95gx0fA0qwIFjF9qgKxSDPQilKxRFI4RRFN21DVnDJZUoiM82z2L
nbiLJ1dG99HwOxnLZILLajWXgPfSQ99LcybMosfP9I4bphHg7rq4Uv2LOISznme77cCb_gZy_MMgLLsGLwNr_2hLrrD7QTrxV95QLjPJMiC_eGEYNP373gjE
hV27g7-ctIs1RqSLtQj8Qvm2ahVF0akrSgUM1rl_kiE-Ub3iJjsi__ZKO7Uj28SnlpFCQHrCEj8H1GNNsm2-Z4hiRWMnOAenTyLcOzLio-qs7QooQcx1_YU6
2SwGr0CRT_7Odi6o0xTFPNsHk8ISsb7nx_E_t6-r4oNWduJpte-DGDPjLJVRmeK6hpQqyYu-8CCrLU41KJLhX81OBtMaUTL4hPNDVdCNpgrnYbRoJfFFVPvg
LPOzguRqL2lNgiaJhTfQV89LBZb7SaDvW9KUyxFeSpZVwXGsNKkcMwKgG-27Odlkdi1GM-OlTorjmulDJetwhQlmxUzQoZdtjIXueGEi8Ez9EPAKVqKe-v3L
TIr3WpfG_FJnNe7qkwPiGuLKLLE_bSChNdj6NhGeuRHZw7_g0mN6w-TATaXCxP0e6ClswRHArTjwLwtoUGjiAgmEK_fYkrIP-RKPR6KDyLCvGnOSuQPgTh2p
5zLgTpr76b9zLkMbk3QXZWmkxQHziEGFzIOkDYsjYg9LADC0GCPqJ5BRZDKJfnvF0DgeLxki74ig3AW8JDNJkMtLFdZhpw-oxJGNIzjAyOlEx0BKLjYPRLK_
3qMcMoa0Fjig4ywJh1JEzDKUmvvuM421twznibiTptjf0aTyLyvxYpK3DSpJt_WbQkByjwEZBsipXIDFU9ESvoGLzeYtxZq0b9Wm_uP2LIwRMys-pT6mcdtp
fJ63qsy9rQkTZxXHLKU6-93RPoTXFkMcNiQ1_9XRZPaTpx-U6w3UzMeIsGnxpsUnM2mMYyLYiLWi5el_
}

