sprite $Amazon_DocumentDB_with_MongoDB_compatibility_light_bg [150x150/16z] {
xC6n00000C2WV_x04wa20000PizEb1laOI00hzUIaFl-x_iVED64APG6hD1hv-ZTVh5KOuqJugwgP4JLtA_qc11ReLfxkQXPnNwgjLUIYC-6zXgJLon2Ygfv
ZweAYKN4yqr4X6A-tNC54IONKd1BaUbjBoRXqjI5UhOeqnt6F1JcbESQM36dP5NnK372nSIUeXzPv080ae5gPrum0M2qAEhGphIa9QZggI98qlPG0DHJhwac
gSgfdsQI2lvsB8QajIAEiwROwH9KH_-H5AcgG_ke4_agWDCp7KKWMSKun_ZdbYbEMKnKwLGGC6ixvsZ1FSKrKnMT6vEChtZSb9WJHvzKLNJA8dqElCs5Q_D4
jcfE4-9pOIzplYgwfc0ZQvtdgkgfgeYhSDMpDVtagoBDtVIUoRtrRrvFqMpLTWpRiSjKYWyoVKaL_4ALRdE_bYh6jo-bYgE7NAeIla_V8EfqcKhmGUmg5P79
2fMCLC6ovy5jbVcxC5Z9y-2soZTw8LW9y-1XbLkm1gWm3LAz1Mk42jB6g6ui7w0ArrcLg6e5W3fk7gnsLXNXY7aG29X_6TNoAKAT_81AnglUcc2PFWkQtuxl
fE-eug5THgdcx5p3sOugekDKFH-DWtg1Aj8cvIgjhgkKNK1gIr95UZVndhd3LbK04E-q1DMHlLqMAlaYgh9GuOke42iaNqpLt_Ele_8lg0f0B9j_1PL7MyKz
rVKgm-FbedRYrIh7Sepl7mvGnReVKKrnH7zOBFWeLJbOGOaAnhA3moe8EzZjXblzuuFYurImWpk3F03Otn-eWfxQHQFPfx4gq4y-SThelRs7qzTw3jRD-y5z
LGWuMgNExVl1VHKMlf5xknL42jNyq5dK5ggK-y52Kdj8blkctK8rXmyg6JvDn7NopkG53rNFfDejwbcJLxFwf2f_7eo1i79r7hJBL15tLusu-pppavUgjlEa
wazblXsvIBMJFrL4i1zvcIfI6IcbS2Nrt_Rjc0W000P2s5J_bklYZo7H0O4oCrcn9elVPXsTBCcRrNtnK4ZU7CdpfNW9LO-gv7tMFFK2L-CDhqO0003W0G
}

