sprite $Amazon_DynamoDB [150x150/16z] {
pCwn0G0H002nzZ_x3sm2AhXC47F_MT-2P4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMGRmP9kUjmb0KP418slz-Nx-wbHE3
0MxTr_ERp9n87Y7k990Mbvo8OhY8H4VAND_HsZOgcS88IkLFrJQjIefXXPZAdsdfCdo47GuMdEKotQf4b7FcYvmIqQrYUC7sdUAHMLIb2-SZ0bw8LQMhBwL2
0-9zAxwK_g-vjIwLcxF_qAesJcCjVkP5A_eunRfw-Op61rNGgb-gwCTcMXH6vBUiSlX1NRsgEGn9RrcbJ-Lrm4QfGddBYcPMUY_L8SxzUvCthK9Tr3eFIm_t
VSygZeyjbAfC6eXOXJYlbfSAQ21WvLDqG5Cge860rSphAXNGGCZAELWVyL813SIiKhl9j7YfW0P2LbdvjlLrrBnKG0D1gtP3ZfHoBdmYFjYW1k9MglK83qJn
KY4DnArEkF_oAbugg86ubIESwTvC_weKR21kLN9HXpbd8hgNIlMnWSGNxraTFslHnqkbNQqoMxDmg_115ZOBQKYJdHJV-YHyc9JgP5whm6zjoBxzpPUm-GlZ
jTU4PCeoBvLhzOdTKk4lh-cHmh-fkYg5MybqZ-71km-J4brzFCT7hzmPzejIk1NFzYjkhB8g80LqqFShQKySRQrQhVDGUJDde2PLUoBvN5kKmYS3oKC2MVLE
l8R4iXG-HVjfBNL_YQ8dW1IIC_0H9rRvstK9I64vWt2YWTLnxblVjT9E88Fd3C8b7qIniP9mNnBzTZxaRIiINQCqlmCa9VP2pj1he8D8YHcUCxHyJYP0ghKo
F6SOp0LKogqCpHdwWxsz8gCWLhQJCuWwJuFTgIw5MDbkpY0h3NGfLSpAvZa3TN86_e8FzewKAcPb2pb32WFOvq9FIXMpihMSWPwiVB2tKe2MEKZEu1mVvw-3
NSv3LHtCoe2SmSdUm8wKDn6nif5Lygaz6UojLCbwWbdPB6UO3tRkI5rV06PbOCxW9qDFwh9IpCfcESDyiBiK-qMOrS6ihDENKwTGrX7YW_tNFjnVk30hwwzz
LOVuO6-acX9ZLlQGComjVArKkrzZLlQGCvHv0tDFYlK6PcMjrKcgapIYTgH2-qEObJtd38c73JobaakXMjPbb3DGAlLXi9yYXql56Fe31REoPZAC_jBfzx7Z
krGiAh5VBCMix3P5H_iLdOFznAKEzbygQmjcPTsS8SNGalpHuL9QdpOX1xEoMSxWiAfSKix4IZ4hkpvsqHlrwrzcddtsrTDvwA23MPbRaKuu7gGa3gmKixBJ
QdOFUWEfgLGStrQObPrMqtkGkrAIfp-BMPbR3RsoIpLEav_4hCojHlUWDD-KXwYpEkDMoTLYueUl_RYCfLnA56VTXwsobl4zw3H_nQeqirBSIhLG6pFKdwZm
3tBEv4VSIHUi5BRoUt2PiwLBLefR_HAZkOv_VijMYbcPNjHCSIH4dcwjMobcPRUSeTvpXa14EJEhisMbc9LvpZ01j5BCAdp0hUPiM9qr8ZFvwrQwOtK-YSqc
ESFacRZ4XfMS-vLvph23loPsjMpfUYRFvRUeCMoLUDtASuPTBTzbHBUrR0g7BrxxJe5rWsKhgxvVyR8M7m6GSYrRG2YuM16T8INvUHBTnAtcb1YSc7BL9sfE
yRRB85gsI3Tdg1TF-nMcPSjixbU95SMjrk35_OfS2KDi4-LCOwFiHZY6eBNt7w0fbwhlO23wL_clsJaG00000104iB_l6aLGP2ko5TcAR4Ms8bkHhSXMP2ko
5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSZM
}

