sprite $Amazon_DynamoDB_Attributes_light_bg [100x100/16z] {
xPWr0eL05CHUFVS_C1tkCAj9ynNIh8Lu0kWHJ_zVgWD7t67kY3ji7TkXPdHemkNG78z3Ir8uP71CTtOxfhSsnyRdSqGZ3jaSqsVpsFMFgpbLhYN-DN4hgM6F
yk-rdPvzS9G4_O63_g0_w8-WF-YFciPkTD4Vz0VzWOF-e3zmq1_qnrPHwJDa-eF-K5VzGN_G7_G7ZYV
}

