sprite $Amazon_ElastiCache_light_bg [150x150/16z] {
xTg7SeCm3CRnpx9aoth_z-rIreLh08Dz7VfrB-wVvIg0_HWXX11222644488WJ41spwAATgFhD8_KrLieDf_NLKRHDEHMv1jYD9t2rg2ApP0XKksLs4FCpF1
4pxsFVCjS-bVISKC2-tGzme-PEj50CWC2theUnb0EdYdFB_guFrLxrLgxlBLyU_zoAfgtNXC5G7WOrTLFh-A_SEH1RYUNwNTwtD9-49sVfLbe2kiuQADg38w
DFKbjI5LHWUcFZ5RgLhQLcMIUglCnbIv4LKR_T-g9IsIYV20A4jHMvXKfIKdV2lbejEhb1DM9TQPLOMmKIgpgZJX0R68FX1XmeDKfrJnFKZKlg5oJ-C9LGp7
rLPKXkFXLHLVPDVaKKPN4Jxmpd4sZQxog1q47sPKLTkXpgg2xjdGj2gmRIIOLELORPKoCBRgkWtS9AxjvMgLS7FVojWgbqYAFhKrBPAzQ6gL49xG3PwGZAeg
JrLgojY4rVIfYkrWrSjfiZBX9UBwOaj3gfoAfos3HCrDhhfJrI9NgcfkVjMAuLM2EprKXKTyh0fZgj1-P9MUNbL_H9K-tKV9Tg3blNrC5L1iev9mRjMItggG
oeuchyB2kLKkbsOlj9BXpgjgArKkPQbg2we-ofnUPVoYYfTp3CiNNiuo-KKLsqcyhX0seMBgLMDvbLbR3oDHivbLJYNJDq5PrDpiAjUqYWXTYDm7-UbLA_vC
LLH5LROTU5OLI6sZHfXIvNXJbp8mgygbjJ0j1CojSbcqcIqrbGmthuhmoCUOeX-g3pDuHBEgj34suZPrlIePgtAPkegk7o1CFihCht9QHV9jBlPXfchynucg
g1gY_qZSIFr7BKVgFy8xKF_Hy87wpnmOgFyiYu6wpqWPglFidS4wptGQh_-ii9ylX112226444888Rm3
}

