sprite $Amazon_DocumentDB_with_MongoDB_compatibility [150x150/16z] {
pCv10K1G042nA-iVM040_BS4ist-rhH3iYNPacn9jYHRaYt9bcHBiYNPacn9jYHRaYt9bcHBiYNPacn9jYHRaYt9bcHBikLMQs7UJfSR1s40ZWk1qC7xl-_Q
ONoHj1YDsVJ_URVzvI9MDMOcIdYK4Z4_oBB192U4dyAKvH7Ma8WYz8iFo0P80UuMwF-eEC8bn4H4N4jBY70fydGL8-o5IAoVFubCCPpWCbMbwH1bxHqGES9M
cgYI0BKeBLSxi31D9V0gP1qvJXEy2Z97fV2Ax6FQSuKvgbWVijamYuF_lNNdgGhg-qvyiMQe29RKpCLYMCeJL140afcJzVhV4rG10ABvM5KL9wc2ULcmX9DK
m4vMXadF5SAQU5WL1McQ2iZ1IZ1R1SY3B0umMrLT0woC09DL2BMGv1PBKe0QJbGHXzC5blpAaXnXAt2QgJ8ZE8MKMQrDE1F2KSYgarLcEK0JBj4QBa4JBgRf
gZLD0UuLI5JdgxOqnz0JdST1JYdnP5LDcI9-z60Y3y6lUa-OCsrbPZ5JX1yAQPQg7y7FqPzKGVwJAk0lgiZMFbuzV5tLikhuzdMLVPh1uZTL6l6zxOJzcYew
FehpLGW3BBygEbHkbdyUxAk8tmeTbcCU75Nn-oSH0I1rM8vvqA6oHiMvifvH0JjLrgYqmnfJGLIVoXfLPG5tLAMlgYLrgUoiYYcbUEUOB-NsF1YpEbHsg8wm
gohzUH2s8icmodogqbEP9ZX2OXbILLOSLPMUoghh72AjCJEj8KghQba9Q-6kglHKTUg2tw96rR2EqcrLwQigBFXKvbELlggcJFYH5Z-gb11j3P5aN5MwglPF
7KIuHKHPFgaKbcmDbcHSLJegrzaUBwheK9K9gd1HWKTLdbV1ljg8RbMPeh9Nx5ULXrNIg4oNQ5XLdbNHwVgwNZtwLEL9bS1IkkwfVAhod2fVhgwfdWtcKvMd
L09hwRh0ZcO-LNdR3_fKt6o02DROgogDAlXKbc1DBaDSKBUgDDVjsQSoEZzPULlskrNbgeBiKrayFTDOdocdgjRk1tsgUdJMwgDpgshjVb3StpZDCLzLvbEL
pdvmLCMDodogiglYiH_qgD3MGgiodwfiAXA47PPrL0MDRrEPJrKsrNKF5v2okAv5yrLbFbKvxmSHhWL4f1eYXltGlgWqd5JH6fNvLELGcKaA_NaGk9cycAXQ
YErDPJvLUTiFZgdQMfNvLFVtWz6oGsLFg8v4X8wOLqUEY3AeChzgf56L_KsL_JSLyS_5LcK-LHbKzMfLvbELoIfpgOPO4Vf5Q_AeXbWQSIkiuNjHhMr85G4W
bJLp50S-AoCgWYLricHW534RK6bzRxfOTTkivc2LJkd5KWTBNgXazxklCdX5eombM0jg7bRffPKLibNMWAcYFApIJH5gIKePko45rGQxhIgMZc62hLTEi4Ks
tg7g9dYzQ-hdkwq2xA6QfqFLJpxT9PIbHaJlTmc9EQkgcsb6k1kIch-g6e15wDIiNBsiCjZlT-fH8tAcnPK84U4H4OdOSnLVDhT_pSw10000080WWFrzroY2
8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bi3
}

