sprite $Amazon_ElastiCache_For_Redis_light_bg [100x100/16z] {
xTX9ZjjW34JXMjVz3vmjWmVGrJz5ZtghM27qUQI4rkTsT-VLG6nqPDo6hW-65mGOtY1e68b7_dheVpCo70tnKzQMeTgEeLSQZmu5Goypl6Eu0jSRAfELM32m
hourP1gwsX0C1GRg3EvsRHZAZERs1TB8SDFCA8SO7PqQ3ZitxBmp8tbBQWU6Izczyi3GWyuD285oPYXiO2ZkjQ_ZzPy7c0R83TwkzWw7mAK6AQE14JGqOacv
8Tu6AG1uCwB6Q2wVgBim7nYqLCiDbuvtYMimVBtXNpBSN5L1f0PEsUqc3fTeqCRPWjs5gSZW68zE31xODxWxDutw8332BxnQeundSSd1m3b7HWcl8p5kmzuo
aAO6JjCJHmPEr18ZmwR1LpWnkAFuljXpW_iAyeA1VouR6XkI-J68tlWt-CZu_9teLKER1Xv-XX4qDRmpBGt-bd6AU3QORwp1J83KWl-S88p4ig9PAm0R03DA
tz_TtJy
}

