sprite $Amazon_RDS [150x150/16z] {
pCwn0G0H002nzZ_x3sm2AhXC47F_MT-2P4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIhK6SVM3dZi9W6AQ9yh7_zKvJugD_m38M
9FSzzLO_SG6CSLijGx_2KbNanh31ScEfJTDKxbw5GohNvXbL-5bLCwhmiwhsf8gddiGYyZigdMKlkcsLphAZxAgeihPGqQw2pjf1jGtL3aj7RQdiB1srfRAp
TDIUoipIKPigAqj7xQliB1srhzfdITI-oixIKVkgVPP47LJjiv907LGXiih8AeoogFGYe-oiEAot3gWG6MLbfROUJjLAQSREgmfH24uKGgBo9rKvUNUJJ_MF
g6eIYDCms6hHBPH-LrNbZHGfyoP4-QTCCOZpLUmgEohcEXiWQhvEvI-g-9YXQEDM3kp-FHLVdAVXjCYJbSkFg5hsKQeOfRAoK7ddoQpIdxacL0fBefmyRx7O
LFeuaANAXTmKLlPEg9BZmffhqSJ5OG-2wdmQYewJAYxM8ogw1Xzgbqha8r4kNsMYuATxLFdwxRIlQi6vOHnmBsfN9GvZgr5L9YPMDV8wnzEmtgpVhhoboi8q
hfuhXJjIe3fT1PUmT1LNKAIiwMkc6BpWX4XVqv1GYSWjZFdFg52XgBIcgbRvPo2ZgZAgmQg2K8tlXjcc2kwV4d1I9Lac5SapjQyQMScYSkEnXzbPhzogcjTF
LbTlzQo0CnxAodKg-WtVkxAoyvWdPg2xhXa6zoShAAeRbkTRVPeOBCjCLiJm2cPDXorDrL_VEqxcGo8gNn6bu9qCSrPvLFMx8rTDfITLiAcwuLorl38ximes
LNz_Nm5e59NP-MDSUtrVSQ-VGN2jK0h1Vsn-v3h-lTVF8FTsl8BiMOztuzMLEhRlgp2ExNL1rQVpu3aLNio3NRIpPbZHhwyPkcowlhev6k4n-hz-UNtL5LRc
SQTELIusgDKutfchQz7-sUgwdLtv5iQlMOCAY-lsli8ATQhYwRaE8fwSfwgwzexJTLPrCvVxp8UGY9C3wgXQVX_i3oo4YUlwzAyNFbNNHVMrBQXqLhvEIPOg
jEGVjf0XL68of_POVsOXpVPamDDpc8fuhqQev9uCJAgHrTAuVuNlQY5AWUC58BYPYlS6RAgEkSi-jjVlyyJPL1rZEIIx2lxpvSEcwez7QtYi2bMk-CYcwhQT
RLdnsZdLLHPMkkvSnHJKBzKwgvjOxgkKAoQ9BoOL5bOtiMhu-Bf4vOe-lovLA2ag6mkqzYKEQehAo6haRIQPJTMXLLEudmKBLhAfEXwgUVWQJYH4DbRVO-rd
KKbMIjYefXUilinApcsmwls0-aRb_kbYCOfPLXIpPZEtJTKPjQFYVnxdAjXKNQ2CHS4QLB2f96gVDQfWK2ae6sjKuOrAHzbPemhhAWMroHfLM5P9LEz7MQCA
oog9EimQLLXKITHHrbo5DPL07MRDLLXI2THfrbo55PL07MVDLLXG2THnreqAkcf4dMTXbgeQKUTPcAQhndPORXBcsLJzXrMmgVeFgt2h8atLZwZelQgZ3lKD
LXbgK5J6y9FztUmS200000080jZVTuqYAB8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6joDO
}

