sprite $Amazon_Quantum_Ledger_Database_QLDB_light_bg [150x150/16z] {
xTk9ZkCm281XZ05Ztl-1Tv8DagicFJmbaqfykdRd_1FtSeUOIocbb59AAQMKKahQc10Hm1L4Oj6_2n92E5Ggdv_M25vGnSxJ2GPOcKKtmanOnh1cfr243PBe
uSqDOLF4ulbvelOqdyfMhnPBtriN9LY9HH9OKBVNCIp8uZJuWNrYpIEpu0TF7enQ49wzXIW0e0Kf03X_F3rk0TlyjsfS5Sz_gyHLLPiYaLMpIzWXT0Nd3bbB
U1NGnF95Lasz2524y2g2HU5khn641SLMgHzwbUTXGl2VM72LcHHVIHAr0xqHmeRDegjyMHmYSrFLBKPLcUkuvs6pCweMdH1UKCXJegjSbyTbfVhwdbRbL1Zl
sX29rTp9LQEkpjm5gWRVNPLLMPLLMSNCFQwAx7AEzkMwO-epK_QtE5fWZvWfx58pWJtOFxVpAh2l6nom3llmOpkl3WTKuO0o79YikZzTkdlFz2gxirMXEQVp
LGmhxf5Lypilb7vJrGeulgrYS4LkgmXSKQ_woCxBgnG6D5On36IigZ3GNrQPjGeUvbKLHcCLZCfGrM5KVrcrw8Amg5u505LNulyNyIhM5Vd_XG1m_SQcg-h_
dwzoZH1ugEBngs0pVjDuxcuh-4DLxlTLMUNkgroUgujK7Jyo01myCWnLeYiCg3fu51KvUXGbl7yKfO2gLvznMjmpZdlnsLdAysTdL0ke-kDNCdB9gchkKg-G
xKw1VNRYRW8ZTrusmpTjbzkbBkHoE_eoEVcYge5L3OS_EZodSj8xHGAmXRMdCre5e9zJPSRmRDIfAnF2YiwfMaY50I8oEq8iuCwiMdGFE-IBV6BLyt539Eb_
zxwegZ3Xe38tpVUGiogh0cJLDqxGnKyRVlzaPlmKw_TF_CPFHt__97dyrFttNw4GVpM7Nl3AbxnAwCDNLAMKKaeffPHIIYcbVm
}

