sprite $Amazon_Redshift_Dense_Compute_Node_light_bg [100x100/16z] {
xTat6iCm34DXphZ_WREavtrqWv0cRAw_koMg1cP6b00n3SpBBZ_Gc8OIXXA6b32KC9Gmf8IXWKOv4N7W-N8JAXiYDOO7KMTu52qPekmYy2lbCPwtSHWiw7cE
mG0248V1wuC19xQHuDaEGq0WmiPUWg-MzXeW82AfCxGj_BJw34Q-tP2qnTZ-euLzUmszfBm6vv3Htu7RJ5YAnikjuqcOkyVWLW00jxbkexrDoyPbcotzcHr6
jKOj60NfZGAZHMg3eT9wew96ZJEg8T96_bfLbU-UvvzTVizbV0TlWKdVjuHxBTvleaGpRD_svdOv_b5z-d_jM2FVzacquS9jqTbkxubKNotVvyptdVCrW7mj
ew_9f6fB-HfPljQNg5a6Qg_P6dA-5fwlwUV79jYuvIV6YdvZxEudnb9_UVny6fHfS4OQCoS
}

