sprite $Amazon_Redshift [150x150/16z] {
pCwn0G0H002nzZ_x3sm2AhXC47F_MT-2P4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMqRozvhYjms0O9dMZIEv_lqUeVGXD
4gVsXn6gz-zKweE4lhO3f96qKbAY7wMKInF52nN0afAOliIfI4TPXjGBqwsu2CJ2IRGGPW-JrodAfJIPQgNarp_J01Leubn5BvEQUNB9EfMM-6jowpV6e-LO
KFeYbNAGxf-tMg8ZxajKIaUrFpkTza97VOMAZyz9dv_b-_5vyG9L8nerxE9pBAw_hs8QTVIQA3JYtrVHgEANwaAZDIenc2NhLCrWLbsdOeLPl4v5t35MPrgc
Wh_4HhHMHKcUiYJHEbN4JH-m6XEjLV5qot23DTyqy3gLLegujFwD9IqpHKNNgSnwfZdEjOhe3vP8BGSeobrNgaPQcJwM4dsCguuMgqQzygDdYTMgIAKa-akf
D8sMgwBUQavCRt7AfNKT_GDLr6NKQcqo2is_LisfxgYoFLKpIsGRbVsu07BRGHMiJ6Tv4vK5AbWxg4mRJRLDL9PfLCu7hhoBwdnKFbaxgKH7ieDgVrME4yHM
qvvRIrjDkz2KxAAoIb7HnIg4LNKZLJiVWhe2Ab-bokS2XLI-HjLfL6o4gTnmbOZqBsDr_0nJEQQAWQvNBtUJ7M4gXrJATCRwUTQRdM4gHrI9edGnwn6cykUg
HbFjOjOZJEMFLKoZUWuNcqMIwQZR5ARofweJTR8iAlH_zYDCvO1AuaASgkY9Yiflg1nNnTi_5PeIN3NrM9McOt4gop5R6LVDFL5b6d6j_8wA7_-EoX-ebARg
G4GzljV-kXvJ-NsLjP-dAss5ft7gD7fVZwdylifuGXsfVFy6pGnJ-MrLFqYfwjjJHB-OTXjXAh-Z2e1-VOhuk1vJ-ODfppRt_ImQwp6LtrBL-3GkMELoFQRo
krVdP1ywPqg-hCTKVgsA5-rny27t_PZAl-sgYSuCLHccykjTEqKTLXccyijTcI9MM6MOoYzshVC_krLSPPZAF-_ADEhd5yc0Ai9K_d7NEFOQZH1LXAdyIjLZ
wZkYYZ2LB_gi8apbd-UArKmPdQivJEKNns39y37uCqpbRxlIbC6g25FvYdFx7ARorrrxEaof6woQmrJ-jcklETKmeQe8K_dNNN5LXAbyiSembIzM6QRonIh3
LBvOPRXA3EhULHDM9ODBeReCLU4VLhjpWG9K9HuzWMukVgvo-XDtUvpotMlvSvKISFcRBfkaTflbz-jqnjLkLvZEnExqMEMQA62bF_ijfwHshr3Thz4KvwQN
UzVCD5NjTg5wKAMNEANIsaZQdqfAimSuSW6LkoHwL6hsi52jWWqIa3gKcRRqLr5L0tEKDHgqylb_iPOM82W7iwNvbYpVakLRidnBbc_9yYrPlYNBjsJvbYpV
akLRidnBbc_9yYrPlYNBjsJvbYpVakLRidnBbc_9yYrPlYNBjsJz1m
}

