sprite $Amazon_Neptune [150x150/16z] {
pCv70O1G042XwvV-WItWdey4M3UzQsoGR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TboofYPjnDrHraO0CD980J2_L_llr1B
UkXGCADzpZVx_awr8E8HZaG8Bo5HZ2BNilP1710-X86lecsgIWgmLKZNi7ITaRu6qqM5XmD5aLbUuXXfEBJnJjLe8avvzaxCAPB3vL89mX5oNWyG4kttosqg
DjBkk9KxZ6zI1MXHEZUS9e9Mk4MLe9NEZ_BFFtc3gXp_OTVaytYPy_Mgs53QShBYzIe40FHFrUsFNw-2_nArFEVMNIetI-vJ9TtfswyL5ZSBxrFvMGXtgVoi
Z72VgiNdMH7WRXKWbrCiHhXJPGNPPDcbz8sgGWPBPSLw9L6-JwMQS5Z5J4JoOmM4gPGxLTtL8uhCIOuISoI28pFTgchbSskSNChzgfP4X8qmIcdThx9JX_03
YDf9LxweiaIOYGXwHCISnF1VK3dwdIhzdIhzdIhzdIhzg4g1AAJlgQovIX1QADzNwKmbq4lVL-b41IzzMMLNGcEnSUBnpIzGsOhQlkDTfRhBfXeEOBBbeayL
rL-QgSIMrZuLPFLNy8xNwWAMbY4yNYm1_tdbExMuho95HnP3upGSi5y5LFHK22tKriX2w66PLwUgNiow7uzhxjaeYl99LJ-egD__BxePzFHe74LtxZ3NMZ-C
eX6WmqGNIJaccX0ErSZAZnSfnfJBIbNdAiq45isMgKKu4e2Cgf55VRmgQrMTgrHpX9wj7wnWAvyq7C6HbROt1sfhgcebWgt2wzaE_CPg_BolgXDLB-qiKx6F
3Aqqi7Z_7dmzMgYMorIAAMkB9wniWzIsgYvLjaoDz59W5j6nyCwY4tixjJTHEHfPMQHeUamKUrNhIfMnqkCxU6g_gRvqgKgfQtfS7AfwgQeWZ6MNgcwf_2pq
gUgLAitGYgBFRT_eKzMBL3PoONxTCCu-LRrELVgMYx62-bJrCfKCLzZqc9HygcggyjS74CTD_wpgKzLXrt8p2SFcIXYsqylpjVEfwbE5kb-4rdDfcrEqovbn
EUvIDPRz2vkeNX0cE2ArSbUfJrKFrJPBO58P1Wfzv5FLGmMOz-VY819WA0u3XHxvL1MUqOwheJglXH7xEyQkhmpfKrcKjbJI3oK6bdvOkTYZNAYMMoKT5j9Q
bRkgzEFQ2XoRgS4jhqer3bVcUqTmSjKmZdzkbPR3PGjLplb5bqN4plOSEgzLmWpLygbg-wECy34SHmRvuwE18UjRFbNLLeu4GwCY3eE1bHddZvVvL5MVoLn6
mumpNdFGEFMmJKO-LNrxE1fX24c6sVcJQhpnvbCPoogvLtHifHfllFbKLLtDLT3JbazLhr3PQF5-YykdgcwL7JBwe5AVgbweoWGzaxfKzJ8LWyNQywcg-bK9
-uM7u30dz4weYfzLdggCNT4Vk8dzNMdjgwIwMNAe2lGMbv5RAWG0gZwMBKaLOIpff1rLR2-rbnME6J4r28immF8Xy0rLEMvMUrWbFDSts2zIyyOMsbfL4xJI
ULRwkId0uy9hpQhp8hGedMFrZr0OTgzbGwLhLKtsnEWkoovSMJqgNQkgZJN4PStAjfB7Hja_WjPQLPN18fOoOnKnqR46RD7FivrqdQbsNFPWPiel9Niqyytq
DZ8atMFLTMS_-cmSJItKhPfgdQRW8eqpJj6zIjsjfCaYPx6qBlOEABfRFLN9V_e8KEQSbmCO9TslEjDR-xVPEH00000040Iml-yQHL1aAx8LsOfiHROYMv6j
o5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6joDO
}

