sprite $Amazon_DynamoDB_Attribute_light_bg [100x100/16z] {
xTWt4iD034DHrBZ_WTqu6mux0yhfer9-ogAebH0lPNtvTGD3h-JSq2lv1yE7Z1c-o8JXwzGDftGDvtICQoAC5eryTMf6kc5d32aX7ICJqeYHaO8HY2qDbGtz
dO7XDndk6PeqjdzVEHB-ckz7HZnZf19YWxhas-ghZAXeP6MeRWz2pyZ1-DF_SunF3lqh37fa61WO61WO61WO61WO6FJ8C5P2TW
}

