sprite $Amazon_Timestream_light_bg [150x150/16z] {
xTk9RgGm381XnzYEoVi_y2vW4DEWJcP2GYhvrx7tzkDG1cf8Vp_FyppFyppFyppFqtFFQo8J1lWP8h7EpuWOuVScqTGrcQ0iYgbJUYBXnA8wlvvZhuULvjG-
2R0LIFGtEnzurDGsHLX3ATa3Ig77_Y9O2WUf10PhCJKBDrFwB8ObQegIRtSnjJjyEATlYiqEeYwecdyCgK5JrVyRxU3V7G1mtKb9RLInxgmCu-shqER4WggD
dQ7PlWAgMkkmXQg6XT1I1QZVBGlDL1RDNrrdX6QgY9jBKtdxl-5cAasSNLuLNSU4c5ggqap7fUWRcSe45gVKLcKk2raqjwao8LXsFTPKTNsBWqiJurA0Sy7E
mTOgAnB2kv0rMJrKbehHiWBQ3L1_bQKQUOcGUEcuFNnELPwhNEKgLmcpZgT20FuBAcMMzDhCMvKghb1TfB1LgPg6L85-f2BSczAQu98SAiHRLE4Z5S8HhYZO
ahHtWsfDlrC16kg5XN2J2hXS9MpXmbfHn6GiGuLwrMHt1n-VxNZQIRB_PBKg8bQgLBBRvp9LmWDbhBYXRbb5JrC0BLHPQAYTfHcgGfNCPHEJSbN21ML9XgfL
sMswXNWnNT8hLOeDlfrbgg9975-gCfJ6crHbKqiorHiKWDohikRh2U-KgtBK362iQbNfDDnKIgTTUuIdfLuK4VjUNoa0lLuUv1-B301zLG6CTOaoLdVLQg4T
XKTJikG9rSwQJVSpnV20wc1HZhBZ-eZgO54QI7MmZaZpUvpEgfn5h_-9_RotIeEUMVHwaIr0DwZacxFTM8Owi-B1xNe_Q9wTHM1fTd1hL52pYjAAKZglg9Ki
KqsrdpXgU-mSDPXQ5dyw6ofdIRUfPNubOwWbOMioL9qgb4ujJNLE3NKg6ghRr39N9TMhloLthA82Qq6qGFK-b9lMzdngMQvgERNaR6hvk6ejKZwr96OcHDmy
2ALXdwbbXQhfr19JqiTKbkgwAcwZv__9kWJCMjgZ4nDb5f_ZvBdALQuQz2dMyP_u7V_fwF6V91__gVlsRoWqVvk3Azxc6EdDbr7V4Xh_ZQhntpuR_qszyTzg
h4zFLMX6p_Cyp_Cyp_Cyp_F-0G
}

