sprite $Amazon_Redshift_Dense_Storage_Node_light_bg [100x100/16z] {
xTataiH034DHnhZ_WJSSzyKgiY2iQsHZf2VRXbqtvaIK074CpCSkVw1n32KC9GmfOIXXA6582KCt6kL4n74-NxeoR8WkKov4dU5HrEJw3oi2MocFyRwDms11
sDpk3IO0iHZyVp3Wn8O4V-qm10GYR6m9lbhQ6Y0W8gapD0i_hJw3aTzkI9eOyuuMzkqr922S1cTbq8_TO05-HOD-UbRu_cuDVda1U7oxCdHj37fwCXutZtfJ
ldaBenu6FhkzKP3M41WzKWD3LprsKRR60naODJJu_QWEgR5H0UFnkFgl5H-x_vx3xyvd5-w1yntazag6jYJR9dBJxcdR-_xRsKTn9dsjtyYFVH9ZkF1Oz8pR
Uo8oLqlCEPDpvtmD85_BoDTa644YNoFBr_eIDSj0xJLRGyxNmlCr_VpQ11kF_8creh-nTlSdrbB_ylhvCIZ7uDnfd7m1
}

