sprite $AWS_Database_Migration_Service [150x150/16z] {
pDTdai8m38PXMTtV_G-yioraQ-8m2Br_QG-Gs1R-RZws_2UqPA4b2orPQCb2InPQij2IXPOij6IX9GijMMZ9GaiMMhBGaeMMBBHaeIKBBLbeoK9B5bgoS1yh
NOMPTZ6hHjx9mdMMAzEViSOTB5na6TDXR7cHXIk5qCaaBh6kc9XsiQXwRBag3zh5UO65rQRIPqCzvw-5ouscwomibkEJT7JHX6rFpGUhajwJd2SAkSZ2MkF3
T7OvJQRN-A4gfzTyPPKtUYqMLUi_LG8hhBZmOs4f8Y83rbXAHEFHgi2jypzMmM-rnj8A5UKQowb4HRx2CYfIaUHPLZ8LgRwx3jRsGXNHi0rsi0-MgFG64y_V
MM7xCqE5wjlvQh3PmVcgGhLy5grI0TFb1CddQsMgryxCEBMghNJJetcmNdMmoZTGeQSAFLNegK9F5Nggq5E5dYeyHUMhhAXGZRd8uWBLCakeH4KZphDor9tR
PPvZfTHE4-p7B1UYGjLsrCIVvKQgKKtPoom2tmet6RJ5MQ7wPPWOl3NeQnnrQ_lKGMVIBDvnqfZ-RMZYAVjWcF2l8B6OUArQjJKZR5V4_BvklJHh7yXjn60C
XHEL4OLt__EcqCCqLI3c37xtGljpvTFk-YfybJUPYiqgPIesgvIfsAnIfg9JHQUAJXLEjvjpoLMyhJfSJTNyzwzCnNigd_KH6B9OMAnL9_uPOKcP2hVRNy_i
zgLIfYBkzlkp8dcfbAdOr-sQawamk_thtMw_tEbsMImCLjRjQvN3mcBvtNwp8sGgFg_RBtVtgKp5vtNx_LMPYl_jzbUhCXM6AYgDJCLcbJ8LcrNAL6nMALEn
MQLCnQEFFw8MbSN2OKtLGL6BMYmircbk8vRfOpC_oc9XiSPAPBT5XomM7kkyBhOqlb7hwYY3XSawhHgu69VW7YMFXS5Q5no-WDrSy72MJ1OswthuAmx6UDMY
LybbuRCqbclDhD3JQJwvqwAoMIGiZTCNeqLz5ZvhmTvkKPz5n5goLosQieXPQwvZp0Wz76vQD6PXi_pnMLIoQ6BvAlpkyrPaAZQhbAdOh5AcOhDAcOgRpp5V
lbM4AcKgDgkKgTYiKgTAdIfrgjIfKgR2LvaieZ5KqP1DfufE5Pqgj76eP579ef959OjA5fKiAbbKigXaKScYaaKbYqeMbImgMLIog6HHoQAIHIMBIXQLhEy
}

