sprite $AWS_Database_Migration_Service_Database_Migration_Workflow_light_bg [100x100/16z] {
xPZ56SLW3CDoplu3Tu1Iv40nPt_LWre_s9V6TwVX-GqW3qytGSSudoG1fJW2PZcYAB-UpCU2UKCZCSGtaOJj9GmNIzlzdtE6kzuetlA6gWCBoSwAEZKZNzV6
X7xWnKFh85kTv9v70JhZcCGTnBClOSnxr-xWtT-xrk1T5lozkvvdUzT_xxvil-iZtlNxUBV2Lo2RTE9fYZDinBisurtht--6E8KkyVKyutpk6gBHLuFs4U_X
I3XpdyXZ-XvkbHZsbTX1HD0OKKn5pu6ju6tjuIuxNKB5gFdMdcrkS-jvX97VCvmm2lSbQyPJUiuW-ZcY1y3FWoRDLitxpuCd3vnZ-0I3UvSof9uZHlbkQSt8
-2h6o3hnb57atPDGbziVTGy70FrxkDupP-tzrGLtVKECdv7x8FUVVnO
}

