sprite $AWS_Database_Migration_Service_light_bg [150x150/16z] {
xTe7Rkmm38HXcgAa4Uz_uBUz-wsPG4oR3ptrnnPx1An_RqH4H4H4H8HUJLLkg5h5y2_JJMMLLdY-fl9MQPu9HJOof3MftD1IQyT5hrNllpyyWydPOWqhuSqM
EQk93vIsyUOds-L7VR8XHpPy0rXEbWQQzeRANl6Pckpr-AzW-aC53y7q1qjssaVUjCliAdWGPEVxFLO9LU47gqb2LVmzc50LlrvbL8MlxKbLs--3YqXQLNmp
P5GzxYkzsrVjnRvAgNA7HRPeKjLUAnjtUr9Lv8oJLnKy3-PNhMCLgrQmYbMiQj_oZACUf0bLuInBMiWAtsnetcwtiR79SayJslojRdcdYOlIXgyQRP-KL-Ls
MrOx_05wBOjSw4YfSXIvj-YLt5FaNTk7BRA58VcEWwhoNshucliWckdBe5BnrNTdeDKhW9k1LQoQXLNSxP_7tSxTpjrUv6APiDkvsxdRAtVx0PSCgrW53-f_
SukQxDZStub3-CEMKDc3prG_jaMhpsLoPDtVwkNympvR4ra9MzsYpUSRUhT5yNwBUWgetDCzivKjcWOcWIsQ2BPjY-P3BUjRz6iDeEwfrZrWED7q1HV_3LQn
IdO2Fx6ALQnY5QkoA-CLh69L714H4H4H4Vq3
}

