sprite $Database_light_bg [200x200/16z] {
xTtdakGi38LX8H28YVT_jJjPvVQKPsZpXKFlUVzkV6eTLPYLlp76s3Du4mJ0baT4ookYvHdHwem8Wq57DC70TwnuixuznpE0WuxdHHnqt45tw7YcOpewwA23
3Zhee8CEEkYWWmuwwA233Zhee8CEhrPKvIBLOjMNSJHJ-J6rXkxmeZAK5eTrz9BaYbBfY0x_TZQOLTzKpRwTCOxcs2fIDhyxp2sdhGJAaUMhNFl04LWtlm37
uV5tQdV3jQ0uYAFAHtRbUTjDFgeG3fVtojs9Yhpd28uuNoUkSW2EyiwuEzqxfFp_Zc1CGVvtXmySt_E_mx_lQFCFbX0EkoL7cs4q74UQSIGGn_Hr5yOnSSbo
4Io7v7wzecV1SKJ5hrDu4O5o99MFjDuDL-CN9HI7tfNDC6JWh-IRaKgvKnZ7xkrSI_L3GYqNFxNV0JdYQD-csSmyChCSWiqP1UM8GtwmE9dm735062Z64QYE
E0EEYxC7sH6vcsNL955IpMRkTn6WOoewwDX71nrqq4477PmdrXb6nN58Fy_e0kHGFyjmi7bYcnXI8pb4_TG_1f3ZX2GKK0xLMFhYmuXOLAD0zq4J2KeRE2i2
8M9Gz_DUH3OMytvmbNNR64GAt3mn9A7HR6Or5YrPrX240dEUcEMASWL-JgmboK2fLFZdtTvCVrbcsTTvRlTcbbL3fAhPh3dVF-WOY0uwwA233ZeuX-ipZ8xZ
o3EEZEEGSfvH1CGn1oa2vP3aPnIUyEPmwcV6YM2EM8aqNaqYM0xrj5-FDFw1L7Aa-xbTp4ByxeVyOgPYOCyblUmNzLNt7S2hPTqFui0SnylwzBNZXNreZbZF
EfYQOp_ljgA_6afRuxbzToBiJflrtZ_yjMQlDN-Dxr5qq4477NJy2z-byZjXVhUDyHqz_hu6t6U2-txCxyF2VN4mzodYlb7Snsj-NpNkSyTz1m6Y0ouwwA23
3Zhee8CEEkYWWmuwwA233Zhem8yE_d_qTD2nLhVda9jp21qOZ8WE34P41mOZMfuHBQ-85bIiJf7_8iPU
}

