sprite $Database [200x200/16z] {
xTtNTYit38LXi1D0olk_RPpniIYkKU503BTqCl-zodVXjXUMHV_7pixE_dxpPXBmpKBWcwN0Duk1Rn837vnnEleMC70E-fWQvFTp_8rpd8xMXpXEXzoAPrLV
REUuInCyPBu33x4xy93v3Zp4xbW0WJhm4Bi33x4xy93v3Zp4xW1000u0nEW0G00E9CJkm4Fi3W04u412x0uynEu0G00E9CJkm4Fi3W04u412x0uynEw0G00E
5CJki4DAZi5xwl8-n5Ig1M9ts24vUdgOZ_ac1khe8JKw6ih5mhl03Zc6Q9IwWy0S3L9sNmqnvd9LYd7t5PEv3-oGJk52B7olMg9tzoLO1mVwAUJAJwl9DqdT
GL2EsX0yNBvGIW-1EJ9zboeVgiQV1-uW24UXhSXR9adcwp0EtXxagWWRAcvxUEqX24VS62nYWzGD4haBuMYCLo3SjzvHwAiYOeVazXNIMkx8xI5Mo2q7htQa
_Y4ooy48Htu5afkZ2-1mR8TKTyV1Ynr6I6FSS_1YnrQnGGhHVGS371JgSKZrzD3104UJZ49A87hYuAKEv-WxbtWKKjFbGUw1WrSwF4UY2wKyXvJewATOFH4L
ljTAXqZr_R1Jv1wXduLyPNxiuAKEaHAepuUKOhaKOmoU-a9XVkhWjGuHJiTsdrIPHnoyrB5LKnX3X0qnwE25ZbP9mJqYk90AjqOSR76etT6g9QNW_HN8UHzY
B8LRumwsEDJisCUxR0wsE7IUGsOvsEBGUGwPvM2BG-SvP9Q3BGwTvv1P3hOuT9v3PZdOuj1v3fdbO8j3vpbabeCj3ftda5aEjZXqdaEW3XrpE7a9ulvxXuxl
YNO8BN3ea2E_0ibB73hY8BP3Agrnw8Z3Lokak5KE7TiJRP1CjCoX8mxovJYaU5hfqAUESSbEiTAXZntUjzENuqSrpgrpw6E7fEuWwIaaN--9x1SwzB53EFIB
o3rCxTSK2fNNElInGuGZzJaVqbTbAtqLlAE-M9bNE_JvdfW3ZTMEQW0EVUYuKDo8mMq8a4CVELfSadzay2bNOGOwzAcZLRu7nOl8UnzIokMYHJhqdiCGrA7p
709rw3o7G1qwpo5GXyvp2DIXynm2TUWyXq0TEiyXK8VESmZKeVCS0dNeReUpHqY7NZjONgXY7Nhb2F920UpGvg3u2WFjqEOmGpWGtg7DGQwAeU88w6Wr1v4_
BBaQuef07Ig9MZxBU9mTjOe8rA7_EdnrLoE835JRjEAA_tO8tj7Dl2xc-iJWw59Y-N48tB6VuNn8kHRkTvIIqeNGJcMRG-2EhUpfLluhsjUkP9j3y8wjclo1
wqJPwXo2ThHAV6Pfc_pU8L27xhwKK-WqtPUDjFOEWJeQfFTyLIwZEqlhlaEW3XLZUuT07JhF8L27pdC8rA7p709rw3o7G1qwpo5GXyvpo697wHzYtdrarrf7
fQ_gAv1ono5B7KfVUR53sDrTyfOweXtI655kjj8Xj47O1gdkuJtTGeTMsefo7CBnsH7QGeSM-YxnCGWd-YxB_HOwbEbNeOn3Ig1VLNdKGeTAkBv-UGxXVFK0
biUP7PQgxywlgjojfk2EtGBQ7NP9o_kKShqgfzI6awOOoEYmnaV_ZnVBO2R77sgFenz3-5ZbG2P7WrYIalmJGoei1xCu6iISr9oYttt5n9Ihs38uTX1xCY-3
upqX1iTxGWoEzuGO7Ey9CJZU4s9ml2V4u7XFYC4n4G9op8UW7NY8tO67p7VW8NO77ZBVWOVO7NZ8V0SUOdVW8VCTU8ZTWOVCT-0XTiS22DI1XzWTU8ZTWOVC
T-0XTWSKCj-1XzWTxz_fE3-F_dISZi_gztFGR-UWq_5M33paT53VwO0p-ZwTqVfqHUi35PzEeHMTdVq3
}

