sprite $Auto_Scaling_light_bg [70x70/16z] {
xPU50SCm40ELs7fh_uNBpArS_WlJnGpwG9A4b0y1zf00z2M-XbX1Kn90U9es80GeC3GPcYO1YwC9e8T8IrhI4bfJwzxDUo2AZYYWxg80vSmzGxEvOsZkaE2O
iYSvudcMs6SuZj4G-zYfw-UqN-hwru1iNspIaXP_TEYFLFrHip-2zpNiDBFnDPGFgGyaIQO
}

