sprite $AWS_Step_Function_light_bg [70x70/16z] {
xPO54eH030IR6lp__pqlms5odaQsjDUJzBz9adGLG6LQ2cuKbgG2DOtCqO2kZS1P5MYkRUDQsf75cP6zkgsWYjbfZyUfip7MnBU8HRIrysKYfl155Z52-orC
SCHYd9GNMiG4shikJB9tZy1PvbTQucV41CkMlJlD9D7d9VxiZWa9jug9KZzZMIO-gxq-Jzk4rhkTuSXwD-lT7o59pW
}

