sprite $AWS_Cloud_alt_light_bg [70x70/16z] {
xTLdskCg38RX1oGmxTt_Sa-nBlCZyPVJoypuJdEX8pdwppmUZyUZUmQiJ4cZrgvJgtNketKMCp3lkjFPcbI1fLyC8Ey2NSiWk6uOR5DHvHS7Lti5a1p0340t
F9KkQJfGfFYEMj5U1jUu1Z5AqISPJ79Y8WcWIbf0rm4i_GuLajIY-0G3YsKXBi_VsGfNrshG4iIoU5pENH-CQkRrS20cLiwwqw5B2TgrJgaCtLiEMsnEbZ99
3GvDOa56ufGEtScnXKQq4jKMk2Qu6bZqTkIluwK1lkD2YYbqECuZ-NaKvf40XjxuNlmAH6juFSiwZ0JpfTEYDmPv7n4HJx9hYIhar_9ssqg4Kzl1lMS_84Ne
RUj-B0NmeUu0j1tynsvln3NlA_A4fZUJYmEsixnVxQNNd7NTQ8IY2kqQDVjUtKV1b-xCQcPrIkfJfz7xqAdtlXHwTJElKu-x9KoGx7ZPe4E_tp8kKo4ugUdt
6cRr5_az8GkxdTyjmstG_UuewEvBcQnN8mDOM_feFrx6Wg9tbPCTGr_h9GFaeGwt1QT3iDgdNerUZL0bEQPxtM3BLcgjhVTQQx7CvZDoTUWhm_beRq6ZwOFz
aB_Zk-hi-WspUU9DBbr_rEorc5t_KlNe-lSz7e_7pm
}

