sprite $AWS_Cloud_light_bg [70x70/16z] {
xTC5qkGW68JXbo3X0_h-nrttHQV-qibJ6kiqfhVsU3mUbfAFoPfULmC_UTDhMWJmCIKFuEjB8HUutFIDUS1U2qdwpO2iK_xVZ-e5HMSIvF_RkQOJ3QB-LI2f
MKfblqhhteq0EDCEH-et1ForkLu5wg1YQ5Ave6hfngcdXTIPjf54q5I2dPIagGf52-O9ceFhhfge7hYNRO7OPkk3prgnwC2LIOXfoyrmmTt1OIdWrPEF3guD
UWU23WmM4qm7ClHJgWwKKOgEZ5BQXwIO3bW_vIBgmCtLlqtJFjV_QGElRN6qf0QXQK-2ECvtMHlCGvWULNnQ20w86gk1BTuqrNBg2VwtcAlUqEFnU7m6
}

