sprite $Corporate_data_center_light_bg [70x70/16z] {
xPK53iD030GjQq_h_F_1PTp2GRdnY89pP9Z-ZYIX2Honm0ICMVpqriyjQG7Y2HOp3bZIydlnGdukNW9RN2sEBT5YSTiX5dbSGGRTMcIATNG3f5HYp4B6e4KO
jWJshiEX4ANNGZFT5vW_mv8MuTFnGchi1fbdz6bB_On-EUhelh_ttTgA8q_wXkK3FU0Mlsgfq6GfLg5CVqEIB04
}

