sprite $EC2_instance_contents_light_bg [70x70/16z] {
xTS55iCW00FGa6BtF_7ozdHQDyYVrd2jxymCoFecehupy7Qgnr1oZ08C-WwWlWVWxPJa-bV4974q58wQ40hhADub54gO5agW_6ebCYsKf_fL54uBXL7QgwDj
ocMREjgclRHHHzk7idKTRH-AwyWZfaTCZvZRXxBzYcoIUCHALRmFCBC7
}

