sprite $Elastic_Beanstalk_container_light_bg [70x70/16z] {
xPK7TkGW40Mh0xJkV-4DweSVqgAysIfdpqmH_eUPVY4lBo_LlrFYYS9eQBdf20KGLPNPKszDH40yKbWKA3SaW7T_bpkQ42Y3_rp3e0p4rx8AiD4YTQgcwYTb
DXpMGPZnKvRLyuhxl3u1n0omSm55vn00AVDaF9l4YVOuiinO98FssZPQprYqtsYfMSBepTSiXPnzxREFu-vK1VtHgFsE0tZifmprm59aFt01wUyJ9_SZLY-g
Uu7R-g40YM7_Gy7FLjy1jU7y5UAu-b5hf2ObnsCcWlLPvHqNlXM88TE0BfrAylq_i7bK3YnvAnMGPgccQlMIfUziMemPEsCfwnCf-6mn47S1ExG8DkeiP1xh
57riSOX1Ps7SOHad7UqWBiU6uNdohTlAGNCs_Jx0Sf-IGfe7M3kDVIQmpEoZbB5zHG6gciSs-m7B_aog03AKzCsdlRhzxBiyjVjyZoZkdg_M6UZFrJVSlKvd
uOFk7UOorPDkPG_ukomwyzIIFBLuKf_kovZNyXptwNVmylBo5G
}

