sprite $Region_light_bg [70x70/16z] {
xTIt0GCn30J1fT63rt_32f78d_nZ2bXwwd-Kqg65J0EWoGHjGDWL6Ynv9a2N_CoG3-ABAgrVDdKTLwsRAcEU1uIzBmCskPKDXjnAG9DRMO3iIeDmAhcpJYKt
vGlcukzB0fQ-uBxuTpSDE4ZlUzDNhJV-TI73kojLgKfLgb8LIF66obyevGW
}

