sprite $Spot_Fleet_light_bg [70x70/16z] {
xPU74kCm20LNW9_k_t_ugiR493BN-qwFc8q4AlZDNyj__WE_WqLXWuyC2tNHYMViZC654JFzVYS1BOS3O748T8G1uCiZkD68fGa0rsDUv02HOQqcW7F-qhb6
85BIQUQmvRWoRSoKz9hTS94qccxu6pNsMP8kUzC-PB-JCAhcWEJuyClWNZF1wgAui5OrxomEi-O6T0Bhl_n-Al6KOdWwtm6pdShIsCRIJMQGWxAvlskSiPKe
ax6f3fJ8JPaVuS9fQOfjUB4SMXp5ujW-BR6zSOibzea1VQv5y2CjV2IhGxMiyOpjBEmiHsUH8FHmTgf5EgzW1KXTNk1bNX91M-dU4en-rq6fcSefTgmv0Mcv
KAVTdqPuSHfhv0xmwpsYatbf1HpQMwhcjRG2tIqr8ROMiJHvOpQJgPRKj5DPuvlgf2ONtXIxLATeiimRPioFxPOUg6_unw0EWV_Wbk7RsvS-eERFNtTaFbBJ
Ic9Lfd2qtM5ApcxNypHSVkiqbbsp0GmF2QJm0M2pj0BRTYjpGC7dfXLeloPOMEWt-JxwQ_dFVzu1
}

