sprite $Virtual_private_cloud_VPC_light_bg [70x70/16z] {
xPLNOkmW3017aeN0zxzlUZDb3VlwY-SdsJQgXlrVvUBYuY97HFuXGqdAAvRkbZXVaBYl504ivUT_am9Mxf00zjcG491bJH58LNth6eMweGbqJPB0Uzts9OkW
_GHBcAfwcKmb-XqNNiaJ5aC7xuDiRdCQIAFnMtbBQcPNSlqmlRuHR_Q0EBC477R70BQg_RPeKMWqZfn938xrRI_vv6CWkJNlh80sOGj4zOJ0q9Efe_Yhi-fd
2GEa32L-J4r0dm3Hu-JADj9eFMI-eksEMtywNY-W-HlQRhHtzyQQ0K9K3JhV6_0rouRqBB5c2TXhog-pUBnXVSjSHP_CMeIjNObFqbxZFOijtXRzIUULOtvy
McsGbYvGxT-92zauaFUHHZnFv96aabIdx3IQRqIPz5YSfHldxFyM5nSN5uy
}

