sprite $VPC_subnet_private_light_bg [70x70/16z] {
xTG7WeD0243H3uCWzp_mzjxKOLiINghjsysVrrgB6rdZWpl32viXF96OZG3gQ-Rg2iHqnFE1psO4ubLJ9Y9s5tcLiPbD6VdAG6QEIcoDsROWxxTkoOCCpJSK
-n-LhhZTKiJU4DHkUUwWRD1z5T4loDwARH-mheHPL2iX01ArYe08KAeOUAQ3LIhAk5zIAfM7_mvPtvPHsvO5xE6xTexkIF6g6m2ZVEsku5ck9CIFLRgYUb_f
v-w6Nwp4flm1hRLh
}

