sprite $VPC_subnet_public_light_bg [70x70/16z] {
xPK5WWCX34N_3mqalVzzwovZMTQQDouydApxaoH9sn5Kr883fIvt6761jbG2GAhjRge0iCMITccTXHedO7TE-doBNafoAOtEjn3b_aK1bxIAZRqPHy7dqkby
Ypo-ajzYIKlLFGBg0uGShdMAHJ22JBDG1k1KYuutM5gQQejQZDX12rcS00d08nO5wc79NKKiSbnyLs3CegVr_mlAKi1WkwWVpg6U9WxGGnOls54yEdOD28_T
7JqjQH6nN7S3iR67nTe8jkv0aYHR
}

