sprite $Amazon_Simple_Storage_Service_S3_Object_light_bg [100x100/16z] {
xDOt5W8n30HGshd_XId9uJ_6fDMKjgGFctULJ2QJ76NfU8CSSCO1PrnmnONREnK12vpG8YUqpWMjTGBB2qGHmGRlSSAxdF0-9xnJ2MzrmfixZpYiwIDC-8Iq
ZFYFSAH00BBMS4AH3nfEwA1qZP3k-QIHjX7w6vvNZJ7IDq9_m_EjnXXZZ94gaQz_xewn_fjXtwuT4000G40GwzzQYu6NWfq3-nNOHS5EVU3-E70FWjiP602m
360om9Q0aG7h0sO9x1KOCh1mOFgWJO360beHQ5wWtO462LegRiA-RVj6xtyDCfbC0G
}

