sprite $Amazon_Simple_Storage_Service_S3_Bucket_with_Objects_light_bg [100x100/16z] {
xTb7SWD134FHtkB-5_R6cGD_WmL72Ii7DfyoEQLJoptwCDtsVKbvAW2d07IOz5IkREzxS2pjdn-c4WugkH1t2G4VZnG4x0N4Jac8FDuulVo8qKVa3VK8RqWL
0Gof081130Dix1tieEl4xTbmbABUJttycqOg37GmW640ZC9-XKPXJqmDjbmz666y0NJBwD-Hky7FMcummMMX8UNJqfRuDspRC7_C1hAlC8P1r39a363Oc8GV
B4qZMYqK6BwLLN9ZkO_XNPo_kmDMmKl2zvK3vpjZQ6iSQtW51_qa9k8LqVFe3OCOvktAwGqva9MdOZ8ay-JO038Q-KKyKhm1vS3W8JRu3GrdGiFz0upa-O2T
NOMTr_gczyBG23J9ZQkFZi10P5Ocna43HiqlDJv_sResT95VOUYx37uksV3FEHjd6i6OR1kZRT60pvA20SjrsJYEQ1W6CKLxOo8dDKJ6B4-CWmRaLneZDsFe
kunaKWCH655LqT1M28oLilgMVYSetfR3_lkTFAlDa3mdIKFWT01EeNz3EkNSym
}

