sprite $Amazon_FSx_for_Lustre [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8b
sP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMmCjPgBSEWX3KI4GMlx_Wv-h8H6soHkiIKutRrEVNZPHJI6z7L2Nf5RUgk4DKeSAl2YjPxJo
LWWtcXwmEmL5lgzbJwtOZx3zWIxuWxJC_cD5V4PKnUr41q8OLakILlRPYlL6XUjb-K6NjuDzAu-Az1b9Azkt8W3G1RsrHlTBFQbbphPL0q1T870DaI7QEcbb
3woQhg2GSAJCcaahsxUgdoUICZzuIZLfPTlzgkWA3oTox70W6YIjRCkAbsCmHFfmYEEKbWKxLegUo98Moy_ggQILxLWn75JH5UNLbmXM3PsqieNLMWlgnrjz
jDz2F6bb6rRAE6eOMOm5jy9Lv-jTDMbb9wiByO823jAzrxNRfA1CMC0fI9oniWshWrx7jKjWWgfyhhawmWdi8gKyjBBPgk2CpWYLuRMQjtfemWqi08MVMTcY
NwtX2ei1MMTJVfNHx6UzbfUPFBIoBIj7cckjfWU7tCc3k_H9UMnbsrQZYEyVgWUEMh_XGUtYMHxmSolRjrAvBCfHFKGFYpqH_Kav2IlRjtA9a0AAwg6vngd3
-pNmHavOsRwLU3BHkSMl0FkFDdNutcebFs6VRHDMjcsbOIN5hRHxLjM_knJArFj7d9YnikTPnKhJWFmwHKaQKZYg7ivOsPwLlo1UYYCq6VLXcwGwE3B-WFfB
AtoDGPug1V7hpGF3w7JlMj2TVsX5xp0kCvUVqH0DgJQr-zUic1Vrv_kedckj4TWiLIIM0FgQLODIkvoN3rvj7zXjFR2GcdvZ_VDDMjdToa6i3Slq8l6ZwtPM
u09Tjhj9ArlN2K6zRp9YuyXm1kV-w6UFhJhHyZysKOv0gJna4R7AnQhThAOd-d1yPXNe0dPqazZ3BaXQcNu3wKIw96bb-blaphzcvrW00000OD0_V-1f546H
hSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkH
hSXMP2ko5TcAR4Ms1W
}

