sprite $Amazon_FSx_for_Lustre_light_bg [150x150/16z] {
xTU7kjiW30LWBH1w_mVk43SEAjsDwJh_7TdXV9BYuFWd0000000000000000000008nk7pIFuqmsFL9dUc0xd4neO_61CnKy_e1KdjV4Ff8Cw8TJDQz6nCXq
ou3fyLGU6_rcSSwdobBr-DDITIAALBcPjIYwcVcPL4OaiPlZLc8vVN0kbSNdz4z3SCOybafZKJy6N9v8UcgkMYwzgCMnqhzZq-wrBrySfBn-B5N8Mf7AdZtK
VDQvL5aH7L_ieJv6d-D0gXgBz8iFzRV3n3YQAbmo5zk-RfkfP5vKxlVi6I8j-olPbbQo_Q0mcZ8brZRkIPMwqcHHoUmZbz8MuX7ClvAAPHL5uvAhphmlrTi8
4_5utLnLFbVKA7Gxc19Rpn2Z6zCaSK-gP7iiNjRicQb7AZCPTwQQc_Z-XTs3NnrsKn6nVhNKRqqLeywsHRHhrKnSpedwDMVtfieGIqVRS_TWCzGGkioMSxRz
rbHZwOVFOteMAn-mPU3TrFfiNyidt9agbXLufkfPAyt_6Kh6CltKyhtbLAqqbtmqCljNjgGpbCJCwdUbgkSNxJakFB9Wrsmbf_HuSxipbH3njlqS4PhhPj0I
AZDcvXjJjMiXpcjbtFBH6igMXr-MolrB-y-wKyWGir4b52zV0Vs5vpYiVTIl3xycEKegNYgIePRwP8DVc2g9g0cl2-Mr-aI9GLIrzN5zNGULAgqd6NLLfqhA
HrVY9tIp4QdgolI6rIEvYEX-akrKrGvBl9Yd-7w3ivX_dDvQ_BK000000000000000000000tWC
}

