sprite $Amazon_S3_Glacier_Archive_light_bg [100x100/16z] {
xT8t0iCm3CLGhl_-5ywO7j2cqe5HxRcenbdk17ChYEJHt9nW8nzctDbnQi2Mhb5Wy1ucm1WXcHZPOXGOl8y9CWR8EeC9D0P8vaPwHg61kvbWOpUIDKROgFr6
eP5LHi20UgkOc1lv6ME0T9TDi_x5_x6xgq5tWfTzig6XeQ6XeQ6XeQ6XeQ6XeQ6XeQ6XeQ71jPTfR5ctFJi
}

