sprite $Amazon_Simple_Storage_Service_S3 [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMmPcxG1DaHI60Z249AHo__lEJAVyLhKK
7uJTdNU0_dwnZ2-qUrYz_nqgLUP6LCjpY8XPzJzNcNAZyZNKMFyZbGhLCXC2Q2cL2PMbLEus6PXqFQDAZLdq9zsiQqIO6rtvJVUhb5xV5r4R3mXLflfyOdjL
JyTKMGsVMyfKxcbzcqhgG8ICKsbt5_Sjgbx_8OcDnYa8gxf19UKMjkIN3zTofgLL3JWcb6LISHPmKcoRlgfbm89LTXwKRMmGv-5hHjNYXHrm33qkogZY3-pk
Mrp-9AlQVxyLRs5IfSTcLj-XAhQPLREg6go-azLhoJvNL2BDjh6ubBIAxz_rErYzbLiehufKiHphgJMsZ4hBOqZwAgjpBO_XZEhy4DF3YQ6oZxsFufKAf1gF
qTvUsZfBDu3Ldpjoc80X2gdamof1T6uIrnDM5MxN1Qr6FuwpiemgHWCV4PCssgqeCbeBkqLaZueUJc6meeABQamiIgbYDDJZATQvKG5JYRLV2nPjwAB7crXN
PlfuSaID9JoNn4EHK_LGZMFw71kFqx99rO_rmEqAL-4D2sUThpEfgZ4QTh7mSMN-RJIq8vLhbQc8QiHgCR1okQW8KlcNBdC0KMOnW4NWxkmZbcAgiupN_fqL
3ogeykHeg2LIFwfd1uFva0MfjDmYtrWTLWrP1HaDNChWi2AJWy5yoA8fLI4TisHMvS1e0FfzbH4h1iEKoaTTPfpNk-AFB9fN-V9ewBKyvRqBx34H7x8wTjLW
qfgOSXdkjUTW44WrPDbSbx7nWs_di9rLURxBoE0gN4k4PrM-eSieVNeZ5RvqzvViw3BQtbzGC7pJu6CMhtKPu_BcmExOKYTL3gmva_-wgzBl1wyLOFary9g3
lv41kpsanXSMed9uDE075h3R1zgq_8GdLOwCXla3YsWikQ6SLVdMDKVevTf1Ur2dLPuO3T1_hTTKZeq6F5te1LKNL8vs6JmlB5rHET1bvbLD6aNBQjsML8vr
6Jml2yUYof4r1u-z3fb5bLzUOIPwUNsBAh-iEMYmjhseyiGD2BAPBAhyaEHe66znYofFZ0PaurrKzOGAATjhgjne0Dh7aieJNGQxTLfIrSJ0mjRm5LMwoqI6
d-K5bUG65bI9rbJ5qwhnaK-hUgXywxYwPbPrhZa95hQMJAhyfl8TFGPaEJWQFC42rzqvLJmHdc2XLmDJglXCUu85xqepgfX_dcAXDMr2fJ4QCYoyqkAgSyr9
iV3wVrTXeo75mllGb4ezmPfQAr4LnS1AiMOQBQXgfPJc2TRaTGMcaXXOawpChI-iAaUALUUgeplO6fedM39vB-18Qh1icSNb9xPPrKkvkcQl7_dOh78kPveU
5nPuXroFxIgNnrzeegp7NsIIRLP5ZCezjKct4QjtRdVH_4BfS3gLbn29IFz9I7uY_ExtZsp7h0gFSItpQNfCn-TYGcKYnFrOYS_7bAb2ltyyLkEhiQuYHFJc
zu_SOKzUDRwN_zti71G0044153jR_y12m7zBi7MJ6wth95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR6q
}

