sprite $Amazon_FSx [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8b
sP9iIROaMv8joPPaIx8bsP9iIROaMvAj6me3CUQszQmAGr62WHpU_u7tf_jtjRI8c36iywfdPvEmL6hXFqeL0_TPoJ46j51wGKjLQDrY9UaOE2tfYroWzOnL
7Rtzb5L1UJBpalF7s_TPvJxlKYos8vNfPMMtMPcTr3AhjMZ9-DO3Lbl35XloMoiqs4xujTMM2MetQNdGYavB9NL5j4FT65bvp6fRVdO8rYWf09nMbg6LHwnq
VRVQa9nMM3yHw8wiV6WrS1OReccZwWUKLkJCok-fbTLkKHWbFB7o6-OA2pKjzjs_h1DM7bg3P2VyQrQrh_xfb9LVjUA9mS8fNbzQ2sPjnielMcawrO9yoeZJ
Yb0Ouk2A5MQc6XZ5GzcrCF-pLdx52ZEJTQg7yhzMHYXCM_aLAnmlPPc91rkr2a9XmWfCMw5Q6rJqjDNbxP9iqWhCMG5EExcEvMdr9WpLd1LehBgmWUOcXrW7
FHJyXngmydahU04greNV-iSQiV9fAr1o0ls25KmXQSpAn_SutG5I9dZLuT2B1QsycVPPAWgszCk5bHYqyajMG7aVBpqADxALe9M7h5vU-J3RogIMTmbODGSV
d7bMWbOUii9Gq-3gOIDevL4h9PG4AEdhvW9Q4IiFMbd1iK5EosSFxSTMXaQzUzRT5olqnrRvtGerGW-nO_Ai5Q5usgR_arQCKc7BKg7ro5n1f4AnUJTevNOP
QTQWGgERia4hZyLeRMznj1Vn6q4hZvGAdI_eNpjcXET1Amz4EqCHpm1zl1QqwclfG2efdY4s0U9X9sRLryh4qZ_Ru8Yu_6n1nEy4hVnmOxk80M5ApGghw5K3
8Xu4hRndjPFpmfpn75BQpFMeXnQqyau0z25KZthzQoCU1ApwMjBrOcqZWCVxHs3MokGFxsa1uTmeBKqmRLWNvGqvrF9fh8jAvPKYQY12qCejG53hlsRdM000
001Wq3z_u6aKGP6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5Pa
Ax8LsOfiHROYMmC
}

