sprite $Amazon_FSx_for_Windows_File_Server [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8b
sP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsHg8hzibrq4G0CE8gC3zN_1n9ivY6kn4JZ9z_-ptzfd6KYAlzHCLjq94jOPOSHLvZTzdIW2ZH2lP6ohm
QWSOFg80ws4LutYI4156ulUAAhjN4A6NgnpLWgPwYgNVL4sS2W2ayqzgbcTPghigwB7SBgZIFLK5W28R1LMwfQBbKyNK-mHNweLKkgD201I_3BqgSmrw65Ff
CofETkRijo5nKAK1bN_cpZyjOyO5LNfRbHVJoOP-ELy_abvGfNTLnHxNAS7yPycUkg1ARwhO7dVrqsJFdFrgKAMkQdsL_8gzMTVpIpAeKb_b3u2qSk5X6Q_8
B5PGfQxAP_M8b-CX_Gq5cGggz4DLsYcs2N24XPTlINKSAe95U5kb9zLwjsE2KMxEmSlZs9Cyez9xgbx9q7DFMERZ-g4yfT9PbV1K5MjUtbFpNwWyFilrsgPA
_TFkLpE0DoYQ3GK2eEkHtrQferh7vB5ehPAWIZTKjYbuttDL4bIfgrg7d-FIjWTF9K6LxgaOUlENrTwNF9K4LNfFvM_D2HBRzk2f9AZIBLKzVjU8PBkLgvAW
IdTKRVhT1kEByePADrJ5VfVjJG1_eVAtPfpMpz-gsFRFCi-k-bCL_WttTfxp-5Kb3whOlNw9_qOwpWD0206GBcM0H19KgLoYbAjCDRkjiKt1WY-915NgxoX8
nvfQnp9Jvzk73PK4LUgeBbKR2bakAYIdTAWaf79OBIzML3nTF_jcmcjs_xEfQgt9ucQ_4gP3D1qoRZrs1goVpTqjbIN_KmO_MwizrUkiHbvDhA1AvRLyrhzc
vrW00000OD0_V-1f546HhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkH
hSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TaQ
}

