sprite $Amazon_S3_Glacier_light_bg [150x150/16z] {
xPk7alGe38ILaE3z7_ZIu9gJlM7yjtQum5Tn4zM5fQQ5TyQ_dyrcizbiDflDPhFPR2AQgGXJHaJDF1ReQIRqBQBsBctTbUa6hEsdfKr5jr7lFoU9ph2eMOk4
cwa8dU7MHpcXb11hqSTNXDkf4SH7ASxqXEt6yuZS5lOZcbXzt2QCotLreGd_UgFtnZJX63XE4mLNwqOJAnDbbQMWiAZQ8lKAMVrI2J0FXt5u2HqNuEtY0K1_
8AEOHdyGeAeOrQ2FaFwWZM9wWQhwpM9qKSc-KEXPM0yMMqDN8bYLfH1IUAGAwYqJjbuOXtG0H8wJ5bNHsl0cLdeYzvL54teYCOq1jj6kfxJ-uhWNRgSzqfXh
mjvYduuIPkOHCH8z8ipiau5YLaKV239LJM40qlgpWsX0MExYQCfqdpH36nOPyX99cj2Bi5u68iDpI7owtH5f6ismY9d75qK1y69fHgA_sa0B4XQmueg4rK5L
drS1NgaWMZrED5GLtiVr2zvqOZTpSFFhou0l4HykLBoHXHuKZbtuAa4JgxCht8gD9WnKHBbX6Hs80zrJtCbEJzZ71I378CjmdZg-DWPvrmaHJ0djFtk2nOjD
uohMXwMv0SWnnQriV2gmwshSQrIrNvoHhOzC04CgMWaXTA1-KGNSfu1TqvKEkEKSCx4rqSCuRLYsMy0VK3TskTpeo5yQv_TMHTgkUPu_Z46JBCWQy5ihRaS2
SR2sy4GKIeaudW0nd6KWNC_lOHzIGSFIWTAOhi3MWDClmWISu7YKSAcmEci0jrtdHHDhhyeoED4NtA80mDQm7ZpLjkEMFeoJ7-DP1lrxSDFhfoKwnEXb8JJB
e3qCB5HiM4xIuf7q_lvkDumfLbd3j7AcvpdAnzTawrwgCnsqyud3owmXBYTUm-82dcNocq7DcwVUrzwmkd7kGMwn-ZOwXs7uqU7MuBaLsnYMcyyNlELmujJ3
D7hkFIP_ks7vLF2i0DDaC3o_U6UMwTcKc2QIR-7URLYUP0LD8dqTRxU6AKiUq2Hz6GkoZDCtn98ie_GbLcDOlNYlV46McNLb3uZIbmp8Gh9Cxa4_rrAIXLe3
xbVfE_pcry_Ps-qJRu_wB8EVWr6IPQ3Cu9VC43NMO6Y-ucmmEEbD5fP5pGTEcWCqeDn-V2bLALdlVwwcvpCl-_semUv_z8Nfm2vhZ292Jl-45g_jBqzNcJAP
fymgGkc4Y9b5efcfi3uUcBOOxNBFq8HYLDAONa9Epk0f4AtwO1pVlx_22VjEsgcy-6qNh3tSJ4GemI9g5cDobDVnKJGV_pOscyrcizbiDflDPhFv7G
}

