sprite $Amazon_S3_Glacier [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMvAjWLVxqD8RXQ4034BDUl_ttSBlQ8B7
WsZ9FMsdVsjZ-SB9iaYOi03ar0O049d_legfG0e31ValgPHAJXF9WF9dLSekcWkG_26L4hnS240aRaA81Lw-5UMyYajg0aWitIUH2I4_hjXP5UNc_vfqU40m
DfSD5rInAHVMsRdLhaQK8oe59w6iZbD1XsK-eA9qf_3Ub9VYlsbNvIZK0oyVokEi2EMcVPQIipPK-ba91myfxrLAEwgw5Cgv1k6NA--ewkmxNMmm_HVUL9q_
t_9RkA6YqpLGJgYI76RbtJi8bONdM3wpzfv17mrdM08fRQlGImYVOBafmOwAaoUZRh7ytkshv5adLrdFie_RRnmgJGSLdMIrnGzuyutZOrJBSzj2eQrw-5j9
viyGvIrLlWU3-WLhS8ZCBC-zApCY_hYXgDTAjbHmgnos7DyMLfLkgR1zFGkLl2JYzkMSzrNvQg921IPspYpQfFXWM5BvQ7Z_YY02m4yOA4ZyO-qh1rGQxVER
I31EwmEqe_BHi9xtTiK7L7GTPCcsoaV3ATRuO52xWYvJheCi75LPEB3Ei5m5GoeBkimr44OaZLZZWq6jnv8nbUPknN-eS51bcwF1Ys_8yXupehAUYYEKL5Bl
SPqRLwwoRfVn1Fq-1qj-U32eTLamfegt7OigMnyDdBwIgSFo7ZEkig3B19qrt0vvZvbJsV9ea9oQb5VNn61Gwx9aR3Ge0Q1giC1KyuhAThkCOkujCArVa5cL
xNSPSbT2VHziEAko0rs6uQSRoSE7xjPdbPNMeCLTcVJbz3wLIPKTwJAA-UM2OVB0fCg2BZCQWcy79xN7SAh9aoeB1jRAZKoPvDTRLI5csKkERNEKyk-m-u5M
2Xz52rZUPHOZ9JNXkeUiobcL1LrcOOLve11pfVPK0Gisjpb-9zkigQmT3VkHRp2OLpcBlCjifxGgML7PmcY8Eskv3vfo4PrNEKjzyt8YB9TdKMN1mDhDeifE
Z0RLvtzx5bLsu5o64dnUWupvEOyNLRRMPPuD3Nwww8igsnuDlgakRxzeKMNUPTOMbFYBbFnfrf1bKMHLHGb8BlGVru_lkRpML3uQbaPvJb_BCjyVFvRNaigY
BXFlgCcPhySaIofOEqYMvE77PkAv8bPKgrr6l5T1U_60z6gpeAADWSMOVLcIz_VlMLCbknOZlzQH1eUKaogfgaaMQ_CeqhqPH5TmbsLXjDw3EHQb_67vDTBc
sTESgCUoEBVAPb2filo3XF1v61sLkYoBKt-5ZRByyZZB1nUqft2TjMLZem5jXaNEQYQN-CV-KPCfLTtcs0eBFabt_4D7FJAZggl4Pbb17DLaKELTnYPPfO_2
_joomO6bSonEGQZBil7HS6SSbV6Jb9eFSyGQLx5vXb7g7pLhIMEM3Ou6ig-ipojdzJO3WwgIKYesmUBVKVWssxlzrbLnbx4vLhxUteFgh6xf7bObcsDTGMUG
gnSR7GqKiC9-bTj-jQswxfFxc1LtKMGzf39ABwxHtkwjtsiyoH6L5J-Trb6M9ey4Uvn5bL-j-nuCiVBpfOTVl-EGoXJILtAXIXjuF-V7tZaxSqlbaP8U0I0Y
QKA81NBvpAn2Sb5xpa1rkSa1bUUYd8O2b-VjJ2QEpUNYCY3BmVdLIPNBX2BQvN7Cr06hhKQ52G7WvTy_egyRNrx_HH0IdrB5kSxdtsRdM000001Wq3z_u6aK
GP6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMmC
}

