sprite $Amazon_Elastic_File_System_EFS [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8jImRcx4EhbHW60gYyhjB__-yhMJA7
xF4YQqoRL-XmiUIM5BbcboNNbB1go8fAjrGILlKrbVvEbVw8gdn5o-TTbMINnQ5u5S_oKRmgiomVbNcLiYmVDJPKBCj7xQX8be_QKd4i7xMdebW-QbF5i7pK
hefW-QXjbS_gxLywM6keVTKzQzISv2qfDx0yrBxgdjKEkIHtLHSLK7a1gyAKP9BSxrWLgALeW8Mn6eVSfDonieCYLPg1QkYcSZPwHuV9SLj21qMgj3vVuZAW
ipxhTqNyqfjNdPZW0eiAh-fdxVe7uFxjgd6YnaTa-NRL0TISbHujhz-hgYVAAt3PP37rwtxVzPFLlaLLiC0xmtcerkFXEogXYWzLMcgzakIPrBvMLL4_fuQN
b2zLfNEelEHjLhY0LTtqfwNrLkIHjgNo2pXM5xKyLFLviaenbGLKUQ60E5Ha79eVnXfJMMnTBxgIdhigMF71iW0BRHNA60LRTa1b4LLNWXKkeNciVPME928v
f5fdTKg51IoteCfduLRJ65M9BgQsnkf9pWn6rQEBl2snSAjfIgM1bNf8PGlVD3Tbqt0two6LUQYYMnc1Ev0vB7J5CNGpptkzBAXyLi837zkijyk6ht9PpK65
MEF1QZ6LtGsLympYiSpg6Ao0okPTLMzGI5bcPJHyG6NJ7-u_hJbMMNrbgpQFTSowQlHUNbLbAfYzyrWeeNciIG4p5cfqtbtoc5S-hZBd-F94G5jlIFFRVoDL
zg7g46IWnUvpK2g7DQwg9aY-b7IUogWyrbMLPpzfzDUqCnM3jQT2RbNeSYzeGKRbiQxJFdJAgeAazlvzIghiSZNbhXI2u9laiwgaogRNU5ubgEevJqYLAIPX
_honQcW1HWLMXeDKlJwOSs3Ob5IPuYWwUDLB5vJtiuTK6GOhZGrLGW7hwwz8gC1A0WgbGW77SLtjuogm1lP_IlKiO2_Og3oM1LXIEDLPm4E0SbcsnaeRghS2
bflZeQFoMtvGghE0vq9rJ3OhGWLMFoGffNhEG9XybYspT7HAXMdNXzw4LDdkZWFGFAJAzbH9dP0gsr9LzKAgR4Srr0sfCbwLT26aocXLrPLmgcQC2WNqQOmg
IxQu2WNCajTP0PH8DafL7oW9i28eaMQCQZnFUpxBKNNvboigcva4Wm9ERYKJLa055AMg-exbgNHP1HId6lh2SbJggYOegz7wTTKNbgVIDHLGY381orEfevgY
zbcUIXtL5BNFybJggAQeVTQMwXwrp-9LzwXz5gy2wWjOl0geBs1nAX_5itYLWzfayQfhTbbooTUfx7jLkgYoRrLPNLGPhog-Yez-VlusEyS2000008F--GDF
emYAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TaQ
}

