sprite $Amazon_Elastic_File_System_EFS_light_bg [150x150/16z] {
xPk9pg0g38N18gNl_y3tpdQYauZHSd18qc-MVxNvREkQOkiJ144G144G144G12K1O8Ca08eZ1i6A7b73whLLiGd8SAvaWXIXWiAN6hCIQF6bn6zb4xGGSi0A
CVXIGrQ8mfOQj48ShjIm5I8nfGXMYCMJebWX6akAOdMlrVG7xOqKnwglLIMdF-HI7qenhFfQLM04f3sLWXMfKwl12Lbww5KXHKREKRVKeJpOdAo5g7hg9hKV
wD5Xs_tcV2e-8Y_DJYZofztDPr9xjOANsjUWV5djWlrVQRNVKhVAoRvcWzGrcj7oNx93wZwNnJxblc-E8hO_Ntptyc5_a4unN9AaVfAg_AZrIauWrm-wIj-_
32WsaunKtIEVQhMZgsvfSD6c1IVMkTUQnoSrEMSkspJaQNY5rA5LRHRRumvHqSwHomVxx3hBjPbMwjwTvQpon9E3kgrasgMdvkGkH9bqCbLSrfexotolYgZL
MtoGbIers1fQa6tbIfNHC1jF2-dV6cttZ44cl2AWFsnKIF5sKKbnRiv2xwILa2o4sNjIe7nvgKQK_WqdQ9uRMZ_RLO6QQdbmPwvsWJ1AUB5h0fMCpkiYdUJp
RryEYOgZj4ys09HjXPA2erNwR3Ei55QWNfH7qWtrYrp9vJ6ab-nmdsw5Pd6SWSbMnVbaS2vthkVlKHvDtOyK5qTZOPolTfovtLQ0-S3JqB6aN2dduL3WuRN2
jUzqkcFTYhO1gtCN51mzb6JbDc1rl8shv5laf6wheu2Iy2chXacQpme5r48Tl85MAYwhFmKK-ZIGvW6hFmKiz6Twd1zSLYXW-i6cHaMtb7rzXICm9L6Ze-gp
mc6dDWU_LJEma5Ms5Qts9QtQYbRPrhAQNy3gjchOd8yaSLhbO_Cfqpi-gnsRJveThYwhrfjquas5fTValmFm9-XSLlka2Jf4z5arzhJXHRpojdvwiMzBJh4k
El6xw7JqifFawq_Thxz2OVtL7EklV5b_bP2iiQ8griIjkQfnqHMWwnC4GH04GH04GH04_mC
}

