sprite $Amazon_Simple_Storage_Service_S3_light_bg [150x150/16z] {
xPi1LYin24M140ZxN_3_wg3Qg1hBcnxLt0Lmtb0WXD2udircizbiDflDPhFPRDo_YmxL9i9qYKXJDO-Ruzg4FaMQ-gq4zSRq5UHiQSCQNGMVfcnqfXa-GkY1
YE4FcAgAq4ppW3DxIJwFPpTjVEani2Q-C6uZbZ4LUgODjAPKL7Iq1WHdIhWFG0ImHnsZH4VKK8QvAp-H3HaABMfqrDSbXh0t3aUDmA5qZvT_lnPGh6mJ9sgE
Ygeg3m1GgtI71PY1K4KZi71L5HFyDnnCrRWI-9cgT02mWMgEXb8YLLK96x8TQe038cdTuqfyQcGr2ZZTOK9Fy1NAN1iz8uTDGC7pD9lmr1wlzyWadZRBgdhS
qPbcH5IxkyUCktTjmZJ1EjB_554j3RfoxM9vWDv5UietZ2fPkQAkNrGrJHPB0rzpdK-ugO_NtP6SrNMugKwJZsa2OZxU3ue2Qw4v_9AL10Aeyc_GNU4xBFnt
CX4fN5KK4N3ddbbT8_COY28Cwgh3JTLkvdnRLCKvs004AYvbE4iv8AbnvSKeiRLh5qILBdVIV7PXI6HHLI86Y5DGQJ1wXWrG631LRtbMt5OB0yBbpdI1ZeM0
AE2BemPhpS9r6le3-fYbL2u6_cAnnPSzOqgunuGlNrBnHuJ9Up-a5uRkzUFKszkLGWjtUaI56KgJm-Pn2k2QKtt_wUEvC1WNP05EBczqAIo3L0ko8Er_vvV2
qbP6lI9A0y1XgIfbCQ0qm5vYHTsFKm1G6f2lrWcWDDI52Lt2W5u6m2JBWBrCDHZis2iG7QXhpZUQMc1LEL1LZu1saEXh3YP2qTSSH3R3Z44_3-buV2WWUndy
YOfFQBmTVF73bsEyv_6HW1_PTb0kumSf0juX-IOkFtz0XqyUV2hZ2mtU2huquEC07n7uFWRz-2BVyg6gmNVne660QxWHxV-tV2nsk2hx1lw-sH82Fd_mUOol
DNWJv_SoZD_JTSmoNWyiNDpGr5CMOhsqEPhZHmqqIWVDhXxLSk3fr_n7ofM94eapS9cMq3xKvZxjF_Ou2PVtzY0FXNvFrxVs7pLEP2ZJrsaMP-DT87_Km-Ec
mlG-wokuUFpOWvIt_W7g7j-3kexDPhFPR3QRpMQpsMp-0m
}

