sprite $Amazon_Elastic_Block_Store_EBS_light_bg [150x150/16z] {
xTjdSjum38HXD874_G-SehZ2zaTDCCH4yRx_AJ_kRHd_VWWXX1122264a54kYb7E2i_OfoAe6bGQ6xA2QXjBgQ3QnLAggNJ1Ag3qxrMnO1LGKL0jM0LKHRLW
5L0LrO9LG5LK2rO1LLLbLXrLLIrO1LHTbLarL5srO1LGPTMQDNxbPZv-jK0LL5y-rIFbfa8fKVD8UKAbIYnD8gOluoTPEhw1fV7QD5fcCntVaQTNFIL27z9q
V6jEBx6QZnalpU6cJ2ybImTAFRx8jPirw4nyOHSw6z7I-T9uNE3pgO-MJbHSwcH5IzS_N9oQLIGZ5WsXJjLJugiFzcxLKsm-uqFpwNjHhoebOcR-z7E3YL2g
JpMLBgIpLnKn3wQ7yJ4ZkbM_cgxyXKYVFjxQLKyDDnCHEXCHCn_nLBjgqV-cWWeggA222Ygee88AAgYWWWeggA222YgeeFAubFUgQCI51lMfzEemrZQC6DQZ
pH4F6af_YgR6ktz1fF8_BKPqDIKDKCPBQQ8YIRrtPU5C5s9FntSlKiAL5gb_EBvrlREUxx3vulYYqj8fnc4YwJ-hnuZ2qgcm2YjCrMwyeEjV6zvvcTc_Ohtp
uhT_7Ntd9Nd_wlw-DnJwRtFSvERB_My9QMn8ly6TEAXkT0EqFuGGGWWXX112w2S
}

