sprite $Amazon_Elastic_Block_Store_EBS_Volume_light_bg [100x100/16z] {
xTAx5O0m5CKmshV_mipW_2gvvXu1oRUV9lU0oCWizO1eo8F5h1fpZ-YZJlHP9lfkzeovGVHf9_eu4tqz9uo9p-mZdTX6vbWFY9beC7fohnZVTWyC1eF1O30O
30Q3mM0m60m6Wy5WC1WdwWQZfny
}

