sprite $Amazon_FSx_light_bg [150x150/16z] {
xC410G0G000W0FuVPWPKytO000000000lPLjCMTkIPI3810LGI7xt_3KVVRagc4-0ax_HLBn553j8qqrPRAry98rAX19ZuOgQtrVuZ76VJDLNuHtKW6gLX6k
DOsgplKtb2YQh0jbKBcvv66yyqwg2YX7YLJgGALJmHFiVwCYDrNwbAr30LIFg1nNQkKXMaRaVYfxH1qNhul93RZtKI7grQ2KwLk4uRnSGNsQ52aFDGnazXK0
UE6-0LJajWQArSUX86SGz8Q_n0_fqo0gyxyEYFhJQXAs3ZAAuze3UXlz7q251gdEgcCdUs0yX51XMyZwp_RGaBWegiEel4IOvxBK1bEudmeIxmm14_dMd4Bs
xN9A5muv97Rn9OKfX5A12s1zbTB-_Q0SeLHGh_Cer52_e3FEB1ycE47towQtoBtegFwj9C_ZG4wXGi9AMLgt8P941SawMvIUAyYMasj9xgkngSdPFQHJ7JIn
IXeE5zbKVPoR2m-xXsIgOoXKUtGQTWzxgEeFbNxRd573xLI4vC7zTrF9U3kulw-mqW2Hywdqt3l0G3bBIwVYRsvWKgF59rFf2QEXVgSQKZ8LeO3pxITXx7ug
krgTJmIqE216K5MIySCTXZG_awAg54Fr27DJZAWGe5Pt2e3b62hyBs6HYkVkRZ_nNi3DzbIapaKZ2XtonuIlpsM2vpjtWFwLk4fT_ngKXsPG2DeH9TCk3pMr
F-t1CH400002eTd-XUtn1wm200000000u
}

