sprite $Amazon_S3_Glacier_Vault_light_bg [100x100/16z] {
xTStciGm34DXjRZ_WJS7wtt30Y8s3j79DFKxXzNFH7RwH1xHKPf47lc63fqQ-ag2JNd2RxC9lqyzGrcYQiqJVhDD-DrA63BNwIC-qKOKIqq4OnfZ-9dCTJN6
QkS-ZJ76m2sMDuJa3Tr8mf10b8Xa6HZM0ieDGvjnAQ5g6vm7mgKAxjYGrgskjyAnGMNXnBmD5WJF828CnR9fL8gsG3WogDH9tEU6S6Rm815Talh6fc3FqD8v
vxoPkJXZi1OrE1Vjj54K_j1-rCRVEEUShA131kxph4540X4qbaWa328rqJU8ODmnY5mL55A6k8v2Hh7n1T4mblWvjotf6qIqPyMCLHdv_myQyVyed8_UD7Mk
1aeHW-ly6MECCPYyCSOOOuJY6sFucJm2
}

