sprite $Amazon_FSx_for_Windows_File_Server_light_bg [150x150/16z] {
xTXPaYCX30JG50Y4xd_XeJjGJ2tKh3Ru8zzFRruoa4gjidys8Y8Y8Y8Y8Y8Y8Y8Y8Y8YQbPKrSpNqfas8gaWY5PV1pFcNnGN-W6fChv9IWd3obHPhrg4ob4s
AtbnAlE90a3CZshUdcfQiDsfAe3wSQdq-QYqAtvcshq_LGAIpsNSph6XorjJkQ2xFXhYUrCPkdIvNc4BKlroEYcwSawfAxgzHEyyrz2EFwLryyhyGKCdnvDh
Qr95bURgA5hKhowPLp40fFvgF5ZKB_kgLB4pQ7jiBHcFadVCzc8dxLIcBjM7yL37OsmKV2QzQB_IOtCDsIQDbqVRgwzA5Mf6D-smF8PwyhUaadHIFPoNTx7v
XTh6TzdkWFJIRfyTs2dlUIZeTBg_ArNGMIpTdSgRJ4QueDkJAgJBk6oZX7bFglagtn1ZgcnDfQSI2YHgQ3jJrNXiHDJOhNQciiDZ3UE7iZjLEJmMY1XfSweC
uF1jYgxVcghzt5dASNRLhQaIOZcryvwQbwLgq_h9_FQXkYOWwKq6H5-OIYLNFx0OJFFR1_p2ArEXIrhiIrKv_7EkyUsUL5Vr-JC505advBMftFB3YfhGJQu4
INV_VFzZPlwWQX9yEpQPTUtsK3ngla_6d9ZlP3fZlXyH4H4H4H4H4H4H4H4H4H7z
}

