sprite $Amazon_Elastic_Block_Store_EBS_Snapshot_light_bg [100x100/16z] {
xTb5jiKm30HHJMl_2_xCs2b5UUGUsjAvOQoTiaAGDZ6Em3X2d3OXQWGnXWJD0X64G0JX4KI4COrm-OPNreqZJrtySRKCqN3s1ZzaFuD_8Wp_xEE1GGQHjX0L
QSBLviHGG_LMlOvuMifhIsIZKIfdPbY5hGO883U40jO040tsQXXK2iEcOaHGjTNOkaRlZRaXlfS88z-zsX0vHuC_9WSCDUVNcPTaRUTlm1467640RID1Q1Wv
mhSPiIA1f9u3rACqRn56o9ZRRUUs71j9kaQOZa5vPUGsvGsh37_z02xpAyuoPCTvhFaobe6gptEkHbsyiOoywwYld50MeLNO_yPz-9-3KX62Y11Cka3VgRsp
SWy
}

