sprite $Amazon_Simple_Storage_Service_S3_Bucket_light_bg [100x100/16z] {
xTb9SWH124DHRNN_2tldsVu18l7GgMK7oUkv84g3kV6tETi-brnF1Cmppj839kkbxcil7EF2z32LS5291UuI0Y_v6ia5xWL4Jya9Hk2nD7i68JdX_SzSzfnY
Ws7d01ksSu0DTXYmeI2uVf0XayMzN_fy_QDn6abW4CC06FbynKOy9zODjk3lYetyNvVftCXVo3Nui6E32IwRCCnbBk3RXWq86IhkG1k6xGt33Wn0G77LOEg0
mVCOlyHymyILS61Tzal0w2jyeSz7N9fvsM3cxSWP63ItI6043206fAg0CSdCZmr0Z1ZIcg7eXnwCHxE6VjxmMKF_phY6jmmiy5b3_youXhSC_Gx3PmtzA-CQ
tZBo9v8RMZFS5Gf6IsdTfUy9Zk-3yv5W5IhMCjAEAWc4GCc0t14ab3IQcoS
}

