sprite $AWS_Backup_light_bg [150x150/16z] {
xC4n0G000CAWs_w53J9WOG000C39jQ8bnM4O5jjEdFl_7pvkw6eyP8s1u6bdJYyBq7PLMv5Ce0kpz6jnqdP0BqIA6y2N8INDGIv2okv5KhsNp2vKgl7lqRXG
iGwLG_NNQU2yFvwNQQ7v-bo45UhZwtO1g9EuNCH99y6cO5nqThLw0uGRqA_ZwXTn-75G6De0nOld3WeyR_peKDIDo-GJnmUZvYLay0U8ZUoiGf5v_tnah6Vu
0VujM05wWaSiBGAheC50lH_8CZdaHzNxmJhFv0VM-q76gjuZShc0LIp0UZz8MCKUKUy77dR3inkPrNwmqVGoFzWuizmFwa-ECPLlw94Vn8WzelCDEhyurFNz
eNL_B2HS8v7vKBuVopeIqGFq3LAnvPWyL24Yhzkq854PdPrI5tyoRWlOdbsH-n1SyRDI6QucwuqpxlyHccoJsAV5ckvsn5t3iu9MIBlTC1GlM72VuiesTxOF
yDZ30YNDd-e5KMd-SI4h2Vp4obXDr3jaXKnUtlkLrTZSKZfK2-5JNzwEzcSd_V96lrzbS_kDVsXDHhFcBwmeNC3TyPJMN6WfM2U8-i3S77Y05H2V3AF2DVmL
RMVmz40ZVKR6kQUkTGjqFvm7jXBGcA6gmyoU2U3WXqs8yOru1XFpWVUY0B3YlAbP0yCDM1U_dlMDcoI_0wZUOwJR3YTSNLtvvZiJrTqdXjCg5kqUP2T8BIZW
DiQE3Oz0RFluT1dpSXui_QGMWbL10yDPo5JLNd5X3MQsBxMmhpFV-xNgNseWBY_VO2KuRGFnBVP4QX1H3ug-WL0E60bplme4keDuwIIo1OVDnPpFD0jFpcN5
kyQNv_yYDKlFwMb8x2UqHphYOhuAahd4tYLKbXzPQemzBlwC1a3_zenbK9JG-dIhW88JyAmgeIcaXVVY1jObDBOvWWqqAqdcB2mi-0Ib3QIYsAf9Q1Hm_QZV
2Vl59ScStogsG4JDRazD1PiYIR5h4jfxvGfEX5cNqFWWku16ieZB4ZhcHICrlCg41cONEXX9do-4Gs52pqVQzaYsB9bZPMZS41nGPEnn4sprzTNVBMX_MKAJ
unZAa4gIEMwX9ciAHzGs44ReAn43rGmik22Xq_uvvdN9xEE5LBKBkfFsKBggaW-XYeG6wCql67lbxrK1U_lu8j0EAohzEGe9OrX9S1meLFcZ58oOvfPWkWWD
GskTNGtuJsDDmF0td5lJGCBZ5-7DNQjOyQUi68__XrfXae57S0BuGTKa0udJZ3TaucsPIH1-qG-mH9NUIHnIbTAVQBOTRs_LEVYoI4Pz3kBRUapiEOpSD_Dr
C6Lc6M-iN65cjJ-NmD_su5W00000O92_zIZsLIi0000W
}

