sprite $AWS_Snowball_light_bg [150x150/16z] {
xTfNSiCm301Hq1GBxd_W5AHh0Zc1X77Rz-sogdI1VWS00000000065KIrB6hwIH9Jl6kBebwFEhwigQOEeOUQemgPcg0dLDbQe9PxDoAR995QHBB2Xo4-jUT
73yzQcnhgfgbo6_AK2ChQeRpf4LDZHq9kqpybpVJhvhYAUFp0ezLsVEBk9fVrSHLR5lZLNRun5VygY8-EuZxgkpb-zIrjdarJB5TkJQxRSp-AelotzVXDblM
CLNkhQESlOBNPd9LtpY4mr_eagjKpj2BL5NPL2zJrMLJJwyAP7LDhugZoaTL05MBX2ovLH9qJLLKwJz5gwYYYYgggAAAAggeeeegglW-IDNr__h1xrS-ggYY
QbvbLTV3z6Egoewil7_35ucAJmx4fopY_2cB-4HAd3-H4f_UYVEdTwvzqkdwfyAkVuBEdpQSMTE6LpgPUNrP_IedVgz-EXe000000000y0m
}

