sprite $AWS_Snowmobile_light_bg [150x150/16z] {
xC6n00000C2WU_x24wa20000PjSyr2E5OI2CRE7H-x_mjGqPyIKu79vbVKNfnU9NTTj_Kz2ybELTIl665nCvUNPI7Az2gajFhBu0RBNbIx7rLgIeEwSuiFq1
pMlczRWDYapc-3pVIERtC3a351rtCiGtn17RmofEbuFX9aVL-AtyyniSHQRJNFQyh6zRGAvOWcUrA4RZIjJR4_k1uNBW_MbGzThWaWRheLnWanogZLQAQnDz
F5-R8kNr6fkuGO1GurWoAkCSEvwSHGJbil8fp7X9_4peTGWrpMMXCwdcqHRCK5qCDNK37HKK2H_AwOjcIdGe9GJEGlceOWP3ewgtkAgYrZlBfgE2gAnzkIZr
e6T9adMvB75af8snO8WAX_cEYQWOmbL2XKlZSPYdPJgg9cYa0rIKsWOKwgaeRPzORGwgfUxQkqz2nIRbPBoRYgEm7T-MbExbrLISjTOq5LxZ47O6RfqdeQ9u
AiGfgDWFwdHKAra4pLr5XIcf-9lpLF-fC2sL2Qa0y4a18FgZE8Q_6PXnFkqCDL-QjBUv3Lsgu1ZguUmyJeLT5-EDgdUeMbemxArp3HMM9BkhPp_Ki2uK8nLN
VSDKvH6mnnTxV2vsl9KXpzj_-VQlmXKojjl7iBpcNG_to7a92gELqjs4ivgDK6zOXrHRhGMfkFCIxUZNVArZN-xtoSxY2EvILLJWD4jhxTJssHdE64whWD1N
FdZwmPTA6EtaEYGpUeV8tfyF0ewU5BNiwaSD8jVJka7Lde8IMyn5fsgMdrZtNiXVegE0_-MY4qYdXVkqDWQkswQH3P6TrYOJS_kqO3uHgezLH2VR7rMufLTx
ePvuUSf6Rsrt2o2-CGaWKG1diXQ0-1BWU_jsR00H0011y1_zrom3G3Z1JXkt1wnBm187h9RKmckkuMGvG5OMP95YrZjawSHMONv1vzU6VfdfLwn-yUlNqUU6
O09ASg2wTnyA_fl3VxwifgyleHvLx--pddg094cI94ao0m
}

