sprite $AWS_Storage_Gateway_light_bg [150x150/16z] {
xPbfjhCm242P1BB_1R_vSUpHn5PHlu7xjwtU019Yspz0KHH5KHH5KHH5KRY9q0SiQktFG1bX3atUxaOGbh3TwmGTy3ulGmY8HOGG0lQR0yNQ0fCmqtO315_W
ukREy8sqoy5-GCABxv7YZPBZEwIcreUlr-8dofclhYqDgMqjQrUna1ffNPe_RjlGXQNby06sPuWSsiJqWTYveRBd2v2Q4Vo2UcAew9KDW60EdxVzsTDBM89d
DL1gpyBX8Y9ycfQ_DWxuurmZ9oLnUh47uUCgx9pMoY-cG6FRcMbHImPVtTnKTF2q975yoZnZqpw-Kib_32siZbt2ywqy8zo9U4QjOXoCKZ06IB2Yr2Cs0wHO
6Vn2rbhQjOvFs87aN0ad6wcRY31zm29YrltUX1aJX6w6N8LW2R9wMyNvi9QDNnsO8FH1iO7N0QtHppsKHcBUpm0TUVfmq2q296BvX8bm-rMR3S_WOwmhPGG1
Bj-AcixZIDRJoZpLHC6EMxNow5NRjBS_U6UgbQUFKqhz_aGxWpMjXignNp23iAAjvL1pXkBeghH8YdtJzTBET9imFEhQoasP009YjPL70rSAWNA6ObnKYJB2
4cHRh6LjWIdZfqMWjZifpjnjnS3sM_deIiumXdrWu3k6ez7wbauaQjy6RW_RjGpYSeQLZJgfScWbMtclhkPr3wGR7NIyGZ_o32wjR7lKDTgssdScuQ6LjI4s
j98TLl6puNsEMF6-BggHmdohs3hsfH3FiOgzVsSAvIIh_QDxxFNvLhp_LAYXbMeLa-EXm_oKRiMnt5rWZ7Y9LdhulqsClIx9AawscF5-1oZ32hF-GOaZJOPL
I4tj84xfLj8ISC54AzQMXQbaM8bQoo6vj_ypLcLLLcLLLcLLLcLLLcLLLcLLLcLLLcLLLcKbdp1yaF3j9Aiv2T_-TwqQpC64RwTWJ05RmhV_V8gYA8gYA8gY
A8hY7G
}

