sprite $AWS_Snowball_Edge [150x150/16z] {
xTg9OkGc3CPnm83qwVqVkBL8l7HdmBPY4hNT_zv7af_DOS-1A_7Qw2MuPC4b2ovPSCc2InPSik2I1PSik6J19GikMN39WaiMNBBWaWMNBBXamIKBBbbmoO9B
5kpvLC6d2ZvL-2aLryUZBweunx2WMBwYoc5LiPfLMrXOCQgsiBHYKfMmboe_lH8f1uqCAcu7j6I385r3cq6b1vI1XIowhze_BgB5HFKr7cnetABwBcvLFURR
AlurVfG6gvkmLyDliJRQLJRMzeDEjrMadx_D-c4JLPblLOgEDbNxpRWwLgKmPXr3Q5UbYIgDLM5I-RAAsz4DrYYFLc8Ph375f2-hz5SU_OU20IkDfeqUp3Eg
uTQHC60D5tvThDAZhk_R1WEuNaLXNkIVK27ELVbdL6MkefzHeKvCYNcvwcQiULF1fme-LV2fmdUgc8xgdMYbYcCmjYrKKJ3dH_L7XHirYJSLZ2fPgu9H9MjL
CAfahGf6bQnLmQWIdohngHAVAl6f4fygMQk2KILhLJ2gPAqAHfKiKFKPLR9M1QDArgh0scsLh53LloDeHfKyhg8Oj5YKPLF9moeEHna0Z2fvLhM5Nx6oR2gP
gsWQFglbzKM2Z3sZIgQgUMZf2zOnb_Jv8WPrBrVnQVAsBweuXRxjUC8o5gvRIjcc4hFgtTCHZBtG5PzK8P-hNb7bpSV61rJtoX-MadJ8thyv8dstAYbA8GNe
AphbDsLjFw3Qy3OkXO2YBFh-4OoOfQniL8bDrNP8p58LZ2gnN_dAwRcgW54brX7iLLHoBeIkz3d6twHwVL6uz3SoBUgkYNOLtJ7bs9ygJlqMzSy1r4mgXBr2
5-etyFZwL7X_0cEtTrXKieMhzQyPbcC2QUdprtxcLRGiAiGxgXYqpD3AyIVElPO-TdTeDrNwZnnlgBffVI2faqIqGej6B1ca1obQJLTLtA-DOwtrmqR7IUoH
brNRSR8qpEiPlssM_7PpfHHcSqi6rNOiDrZlxyOIZb9_vb1x5Iwg92gBRx5KHTTKw5N0HHK7RIjqiNvjZKTmfC8rbTJGCkmCPJpRH-SLkAOIkg-Yq9hj3Ftb
4NtNLCBRNHNGFeJckoWV5wO1IwPnIJTL_R3DhpYA7B3aNZXlktPrRlO1IvvbzHlH_4ucPiPhHfLSknLbZE_wk9jI0vOypefj0etlaClqljweaci3E4vLZ556
bPmF86RnYTkeabDLFHtZZ1bBdcPH-61nBJpUEn8ciJpEoihQz8cE2lGrPWbdAeYnQy_FzhiIxTnKFYz3HfMT5L-VeLLBh-MvQZaBUtmB1Ld2oYdbYggwsaQr
Bp6MgGIdwPIduoQrVZpXZRDaAIk7BcgNduhpP2shGsteMggI6oUB3QebhFv6Xc1GBMC1j8TRoKAMFN794fSiSSaIbonnoHANB7794fSiSSaIbonnoHANB779
4fSiSSaIbonnoHANB7794fSiSSaIbonnoHANB779-Wi
}

