sprite $AWS_Snowball [150x150/16z] {
xTg5jkCu44LHAGRftF__tmPbU5BfvtgkrNVWB0vkCucFD6iRVmjB5fOiB5bOih1aOSd2aeKb2qiMbYmiMLYoi6HXoSAIXIKBInQMB2nPMBAmP679mfA59GjB
5fOiB5bOih1aOSd2aeKb2qiMbYmiMRnlRAsWxVoCQZnQKOyphJfQOKTE5QFgMOJDjjhkldTwdbjRZOnghLDzLco9ewzrAw4Q0UeMrboiyxfgpUO9DQmrpTjr
LV_-DRutzzvUrGUhzfVcQWHVskVg-qJtwwerYm56Rr4pLeqMrTTQlZRmd6e0CqQr8rOTBMQjBJ6l0jXRN7-fuhawnws5-3bLV-xnNkzZPxJAZzVxoR6-rJ-l
MZyVxMGF0jOHxIRN6_UePhINxGJrQ2yvxbC1N5g48pxG5Qjc-q7pPwXul4SzgbMfCvtZvwWutw5Eg5ObyrJXgIAfKgsAf4grAf8grQf8gdH1jRTKUqAbZwjQ
ienAdYfvgdH1nSNoAgbMHLAbMXL9bMfL95MgLP5KgLP5KgLQ5KcLQbKaLQfLaLIfLaLIfLeLIPKyLV9KoLCbJvLgLIHLgbMHLAbMXQUA_wxgVvLkkVAwNQLQ
5KcLQbKaLRhdxaUauWPLlb25fmfF5PugaYhLgaYgLAiYgLAjYengtiUQhrKaLATkOns1YckglbZSmveBrL-f-B0AIKUxlVsbYe-gXYJwtQW-WVFlAYweDFlD
g46WuiUgxvPDt-FeDvhs-TkGfKx4KjJst2NyfLjt41iHIr7hUvqQrdEj64GiXJqMQrQmdgW7H2o5qLRRcFUoVXjjE0bPYZjRQGU4B2LOjIXuhzAi6_4xUDFK
-wf6H_C-9QCqMR9aoP8bIvOiMR9aoP8bIvOiMR9aoP8bIvOiMR9aoP8bIvOiMR9aoP8bIvOiMR9aoP8bIvOiMR9aoP8bIvOiMR9aoP8bIvOiMR9aoP8bwoi
}

