sprite $AWS_Snowmobile [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaoy2yVIWuoa9H01Q1szx_VV-o
OevE5791Cdks5vnFUc8OPr5Ewxgyigufy--gEC5pofhubrGKbrf2vA-h98UbcP2-gk9ugfH495kOACMZD_AtL09JI7Gr4kaWYzzHfHSfy_q4mUa5I_DL55vj
qvgtAEvydgnAHrEB9RoxqamLXs9wAoWDL-1fAYfVWJoBpzxaD4cLIsjuryJIwdcAAfQcy2_L77oTousAqhM3M5rJbnULUZSsqSDoedB_VYkZ4HzJPQ36MFb1
5G4rokB7L0pKEEifbOG6ojNbrt4LrhwebRWcY3IgGli5qITOuQEkzN7xFVGKWxOx75UbLgVohubfM2L_UgWwqsZ3OLL4-tbIRyCqg1ACFr_gux1VXQeIVP35
gAnk5Q_OA3XJdKk7PuOesfVkojAfgLHMSAhciwWrmPlhLQ0_yNREYZNLPwobEtmtmOUgobeM7bBHRN_dgihcglIk2LDTPP-fMBtPL7ep2jU6okQgz6OKjbIc
ZNIha3NB8VMEPIKJLKW-TonggcoY2bbF6uVKLjatL9Ya4enLbSrHaVuVeXXEjPKRAcIY2gjM_cGGsZ7NjSyFgJGle71JXSnLQJfKbaDbSrKQq9iyAfkhoh2u
L3QXjoFKgx9PAlnDZyh-JfLzGqLkbNr95NmggwcO6JvXPccgX8Zuy3Vj5UUUTJapnED34ofh6rTLWZBOdQOUbLshU7c5Yn386nKTDWoelSPEvYvNAbuEaRWW
wLQL5oJ8hjB6hkys5wfrQx3jbx3zl6w_Sdr_LVvNsbMj7V9ztdhxwrrR2Ki9xSj8hAcYg3BAO9Btgi22AlsFAiiila1XLLJhDboFgjOhhreksYBh3W5Hbjl0
Zi71vQwoGrNTGM3IGYMWvXggL9fpByxgLe4byc1TfG8iXJjLaiCINlU9_dCofeeelF2C0XhsyT6dsiQA7keay74yvSfJ7bJgAggqu5A4lj2bid9NhpP00dw1
_3tX-ByIhXDqIvVgFEh30NLgEAe-caAPOrkMzAZqV8LmMDF00ghAMkNoBVmEbSNp59d27zFcP7oOe199oru6tJCfqg5wUs8Yp0S5CsixJ8Gowri_zAiCzVrC
w6AFuLVXITmp2LTtwLPPzZ-rz3y3TQjmTq-rNz3tU5N6k98ZtcVONfLjQuhfUDRABj-ZGXlcSLQiZXo72kDmeL5MNkezrAao0ciKnNeVfygoXzN_OIcdoY9O
8wYazK3bOULULbd8jHMdod1TVsJzk31K7bOGTOS3cgyPg3nTthyc9byvfye86r5VHVdUbHFpHV3fw0yZiUDEp9kqR4dYCA5BJL8PX-NJ-kBT55WdgP2C4mhI
E8JIEJoi9neNm5WlWaCJQEjPAaH-d7pXtIQCaoymJLOX-j4feQnTiO5myqILTiR68ld-z9dsnmQZgapvnqazWkXtLAOpyc-pSom00000CEYVF_0qYg38LcGh
iXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcHh
}

