sprite $AWS_Storage_Gateway_Cached_Volume_light_bg [100x100/16z] {
xTL55iCm00FHR7N_0vTTXL4kpfH3lo_aPbUaO2438tHOCSR3qBtojJ-rJBh_A6qpD6eeQMZKKDhmZ24sDBOVZv4ZqvCZHZCqLDMulkQCUxiD_zF-r99_V8-X
lf4v7YhLE-QgQCXJlQsSOKIo8JrfPGpNsrZ-lji_H4d3kyjgzr39aqqpdcDWO61Wx0m30mC30mC30mC30mD3CuKCpHOnj136gbNo1WO6ndXRLWWP6FFH6G
}

