sprite $AWS_Storage_Gateway [150x150/16z] {
pCut0OG0002nyJ_-3RFJEnS5iSV_MRy9oPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMwu8hWRcx3NDTH040t0417N_-psNPaXC
An4Jfwt_pdNU1_KJep0H001Iv2zHCOQb7a3oQLMYdLJ1-9EgH8in0dzCnLMT08WGwj-GpwX80SXfsucyJob_G9NWPwxYSq08glRjglHJajZABS5vh0ieI4QS
Sb3MErL12sMcF2ZhVIhSKIPh_JlqFXKhoi7YTwcIeboijwXq_j3HGS24fJLKgf2oWxNDeJnwYYi7zr2fsDLlyHeV3DSFo95IGUwDQWxXs53CL-dn9zd7abO_
yHkgeALoiN2p415SO0rCOCnUbXpx6jB4dwoAZmpANjPwOCQaGqQZrRy3my3D9puTEpAuultBYl88YxGorIJAP9MrhFptH5rPirNt7bSUQs2kIYoLdyKwXPDL
ATzY3Ur2_mtmpkEAXWN4MIgz9TnyN87znZP1jPeibP_58rVPxehI0NS_9CLb6tHFnNhAnfDA9MOYmhN38sAn9b4eE3i83mh41X6qsXQCqjw9WYwMO_hO-cCA
ocZAfCLA0WvMwIJw4hhVi6mOIOELkD-T5fk5DagEynO0a6XTNA7_gKswIxwOBAbGjYdGoqQGIC5sxQmpbSb28wIq_rsZsje64S_oYJh5AXOh6RTIsgga96j4
iFC9pejLB5PibYg5hG3PVrWjGLehdZkgucoAMKqlPU9r9Cl5ZSCQUwhIZ0Lgeu8S5pT2lUlmkFoDVCBJS2WMgvMVONcsCePcWlBpMbXIurJigqg__HGjb2D9
0wMTtX2mKrMCzjFuFKq8Uw3Kgjo8B76eoeiWDrGD4r2K5PiuriSrrQeyq36NUlXLibU4N_VZ9gPQbI-gobE8YgaA6kwT13seillEKveitOEMIlf9ol2gokxL
Rh4UCMUh-eqyDrGxYuPKvN3UdQhok6fdGIT53HRh5CvLrPzqQK1LgYaCyrLvZtOPKPNgeA39AcLrMlTYizQpVgfAMTZh-cmMAsksAcEtGswF-f5hjihn0bNE
MFfAELKL7M-RnS5Qa6Uf18FdybpEMR3r1JDKUpk6-QAgQ3wiOuPgGyMSiqDbin9SL8cf-cbJ_xPh5saH104CXN78k_zzSHbhorU10FEsRV-koqmLEmFXKQhT
cQsfOcT5Q8JgSsrhYSKwbZH0TPof8gkIgIAhagaYgvAf8gkIgIAhagaYgvAfmbAjlzjKaLN9L95LoLIHLSbKaLN9L95LoLIHLQbJfKwLEbNgLAbJ9LD5LYLJ
HLObKqLM9LD5LYLJHLQbJfNAL6VLMKMdYXxLxKlNxxv5rTlfcRHgDu05rKxVgUBdLUoV3M21jNztJlLmVVNPzGCBhFlTk-yzbP_6HoMBIXQLB2fPLBAeP579
ef959OjA5fKiAbbKigXaKScYaaKbYqeMbImgMLIog6HHoQAIzGG
}

