sprite $AWS_Storage_Gateway_Virtual_Tape_Library_light_bg [100x100/16z] {
xTV7ZiGm30DGNld_FxoNBLeOD417oZJoCeMmtjGanb4IDgR9Y87BUGuZHWoIfIq1oJw3TngeTneDt6Xms62PE6BWhGoE6qHf9WoyZL6AAGDlRloapK2puIU6
JemOCSJsJlQ-8JQHilSDjLNLlMsG6qJqfa7k4DLRnhBgFw9xtwZLEhFsdh4Igwfxrm3K4D4RHYN44DrRXgfrtsOGO8F1AmODewb_VsF--y2XSTl_uzd-v_xn
oZ3KaFMuAmZFyCyVVBBp87WKM0QE2DF00M4RW2juXgzaRp1en8Z1JPeCRjDYa1OImr_W6p5YnD2n5lX633_95m
}

