sprite $AWS_Snowball_Edge_light_bg [150x150/16z] {
xPhhUkGW24114UJzNtWtitnZR1isDHFjXVEhD-qPG3GNlKGG144G144G144G15LUpcKbGhW1PBq0mLsWw2WPReGdI4tJAh2HM5zD9NXGTG3OA7eB202GHokT
L6_KgcFZqErPQiWRpWoImKIqWfJahcw1D_XT9RSFdVIpo7D-XaCSA_PQbKdZk9N0CNnibU4GRFCFMoKu9XzRWGDVjgfm46fofhK4oi6qwPgLDrhS_fm100yR
pdrMYbuZF5puShCLFPBqCMHDShwLW0_g2Yj5S2bhh1XSwX8hFuT9TOsLpxUt2gkmaa5kjK8OX6wq4XXclLLOZSyLLc4LLc4LLc4LLc5rbh0QusjOoL_g5xCI
X0TOlf8LFA6lOvMXSQFLoOVANCI6DEW-An_z1o4087663R7gGksORPNVFyDWUmxEb18jiKBeg5Rr3NobbT8fAuIEyi5OdBOpzEgid02mrFPpX4QURPMUZtWg
QmTlNfXXWsPREQ4eNAtmGUPd4FKOqwAvLcphpc61LNtMbUlD2zPWqIV2H2nlAmydLtlVZnZVlTvKNx86HJy1OPUU14_IrGIs6C46oGds3HpLG6ZqFyrNh3AS
nLv4Ub3wIANKHuj6-zN1Jdjk1wHzge1CfALD1ZUTLa-2dx3gojeaPJSZzgTcKG-_pt4wQrNxVoKsoVkqbQ6JWzLJ7SoxmVst-vLNyq2mR4QyPaLMu4RgJ-u3
LbOJA4FLw5iPGrO23tAHatHhoy_Wk9KoEFYTWVrgRx-iUhVMBi3WTuQsFUe0DOE3TyqbVXTj6zCGbTBG4q0wiUFOnZI9V6ftDlTfyBcJ3CvqilHKxzHdSPiA
MbWEJyYb1NDs0XsikSvFuC0rq0Gh_c-EIQSYO5gLYzCxqeeKGaPRTtkuMbtDjz8CHj-LX3OPRjlGP11sK6i7VPjVgwKRTQcKGIaHMrldWzktwq0xPTiXbGcj
rfP2OBJBoyAwd86qpGsMVY4AmWCK_Lh8XhwG80Y280Y280Y280Z-
}

