sprite $AWS_Backup [150x150/16z] {
pCu50SGm0C30SXl_Wf-PSSifE5un_gjVGTb2sKBPGjb2sKBPGjb2sKBPGjb2sKBPGjb2sKBPGjb2sKBPGjb2sKBPGjb2sKBPGjb2sU97hP9MYcN5zXHsYc2r
RwLma2GhHWudicIrfCvCzoH4OI0k423a_Hzu-zT61xlaYZlRi_LbZZxycvGLmRGNYMWlMVeRL6-Oo2z5wE7tgDJbf-l_15NUNihyblx-7IgqrP5ROAplrghy
iLhHs-Aby15Sz7sgx8wOAdm4byjVfefLgbS9Jz-aOWL1-UzH9KL8eHeuvp-_GyMaPScb9AUEIipPFn-8ZsqUB_bGTF0yDBqz3_J8zTmvxhSEOlflgVWux7KQ
5iLwd15Fyi2bWbIAbHwLwq4UU2v8TMATxp9HsVEW5AIgiHvaX3aFkBIf5CkU4VOyw50fbZqZdkG1KW6MCIECUO1ABnN0CcQ48G_cdrMRCs9jrOSsxsDPCyAK
1_DOnemOvO1_AJBamJGMPCJx6qD-G1Msgw9z8ucsguAPocsgWSqvaNUwh4_SmCgVtyOToJGKjHmNFge00Q4AyrWYVN-75FsjpVNHLFORoATxhAZrZ3jVx559
hrJvv0kOybwd8ehu3YkSB7bGB6bXiHReSBsxeJgzuYYcboAvoeE0vTJbHzbobqgQ2_NBx_YoAcIyfzWGQpzF-Br99K-e0iCG02mRbJIeM8tVeSgvDGV0MvN5
ynILD3RBAkEx2BPxoxTkBdovOCNzMohZyv0AiVo1nVwkMIULAosiM9Ns32kV3oW_faAiN6zgO1HjfvhNojd3TFqEFvpLqiQwpo8NMTEYHrNYQG1j7IZm59Lq
XdCgoLrdD4SYYksd_FueLgpE9yv1iVImJf9SUuFBZD9n0doEHxtsT9jacahG7p5K6Sy4ewS_tFrHSihxbRWFByhSbrpL-7QgoiShj_dxQYrU4jRnKDB7mY7O
5mvIFCMmJYNt1ia6B3KM14OoK4aZvDVbyNEpJrG4zQI5I8LNW8KAiHB6GIQYFBFy9snWD5B9m21wpxTUgxYVdv5AyEl3lq7bzMD6Ai5JXF-ucHY5kv_zFqOg
mUG1W_1gNiMVZ35I2MGVM2rDP7lpOZPIoMVCt0-vjZoyvRA0CrB9N3DgOGfqXeIHIc12Lzf6nV9WFVguH8nKqedtC70MhhVHdKOgQSSxuyqnlimucKij8vMq
9pHjdSnYr_X0kSf89Uq9xTfO3A-rBbiZbRGdT7EhBRjgIG_1VfMHIhgtSDedQ9L2uMG66QdaTa9h0M6fVwx-OYDKGKOgWVa1Mo21SYubPmgRIYk53KGPgUGI
xvYLACz5XGr46Qcaoa1So89SMbmf6Qa4ugR5fJPRN98OgGHRM3iyE2KA4ReqjNmpKWbCQ8QjRZWIJEQsZ5JouGngDWJVWAv46QckyPunrp7VCqxcjcnKSaaS
Dp2AxlF3P9x34biBgNrDmJjWCe-nnD92hSJ4G-eCmTwJXKedDFQltqCCzhOCLEBV6VbIWFurUnWY4K43cp9GnKk4bv7O6Px3hbFnLYcNeJA-VwnbNrtEdHUf
72zWBJVG1RzjSpxHD-gGf3AFjNW9Rab4zAAVA9NcVuBgThKySTAFmNoCr9LNb0ChbLdnMWET_axRf0Ys1AQqHkMFtrUfl87gVrOh78DLHlY1D0zmssYinGnr
B2Am8TFRbk4pvVatg2HiEjZScq-a3BI_ZqW_M7w5gcorieXCP_jYgOfr3YQHCLQQduDsAc5_3BKiCeEL7IocdrEXcBpt8ScfeUM3zvvoMPCyLVaD_TFi70i0
00003Fhd3poD8YYo5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TaQ
}

