sprite $AWS_Snow_Family_Snowball_Import_Export_light_bg [100x100/16z] {
xTatSWCn44JHJl_zBwnurGMo1uM13ESdjE2JXQcLDKtJD76yTi4LcZAY5Q6nRuQEvHzgmb743Jn_AHnWzr_-NjR6-n5FZdKhWtLkw8x1MOEreKVsTFJQ6qDr
GrxLq1LZtIr39mpz5qCAXToers-CiVpDyggIGTNmT_vI0s83zWo0q028ZN0LaVnps3R83M8ZHtpl4He1OeQzDJ1Yn3UFaP4WRjXRi_AHFuXGhZ1gsw0mgcgC
aLSOzm-9-dn5Fb-Xea4-9rAR4tD2DWDiheFaws1zVvN-NyZUMZMK6nVsFerxE5NsSDBENbIF_jlvOumnE4AiZSEvSHoH6VGPRT-8hV1s_uYWnVtk2mTq4g8n
zIDNhdcr8pUkGNhJD4tJ5m
}

