sprite $Storage [200x200/16z] {
xTq7Skj640RXbK4LyCzBzp-jSrnR03rkiIaOVOEFSMDX_1-xkhhwzkIH13yAuKSf_2Y67yJmmnYNWuTyEvlZ8_vPdy_npNHSZj_w88xBaRqsghNPtnnlqc93
U8SFuHqyH7Bm4Cd1GoG73v4SF4Hoy13PmKDuXm_X7Jw4T_WGti53U8SFuHq-X7Vu4Dx1GtY71C4T5eHsQ13OuK5OXmX17IQ4TAWGqE52E8SCmHmsX7Be4CZX
GoJ7RUnsQq0CnpOEMW28u40WWYFZi9S6n76yzMK788uZamE0E8vCZjyWQmEYEZ8xNiVFDI2k8vDZMm68uSZa-0tose2eZamE0E8uCZcszGM028vCZcrxQGws
P4Scns-GfG4H7EFNaaoEFgJdACgHsR4jJKZFKPGZisDRccEKdgCeHoP77z9pLDinDpksMnFISnJboEpONfkZnfwZQCSC6Gr8nr6aWu7q7FLUZlvWg-Sepa51
UewY7C4WFKTHZd-0D4UDFKVzr__1X5xPwZaATymzo55dSTG97FT2kgTC7-ieoX7PKPGZigCeHsH7KOx8Zg8SaHr5EI8xYd94TXJbYEmeoX7PKVSunXr5TXJb
YEmeoX7PKPGZigCE7FSdEufoH7OKvOZiACeHsL5dSTHP77KMHvt2yJhUhTi37HdlsBzsN8uwa-DmyQ4niL8SA4Hqi13F0KCq1msn73X4Sl0GoS53NCSCkHtj
q3wdOuQy7DyzU4R73BcDmvPdTCoGSKVFw9WXkozuiXmv8ZlgphdXeIEoeoX7P4THZiYEeXoH7KKv8ZkASaHsLFjtTpRAZXe7tUk8x6YFIsP7N4T_d3WxeZgg
FswV7L4SmCHgTaHs5EM8x2ZA4TbHb2EoeoX7P4THZiYEeXoH7KKvqdDyeXn5ET9pVA8SHJdIStoY74KvqdDyeXn5ET9pVEex-f1jpv6UuzEHO-KXwwuZFSUd
0yTIEEIxVKSQZdt8yZDa3GfPVsOisQdXs8LiuzrQTwqznwV77vIvPR-6mu3SSbJ3iGlP5bwnh3ckv_XKL6a4E7Y8vE0XaeE7I0uU8ZbuYEJW8PA3XqWE7Y8v
U8Zau26IWuT83XuYENY8vE0XaeE7I0uU8ZbuYEJW8PA3XqWE7Y8vU8Zau26IWuT83XuYENY8vE0XbeE7y8xdxt9SpwE_79VZOtK-npYTOroEPs7CaClXCtp8
vHXp9s004a-1I7m5Jl4HV5TNFm
}

