sprite $Storage_light_bg [200x200/16z] {
xTr7bW8n30PX-ScWfrNV_xIJjJ8vUFn3rPBy0PsJlMD4j2sUCc5C7r7fAofzHYNFgDPYuDXECFGTYXFhrtDi2pXmR28E7BbqHnsRjWC73XmuSE30WGC73Xmu
SE30WGC73XmuSE3eThAkuh0pkR9ZXEWxhCaupXYRlACWyew2XBnZRp-5kYEZ8EAEWkp57GD4rf7H2gBjoFo5xDGT1N4DX_qrt3T0T1tf1T5s5AJ9EmgYEvnN
lI3YZjp_GaBSKH0BKSS8qNOCCrjoZX4YwXWXwewQ_TtfJ0TFrzKT5OwJ3XmtjAO31muSE73Wm64NDC610mV3kPG31muSE71qUrfzfiEUs7ixSEGJUcS73Xmu
SE3eTZ8NSJGxKvDmT3kRApZiWbGSdaTp9KUU20SE73WOxp8Td35VmdmYy-qi3-B0WGC73XmuSE28npFYFnp-U8VFTlWF91whYDzNdUa8Urenqv7zMOoUKntP
9p1cE3ByyGeFpdE70mSE73XmuC210mSE73XmuC210mSE73W4mi7rw77WqEdr7FPo3iEn2AF2iGYZmh48ez9dLFgAIb2XJh4P4Nq2
}

