sprite $AWS_Marketplace [150x150/16z] {
pCwn0K00402n_cN_UTKg09S9OcjvrnmasP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsNAcDIjxPgBZ8193mOGZqDZz_v-x
HuQKlCIAcQTXxz8vOwGkXKVR3TCmJ9kbXBg2QELcy-t9R3aRTGNHQhdVTkwh9OJwOWAALHjlWQ7PWJOaTLdBJs7JljpuMdm-1EgbGrs8rpUj7k7MBBUTXy6S
rtKjhrdlhECuX7XHdpT2JrtJyehj5QXnUsqG_6lOpBQ1kks4kgXL1Mecl_x5uUUXlXfG5-9rnghTTfRZBhz7ZRh1eTu4hS9gV3rm7Y3YC7_OKmVx9gLLYuaw
QX6eF3xKXSYNLZnz0Pv4cDEVIhIosegTo2EsK4cR37N9oaeh65lMVl8cimwXO0Ar5GhJVl56-ta-Q2XCR-tdSPrLc1OUxcwqdzNMhrMfpmIA-dLMqIIq7pDM
dMCTmukjw3imRUvnrVUwNMtrf0rloRV6gYISzdEvrSxordwmUaATNU9wArerEofMCBEZNcvL_Ms9XMW5_rlzR-L_Jol_AwpMDmjux7Kiifs26V0DqMfZ5Csi
siXEdrYnstz9eQ9RmSWC4woOPs1Ah5xrWSgFMMrC2C6AcnTu7AsO8ZR-_2chECEqQBLYIxr5gpZFF1b-lzFh0S4gEpllLcqCyqoelwpQGDrslldYmMjOP7wk
-dQSpklCCuHzbQrobbl2KjMrZGkhclUqFknpdNc6i0-gLHqlCbJLMO2mJu9LJRjp96r5dGILOTUju85LyVBjI2Fi5rXvEtC73M3X_nTPrMatqCAkMx4p9Et7
3OgmQrPjiSIgsaNThGoxRlNxMYsnyjXaqexaPTXrAqO5-DoTOrqCEtoUhKQ7Of8vr8kmIrQiUq-iZXzHygcm2BjizOokPLOx6nDoLY_2hbhPZRWNfucy_iUm
Dz4gZxjo4jlHmsvUnLstSZdivcNSTIitmZxBLddSPIkq64pFqwkuIrQWXTrwB-AkMO4KTkkzduzxOuR9qpszMtaUzjggduxxnWppuMrkrkLdmQgVZliKPvZy
pVUKvM1HhFhPk6_Xr9n_9HWj_HOaMVKYxkcP8VkYql8ZY6bMlOmxOB1aNvyWtlHHjUfbtC72bxZaIrqMTbUjUXrtG2GvJgTXTrUjUXbtuAR1VNL8mkxkgbK_
4NSWu4G_vy5ZgbhrDEvJ-JvasXpIiFiJrQgVYZkqWG4Pyh1_eLhrSt67PHmN_qYSeLsrwcdSDGZxnf-gLS_YhaBOGRNgITnb23keLZrfBnff7rAj-Y7ke43O
GRNgCUuWGjX1jUg73GS41gH0jOfQJUBP9zVMcZc0P8MMJWl3ig3Lhz4Q2LIEQjKl-Qb0i4grbk4PtiMgBue3pvwirKzghUd-0-Ul0zMg9ujnIirPwkj0jUgf
LFuhdByEH2kqzjcyjVquQ9vY-v6ijONhFY5PeVK8ZzIKtvlZTJQT6O8KAxI6E2Z__YiCdXAlCwuJj7e9OsuCzCUpNpxmvQXMtJTsd-pL6QJNbQXM_L8hLwtw
9NSGLAjhqWwYrKKx0sXMRxkeoxjeZcJLptQI9RbEqUg2rYfqvmh9gckJZAhLpyBKvv-nC1tAMlqx-AL4gx-brg_Dpe400000W222_NNNA88YMv6jo5PaAx8L
sOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHRO6
}

