sprite $AWS_General_Users_light_bg [100x100/16z] {
xTO7ai9G30HHBg3x7tTp7XUDcj8cD9NWU-H7S3fTcKszHvKvzJcgpCJdY38I6T458cFAJCJRPfc9N6cMsO0bBZC1Yr3-9gFGW5Kghx76_B4xRynVI-QlYOpm
59VvhlFr3PTxH4QKKSYeCXFUA22qmSZdhV4w7mYFo-SGyFDpFwzszYIVrZe8JCcZnn2P1d8f4IimSw028Vw_GA5k_a9120GCsbFJuAf4sat_HQ3ejuP1lNc3
DwzHVyqupgM_LHrcZI30U0uQvOqJH1nr4DZFl56Ay0Zh6XaZ-Dd7nJ_3UU5y1WHGBC4P442nH91Hk98G9KTmpHEYAOWf1AO8yGGF269on7zpqPz3105JK1R8
k26gCuWWm82YHNxUQ11skFw4mTDGeln_OuqrVFwGiGPdSmy
}

