sprite $AWS_Marketplace_light_bg [150x150/16z] {
xPg7hgim44G9DiNO_l_FVNMvpyeGpTKcyrhsgDmobho10sxfhoC8WY08WY08WY08WffJojMH2sdhz8FLaSlORvDnAuvSmf6cWNJmN4_BPtUp_R8qcgjPprkp
zxvFnaPpAUKKPcqczQ0FoLNKKvXSkr4_xbUbkOIsM0TpkRvyB5VeLIPZlqys2sWkU1eJF51m5LcU19SAz03XQAweQjG3XnUIIwkoDz78FXaarrM5WqX94m2v
jggFBdAxVnrjBDTLDSm6rhjNDysLLOqzbQ42bckhihioaYlDnLNPx_DWTk6vk2fysdT7BglA1f6rEN9XLVw__KHLKLLKLHxtilBy_BlD4z1z7CCS1NijQUAv
_Lsd2vwSj-S6lTh8n_DaoGkhEeOPmD3hi5nc-QtQdw-g2XV2rkkutcDv-tNHSxcZUy25iFLw3CjbbXiltdWOvoZBZrvXEStoK_RINyi-NR2pNFNYmeKohW1v
RhBFkgqP48RbW-nTGO5zJvw3x08sNjLrzuV9hg7WVWVUmVRWQUd2ghZj7LbCTcLL-EHlC8u8PIzRWwhuMxGR6jbdDDHwhMJ4KSeEHpAV79rrigCCP2Qp3RbE
TkltzdWUtyYiJoExgNrLbN6G6R90zc7suLXDeEnMkK1tvqhBP9VexgzgiJM5G7TlLVRfbjubklkhik59eBkZAetifhklAfHTftiXEv1v-1jab-b-yDrQh6es
sNMwvt4ESxspdOdi0jrhOgS0gS57CzabkkE9ilL8ZkKtQwFI7R-yWATBI3RPPReRZPp44Ta5klDJIxNifZlv0X489POTTUUduMBP-TosPjZhqCcEkfFjjbGW
GDc5kYDxIiHaCrEck_zZrTxrkdDGThtkY5fsrFrvLj7Ua1_pKg3xCmXaXnCq3tFj0bfnyMESBDzetOt6nzp_CX88zKwNgctp3tctHjkHPq_puYh-TigpkDtH
JbSKlme5sWbfjjGgnURhpT5ECqRdOTcrVRgTa7cOABSRx9wJTYfCNPp8yNOQSBUkM6-qtHjK9RY3xsIx_ytm9czHFfBmaUbzHcVzJ4O_wyDsAe8W288W288W
288W-0e
}

