sprite $AWS_General_Mobile_Client_light_bg [100x100/16z] {
xTg53S0m40J1Ry3zjnj164--3--AmXCIsf4J5J67a3C8FOFGCmdjACEGZwmcnYiLY6RC7wcCoZ5cBttBYBc14QSOmZLyG-ZvXXw67lyL1WO61WO61WO61WO6
1WO61WO61WO61kC664_zTp7A0mnxia6NS9Hdw3rdViayYyXN8Ybg
}

