sprite $AWS_General_Generic_Database_light_bg [100x100/16z] {
xTh50G9144HH4gZymyNbWXGVrdzTPxeVBjkp-sjCtcIOxbpY06S20W0IBg2zFJ58HRsRbzKxUIaGYcf8yFfUu1qmySWyxiUlI6eZuK9l94Ge3Qmam2WSLDP_
NlEIwuOKXQ_szEz1-WrL6vSGe3Vk-Ge0HWqLBUeDhtep0qH3GqD3GqD3GqD3GqD3GqD3GqD3GsC3Co-ay44d9qQO2OymsnvnHZ_-MOFnpqnmPYvdM3Wp_faY
7dC
}

