sprite $AWS_General_SAML_Token_light_bg [100x100/16z] {
xTO7Rki034H1NO3tF-xlHM3A27xfoQAe4PZ4NWe-dZzVcOlfXDC9fnDE92xDHI8OWO0H21YTiD496vtOJs4qOlu6HYEM0YCHDapO61Y1eD4RDNCwsqOdZjD3
6IQwOQ9-LYPiu3iF17eLYB0V9CAx18IoY6NqxLwZowW41o8H31EpGiD4DKoeGZHCe4_1MCJA8c24HbsS8y6L61g5610mL5eJDbpQwyJaqfgOsqgxlDltwzvR
PwCJV3TD9xRWqduHfrlFHkpPTqDmJJlXsKxuRPE9VUk0qOZTr8qdOXlp9zlenB696HepuezxZJbb6I2w8S9FRLmc_9sVgMsOC4B3X1TavtpVX93x3HCPEPPX
miWs-Cke85imSHtPYm4Y83icEcAY8oPwkqoqFS5eG3IO4Ozbn4CDgKH4J4J4H4HCHCH4H4nan4H7J7J4H4TCTCH4Hqnqn4H7J7H4H4TCTCH4Hqnqn4JF9QBd
Azy1
}

