sprite $AWS_General_Office_Building_light_bg [100x100/16z] {
xTIr0OHG4431ty3sNowUuExpxd2PY4r7ffZiF68SOQoyn8YoPlCkWy5WC1ZHQTpejvJOOyJ3ZMvlCTA6_cgCVt8Z9zvdC1YC3J7CTWQ3OROpp7O6Ws6sCyns
1eF1CDkN6rlxeP4k84PI3W
}

