sprite $AWS_General_AWS_Cloud_light_bg [100x100/16z] {
xTS5Ri1G38FXNC3tF-wOhB-Dt8otM53C-zIKwqes-jHCZ3NgKxB6OTPOOuqrrbX3KkYoA3BumhTQBiYhfCQ0OFM-tK2KNJJqigupz6d6omPTDvoB32jh3CGF
n0-JhHhU7sZMrnl2zgc1cU9QGo93Jw6Xrf0K6f875v2Bg0aCXGPk_zcpX5VGqp8C89s1WHE3J61O5UgzPPRSA1f5GqwOaXiwCkeh35z2GaD7pOLXLTbny7aU
6zR4n61SFpRcxy4I3RI4HleiuMrsRXI8rc3ZKM0BLFxPj-WQUiad6RAS6E-Zb1hI9nibAAF0mDm7CArHqbp1Ypvu9ew0tY0YpUwCuFwG53iigC2Wqa6InuUZ
qIjkTLjxWqeUZak36GZ1F-USiQBSo9MFU7-4u-T63lstz_aQQwonnXfhhF5f6HXhfDdS0W
}

