sprite $AWS_General_Virtual_Private_Cloud_light_bg [100x100/16z] {
xTXPOiCW48DXNK3tlsxVN50iEhYYw_nlmKE-x8lXwxgkwxgEKyU0amnDIS5tWj05XWMpd2CMXqB4-cZ4ADs4FA43UK97WaGUaTrfn1D-ZbTv0tmjHtY30IE4
xDuSVLP2TqCHkHIu6_u6nGoTDcR0aBxGm0ysyWWJ1idLGCeWAyVhZVCSMWcyBa_7P49tUSGFgt6t_PQ5Gymjj0QND_eUcTRKuBjnZSwRx6rU4i1iZ0kJKVXC
DiJQa8ND3sMTySOmK41qMXTPC3mYe3GQC4RbWqcyke62WPh1LuCC6f27X4DVOU29WIq3DGCrWp3N6J3aKySPt35umk2d3KGC38Gnk6FmWJ7sWO4DmoALtUI-
WO8XesPi-HGNxeOWoTplbPC4JfrWayKOuw-B9u9sNiWZC8M5Smn-QbtNTLtNTMy
}

