sprite $AWS_General_Disk_light_bg [100x100/16z] {
xDK72W9044DHBv3x7zTA_q88VBj3tqdssJteyv-4yy3xVITrPC5NCen2ZFjT64ExC2PtOatlnECAQEYTLM1jp_g8yN4VOpx2a8ymuYCbC233NaVSlvoTa121
Q3V5Db9m1Ha83SaZZ1Iu_gtkJwJtWkdnoY8mAGmCn8GGNONqKZL8y2YBqOb-p038zg_JDrmlHbjrenCiTeH69t8RddGZrI2HxDqU2wOYRsRWWmfaDlWq-EO2
z0niB0CPh1mZzuteHjavnj_mttF_i_ifty5Jk_PH000CGZ7Kl-iUgu37zi1AVi0i0JEnvVuGknRS3E3s8JUSk4N1JIr-0_7ZW5zD_9pWTnOCGB0Cm6G0MnAC
3B0-mIm1UmKC6R1mmVI1cm2E1RWYuBo0kmCE4hXKu8I1smQE7cGDH6R2PpzyXiLdSNocwDVL0m
}

