sprite $AWS_General_User_light_bg [100x100/16z] {
xTU5ZG1134FHDE3-sptnuQoi-N6EOk5GtZ9K8XkzImn8CZea8EGKFQQP-Dhj58uZRSJJO8_nFAe0OKm01438-XQZAeXep73d0ODC19jdpgHRDs_KhQ5fWy_b
snOmrbX3nD3FCOQVL_bdUzxW22UuWH5Ey6yu5KCeGRTHXk4X0eIF0C97P0nnH5O__sq-zHF13n2YYYu2YC_cQU1IEC76T9E8hM2xVZ4xWl1BCKVuQvLxSyw_
rQem0WY0k0H70E7MKQyXG1349Np49XYIDoo28td38ZYIDmo28xD68t4ggfoXSQFQCsqeQUYj5yWQTjPOeoBvWqOiFz9Omy_c1G
}

