sprite $AWS_General_Corporate_Data_Center_light_bg [100x100/16z] {
xTY50OKm30N0Bj3zn_tkIXgSUxWUBYsvI6rEG4XaDaPD9c2KSA96QSfeHkquuwttdj-3RyiksM1SEZy6Lsum69ubZ6WOypld3DyC38Pl1iORydlG-pnvh5ox
tkSCXlSvGna0Wy5WC1WC1YEHeC58HFO
}

