sprite $AWS_General_Internet_Gateway_light_bg [100x100/16z] {
xTa7YaGn38DXNq3tl-vIjWM__12XwHPr7EDlsklrOfdeNsuu_uQCDeaAjqQ4IHDGp12m42AGJnEywXD6WqLmIv3W9j_mkloFmOX-Scfu-u4GmOXhv96pjzFZ
Vmn6sekuSRp9G1itCy86PsqD6Pox6JACoCR5JSOMhCF3dx45GxT-quhEFkpWPCT7T434aCkwkUlUz5EH4LPwhVP40K8A4-lqCf3L8EB7C14sbjdb8a2Krj6q
Es84Z5edBpNNg9QhPI9wmC3T_ISQOuoX5p9uf_W21X28v0qfQEnF1sC6dqe5ZDqmRV9Zz8u_NhiqF6zKIzoegqIDsYPaL2udyyOOOumnnXX3tKXJwzduKWga
JvRMKefeewKmiZzdg3poOm0HGExzyBxI0I8N87818XSWSW4YZzGj0qGMgLVBv0i
}

