sprite $AWS_General_Internet_Alt1_light_bg [100x100/16z] {
xTO7giD038HXNK3tlswe6POnFmZ6gPfN8ydxfRZLcxFPR3QRpQPRkNLzvLP1YGft8ur94r3C4D084SXd2EucYC50dj18dk2XkH6O6Zn3d8FzBF04-o9HWf6v
aKV6JsUEQ720s8EuCJvaO8o76M63Suw63CxBZ9uRpBB1G_190W_3T873Wmkd-R35snCsbCdDZiA6Rp0W5300yPOL2G7PMr0yWWO_OwiO0IEu0p5nhcv3RFWu
4Lh843C08KCBEQ8M842KYkg2mOZ-zmcrZzh8m4bhguQ6WWOiz7d66bTRTiSC5Vo_eD4NXwTAKQFL4ij6im6dIn4fmq_xJ7G1mXTjJuMDcX20e550eD4D1YDm
6KI4ZMA2RwNGe4suexf7XdNqZmNmcL7wouGoDqf_Y625ZMTGy8IC6cUpsMmscytc0G
}

