sprite $AWS_General_Internet_Alt2_light_bg [100x100/16z] {
xTK7ZWGn24HHBi3zhxkAcr3fjwm_cL8Sc-PrG9vwsMmscyrcqxzoo_wtSph457948iScmg8dm8v0mAPWq1q811O819U8X8_0rL1ry1Y8m0Z0jS9n2OI9iE4Z
K4b6dpq68-E7Ri10yglYQfXwCZX_IqM3hxxzKLSGtU0Y_x1hAEcVK0LsE3ytqYvlTqpemcrGE6m4rx32B_sYa9TvUkYEpZUHe54bP1eiT5nYvCeKf8zDtmGU
OtRA2XnCmQWX92KGqwYPdnQ01AEIGIEQ5zbW8UvO1kmPHdWevrrL7AuA8tNspVa_wjpW4ruqEkQoWUMZfMl42YR6eSW8BB71I47muTdWiA4hewE4GCDkWQ5c
VOi4t2K0yGbVgHWB-DXiDflDPhFPV04
}

