sprite $AWS_General_Multimedia_light_bg [100x100/16z] {
xTd5eSGm40FGQK3zb_jnoJ8iM0gEBk6yS0nnqcHW2WbU1TOSq0X3o0XBLZAUFtKnc8aYdnkWUNOZZMAaNagZR1GZHcCtzoCD_xV4aFqRQU0n3WDLv0PQaHhe
HMUW7u51H6VMl45xOqLX01WhyyPrHmDbmYXtWm4YCRhNNs7WB_tRGdD41YFJ1lqsMuhFuBTnrYX6QqLjqBrN6ErT4Q8mEkFqueWDHan6n34Cm6sW9c1xTltl
8A_Z_vRuludkRxl_7oKo-5xNonrb1YRyPHzP6Quh03ieYnP8Pww_Rh2NEiuOsK6Ta-ElEpEJxINPRv16zXiSvdwaaVq6BWHaE7908yo4MOcJ9lCD
}

