sprite $AWS_General_SSL_Padlock_light_bg [100x100/16z] {
xTZ7OSLW20HX6fZ-s_N96QDP6JcAux_0zt9GVQRkWZ4yY9KmRa74qc0CGS_cMq35ZkWxiQabe0bjgWre8fSU4oydciTXJ8-GvvmFguxI6MbkMoVCwOo8DLKY
dH3nHCgmDHfTlQqOXmnnlYIzZtWYHt8284Uy0K3M6nAygGo9Y11fI4UeWTP04LKA8Nv2Y6zL_k8LdqdsJIW9Fs56lD66pXWoOLZ4t2eT7Oo8OscG6eBuOgDs
ZTetRWDRvms-pxWDr-nlckZrXfzZs-2qePj04Dquq9-9RTBWgPJXuQFVrFOcOmnUbJ5es3sZzC_4VbbWqA3Aw8zxP23o-p4WiG6SDoert7G3-lU7D716XvGs
XgRqywehOOZFtNtZDhZMu5yz7qtzRuEsIPJy4tkbqO2B1et1fk4lMg9h8Aw-XjmSiKnGguZPneuoh-AyulUGA_aIo9by0UHEFWgvam-1617jiR8i-5aFU2U9
pqD7volCSBQfv4BEU20l8QmhTKq9Ob6fA-jYugu7
}

