sprite $AWS_General_Tape_Storage_light_bg [100x100/16z] {
xPW7YiLG30Dz0T__kajBrJ8ymK_NK6CyLdghGK888OGGGkY5OuGM_7xBO8lxsL0E440o13QWvWbiQ7rGW13OJ2sp07Ei41OmktYtQ8M5_si3ZYjefKSS5Gg5
NHyxji3-0eo5VfoAYY5W4zu7rAu60JOMCtoX2YuNBJe2PlGCP50_P-ZTJkxPRGYG8IEN-mRq6nbjPwmnCggACr1OSqY6lwyMA6F1Fg_yZ78oL1awTy--1a-z
b-YsunkRBKYUJg0CrLNurNEG1VlHQGkoQAwL4U6yolY2LjfzX-E8qzv5TGf7-0A_qBE1_Rm7THR0_VQt6WD3DCI7OvK34WvBEVvVnl7_P3v622644488Vm
}

