sprite $Client_light_bg [100x100/16z] {
xTd75GCW30JHRM3xRzStvsmDJZCD_CS9aF9mLY0ME6LQ72dQQYFZdHW1EZA2T6fqjBD6XnimD3AIXeQ6XeQ6XeQ6XeQ6XeQ6nbG3XWO-wsk0kjYW-a4ZC04h
UIuhadirzsf0KqOlTNWGWjWX-KX3G-F_tec8ygDlE91O_au4WCUp3G
}

