sprite $External_Toolkit_light_bg [100x100/16z] {
xTb7SWGn24PXjjp_mCw1nIk4NXMpwj_P1drEqm75AK-UPAuBNracjf4isHDsbOIi4VNz7I7XmmL1A48uAPwOViKBUVD5BpZ52rpaYMcT5rALUk5SBWZHONu8
qMIAlN8kNFahmk5rj2htpu_WZL1pUsI0ZrgYbisCuVL19YDnDd29Xg0YPUJ4oB71YxI4DteaAVT678ruXH7IA3aReGr6k5ORZ72jD6eOuOEEC615_8GqUgHU
mIjZZ4JeuzK9-NfDX30O-IqYmXjy-6B26uo0e8qU2OWs60bhd0cej0OJKP0besWB1YFUy8WtCYyGouyHVuvg4M_0CGaHQp2HYOWrc6WGOp3H8zw8g4i78iAe
17pO8Cv8kibYn1i90-e6aVTHq0U8CogICyGRMOqUyKP2NqMS4MWmSlkxofmFsEKCu2jJ8-miuokCT2suHA-GqNKmoKYZT1tX9t50O0C8GcdhGLYVlUxFa8tY
IlTd-ljx4rxnWbUyuFUyNhztvnKX2CKBVazu1n64Lc8bGX0HWaLYEGFXoPDt
}

