sprite $External_SDK_light_bg [100x100/16z] {
xTX7ZiCm44L1Rdd_0qzsjba27YQhLvRqswKSE5HxxJNdfmjlzTc4aIvOwOALBbZfn1X0iZ2l9Zz9aD85AOtGaYvCBko20rrmA14XLpR2qIvqHIszOwh1JVry
ZOg3M6Hbax19oPUr4mvOw7zYmZ6lg0J7RCnbAt8s3hKyNH2pSQZLzYzYDgxR7tGjOpAksXy9YvWDdATIncPZ316hc8r3GLZ4R00nOIEy-mG3vrKrbiZy10FB
Yk5lWsxuljiDVwjrmz-StV1HxeOVSztm-rCtF2RJZSVlehkn6xinPSniNCzJnePlJzTJrHWFRkGWQEW52XyD6us5SZ0MmbP37nfhmGO7Tpt4QsEDNDVenhLY
mOOL2zyzbl7vOpAVFxRq-MDa3jgmW30CD46XuGuZqyPrF2e78mj-_Y3NDkLW89IKWn65ygpjohK18MoAnaQxSZ2gq9-rNR7G4HDTiT0L2rsnq14JNR6mrrxF
}

