sprite $Amazon_VPC_Elastic_Network_Adapter_light_bg [100x100/16z] {
xTerbWD140JHilF-1rvdkQHu0z4bJ4UiFzXS8tadIGQ84ICJHYQCF8kH2ICJHfx5o5AZ0D4CG3oZvemiDBOZEPe2n16IhSLy92DhY1GWhi68TdrlCCenWeQA
SDcM20WO0Z9aH3OOOSCekBhnvwbVSFb6LXc0g4P7s3ZQ4PapiiFOV0uA43R2wKP35XarPyGt0DbWNBn-m6Z86gFcZCW689f1Y6_qKv8fesvfK6vln3U0q0mW
rXgrmTWGA1Dr0mZNw0GRtRdMlBrYr4eZgmmWDACJRDH-evyCDl3kQv_qYymtWD0C85OQEFJ8njU7GA2XzvtPq0dVA30CWeqMWvWVlefaM6EMLDe-xDWh41e2
9qDJO3S6vYOy0mZVUF0vBu6mvo3VyxNFCKTVps4ynngMMXpVUES3
}

