sprite $Amazon_Route_53 [150x150/16z] {
pCv90G0W082mh-jVs0wUK83PRvnFaYN9acH9iYHPaYn9bYHBaYN9acH9iYHPaYn9bYHBaYN9acH9iYHPaYn9rad5ETR6TR9E7seImY0KXIy1kTbz__UT5kpA
nvOpVMo_cknJG7CM_r_L5R1a-OHNKy9wgykgxw9AyKepLCuQsvTLDPO36Ok8UCFIK5TL9HOHIR-zKidLeYpgegh44YpvUQbXavrPZYKfgYgiXdVZ7OtxXOp_
oUlb7ijZ9pLLWMKnP1IZvXkJOiJrFgkVJT2uP5fMvInV1enZhfcJD1MCX1_YybFDNrcGOfnFyQscobdSpBxUS5dhN_boRcOYQwgSXNUo60MdP7l7BfVtQ2mi
gQ9q-Zs9DGziIt4OYE8iU_Q_tpalSMMrsppKgKu2Vk0YbyiYY7KA2iN4XE6AbTngNqx4SO6L5k4e9ONJNsqnvgUVGYgViTLOwP9gZrN9A2DfJVf6KglOEFtQ
yKDhw_Iz9CMOzfXwxQatg2oMQATBZg7SMvrH2J4txVXsJOKMJW_JJbwVSs5z93beaxDpGOLMJcU7v4Oj7vDoDLCZdd-f7H_lK0sxq5IzGtItfqgE70mg-Kjz
AgSm0Ml7fpjKOvv-MTi-73zNXdoboKqPnrzG8TDzWfX9RgEG1GCj5CeBkRndOhmerbZef2BKyyTXpPxOzWXfWTouhlwLiyPAAXOEDOBnauyvdjcUIkj6hQGp
ssCkedgqz-9psPUEBHOeYUdeKZMD1r2NL4WtLY16FrNagifrkeyTLb7MIcmw99IgiHBUfXfs7WevuL2cL0cdtwC2onGhUAd2WqILIhnKmvYq-lmEIgLKfNke
m0ga0qFe6q2Cy2YvWmgioZHC_baOpp_bAOc32gnZ_eS-AYujOjJxL62bawMviq6mbLvStLH3cvmjJx2pLKvQBzKmrrazL8nzcQ_CJJLcJsJl58ngCY8tLLXI
jJofVZfqAqjbezXBzM19bihsdP6qd0NLj8MyLCjQfL-aGh_JLz5FPJFFGzMX2eQgDFIn6uhy8MxAgynpKBtoQf1NKEtJ0AZUoAjbkjodUjNyaV82rOlm4Yfr
HTKsNTeDAcmLIFd-7LK5YdMG7kGAwwi1BECXshvBgWRKoPBCmEwmlidGGywgPKKLBg2s_TKUwvjI9JOhvrttMklxeMfxqGtMDLLNfQAbWKfQMpVfzjKAdFBJ
5ozVKnLAnUmnSHaIP1YwDauyvrGoqn1TKq6YIoK3AgLe0NWamg1o2mUXqIKL90N0ECQ0IaiMLAJRt1bdBiJg6whNgJk0ZMSGCUMNmgikQogmcYrMtM5TTGj7
dKfrOg4Mz4dUCw2rJ16N3nfYts1TbIeem3OirZQ2mfG1JQ64JQzzGGK9iRN68ZDcpRGH50WNsbDr1es4jrYRUtqItPGKxw-rfSgKgZ0NLrXjIyKkGLNPN6X7
5KvNzNCk8WUL3ggmNKTbdw25KjKno_PIigNYzxAvBrnglzXqKxK5rkR2yRJ-HUfMxbEb4wNzM2e1QrhOADYoEoXCmm3nGbjR9Mnl2vbA6_hLwcVCpYVTDInY
3FwuDTR-XelRL4lrK8WnpjzUvC_niFv29PbRC1TLPMj5XIh-djGsZq4yL49QdLkefKE9TwZBupP3s6ftgTgI2lMQO-1zDteVZnntK3bgPV3ssbFvtCwzpVWj
MDdwoa-LoDDVn9B3FmVfOw9fOtuLAvAhqPMYkaBXDs6bOrvnqaqgrXdwzo2_XYM126FjMMlVz8KfD4ltOX6mHVN8Se-A8QnpbYVnOSadNVFq7Cb1DVLwbRVj
SXUhyMb8dVe_3zL8gd4V-a5eAgr_YTLochzeOowcxgBgnpJtMZYKGggonvAQvhzeyvSkugCQ1Iop9gz7KoFPBzPIwpDKwGugnl18dVFM7y3w0ki7fDhHvv-w
gKPurtuejPB2N8KPgoNxeO-v_oTBdLGzV2QqETwo8ejL5JCgebn_abf175JeLUzbWeeQpV3cgh2cAiiaPVZyL0GeNAYNeBdgzfCroGTHwgSY4J3ji9ApO37g
pjYg9fCGFYgaxn4YOK31Zabb4Uvn-QMvdmftGPQhBBWOvobACqIKqK6rvs8qBHVUCwEsON9J4Q0xC4cwem39HAc3oW4cOodn8K5rKzOeiIrcRJGsRFscXaTI
akLQCt6hwgToZ2PSC3b6pK-rI_Oa-4cb-p-WcYjJpjM9zVeVK5ck81BiYFuZAjivssxixrEXgg7gG6wi_uPVTlscFKHEAh1-VHWPFEIZ-arOFLEeMIwg6rXE
EQd-RtOE100000040UplkqOHvBKYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfi3G
}

