sprite $Amazon_VPC_Customer_Gateway_light_bg [100x100/16z] {
xDD7TiCm40HHhkl-1_RAkHvO3nuuZxAwEL_n6f__GURW_dc7snaMvXNeCqB4V5-8fNsXDpS93KAx4nv0E20Ax2QTi2I40yG0qluEwyOGqP5zOXy91mE4tgsn
IW12CHB-_twwMJS9X8PoMzPuvl4hwuBzZ-DcOiTRJ1jKt8s6P28O5U64WS93XkyBH3Ty8MSCH9qnV2Md3Bx0k8OCNyevWqythcdZMXd0hW6uWNmxnUXVioVi
622hnE3Z1WiZ468eueOJmN343I6IuOWRJhWH43MSS2CXRipElz7doxxpXtRjsW2048Y2QFzTNtRkm4Ct9CDXvaTTks0FWhC4d8dmR6TtbBXhmPj1l7rQUIU2
DtKh_m_mLnD_Jl1t5Wn0i0p0P01R4emCi3x1B05x1GmPi731z86R08u5k2BWl82xKmxIkrJlX9-7_jYmAk3eGTQ0P2PyziDdM7mMnsUAbXer0G
}

