sprite $Amazon_Route_53_light_bg [150x150/16z] {
xLhhkkig21GHaVt-xtik_TfCIh4x9tZkph-LhE0uZeZM7obiR6niR6niR6niR6niR9Zz0rlbKlWlPsrSIlloNifla1zpj59u7Iz8yKsCNXxe5x_F0wtEmuxo
n9YI0kiyVAjaSyxpTet0EWKVzO16dW8YRodUebTvr4V4MXweZjTuFX_Z-NuuJhMSFg_BIBMdI5m-UUdhuS0uitvoAloKh2rrkhpvXqL_Wp2zHcOyP3l-VBr_
yviiTFmupJwh9GGRibg4QfY9InnlxovLAXyWZDYNzvWrbcVr4KZPjTdTW3jUh1zTJ5AAHRT--AdA2CPSwk6lRg4TSkXJWveg6hpw7W4pqCjTCwwLxRBucdVw
ym-f97TNPw4gveoQMcZ8pdz8E2mKM1ym2GBP4gSVCyyRM5jvGrCtDV1brl5OQBfVWP6wLKKg7XAIfhpUCxcL6yFT4awNS_-ep25Wxe5FnxcBcga-qJs1WHn8
30Ow0tOJ28_OILV9gtEZKV5WLqCuK1ilwINjB2iF68QpllpRwf7RMSPdQkSZjzVMxLIZgOjyhrW05KxcFZsfKp4AIRyR6DulPotXTK1EIdCg8nkaClGrlmkq
L7dRNFSuN_AD8nfbgZI6MvE5NqV7D67H0IVnYjgTq3FOuPv1eJwbDpZWmlTdOJqKbxnKo0Zey0r0PcI89FZWehS36cm5dwRG4V5sybFqRD4-rH3dTiH-iEgH
tdbFoAqfwBsP1uMiLDxmbD348s15guw9sBFoTMSz3EGGiAfBM8LQyG9MwtrLRx1Qw2i3AtAiH0-CrpOUg9YoS9CiceCQvwlwi-WTf7o-qaN7ZtPU-0-6LueD
S1ckIalRYj3G-V6bCjtbNyA7wse6kiPgkEMEVCsmjBw2-60u9mMqbVKLxE6DghEy4--7T6ajQf0A9Ss9bUc8F_8dGMvNWhTt8C4UnwTBOWrwechVzZYIaMgw
7rH_d0w8EnA9zuC9iJZSEuCLO6TMW8PxvrmzgbugD38gomFF8nhoh3mjzM9fwcoWOwxNc3kzpohJtneSsY0YWWrCx9gHYjmvZuTFGTxrWcYWGWcnm0Jwp-tt
KxRimjNCJj1d-7bP4I_idcHoLzZGbhiMS9MLW1MYu8jsTmKabs4Ih106mMyUeyYbTLu2qXX1eBkGuyPYSxLZ_hqtvbn-kPVNQROBjt05Y9zxiHGLL-9q3WC1
I67Hjn_XxNW-a5p3qg6XqzaD5qV7k5HhnShozfpYknwStOAvGu-85Q2pvz-FGJ8dcK5uvU3UmEpv_CXehDW60lZPX5WiUbxnVCvAyrhbaTSARiV4MRJbpRfT
N6sS0Uha3AjwJEAEM3bWruNmr-4L8j3AaoAdscNuTKPnWIT_uKsXlzxq0BqbHx449y4z39IH6HCWP_EuoOc3kmEStQBYbXh97oOsX71ZBRrHvQC-ShVKMFHY
H5FXO8jT8TLDiTZTGdCtg-QmpXJVQEFKdbv0Axwb9ZOtz_p66YT_U6Q_z5iFY5sWrCqPFvN-wD0Uy5To-6kLGonu3n_GYgk-pRoBsubPxNZJwubHK_zTSnT_
iud60ZT_t8Fiv4VDPrBlYPJbmSiR2Bp02NRpd596zqv0zpt68LYjnQy0NbYuD0cOmTyFzHhCDHrI9w_JxW9gwyFncZOwUglX1cCzBuocvoKMZzfwJhuDJmoq
sIxz-vzFpEv8knxUA5M3MLi36_xv6CAULyo99K4eCPgUbzRKgELXGjvVnYwx_os0CeBL2Uhz_Rne35hEARzEvjQvzUZbXBuyV7xzRbcFhn_6_E2jbmj2_PUm
iR6niR6niR6niR6niV4h
}

