sprite $Amazon_VPC_Router_light_bg [100x100/16z] {
xTfdTiGm201XVi_zxvlUjOlc4KGgwG7xU-usLhJ7Vy0Q1-VVxx2DPg5V0HyjXCpN1LbK5tnbaRYKCTMUk9999h12JkI8Kv9gJAw148WbCdrNq40On1FUy8Wd
wiX-uW0GTPyX7eq28h8lgPSVIMaj5o-fjp-fh8vyHSPR8xRhtEfhs1eWmONX44q8moASC11mtOYhHbZ38WdRPf2etl0BmYc3UOFmXaTMijzWt8Xk8y0RSDq0
PuWhSFQNMbd8odMkY4czmIM3PeFLe60e140Igo4H04ciXaG05i8Q4W5O26jWujd0X3V-ZRbjFh_lpX-3_bmoV4wSFxUFNQCchhK3zmmJzpw_xJunpXc_x_aZ
JXdJpvpHRepr0EPx6N726EejpVV8ejiGkkedzZT6rv-T3LxVt_MDwdgVslRRIJ80fgw4BE49ZpGG0l64HDWWXrwiUS8Zr3DUmQvn8VX5IVuf2BlgGLIElwEV
7simFsR2C-DZMFgPWJ55pV4Vjm
}

