sprite $Amazon_VPC_Peering_light_bg [100x100/16z] {
xDRNSW9H38DXN-lztpSzv-ftj9fH6Y0wjlSRs3hrF298V_cSEi0f2tr5GIf4MC-5i2aNmiwSm8BfpeYjO0O2GOMA8R3YYmMYWFZTmNSKY0p9YHp9YJbF3Z76
LvNpR1fpOaxbuyLroXDSXDTmCVOGUxhEvnY12kHY3tUfRSZXtl18Gh2H8_eEGmYtZ5cDoGoF05it16feU0JGkg70WAH6bU25PgVwo51am3asDln0Zko692Oy
igvbmTenXhBLp1KXmTUZw-Xcd7cUHOLcsM02_ammQ9eD9av3Wh31X3SOOMCdU0MD-ILis1N9XRr_DquOPbqd1OEGZZ6SXW44Af6Hd-XXOZS02GmWm614W801
11c4N5qVIB2n8ue9DXYHYPczTexAZG63AzSHVwxrrmoUuD7isiS043OqvUZ7ZGcCh5D05WtzWl7ShXqQ0033C0px_-kYOZEX3E-1oW6t6hWvmUqC301O1Z0P
O4l0o83r0RC4zWeC6LWuC7tG9a1Z0Qq8D2_Gxb23z2tLD-46fFW96ZtO6e3D1Dz--0sBt-BuJT6_lGC
}

