sprite $Amazon_VPC_VPN_Connection_light_bg [100x100/16z] {
xTX56iDG40BWMNF_-zOjoZSDL65JpVpHPsL9WiVu12k3sOW5DmBOaRcA4eIM4o2abWZXbGG8gQD1U1MXmNR1HPnZClf8dtYzKHAZv0RmZ87XzdoBdZ7yKsEd
saRt9i54R1fW0ZyCRe0I6mo2GDg8Ga1mf4N841X228_XHyo47ddfQ4c044BUbX12qYOIOegOsjrp10RVHd2k-2QAQruysun2-Otw9mCRuo3yHWp5ZHW3WDV0
DJu33p4P6CHYm6aCYHeW3kFyrchKEG8ZnhTSSs3mxXkVGRr14N-x2sCVDH04XlJN635YnE29mHCZHjPBOdIJx04
}

