sprite $Amazon_VPC_Network_Access_Control_List_light_bg [100x100/16z] {
xDWtaWCm34DHrBZ_WRTQ9rX3VgNAh3mKmUUSjBr-PMSTtB_VSLc7XNN5eBOGy9mBS8WBS98JT9eJvm8qmJDKu35Ey20GM9OJCCq9cEV4AW88i88H6E44HpYn
ZXG4HbewUz_DLHNEZTnL4jme4Pymh0Ac1j_7ZONxBrha2ZgdIiD-8ZJjdc47KXYcXXq8DGGD5dVBU4w1gsXkE2uYGxiDtJJoZbutlZriZkQIyTmoDfnH3oiD
jmmh-kFwDDmqF6-uRTXpXaqCpnY6XZ_x-gWyTzjuZ1O6oaLlpT0ju_vzTVynVvQu8MXenX0n96ZmznBD6seQMZ7KChHcA8niQjLGN6MuWvyJ8uiRtctukg5v
euY3tmP3PT_lZt41GwUCH5UDOkDsuzf_0FV_o_Xhrmu9000048RrRusYmjI9yG6Q36XBe961rWUQ9MYle2635WwQFh09O2p0Ye1v0Ri31Wai5PWmi6rWzE1h
03uJxllXFop-Y-C_HLyR
}

