sprite $Amazon_VPC_light_bg [150x150/16z] {
xPlhagGW34Q544Bo_k-xTx-sgA6t1KLgD-VVNcOyRH8acBR_3CTn7CTn7CTn7CTnYZ1JZ8bPr9P0cROZ8OazJOuR087rKQUmDKYFUPM3KupCd6BO0DiZy2jW
nNPK2A9gqr523ZLpJQPBXNTnaZ__cX-HQWU9dz2AVqte4gPhfG-kg76obdnsFTf-KcmE2gbFj8BQxU1Yz75D99k1V7u7z1X35H6zj_xan2U8PYRxeflqlbj5
fw8j4hONf7TbbPwgZ7fd8VSK87Kymy4TYrW-kGOfTbnYfX8t5C3L0God8_vA9WbtB6AdLw1IXLp3zNl2SZvRCnoECTNBrmKxHwarBqzuHbeD4F1BBhIAb-pu
TJKhHNAkP6KNLw4Ih4OVy86osZXuy8zRxJqZ5Hj5usLTSTbsebpLAjiu-PeJ2QLhprjKKjX_O-dlIc_OiU58ebSBhVAe1PKw0lrQD9xb9NsP0hBzOgGhxKOv
R0TYraDkzAxpOKmg4tm0oKkhBztpIAzPZag9De0UJBK_rNKeShWzckD1BAlrefsPNWiqLAVkXgGELliVI--o4FjMtJgnHVIh4eYTQSKzgLWj0Zd2iOfaJobr
R1m52sPLYlZRQccTPqNbbVUXjLgPn7whCj2V5NhxgaVwhRJB2hS99aT3ogDMqcabLTIgLKmViT9m21ZG1DCnA-wpajO2lj-mBYkqIJHWnThOSlTRuOdJR_N9
_-biatWjA-naLhB2he_Mii8EUIqhT1DBMU5z82zbXVrIaBMiqD7BIbQcX6SNItdS2l3s8LEjJ6anAtYjPGKanSMiWCex9bXri9oLMtLk57KfA_H5xzznyZDM
6U-3cmzymXl7QVDPZ7VdRy_g4ewAxWQNoWXXetF21xYTtGOp6Qq01WHxueYMl9bVoRjCcJGvXbkHS9BLxEPGYlCIApJcedONHYbE7VsJrWnPmJbHWVIq4CR6
S9--MYQQ5q34IA0Gj1ubZV0ZcuRYob9rROnpFfJeF1AYbFVpFZ4L3dXHYGgT2EOVeNMaLDD5q-1NFadb54erJZgH2AsgEsA55CfW6deS352E-p6x7Wy9Yisc
LBCYAbBFMMIR3gfFh48Yf1v0llhg4CO-8FNWjsD29EOOGrM9py1R0rPxYFQP2QazZEPA36Dg2tsPhzY_ZUCuZkCuZkCuZkCutm4
}

