sprite $Amazon_Route_53_Hosted_Zone_light_bg [100x100/16z] {
xTWvSWCn34HHnl_-1tReXQK_g683teYGFUXdQvVMJno8j9mOr0Zm58zh17YAnqK33V6uI826U5ma00qzhHAWeQTb0oJoz9dO_krF1vxYo8USbxCUKaE-fgy5
JGtPCo4iTQHmHqgeJQxx0mLT4Y8mE1r7d0WWJiIGVaE872946Y6CRAs2f8Z--poDU66F8OTfej_88zurPf0cvesLDGhHDQvnZUddUOJmAj86CyRVUgzr8ehG
Oo1iO0Q_umWQGuJ88PD6dDXhwJGODbR3_5JZ6lGQ_DVxunfvPEzjC-RVe_B8d_sDZ00YVL74syWeNaL6yHu2ocC9733b0gWvPwiW5yUMs2TrkQ_51DzD0LvH
ZS-Wf_C88sT1HOGSOq1UMGqZGcwCo2khSuI8Akk_pXi
}

