sprite $Amazon_API_Gateway_light_bg [150x150/16z] {
xTe7RkGm38LXqXeLylu7Nc6AyRRRXBKqDkz7IKy-Y6QIAVubOemnnXXZZ376s2YYtG_MDodTbzStcQaVJ6MszVMcPtumcO5hbIcW0jSQKq05hfMcSbPLTbVp
IskwcypFgjnsbxP59Z-lyijTQ7fCKqXriGjDTPh2gfbLS5re2gkkT5aLD8LLl_sMaNxt3UAg7rrnb2YQuYfqQPm55y2bAhnS0oemNQL2LrpbVgqA-oSgggYY
Ygfd_kpFhrD55NTmWOegggYoQZTKDP7IRgVQH4HlehBz5PbLU4UYggZXhMrpqvAjCXKfS2-sFkUebgeQAhE20omoqv6e6lBiWGDyoBEHfchohC40uRr9gYhF
kkC0PrsUrHJL2wK3Dz3WQfEQeB8NoXmt43PpPWbdfVjHmG1nDJLlWZ9mWBYQqX9KFooRxh-tuFqPAbmssnrmXWagMBQ20opxQYQeSDag3h32QYQfdaTJzW72
Ut9LNZVOm6TRzNGLRY2MhnemmFke7ZApVDM10QQhMX5fzrBX3LJUegUAAghuE0vL9-FZE5HHHHLLL55bwrGMLubMMw6ogX9KhNs-Q53LH01sZGf9i-Rdmwz7
M5nbFtnB3sK_mgAgtt-pYs01LO0KW9rL1KW1s5dL0XB08gfb98G5LKXQ25C_cAuc8QpxmJgG_lCOOumnnXXZZ37s3G
}

