sprite $Amazon_CloudFront_light_bg [150x150/16z] {
xLjNWkmW3CE00U_zx_jgD2aacYM4Lz7lR5XX2nVAnx-3YOc9YOc9YOc9YOc9YOciqOjxmVke-RSIiXp5dK9Yjjz3AGL74T8l9vP1YIAKNyafURV1ToMze77_
M_fbTZgAIMldYWCa_n9EVfLqX4Lg1PLr8VZXVZGGSU6x3GpoEZE8ldX56skebzFiu4uxsWfynxinRZa1-hBL3pb9o3zOkJtYCE_9uZixc4LSXDLMcGaMwA93
6UF5SkaCq--6SXkK7oQKcBTE7Y7wj1gAAWuoCuJGTKsa0QJemBQe9oz1Fv2ldoObbqvGI0UUhhGtW5Pw9rZP_5nEu_tpj18aTOdTV_pkH5_vE3nCgwnIORBA
gpl1QeVmu4g4alr79olGicTO2TSKzs2jBNagpN1INEqrhVXCGkPgi52Mo12saO4eD3-K_1B_0rkq9xf6KRAQnHxnNtZ3MgpEE1S8J_YmyBaXEEOgEvCF-iE3
VwC3HEogak4wzPrIv_xRn-iK7Ag-8eLyqobuuM5FBvA8gND28wxqcahvpovTB16bSycTgZAUYVJo5sFV-Ru5g9ppkUYKwb6xbc6Wfb8IDBWW3PmfRdrSQ63Y
YvTFboDHLSedt6kCSxhhGBQ-0vSiDxJST-6RZ9N5sIrH8dJS3rQ5wIxVLcMv7RBYgGCj2dPaUeATD5GEtFUWIffe8ccYsHQS36hYLeXzObh2rlTTMLazmnLy
hZo46nSM7_Ci6_kCCbZv2COMCVsUYzsVw3Tj27O4F7zFxlwds2rdLGs-OEwy7Ad5KyYaxx7otW4PIcjmWP6_qNkit1xvvq2oOwqtNGW9TBDIwF_0ojwwqCQm
4k-3vaCAiXVLKBWByzEi96gsiyo6OBI4oiG2QNoQLQva0bgwX563W-rIMFvfLkMi_9IeAfiLG7X1YYDj1Gv0s1yKIYBLq21MTIA4manbFTmYeunYXS6g99Z0
Iy_ahWDP0IbuvmDKTEGbvIHlzR7Yi-GmhSn54miI1KT_KZUF8fNyyvlPcNzccWeloTOYbJkAJvh_2w86Pgv2FkYe-Z2UjQf13uTRnNiVM8RixoQmf1ZodXQl
9ZewhqQx5o4rVN_dXIwLsvtlqEUacX_iKf73YDROnaZQXJ3hwEX9uzGO-a9QNUakqxnrx1JTRG6Aso9ppNBmnealmVFc7rsILOnJzmuaxsluLdmMZDEn0qa-
Rc450xtCPcIw7OS0Z1NV9ifGrZF709WaOSKqMLT5_KSc65ivAzQmdt-di6EViMwK7tfjAvYgqrYXELv1IgUw2Z1LxwabOKLRxxCrcBjDXJ6CL8BCXPAhU6NI
iW3vwNLxOsBOEH74TdAwJi16p-qLP7P05RgSFNVBWbTzd5OYjopwRwJu5lDRE1uO62JM3vELLcnRFvPLDLir4j0lhT3H19WAkUdK9Qr0vFw-sKyWbGVSe6lh
0bp8XXHZOT35Fh6MZWdD1oBgk4kG1OrFK-5l3aY3Rh6w1XU-5aaWfBffmH7IUCPlyX0f7gjBamELVzKVJXV4XYwtoDfx3NwUO9_DL0Nz8CgouIyKE8myGnbd
hb3UbttaIjsubozAY6LYgD6lX6Hvp4LU2T6bCVv5LQbUL15EOr228o07Jh_zfLwqZzy2zghnuxVYkvByXWzUWFuZc9YOc9YOc9YOc9YOc9Zu2W
}

