sprite $Amazon_VPC_NAT_Gateway_light_bg [100x100/16z] {
xTfNOiGW48FXUVxlVz_qJa0M0bBrvZ3uo-wwZsjv_WDjDgv_lOFCPY5NCBA4KEEnO1RvWbdf4swrJ-oVGDMcEQwWf-M4Ft75vcwNvOWkoX6VI94t1U5lSer8
4JtAKm94Zh47UJT2ZaWTXMW3XODIDAB-p0U4DZR2PqPLPZ26ULgSDAfhDCiW386CMPwI6GpLySgqqTOmCYemk6RKIaESd8MXYkWQLQ61D6gnqLPGaL724F4D
5XcZxriGmb0RfvWnOQ2CTe9lu1fC6BW64mQk0Rw1RU0Rs0Q-WMrGXPlBHl4KRJILbutoZJfeVAVlYgVusnK7jjtljmzM-SPN7XDPVsn_MbGRxuHXN9Tq16dK
o63rDGF2cBg66rzgxhiMRTOORBlH_SSoetRTumWql5UZhHaOC6sCMOP8y0oWsPg5eGW6SFOiGp_uyPzbQ48_8_EDVa7Vg2b3wX_NvHF8iVX17teq9_JuDgBP
LZSt3ZBYJ8_bVA_eVCyhxzqTwq7g91FEzuJFzxRp7ltvTmtElpEHCnKc5dBcz3j5UVvp2m
}

