sprite $Amazon_VPC_Elastic_Network_Interface_light_bg [100x100/16z] {
xTf93iD024HHrdN_0-S0oAKkwKEcPfaGNZpRuCBZXjG3hMy20tp00gye28G8ly-5C2aNmioSIBDpOlu7mXRS_wTSoNAd469t3z80n2UXY4_X4PCG8W0H8141
89w048JmbKGRCZY610I6QCAGWO6RcaUZl94ZXiKCTHKq-eB86CgZrJHRY3SAD7fHpHawDkeul56qKTk63WsPC7NRvyR8TwOfunf-L_mlunhNkEUIQvo4DoQl
v_ga-vB-_SEjfxmXsj2wKNF6uTDRRBIQtl0tYAvNtMiE60O535EHDU8UW3FyOdH3pK0xFnE6-nYQpjZ5OmWjzFfMUfO8mZTu-KOrJ_0zVHpX1o3y88Sd-9dN
_koEdq7kprBvcV3-R9kVqU-_Qy2_Cv47021A4H40k5Dut7W1
}

