sprite $Amazon_VPC [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBSdMPDO-b1qsWIY0chOj__-zQRBku16G
1Sd4TyhhpyUKHGAPheSfvnHZpeNaMPOjigJ4LvsGwK6MBR50-eJ9KonRO9NmwgJXMbDDixWonPZ_Jgo-KnvXsImheyCAuvj22L1vW6LpB4aOGzsnHlTPDiTw
zrNMLYXqUd5PPHEeAEFklS-o6LP4GmsdmdsMJR0oXaq_4fzWcPz5G0rpp0U-nJ8_2oWFAyWTbhbOUB7agHu1es-LPLuM_zi2wedKVSX49BCiyx9YFLey8p2g
Afr5D_4KovmizlLV_HQ8wbKy2LWBAXkCAl68q8Tl4q9-bZbPtgP2QMkak5dcOn56bIzoIZAfCiKN9i2oojeT67GYwNF5f80YvbBvM8FrppKxwYBcKRbOZ0vq
fno6wbzWlYohh36iT2vyOMBLTgl6h8nXTIC1_qHNLM115U-gIbNobbNsj8hhQuvbbTrKZIVoiWeiINTLM1r3AWBMWWei_iVqX2gT2pM3jQGoN8YZxMyEh2EH
m5fHMS6jijvFyLxOs31ez5147uXG3kT_v05hZ0fuOyy5Mn9WJQfmgtnB4T_Z6-4uPerLnvigfklXt1m2T7nJmVAhZYb3Pgii-Tn-YnMC0-hyf2gSAB1kxr8c
WZY4irUdLF-sSZPROd6gB3arDazPz8nNXQPIMs193dNpOCUvMsNyAZb6kasn1e0BTSGQ5tMnIHPzTjReXpnW3Sj2D9jYITqSZEyoIsiAn3vhEAoApR60YgLo
m8XoqLhlVIgK1J-BBuE9Kwi_KLgrZbl5DiNYTgiWaQfb22h4gn9piw1gLQowmGRtSiigSweer99Q64jNfTCzY7XKN27eMiMafz9bbJbKeLN59KFQLQb7LMo6
1HMZOdKMxBvAnogB__nVQyQbAeFJgO5A7IkEZbXZrU1tXYhrhCxjV5EbdYkPThwfql-ywalMYKErB5VF5N8xtrIfvswYdSqg9Bz68zxsg-gxrC0ZrduLxkWx
hhqgHB7Ofy8oOErIeSGxirLbcdvC1TTlgH3EySTKYF0ecrJ-R9s3_locodvJPOfZNVaXbU6WXjywrcRoLfMTAXgV1uVtdTVunD6UPCL3qpaxHoUNjofkK1bU
2iyPz4ukyGOsgEpGu9cCuIdlqMOxL8PXtdb-vM0J3ls_hyB5QyPELcSpi9gAUrIOMV7I5h3aavTsgT0nU8RikaE9psYNoivofAd1-XTLy5FTfYhekHTO7u-I
HbIjj4-bU6N2YUd7wQwWgMIVoZ9wYQf7kpa775HYXcvKwRj5m4A0mgziKc5a1Rsoq9ru4ckZoY9OMjyT0HBmyvqgETf5FdUq4tqSGF5M5LZrsikd0PrAkbrb
v-oxl3P5eFQhZ1j7awWEGErMcLJ7E37b76EeP-8kbNyl9okoNsMIMgOa-l-e42N0K1sS-SE-6g5IKemvPnA71geliqnNybUpSo00000080XWVzyrYg38LcGh
iXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcHh
}

