sprite $Amazon_CloudFront_Download_Distribution_light_bg [100x100/16z] {
xTf7RiH030J0FVV_7-oR0q501S-setXSDrbAJZDwFBtkobBb-Uuuq6H2rGASSGA-VYPGw4GuI5hZGHgR-Wqfd3WS4xPvjeMu0BqGAo0KIf8Z12B74qO031tX
n31qY1F3KCG9A1baX2Egxp4pelXk6C8468gaOGHWCln4W71Z7vYE4JWDCFX4qZ821fGQ1M8EJS-86hFpquOUdKU_saZJoF3OmFeRncrutSPRzZPkupO2emuD
-uy6ZPdZotZHdAjOzh-CbyZ1toLWN3HZ3Zuu-pinMT2P0EC12p6R0SipaxnAJmEQsCZyWszy38OUKZuQmPEVA219maGMLH2vKFl0CEB4RlXn4H60Hs3UZyB2
ptYkW83JmsuRvUs9frZVYQIuC7f0EE94Votyx58G4OlqDq0wH7-lgB_drT-xw-z1zlTI-tl2_Rtj_Xvz_rs3_ZiJNXrW5WfDflvEqTFhhXS
}

