sprite $Amazon_API_Gateway [150x150/16z] {
xDc7alCs30HWqZ8bxlxl_xw9IvPH79s9jJM3b9tY3dn377GDdwT_FqZ9GaeMKhAGaeMKBAHa8IKBALb8oK9A5bAoa9A5b2oaP24b2obPICb2IXPIif2IXPGi
f6GX9GifMKZ9GaeM4SssbBhEijPBkQo6Ya7JfVoUYidKKehX8XartOB9b58S5qb6J8RASF6MWCbG6IvEibQPbgXgaQl5L7ndgZ9rH5NOvAejfEAq2N4LUj0b
5ITCrmvOAlIWYyfR4m1NXLkhwxoB8nCcMuKUSl47beh8vAlGzwvodLLnmcIhq0Ck7h24gWtuXagitkfR5ezOJzCAV4ibbbopgi4wC9agiUGAgVY-jwz27ucf
UAOAjefdgc2hUAOAjefdgc2hUAOAjefdgc2hUAOAjee_gyQhFzy_g99JXPmgv5JX31KcSuQAELNCgM9E5SzKmLRnJ1Li5SzKmLPnjbDlFQo2hU9afxMKIukg
OAiur-bIIgbX5MmLPphrsmiDw44LR1KFEoqwdNQ_1A7N9QY2hU91frhACkwMUfzZxJ4LR1N_hjvsaznP6k1IRhWjfeAjuckzJN-p6GEybdksc0gsYd-jjpu0
AyO0nxCjfeAjuhxU_bIwA3h1a0gsYgedLDts6tXdLR42AjWgOjHxe83z1kh1pHXJmLPnrAiwglq0TLWLGHLi5LMlwSjg372tcYsiWgsYwkrMiEgwDPOmheAj
ekgDPKENRwoceyBdAlHw1on0qvEBLjDIuLELbgsD0Jvz5N1L-88AorsZ0UePNuKlg72z0BZ--RdB5H-fOAi8PMoWyg4Ajcgmj87VKy5MYQK1fb3nPO0fL8Er
BgMiMLJ4I4CIrPwLICMSAkPKCQUAELNCgM8QrNZL-2z0GjN_AgPGyIMvTb39gM9E5NEgc5F5d2hcL36dYZbLpAdYsIfOAixqxhwgr0P3nNUgtcgnLO95LJnK
YMIgrg88DgtYgsgGb3MkeZulM435LvL8ewIX8l42crTnhtebTS1G7S2cLPGgH98g2fjKyGzLY2HL53QhubCL8adbm3Z92fEaSc2S2y8agGnOvMIgIA7y8WtO
nici8iLKOfqKEFdrMxDp8000000W261_tpMA8B8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsHe
}

