sprite $Amazon_VPC_Endpoints_light_bg [100x100/16z] {
xTgzRaCX44HXwdd_1qwDZbP74wsfxdQ18TzT_6zyrkkhXFN3_x_lH6jPs5TIr0fHplT26Ug5CjaJRRedVhyWQutxDMqlOtOVaQ1FEi8O9prG4nGyKnC4FAU6
2ub46u82_cuGpXAOHXt1d0YYw7rYu_LZD10L0H5jXFYmkeWfSMPX6Zs2U2oe8IjtKOn061Ii7WsE0439Sh8CNOACsCRCdVdZV5uVe69mterqna6bDyve4D0G
ncB66SkCF3VEjd7-PoJ_DIB65MoDm1iDNeiRfpSI8Ei6aNs3I6zu4TatYEmRH7eZHQqQd_7-Ddz_ttNYpNF9lf6HM3P8x1i7H6dChvIv413-MgkDtCb4hcDe
ezWiYRYH8OBPSglSo8wX6Vyax3U7RzOyFLz4nD16l0qk4eC8sf2jajYDaF2jyaQ6boOINAiihvL_D6sSI38esoc76Gq5RwD5UeA6Dmt1xjPL8q6esdVDomhf
lKA2k1Cz4XjrmX6M4pHwPE_Wm0KdF2I24H8ZOu6dPrwUtINspo2z5XVidma_EDj-VaR__hS6ZdWz_-t7llBujpZxpbclh_u
}

