sprite $Amazon_VPC_Flow_Logs_light_bg [100x100/16z] {
xDRB6OH030BWdEc_u2s0HICVp6auQfBVjpFnt02SpdnE46WoMAK2S2B4ShylB8jyOLzf4kbgRketOARKOmZKbYIyniJZNY2ukqZeVbs2TJuWHDZ8Wh0DHWJX
6Jn64vwnG_uVqCZeCcaWRK0POniyIn41Go9e650mD-CfPBpD2nXw83e6X9enU3DQ1fR6SxuP4pHuEte6ZXipsNi-KpBaNKRCqBUP2DS026aPC0oAA2CaRH2Y
3J-Ci957s4WZqa0WAUCQ_NlUVtOBHFzRqlycdl-sz_zH_NzjVyrmVktpQzTE2W00G204zc_jomhZdS851l-9uASMsq1i7B3LnEO4sram0C4o09C1R4amCi3w
1BC4x1KmPC321TC7RW8u5k2AWFC2xWuuIE1IWHC6RXiuUj0Qc6R2jn--OV4jZc-Aylu2
}

