sprite $Amazon_CloudFront_Edge_Location_light_bg [100x100/16z] {
xTSv0iCW30LHrTp_m4dbzOiTlCsqYVqgWsGbKHXQZO5XGtglWO61WO61WO614PBDDZ3CxVa61WP6ncdnhzh8Ev7MIetyKszVjb5qifxAC4fFRrNS4FzF6oOL
RSX_vXZoOMM8lnGOoZaQ6iWtDECQhTzvskXnbaIDVkULP_Gz4vNHVEvgvNDtbDya0uET4mC30mC30mC3OrZ51aP-z0C
}

