sprite $Amazon_CloudFront [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4csJERjTD5r5OG2S9n0FE__l7Tex6gthIk4E_9h
p_q2HB4vvv-B_r8bhUPq87AkJS3wBrHTwlIiaOhqly8QOLBB1utSkeLLCPQMmn55ewe8wsUQSgs2g3Kl2GkfxhDaRQQs9hALruyaYQZkiZI_MheyCz9j3Qs0
POsf_AnUNprZPltf4lkCbwj4L7wM7ZFgCpiwNxhJso59GELbrJSJeY9NBQV7KlNkZwLh-5azhLs4T5NS1FY1vmy_6pzfH3MSrKlwoMrcrewtqCVdgOgzSJMW
kcB9h0JzDg9RBqy-xeaMKGq7IdRLdGqdKhxXsqtMyB7aM_NMbqtzLUcFtcCihXeNgBqwJHHOzVkjqYAgmL35zl5Zuyd7SMHRMVa6QpXOIb5eAvItJjKInNyd
ZZLsdPmjga9aDsjSinBfANy5qLl9gUAiIb2isxUi4bADBqsbf7f5vygGbvLXrw4IKesF-WdV7VlilLHrhgAPhcinrLZgLpZgIFrpnzb4STLmS5QdJON5KJvs
P_uB6bA1bI-QwaGrR2gOPFZUbICgiEIYVWKe77rIqGTHRHFPqV23iXBj4Qj0hTCzARiw6dumbc3bOVVvHjlejKXKDSvaystcgDllTFPxEQpgz99FSzalIuKc
IwEgGhkAxKIy8VKq1_kANZ3VYPJ-xhpSa4heMfKSvUripMfcH4KBc0QxtamMVPgiD7yve7hSOMFBqeHSa2gHdhGzwwA0zFqjDGicIx7GtLNLHm77mkhrdDmW
YdLM0lccwl6BtmQRzH3Dyj58VPDjMRoj19iFBX6Hp3Cri-dFm7Ahz6oh6RX29mklhAonm7Ah7dzp85uBPnRLWYtmgj-hvr3aKg7PytW59YDx0HtzdiZtNcAt
Af_DRYgjjPBxmBMJyhXBk9vaxwXoHXFfizDiHg24H6LE5JnGDHG49OYNKDOE2AdQx7-t2YNiFfNTLAMSI_jQmMRMZgAyXE9KcLULQbFxCczXdfnBfR25j7fL
vbJfEjg0rUOoseypAXbtt2hpgVewnyy4jYydvhfjBB_A8haQBmEo9WNj9vkDHVqgYwX6ML2FQ0aFjsmDjBjJPH7L4A3QjoU6bRIxJsNtL72LVEG2q-9A-hcE
5hSAB3hqjR49yZoiqOq5KVVB_jK-MCSDLi_eD_BYX8jmJZA8tgJlM5WcKbzkmij9PWtFrBSsErZRTEcrYfzn-OHiNwW9HTntbq2L_mZt3edmd2RMKP2n1Ap0
D85mdBmMQHkKfSapqnT-6l6SKX5zMSIsWmB6UwbDoJ11LFJenNjjcmXvNy8gFNZvLHYdwgxPEKlEKYBKrrQ8otUALbLUxEn0ls7XdQA8Ib32vHPqiMQcycHz
Ybj0XObuLRLnpK9F2JRkGjxRygimJHbH4TPxWjAIh0vcH7KccgZ08ZSPFbdog57LI4WMLGqwFc5rui_H_2f1ihXgN0mg6Igagd6LErcOkJoijiiLKXLK8Lc5
h5S8VryLf2gYGdOEtQWO2mbPxq75T-Ag-JSsao1XLPmj5ElLYwW-5L-pwhjn-5XpMixuTt_GWXXNsJ5hY4-Ki7Rx8BfAG8oha9-ZBrFVJPQGfwyXrQXeBMpF
FXRU22_83LhiBwiiWONvrCaogRKA-NT0KHLQgs3zCZSBKTChTzsjug5WiNRdXtrvejJyAXvoikpSWkhmieuYM54dIYoWegnac9fTB3aBDbTKe08gpkeu-B3u
EFGjAqH0HLc7OAbtiB0C5A32AivAAE4bIvwGdXoec6heWUWU5WhOSFeAg9pBAKh80y-MS5Zj5bNniFfacVU7DPC7hrmLg6Bp3Hk8PW5L85sb3nhjpPIwXLJ-
q8pNQWIcWKH5L0XD1s15R7n4bv8EHBNxCI8Xo_-eQgggNLLLMithmvw8AXQz78v8Oh7uDO9XSW4hZ_iXg08h45hJ9abLe0-fm8hAMitvpPDhq_4U8PMN5O-8
wd_9-lLxitCW00000208O7_VDOeWiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8rW
}

