sprite $Amazon_CloudFront_Streaming_Distribution_light_bg [100x100/16z] {
xTex3WCn20PXrtF_0wUt41g9XRoWpG-Vd2RPnUVnsYAevldUyK0dWwekm3EU49_N11Mg28MaQooaPLD_0rq7Fo8jscos2_62xVMnEk9302L4HCeJhe0mx0XF
N8OTuedBi8WdX6462I8s_2IUDh1uR3X44yAm21q60bQ6FuWWl14FfCSWKRtX3qANmQoX2M_SG-ap63VEqyQPDkWqk3njoFe6OuqrrbXZZJLoXDp0_J593I0p
0F-_H0G3GxVw1-hR86kD38K0fCHjw1D3P03-MyOZ08w83OC022AOwTy70GWY68b603H1e0e4G13HG2m2O8dRi0Y0JYUmNBWqlFYf4mUBwA34OyJbCbqXZIz6
YuH7F37_Bjn_5Oh0H-ON89uOs1LDxhpcTtVr7UJWQdHW9pousvxVqS_VDPY_C-6PeJiidSpqdQ9wRRq
}

