sprite $Amazon_VPC_Internet_Gateway_light_bg [100x100/16z] {
xTh9OiCm28JXEVF-3znBTnn-goFefZacY2zxR65jpqbSfAD_cnEOPi5NOY5R2BhV5cuLEO9PoGlTQbxKlo3i9-u_9bx6jLt8Ze-xKMOWK6GW1k4XBi4jcF0H
9k8rNqFu0UGi8yKzLSITM0_AQYiGME5UAC3jkLjkLWZqFd4x8ExyqsA_aYWVTu4W6o_1xmSy4NuQyE7YLuRVZIHSC-LwVXo1MJ34XjvI6xbf52Nmaq56B1Yw
pAgXmj2ZL8QcZUWq8dbR3VreunZ7ECOnZd6CkVzQTHgQDcAt4UE6-en4RZLYtf2wZ8ow1dJiCLImXi5x2fQ1EpyTXWI8Oy1M6CyrUEVdyQhTHb5l68iRezbW
f20OKH4W1lR21_RqNSGVWDZ4_AneVkRbp-x6Pf0SPy7yJ7X-jktFwEUlDPY_Pi9dPCOMV6RwcY8_9qy
}

