sprite $Amazon_VPC_VPN_Gateway_light_bg [100x100/16z] {
xTf7SWH1449Hrjp_ll9UggWlWXpRR9liDzxbg9uZ_YE3v-yxtgOiz1MRfqB0uxa0Ixd0co6HjldG_82beHdGXcEysqSQ3tTSAoEyn15UwHT4NZbO9oJWAstX
A4OYee4mGf8OmlJrmyMa7LsDe9uHEUAoyUy9_NbmF-5W8BrOl1yONfm56D6GfmoVmH0pmYdF6JwveRQXandWvHvdSsC18aFwnc5e4L0y37lOy5i63NzapF2N
31d-bYit98aPXs7fekzpzvyVtugJ1kYGrojk61YBwc8yDMJR2WpD6GkoPFWCXgQC1Leo_19M4mWO3hwpv-UpMuPjVllny1z-EiPcAzCml3BKDgJs5IdyCCh2
Vr-j4ZcI4tA0L1S7_GL8d-ZlYkPtNlExk_aT94nveByJdjzjp-_ev_zha24yofC1VKMDSA3lg9uZZm
}

