sprite $Amazon_Route_53_Route_Table_light_bg [100x100/16z] {
xPbNTiKm20Nlzzt_WlCLZZdZ8cES2ca2bKb_ceTknOHV323UY0fZ67eb_Xd3zaBTnXmPsu4_G_dlI8fixmzCoCYmoU1PPEolyYaZYl4EZFpTDOWwPiYPmP62
eSJOb68563WE39p0sZ83etq6DfKOG83X1moMoD0p1c5aO76HaH4uBo_sNSRUtz0-msPcowSCi6n-ytCzCgNidE4hXd9zWx2qp51cH8dVpPmvih_q6FLFxpx3
-54n_Z6CyG_dEtNcyr4OPPo7aQjk82wo7xe1webtsmsqu0Pan945DzY_jmiR-zr0gZ8ueXkGqUy6OBIwWIGocjt0BGmWEXb4v4hoOxfKpBMwGKQhw0QWRyfE
vM0K_hVRA5Yinz5_m0t6FuRH3ndzcD-hyO_fVnYEOtjVNugz2NrVR-BGSTBpiI2kCzPw4xnYUkNUhZl-0KPpRmAhEXs7xBf_B34YwUzD055YhFX732kz2IBs
6GQZqfjGhJVHt_zuoN5aSrKWnZ_6FpfZ_6FY0m
}

