sprite $AWS_Cloud_Map_light_bg [150x150/16z] {
xC6n00000C2WV_x04wa20000002O6ZFHjXm5eIX84E7__xS7R_eiamgTTMEiOTVmfWpx8QBoP-2c7wpzBaPLQ4Ignw_6e3GWFtZPLeYe_1nZApIGUYaJs5Px
-JPwgEeODyLbZUc0nKhmjXwm7ZeYua8VsFVBw4oDTHXzKBVHgeGB8IYGuitCb5ThLKAQdAm2NZN2kJlLOoAsfP7Y5d5XXK1wRFjWzhbQQaGNvbX2G-fSMkqn
gk6Vop2et4AMZQ4pf1AhSA4QeP_nAWJSULMm15AfLOH511EHX1A14hNBnUiOf18hqATYToErojt75nKjnZnAhSQVjFyqlDj5wV-_ZHvgzxsL8P5aeHNIzGih
Mcc5-bblhVfLVQWRxHhx9xreB0cL3MXgrNqLsVuf3Mr5TNUw8BEIFjYL24Z8YdgbtrXP_p-4Fg0mRF4ovHkhuECsWZrqIH6bIsfYfNkjCc4YgNi2b7YPblog
YTLP0feBLfi0DrPd2rWkIFRoXPKVzrC2oLzgTLoV6aBrYws2XqmiGmLTNwuaSYiZNA1xhNhvk6f2trK610Wx6V9etRF6ExH26PfQxJBiWIsxKOTVyTg8dbXX
uBfC6RE0xPKJ10wS8pnONH_U6Hk8dlQk2Bh652tlNfHRAwEpXLUcZin72av7tzIg7GR_l8NbQIrEsobjQ1q87TX-6FvsqTFP9gjKIwKuRcYNMLIdMaSEgQpV
y61DW1RFr0HBEpFirpj2ELnQr9Cdr-SxlN8hbMTxpaJNmH2gN2gf3BTKs7z9TYhHiJ6RMxcM_-FnD4JnFY387PNY-OeZT0i_JIjBfVfdabiLkcVc095B4SrP
-Ii72F-yIY5rOoMQWmldhB20L4ZTMLdaJ5hbKh_UQfHoIFrogqQT1ZqPhLXtbbhXlbIgscW54gjaXZ-jegbKFBV2aZEtuc3d0YaRHjZfXDzRzOUNnvrG6zTZ
IBL3tfcK0MbnR-KFpnHef8nI3LAmIhYnqeTx1ZITHYc2r6ZbUi1lh722dTaXRzYvGEfazMrUuJWzs_EGE4lDp46PwnoLKGe3EMC5AMgpNVOoIbrRbPqxAsmy
wlo9NXmfdrWXkZTMhZZApciHfAQiq0ZJ-QOC41teBy0dPGUNCQu7PSYyQPHUHZnUmELL9ujNG4Di7bQFLx6g2Liv89fX_dTxS50000010UolVs0nuBRLGW00
000000q
}

