sprite $AWS_Client_VPN [150x150/16z] {
pCv90O0000IXhxFz0zl14nBGVSVp8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhP6jaQsHhP6jaQsHhPtCsWUMt20G
152Hcxh_VHtKijcdLM-r62QKiosB_yWmEyrgESRjRqBCLTQoCCMIeg2HM6GX2nCioTjLiksQLc7UD5ohMBZBQa45sf_Qd-Gq_ggjOU4cgswQaBy2fFo3bIKi
t6CThHVRT-xXIYjOkCLAMdBjLoc4DQs2f_c2MMnSnS8f79L80wzWmSyIYkgzhEdoyBFYG35MUv05DwjgdsB9zcD-5joie9L04nVCyl2oib6OqVrahzw_aGaM
l2oZOQokbNgDsv5KxxBWP5LZzZJRMar7Oht7WfCLHrNHDBQTu2eVIyQRdPMb6RzBTrZmiQhsO6UAGdHRKTDz5doiv6x0CJJaj3vMFmi-Ld0suAZQAEVA2ztD
We_b7u4QQHUpNN6pu689cTTfv68DdLRXwrZlZoHVTCnf5LQfwjKRfbLOglAou659NgCAkVbOu96qxP77-fKc50yBBFg-XrLbB4ALiq0YOInaHcgENvBBjJv_
MHA5i9YgRffOnMwQSzBrirBJfWcCvK8b8RSEvpHsSz9C5bV9yGe01cepKhlf8hL5LJteeWfOhA15fFm_AR2XeVKVky6YgdAWD6QVgbUD6jbMjVp4ektN0PDr
tOU4dT7gQ4E3nQgg0YQh6gKtSpjjxskwLnN-DWHWikmDQjGcD2CRsK6G1go0pOfMbHGjb5IMs2pIW1qcorRnBOPStjnuL4aRy9GrgXukbp27wc-P1T-oHfMl
UnvNQRVwdYMgOZpXKZLSP8MgMazuLJPBMclIBrb_CgVgqohqwN1Ld-jNocevqkGse-fy35ggjBcIn3y6H_XyPIz6FCOCpzSaEhSR_-IBlKYJzHjczlzPxAfA
PKysawpAulUPPC-mTTlhEstPjzzzIbMjochAvInhzzVOfnnWbTKCrMdUaXHZQbmrDgiogT8DjjYgmP9njE6gf5KrgK9Ibgt2-TROephUEgqw2cks2gDyVPIf
njKjKV5ZQX9JfQpcLfKnZH4LPssfMIhSK4dUE8ghj14riHoHeTf3L99h-vioRcLA9t7VNusqamgsIfy-9RJE0Xw9H8Kxgb0w3poHH5J_tK5-LiNIFO4pKb8y
8cTL3ohQV_gkYZ46ycLQNCLpLcdFArefYSnNhr9rHVsxcPBFKEsOYl7PvaUezhiE0CSIbpv75R6pzjz-K5sD6I9zKBygutUVD0PJQ-MJnY2ASTHwhmh9E9Q-
LpLOiUDpL6Xfx0tVghBp7fMMHbcwBighLD1JIYEf-sFzPQgqkPDUf-f-LN-T2X9yfY2lLA4Nxk871wvQdpwVtytEmG000003eV_EttSQHT38riZMoDR8LcGh
iXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcmT
}

