sprite $AWS_Direct_Connect_light_bg [150x150/16z] {
xPc9SkCW340HCWZr__zthwY37Mg15ndleJTNXhZDiqLqa8-_7yTn7CTn7CTn7CUXX11UH4pbZr32y0Pi_AmI9mXVWVIWL0wd83_anB4w9Ff5tkgpIuz8KH2s
Sd3DyS779T63tBx5AE_nSYarJ2I1B4-43yu_DJsWLIH2NU-mC8WC8ZLWlivggr9ThMtjfkB1EDCYAnZziBoB8HCHtvqKSEXIbEp16znT867ykyMlM6Een7BV
haeJzJlVOOMNqX0iqb9sbVAm8d7j4Ca-W1SBoT63mJpZrm9tyNhOMU0jgJLs0rZuhH0WDzMARyWBgTV8O-v-XsrHTsk184HMxoikj2gX0gpkp7LM3647gaMR
Lbb9_vaBlLwGzYyIcq-bTBfX9715VLZn5UB4Hav1oysygoQejQ5eESfI-8JFt-VTQwt15ZQUhif2f8yvAsctfcjYlJ_8yhaJ4JoEs7csrGj0O-qWZJGMZBDQ
E32lI6P8HDjWR0YcWaZwJUbPjF-uU29-cXJprnM7UIG8yOwf9eESpXogSrtlFryodsh4H0v3SfG1wxX-Zbu6Ud-Opj-i5AbopVh4TA9-jtXaY85grQptqzpr
fZYgCqmgHHe6iMhNzVs1jaqnI80aP56isdKz563RVigMgpscMBNhUZAqjw9zTHQhPjsj_j08nfFTtgmljP8CG7J83EswlHL84pEPHMtdGxsnvB23nQfTLy1E
XBKebNvN1VmPxsPzE1JZSAUiIv-GwovirXNeTriPLFzGJDJNzZs3t0wmlPK-U0pT3zfQpH-oSH0jOokHmgaX9xAfrVpXRPA9SihA_gVDhKxqDbQSmE17WHm4
JBHdn8hUIHkO77_8ADKoOXLEWJ9_gcPj1Tde1DBGAegJ0IL5CB2AMsOR8UlS_azRkPLREKmA_8XImT01otAf70R8YwKe345hhM8O8gwrwlT81Elpmq3VNPwn
wbtZLcxbLcxbLkgXfixh6bwc5CC58ZtLMJtVPN6up88eOhWCBkgiXk-U5tLP5njVMcV55wzVb3__BIktSglrE8xZE8xZE8xZECvt
}

