sprite $AWS_Client_VPN_light_bg [150x150/16z] {
xPg9agmw241P98Jy_mU_f-La9hUqSOdcBfnQPZT784omkxn640H140H140H140H140GgJ32396hbDy0IGmib6-qqmHPY8vq4zf0oYeomWYmw8_pzhLo6aBxM
bzp43qU6Is21jFoAhbvSNeTXGJyPyvZqePLjZ4PegRlezBwM7LWolLxoLALShVncKTMQyfA8vIKC3mQ1tioXD8kvvRV4L6UiF4YJFp_LN9HXXVNHgahb44kk
2Nv0-jm6n5DzhMKg3s2dIXYhpFTd_5G2xUJ1OifBvFWnBTvFeByrZ656Is_mN6ae05dvHfvfhMVlrV96nq-bB_dkFpVhNLbrhvUBr63X22l_2l-2bKrzh73A
_PmO5gp3S0IO-iNflbM2Br1xZigyfwr2Fv2qRIzOlTWwZSgKp7tguArgzSI5raEApGrbYtfFJlAzbZwZpYzie4wPejqS8D2SNm1agJ0wMyEPTNt4kwjfAoww
U96NWNHhLZRl5_Bf6KtT77gXKcylw4umnBjokdxIeqi7L7R-qguV0hDxGxGN4l4M5QSslBzqhNOBv_x8vAIXkrL1jpduQ_QtcdPksSKfAzVABu-ROqr_AttE
Akyz1pBzdm5MGmO1lwvq8fT97QlEUz0O3i7seTgfTxz2E0Ww5-_PsmKE8_lb8HqVfDLGiJZmVh3qsbQgQvlZUotQT7tgJNkBwxgQX-r5HE-SaR5UrT_MnaIi
nrgUuPsXLs4ckrRjDEHRyRrnWgkMOrLRXMjLhtftz0BrhM15NIkZ-eitnrGsnqeFMqbjO_UrWBM7bKcdLoeCOOLanSvPcIITaQbUAZtmzXCzPwLGwVbMZ4mz
hJ2LJcJ-R6NL6-sp5QNIaonCAxbQjRM7LQknoaI4080q9IlTS7lx13EYCCDElthBoc16lghBnbkrB_xcLM-uLVkiWviK3hUYvjFVB5OqF5Rjbx9rUXs_1rbL
nk_1lK5iAeEjAWmLjB5McrfaPRnLHRcU3STQERnkPVvg_ZJR7vX9wf1Wfhm6ms6ul8R1OQoyHqPm6F8URXC45nGhxn04GH04GH04GH04GH04mNy
}

