sprite $AWS_App_Mesh_light_bg [150x150/16z] {
xPk9Zkim24Kn11Fu_mz-VShqpf9MQbflaZXQPlUSqc0JGM8naYH9aYH9aYH9aYH9j12HU2m5qy4U2x7H7OzbS08Qos1qOpEwmR48hlGV2_fFiLY1IWU5wO3d
UrcXC-npdPWU8_EyNEYWLFdwn1J9ECdhMo0YJ8YAEbIdxQZwC2ZmAZ45nz7ty7ApQNi2xqzJasCiXYZiyHp7--c34i_ZTOHeyzvEsyKZsFjl4wwNwnNfNalK
SdtdDiPEs_V4OxlyTrsg2LVTFbYxuczLlU6-14hzT8NQNahVZtPhBG9xazA-NL5U2jtOuctqUnLhLXfubFVJ2AiShr2RMPbzK9GZ3KsRMUq4uFMMKzjgi7no
im0dK2AQ1giYlSMlExKkd7U-N-dVHRbV3RJM8yvxDEEUqF3YYpM3UeJYxnfRmSlYHVpkrDagmlZ2udmuzRVwnacV7Ni8hKSCjfA7LOIV_lzGAqDryw0yi5bM
WahmGSaYiwo-jqYk6xDKE260Gwq0D02S9bg5wqEdULRmEZdDjqAvAhZm5xAom06va9NeQ2kxuP_s9jpCzXY8hDZ72I-u1Lq9Hm8EX6xOXL-Pb8FhMwLLMgLL
MgLLMgMLtl2bhC1GAqCBu1EaRLqeBUPCd8zLfFKqXJIvuT3M8rzxarw2DxkeMF0oh-SW0YxSjhiKKM1r8KqxTvSsfGPMAZswI-nlMssjMoPCtuY_PUL2W1lU
hWFrArPm0iNRtgx3wvgLIxVHEhE8_NkCutKhrny-Pbs72-LLgvzEqNjKfbwqOXimjChngfNtTZhtizIUM_b-3rQfCGH77DYUM5KSmZN68bzzvBDLnQ4v7F-L
NOPFqNBoALORVNi9DcuhXC_dpY4Jupp1PpN09AypkieikMndf_bU5kiuVKyvYY8bLt_o9PyIEbDUhidpwRD8aYH9aYH9aYH9aYJv1m
}

