sprite $AWS_Transit_Gateway_light_bg [150x150/16z] {
xC6n00000C2WV_x04wa20000PiPCb4O5GIWScY2-__lUfUrCtk8wYVsTsLhr6pXWDbnPE6rYoHy0aXHfgaGnoSyHASVfLf7r9vY0T0_sTfZIrAIaBpB52Gf9
c71AB2bCKDJNuqGf_ot1wQJbKg9tuyL0qfLo0mXXkxvT1XWF3rJO4tSKVrfd1d4wsiRni0uF59XM7MaxabbsWOl7kvoaGB9F2kpJRHheUXW86K822QTqyG3i
vYoK6kNopwG1fs6dWZAXE0T1pQMqKa7pAAnSkRObWn2FmSgtmmhyZJFZVK-eUyFgVWS5SVaOkMFf3HHCGu8sC5iLhCujWTH2dYZktt_QCag_eZ7PvUfiuKSd
ACPaDbRRS-neAhQNehRFAV6pLe233IvUq8q9KHd1AtzK_YjyB5YY_XmYVzcBAdVd435FnOkg98pN6IegFbJ8eJgqAl6aalwcfQWPBweIkeEL42etAkbs5aBb
GuLWzVOgyQQIpfuLKO0-L2Z3sEVrv4e5jsfN0jMVIf72eGcKUR5mc6Ly2biJUFvJr9h2Xr3IjYvdcawYtBP6IqSBRJ5VBUxBWgsujr19VoHgGaKMuMXYwJhE
saWV6GlROFpQczNUKjkRP9tnymyRxcTcbqpcJW6xgVF-ojnnK9OdTiSuRE-g651dh6H0xSFcnoMuHef2kDw14gwP7uewdSUXnqM8C35swz5OPuqrFIueKW_x
G0bfk_kpiHZusf3ptHyI93FrKF5rP8m2NrlARVJOWwfoKIrkQAoLqnoeGkMEMd9L9xNECGtVfFfo1h_lzkztXkztqU-lEFshCuzQdN-tRzS440H054ERkoN_
VfV1mYiI1TCDvGEJ333r8HEokKsOcnUvfPeRlNdzC2z5v5NDl43wrrh_ikr_0VoFYVzTMlx09mxuMW8VNkaR3fa3tuGuavO5QQIOzWvfEf5M66dGKRRXU1T5
cfcenKeQlwOTBPhaf7Kl9XJ8D0UPV25JGc2YglGPaDJ3KeqH4H4H4H4HiG4
}

