sprite $AWS_Global_Accelerator_light_bg [150x150/16z] {
xPhdmkGi28KLWiZS__r-PSenC5ctaSmMpv-tHXyFY4RdzYTfQMbfQMbfQMbfQMbfQScqYT1T8atjyqHTkBo9fNyGIHsH5-jduYQrJ5N5BcVoDX6nY0WJUSFi
KqmaQZxtXJx1PUApPvvn5yLHwykbTfkelHohL-Iz7DaqDqnEZzxJAD9lifMUTfqRnLuUQkwNJGXHPP_yhJpKpqofzucbN6UL2jFrlEHgqIZR2kH5xU2fCw5w
jE5O5HZzJApk4pVwn29RzLpgfqW_7qe3aqr-UnwMrJsKCVBdqRrdtx1oQtWwMRnlje-gnO3QOtMK1DbZyGaL7I7e8s_KUO0WqbWj6S-aLtb3E0RKzZyB0TQx
giFHka-vr1WI1WeeHLVRmGZgBljePpTbLofoSx4FMZkAjku2pxkXjUJusViajyDSiHt9XdHopMH8TfsFac3FFcCtuzVzmUITaqohAW0XaWfJtX_Oi6mFz9fa
5aWQ-WlQD7QZMeiJs5kYMVLf5UQYSWaYw0r8h2A6Q2ff0ZPN8TtBu4oihwUgQojfhO5Lg9acNERQ52s09MNTGUeEgpYiBUL05P6AqsLBolSssc7Vf3pxKcqo
f6fFu5XN0TXo0bXZTSHVU6Am7jNLcXF2CPabk5_nbzbJEvVHICvhJGS5XPvrifnBs7KrVASf9VHsb19zbhYR6m421nSJqefSsZiNPuEfWRB2HSuex38QddJi
597L9LRDIFOM1magcbF5IGdBCsgekeJuTYgBde-_94n10nNBqBr-ovTqzDyynfb0XUz-Hd3sZwJ2ZCcZGeRzF1KDAjhflX4WfybVAngYTAh9eX8KuoIPL63v
EfN9bEh4RBSlKrajV3cLRyrlh_3soiTKM1cog3esCbXxukW1jSVgnxKTBIQiWuhHRf7AGm4B7aF-mEI2FGEWW7NgdW7vCDzV0GfOn_khuZPiISNzU2yAFiXc
Ur6OdxPfGCinLN08IaXa9A7RjsTi6Pn3ytUSLkxzAfS-VST17cIaEyUtwBWvLTKxXxR-bVT1JaXsxn0Tl3iBKmcg9DlatJaXhP0Io35nLqipgS4gVoZJSu-l
AipgMorV5pT3MMYv1rYm7-TNrXpILAmFj-lUxGHPF9psYKGYgeOwqLM57JJXh0zpCK7xfim3ZUv0DU0T6hi1PiZ21GDo1bN3KM6YTG6OdyGvubsFX9jbdDmv
AbzCkhjrLbYLVU1kk362AP4ASS9QjFafd6cMn3jLX2HGILmWUMSXdtGHf_7EImPLS9RFlOfJj0u3YdYpG8MQQTL56mKYJunvEDog_OKxgF0RJ5SoJ1F4BpU6
VFFtpcmFN0OLWjsgtyWpufUfZZxS7JqZdnymZpXjM9AQW-gtR3NVhXGdjZkL5YSoZ0c8oThGBkoAgWKA50rLAriS1gjKPXBpLlFj7EbRil6tVonJRzV9sb4W
jtxxaBg-91jL05MMXh_OnKnIlabyAPUMRnJ_KbP1VpsLe21DRWjRlJIpS31K-uGA5KEleQgZCDax5Q2WVdLEoJ6LdwHqcLND6f8vKi4gCQqNcOMpP7KT6gm3
EhlZhnC56BZZjpNKetC4s0kzqdXSsm-yailowgQxlDeAL5rUzSloIeuFDGepDg2Npq5_kcxkmsmTe1VNAu_LtPcyEsKtShlt2sI2pPEd4b1TkWv2NNl8D7q_
D3FLswU4RDzSm3ulZfNXyufLzDUHCNPSlvIw46rw--EqjBIqjBIqjBIqjBIqjFGl
}

