sprite $AWS_Cloud_Map [150x150/16z] {
pCv90O0000IXhxFz0zl14nBGVSVp8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhP6jaQsHhP6jaQsHhP6jaQsHhP6j
aQsHhP6jaQsHhPt4rmbov2mCXc4914ZS_xx_ugzDGoYiGBPtjYx7DNu263ldB2s2SlbkLZravK1z8Ubtike9gqIQYph99VmFZftuLEMp2eR9SoMcbkWUgswp
f7U8I3zkygOp3UKjLjrajQjT0tOT8I8EX5ZDxeDZQOTLzrYvJKdfLS4q4YeTYYNdBBpFgbki_9we3oep3UtgofSfZVTh-JohRh0W8IusgNgpcc0omGd9B5u7
xEvOLTSeiuKAOvHCWTAss0fOwTEiki5YeDOgqqZ9J31VWLfwUTbQfwgP5O5QgL1vwUEmWmHBcDlMcMfc5Q0ULUZQdp2oaXDZi73mtR6gplDNF5NxIhaPYYKL
tfiiEbIDh8GjOKl5RUPbLfclybbOhdigUbJPiQeE-sTsLTTPrrINUozuVS2cCNQigiEgwafBLSSWmNcafQtAlcCLM4fJQrMy9ZiDEmEEJPsgm4exgappBefx
PUvG1LROKHcFhn6i9jqcEdQighZQN5we1FzOYOodir8xQUfOLNNnhIvK4qB6EtZiM8LjuDEgDbXeLCwTgjBml_eg7P-P4KErx9TK6ApKpi0fwtv9PTojn82Z
JnshvkA3AcDy-kSwVbnTjAygaRPsXd60b31icCTaYpPL6cYLh5N0iBvugVsimIlNbag8ZbGcEADDfT0hpWxBLHaJOYbZtAd6Il-QaUbUzYfjqCLZUNiw4frU
0uEhAlHHeObn83gipuoKM7yCARcgDcTixp8xB5_5kChoVGiB9CwB3IaFJAH2_YJwkzHqIaEnEM4OauqbUdW0kIgTKSWAK6fUWljlPgs_9KybcBwvF8vKeA4u
089Czk4fEUUehet6GIrMkvFoSh30SjwfYeCwKrbwFEz95Oc8LxT0D4ybuIdSXglqULj8inMeMYt5eEidJYGtjcNFowgiKFWKrwf0Vligx0lsY2BwcagtLLZi
TUXrgGIKhugo3YUUgkQdOWRAKpatupUfHjHVgsPKTt_LFrOf6Dfu4L-7YkNLWUfyPvXH-LOlTb57LVnxqDz5PzHxB8zKoTsl_2SEBimzggaWxZDNXQq_dAWo
fh1x7ZUK3kiknz0LYwTgxzSdAiERJ8_IXXhl1XlpLSucQjuBSkbHr52zIjET_9_wAlNUhwipM2JO1mRKgA8FgQl2ZzD7AWmMYhL3eVDx4Bjmi4DL3HEAjNvP
5N7MiSheAhnHE7zMXLU-IWDX_WvLpKBHSeUQLVW0ZACIkXBpL3uB0RLMLLTL8g5afofaJAsOkguBuCCuWtZPOtpe2tINpLEv9VhcehbLFulVQYfsh1gp5EXR
ugHcvwgvajCY2KCH1sKkEoHVTPvzG_ysEmS3000038J-Et_VQHH18riZMoDR8riZMoDR8riZMoDR8riZMoDR8rkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcA
R4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2koTG
}

