sprite $AWS_Transit_Gateway [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIhScikMwxoi9GL40IalF-p_jTBADhO9N8
whdDNxijMsSJRg7QJq2bxfqg-ZEq_4kXcjDs8kKgNsevhzLgtcx9jNsXvQmMbEx5Q2sdjDg-FM9Nuwm8hLOsa7UHX9T9PCyRA4fREHcdjAkPwJPmlBL3T6Ui
LhKgbDhBiWlatDzlPgDO9QoMj5hUkeDOvnMw2kFTEl9khAjMIrholWtUUwVjdKmpU77XyXMjqdEaPz4wv5SCICzZ8QrYhRGD6K82qzZctE0WCLQnbY9Gvvjc
lCmVLgRzsoXdvP4KxhXWXSmhP-MXb1W8CmZgefQF159wConrQ2Vt_yzP-KmgDVkazKyCC-fbixIYvO-qNb9soOune0bTxqPhmIhIIXCfQtribjB7MhE9LYAj
_6Rod0y4e3RLBwJLMKjmirWhRbT9Ax_uYl9imrLQl8mgPpLgPVJWYLTzXU79GffPApzzlsGXw7hXKbfPAx_SgF1MOzSYhQ2r8tzVM-5wj9KRPcuZhAOvLDhA
tzrJ2QlvE2n6MtaFLRQVPOKnhKPRkTKWL8oLz9vAMtaGAihASc_AMaamgrDMg3z8gn8CGCxAKi-0KLR7dIfb5SzPRQOL9h3zV2l5jrspGWBTBKRstCzd5b8u
qOf6OFLOQpWfgazJQ2zMhOv0nyTk2YUKiLF6IcZHwfX2_I0QvoDnkD3gMYleLldezVK_P2vLH5NALAl9_X_7TV8mEozPfQDRuHXjZqfgIEhiY71lvu9xnUgu
NKiRQ75DXdVE-Y3f8M_WkLKxh3PmeILG6BNglTJxidgl5Gp1r7zjo3raLw6o4nUcRHklathQmLChX4aEoUDAPGmLBZv_js3Ag3T3zQ5LtJgz3G9pdWslWhNV
df3epUXPiv8XfNBUAPNhgYyRE6qUAwm6bgo6gU8JUJAnZZqDLYCBLdcOLZ_HoRa366AQOJNoTrhPNvL1mFPszv_SsqV8cS6XzHDd1a3DeY_1dp-B0cR5yOEV
lEAChA_EtebMPrbRdKV2dOosT9Bg_DITp9crNPyxG6heNTyzJtR8-jeX-yXaXomBE-HBuce2JBG6PA6Qk2Qil4AjHbPUIbYXIfrmLQNAMfLwJLpHp_YcecUj
1FFc7TJfHmjBsVYaoAVm9qM15PD2G9-gCLP8eGPQv0aaPuNJMWyWJsjvgufWJLYpKkojI2j3i6Qi_mhGM2iK4EeH2rQAqeAnGh2IXop-kjHuA_IiwY5hlyJP
brQ6xTwSfLyjMQjnpagyLN2uHLfvFcBkSr3OnFdBzgKLSYZJ9WLr-mn1_cYhiJ2SLqEWHPrAx7ihd7fO81LhJQ99MFLgwgQjdP_UCH2SDtDMkF54gp_fXAf_
dqX1cRO2xLxBy0dEJk-V2YEimWxTeZrOz0IT4LQnbbmkIUbKSDiPWHHX5MljLrOPB_ELrGufoYhMIctLIbCenLkvzQlNC8D-4QXa2_W2U3hQWGxTJVghZq0L
OwrYy2Gvtkk3qv5bb1YQSI12MyLO_l2g69o23Flmr7qpmee9rvQg3TqjTuS-exQQDY9Gf9LRtI3MBbPdAE40cxHQxFKWLnrFYgJc3PHcf1KRhvZQZC9Pf4HA
HTn8dCUap9JiQCFnmxz2QqbdeLIgGfspWXPDKwaTqUOZdDM25WTbzLTg_VYtsJaG00000104iB_l6aKGsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8L
sOfiHROYMv6jo5PaAx8r
}

