sprite $AWS_Direct_Connect [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kJMVjGSfm5WW1C40pq-x_l7-nPdN51CqXQ
dRhIbKFvEmODeROUZMp1ktT2J49OjwboS5_nMxcGXGELsRph9UJBM5Xc9JTCB1UniCWgOJU4BSl_IHzZbwvXOOqbJhD9yzif_50BPzbLMAsUJvr1ZFhU5Ioi
iBAEq-1TBQISP-6T1PINEifs5GjsbZGLOeDvkeYmito3el9waWKpQsj-ZxEsaonOMQAriR7oEHO-CgzVjdOFhvQSinnWuJEpUHoh9K5hkA-NCQ-oq6GoLDMK
ygvr_5ouPOs5DdIsR2VMxxJ4WeqLTQXiyMTPiB78h2A35NAfDMifCsTn5OO5b6hExdX5_DvL3gimwg3Ldkrh5GZxMA-fE2jC2oYbPRNxqkBt5hoauYnFdy2I
NZyQqgJTfMfbmSIYqqgyquH27yjGhIpqiw0I9V4THVgOcOTLCAjAqvn2PVPiPM4KeqhtdqbaSxJEpH74fkAivCdl-RrmGbjjq7E8M5WOfncCaQfyd08ZsnO6
fuaoPu5aVwJ9Xay-tXBMQujlZzXSnLcnlKJWginKkjqYQw9PvVM1ptmpbKa5-qVin5bWySq1a6y7zzdE8z720aaa9sNM6NYo9qMSg_B-RHhIHUcrZX3Mh7uP
xEApi-BewpHn_myG5Hcg280LmkVlrJdvvjQ6T8ayPas6ggBFKea-2pbeUsnV7qV-L7jDzMxQU8Nk4vpeAjTvdTTG1YoYIZfKhz0PxbNLUPqFbbPvHVL_KG9-
qhiGsdwwGLRLz-jfykJ6EcBHQPNGP-aUOfyWgkgypiyRLMDNlNu0VPOsrxs9gghp-Z3jcdbOXVucK5fL-tgngkfX5SQgSbfL3wlmEnNK75RjhD2TxRtNxQfg
LcLyvLnduAfgxGmRlhFSHVdvSCIYcokF0QkuZnHLTLxdIqwe8nRVCfGXoxUR5rMrhmz2RYwcggeRcL4HSzWlObNLUPrFgrn7hCd-M4OibP1_qyHHYMSgUS_O
0Uk4Yj-JJrI8enhYhAfuyZHCLDLH5bTn53sZSHL4Zoq35bLn56ySN8Mav-yUwx0gpVVFN8LjFz7ZEyTK9Vdzx4m2dkmqCSbd04nLqgJz4uDSpwXGlEi506Og
DuoNUaw5cgvM-LHd0GmkVw4gg8a6ffGK_0MgiALIBS7XSDKmTwZmJ1MUgS8pLNYc2ezHjQaaDwkAa9I_eYhHJHBbTbLsXkIRLU9CaNjLmQOAzwhUPsFo9EeD
z_sgmXj4-JigWBEUey8pLNYc2izKuPagF5E5PwhmJ1LkL-sBi_2yFtERIe9RI91RLDaj9j-WgcuvvVTLSLqLVr_LtdRp_Do0tgCImCgI-rGLTjPzAjZpJ1N-
RNPE2W040W08_Pt-VSsmDoHWSfMvobnbhlhEcbcHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bi_
}

