sprite $AWS_App_Mesh [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBSdMPCu-b5q7OI20Yixk-__llIsnXepB
0q4ctjjhZgaouIrPNCIAJaH2NSJY6fQNHyeQ5fUmecofIrXSmQgYILZ1uWfM_lN4l_SEArYSPzKelycGFrPUmE8qAyaZpiiZFa-pECdAJlRnTPB5ALRnSfnG
frYSODNDv59uVb9qZOXrWaKxIm7fsMhkLrA37AwePXLDgbYFcz01PXRjhBfjVRlaNzVCJEG4AualfrFJ0tOMnrabwsSuJzq-XZBEuYYh1X4C9BGZpwnYnn2F
enktkimgTYm6TQ2fNci9iuh_tLq2kfDrfNswp2fUctonxPGkTxFOnKenwFyk64tIlusfTh7OmSgYSTbUxUW0CwjuZ8hsod28nV-pH5EMbFO0p2g-D9LpsbIs
9D7_aW6OLMpNAC0PX_hBVybwRMOLcwlCPRSi6APXJhgWmgpYwuXGbycq6vqsbRBS_cR1R6ghGREABusLTNg7QZMr4zciObFovhOexsMfAQPz_vjKoi9sZUho
WpL3h43S5_Dc5LkLkWewKpSJ40-kngoYghOKxz4T_pGTgs1MKLMxL8bdsvusRGKkL32hUAeAnsSmkyU_KC6iuecgQ7LpK1wKJXLMguA8kdObI-XLOQsghPfp
z3vagCabTAkmM0LbQDGqeC9QbRfsfZ4LLglKrPg6LJ2hU7s6x88eVbm5i-gKLHuStI0jAfXLl5A5EAV2iAhy13ndYIRXDFNlltInE1WS9gWACp6hU5tSPInX
aGjRonLCnZ3QBrcwAfX6kyQiuZjLCAluJXNCAhvJ1REAxrJ1hE8xLJ2h-4uLp2hUKyLxgdXF5U-fuZrLlAUAzrGfA_wataP5z6Mzglog8YTPNZjvYIh8NppC
B4M9X4Mg9Cy4Jh22F1ENg22QQcSLqTHPbGug_tUfYUUiz9DwFTGb-CxxeCuE99sgnWufMnKUqsQPAYQvLh575Hyjla9LHUCneTAK5Ifw4Ks0ILL3UsbBL73I
9654fIQDmneLdxVhwXfKjIO9c5TfIY6hruFi0LLKJqKfm3gLsZPNw3saJ8rf81pByu0zznvIHjkpmXnD5X7VVqXfC5bKHDfAhLJsAcNfqsykOpWq1Bgy-h9J
FLXPpo8D9fkgBRjytQc8x3esblUegiukhIm2cXaX7r6rAz5MhhhAucJx_1CgKdSIyR9HzBCCV4QbhdqIi5XbM-ubnCP4BbNPNOMlLSKdLJh_92ITaezyM4M8
9f6Q3wiOLGKs-R2AxlYEySCg9gTZQW7h7zyRe-gxsJaG00000104iB_l6aKGsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8L
sOfiHRO6
}

