sprite $Networking_and_Content_Delivery_light_bg [200x200/16z] {
xDMd0OHG00N1SvU0rt-tUBBxQRQ3KViQCKcfl0u8ZpHfh7D51vAqsPxH1IGSDK7IcwF5MVVdI0KEZZJYuFXLtQaZtJauE3WuE3WuE3WuE3WuE3WuE3WuE3Wu
FYixTwBajWk30HoGXIpU_tt_H_FjyKtgR4YPICnKlRiv_3FYi4nMfTvUhedwfWxNMYYg-duE5p8Wr3TpQFbzr7CdXzU24BN_esihYBwFuon0s7TRhu3iuW13
xlf2ltt1zd20OTVvvZiulA8_NtzHTd38BuO_L5f-Xr7cN7ozvNVG-RvihpEt0qFIyR3_u16v7VNdyKXekPNHWUpNdn-3qAmEUMPwA5_HFAVZgTdX-0Qfdj5X
JqqEBatCUYjGvtFer3ErW9tE8NDpNCUScSk1KLTdsq_pEP0dS_2Qpk7JZevdv7BO_1EHM9ixC3AaSbXNcN-YfdAujeAeBwoFSpYuvDOcsoEFWqjkCgRYW5ww
npgyVJL5ErHzpj6e_1ldy8g3q7Ey4WStfWSvmAZsSh6h5OeUun2wh7jDOcPwr8AG28SjATXo-LS271MCDM4tYRxTWIBFia2Q-hiT3U-w629lTlXa7rzpQjOx
T65pyBbvhqEG0yiRfBtNKTUd5HhvhGvSZIyEszlnr_7NmVryVqV3kBjylAhxpuD3tZz_d9XxbqR0V8wRWUkxXqMissNzEd7RwoXk3jdskfRB5XvLPpXy9KCY
wbUe-_GL4cpFyhWw73Rm-PyKVmwyqXbK5vMoD7fOdTeMAkePUTz0woA6Ul3zA3lQ7pU5z81w-rplgVXjegIUok4uTl__TuV9jtESdvNdsoiAHjRD7FOvai91
6v7tSD11mq6qJHoKH71GgctYe4uD1tVzz0u-MdAGCBc3iuSTd77f7VQrgvKTl7F0KZhSkff_6wZwk73m8zoqcsTn69Abzd5msh234-yOdtTfBONZA1JKZSb1
0m75aS1nTr0D378mfDtHmns25w5D2HSEUXO_JM8T69xa7CCxxS6wSF1Ud-vZd3UJHJfmF9qgKCyu_7i_wl27EN0ymiNhPnnAevgGFwpEu5puVyRHmAUzly7x
-keFDuwl_azvpDDG1pU0pJYCcYVUKIwQX-PwiKUt5qkqm_Z4Lfu9Xd_DzLpG5W9RUFyOj0vHMYBI0WGFeyMYqiD6g4DmX63m-DaAHUFn6X0m9DRXI1epR0zN
EkcOwqyft5GmDpL3waNN4-tYdDETDvZgk6mh2r_lTcBuOA5I0zZLchUFO0UsUYBqmPZykwyZgkMuhZNvdzBKhzOUl6RXJrnKiSHrKJXqubChMHrotnwodmFv
xxmPT2C7rqKEgaQS6pemV-YtngbZHmUcoDO_FzziUpg650ePcpg6C6DJ1t-UJSV6Zk5Q5tyxid_RknCY060W16BdNtKnqO_9EeW1QDwvu-3WuE3WuE3WuE3W
uE3WuE3WuE3W-20EV_GS77_LvvWwnt2yn4WSBp4InqkCLC987Of97of-fyo9f0K
}

