sprite $Networking_and_Content_Delivery [200x200/16z] {
xDM53G904011OZXS_ztI0FOsUTiE9hQ75TljTj5vW00321HGe0031HYclXZR4P3X7IFEUZv7TE3OZXZ4iHsNZCwrEltgeoCI700270O270O270O270O270O2
70O270O270O270O270O270O270O270O270O270O270O270O270O2712IxhZs2Kbtz0b9T_G9INTq2qbtlAYt3-t8TH0CmAWYyFi_xoqASOpNup4Q7P7zjwRx
E-eA-OKGk-DtGkoENmenE-P0CCS0FJ4Ld06nEYP0MWwW4ieaYDqn3ca9Bf9dGEoESKY6wmIS034wnY4jW2IL-dzAZY0f7qECZd48VYFgqLR2BCYWWySOiT4f
1NggbuD76FLrVtDpi7bi1BnvOtHmc26nCzgjiZeuZ93QFxxTlpqwE8oG0020z3gfluE3mm2HAIc_dGQIeuCVDqTxDu1wGaOV1pyS7Vdz-qZo6eSTagGvRWC_
YKiSTaZl-u-mah30OOUWBEJtQJ6cMak4hlPnyFlT-kEZRe7Ezd7mknuJoGXnSl2RMJVJSqXllxp0OOJ8y7WE-HyU5ZXia2PxakUGqkLU3hwRhiYGhqVARWwU
vA0M0I0wEQuXM7CoEoZxEiwG4a4IR8u-G3mT_EBABTeSsTt1rrTkoUP8wlhNnI6Gk1DYpBcGBH7sX8mU3e44UOY2D9Aa6zF7mT-CW3GOZA1IN1oSG0w0uy5Q
Qqa19Cd3WN2_ep9jKO9071n165CWhNv9ydA7kbMO096525Sxekn39aFIOaV_V8Lv9YHAWwnqbDuSF1M2ClckT2G0ICnJ8RAHN-e8lLjDXlH6NkleNPadGwgN
OpB4sy5_lqCoqU4qpYL_goFAl3iLaW4WUAo3ao6oVZZiI-P2lhQUAnsoRQUfa2edWVNxziGp8ViMsk4SDH5IVwwE7Cwrqo3jM4NWSSym1IACH9A53fPxdqeJ
80LEjIaB7HJs0Zv46ePWhJb03z9FrZcO4anDKRub3Wd2l0GadOKEfX9WJdAZSnOv99WZV9YGYYXq9ZliETodX_qlI6IDgqCWyknzz_TjCaEy7Tn065yEWG1Q
8SwEkXVoYeFsrnZZvz0CSOn371rftsKS78GmDje77Tkd2ZsenT4JnY23ZWyX-zCodnrAQCYWOvinKVKNJexXQMl8yH44eQV8YsS7bR7HFkAmGmXhGJfELFmT
vJXFMmrBmMQ0c1nM22Re2PKpzBIZKJlsQIjJ3T0JqG0nE8oG3AS4OKZ4eO-mEla9nEomGGAS4ebVEYJn3_fZYDsnMPOys3c9-Qs3qWwmb0eP7HO8IXq2impW
o4yS5FV1ZkdvJ6npM22nFyvn0MnF7Etu0qZrUGsQoM60K6-DcyjhSV1LAHnQVb91OdP8ddGhKeCbNZfEaAY6H3EiZ0Q70L808EWNuTgX8RtXR3NbTeS1KdG3
u8s3Ruh8umB7ziu1rysZr_g40hbi05ZWk8MW_hvjEAqVb8zhDklr8-YT2avtM23G7-ZOEbMTH0u91qXL0wI_6qrtM21fXmW3wBYug4Hc_JZbm4Zp7HO8GKz6
B15EoqVTrtefTgld0kPO43Fqq7o72OAW4bzyvws2J04ljefrWUCUKXM3JiB2QkmeY8rXTnWX6E0xvMPEbhTVrSO7f3MEUmXZ2hspqwlI3Rrd8KdhGogaIhJI
iR4XuYYNIpyPCjjXXoJL7kf5HuU6s4jfI8qVPyTclf3BBCdwZENdi4F2eGaAdBQGpexDVBKOAsADVnPnk3dia0GgYLLy7UEGnAUuEUoG0dgjrt5sRFOwWL0Q
NyJPiV6_xTqt0S100CD0yqUTEMlAVRCO709z5N0O270O270O270O270O270O270O270O270O270O270O270O270O270O270O270O270O270O270O270O270O
270O270O270O270O270O270O270O270Oo0l70jNH7tqTTIpLVevivqWTKp76G-h8lJf6Cm24C814A814A5QdHDJQ1G
}

