sprite $AWS_Marketplace_dark_bg [150x150/16z] {
xPaBZ-CW38IFa6GXXV__S-z5CuawgjppPkvLVtejEwXOP01Zlbn740H140H140H140Ifr5gIGrUojlwTjZfq6VEjtxdD3bt2LFk9EhsWwodxS5iVVDYwtb37
fvdlVxV5rlM6EcoyxlR9evqDNK7Q3LCJ_okPkeQFFjZoQ6Dw1gkbAsBAkqbehIztnTARO3LMMb0qYvPUhvygiWSPpjP5KV4XWfLcwCge-131hcJeogZu4Ccr
4wHhey8G1VdA7iXYwRge7ZVtutYnTMLKvv6E26nT71MMEIZ9rCLH3VBMGSssBewALdkR7ReeAXmYgqDNHkLl-uce8gg8Qdu-ochhQ6-Ty5wOJpaAZvfhjtIq
K-lC9_FsGgCYNp7rElRzVc5K4pA0Xr6H9LZwBOtcPL7nHHYZpeZMqa-JNlC3rzoTzr6dYdp5rWS_PcwvTYMYplBJ7UVhjAqFqeyscXT0DnhALmmTPjUL6y1g
wUJEJLUQWOT-JQzZ-n2GZxfdVbMNc9thB3mg5zzu-0bcLv3jByYcXjbLPClj69tLJHSLhNnyMefAPlQyK5IlxA9Clyxist0eH_MyMZjqgTaRkUUrqrbhzif5
pUUPp7BeChFZbBYXnQCQMP_2x3plFEfaPCWAin_PX-CsmMP7v9VOtN4JqvcTxUwFwWE_8x2xEwgArmk1tTrHmNm2ktkZWja5TdT7XIdNsJqR5SQ2DfjTP_V9
hjPoL1lChh9xGGxpjB9T3BCBx9wgyGh0togJsGN93B-86C_o2oANsTryNM8AVaDZTs2yn1bc5zZTVhKKcvtjplRY5rwvsTdkzckuskniTxujK_5CRtROtIYt
rKm2crrfTzPh9KCfpSvszzS04ffgkzl0x0qjfTqPlTdPxdvGL1BO_JC8p4wlGYxQvMR72vgVBMaAV1v6GNbsFDOeoKXj_YOgTi-tdAfb-sdUvQL-ugdYPwqs
U_jfTzFPrq-znS-EVWBQoCrp7lbwy_JJdD7bTErQ7FqafmuIvHjLpur-Ak0HkhMO_JHmjIvZDAFV6qGb-8Blv7R_pl06kwZWn7cJqrcVoUYpFlIJ4GH140H1
40H140J1Dm
}

