sprite $External_SDK_dark_bg [100x100/16z] {
xTW5ZiCm48PH2tp_8o-NMxz8dvOpeYRvfoyC7ggzzfhpquMt-cp2I1UiTC5A5wnqOWmWMPXNavyaIEc2b4PeIHSc5tR1WIuub8YGAnlXQ1UwefRUCTNWfdw-
HiL1BBAoITYavClQ2GSiz3ynuPXNL89ZDkQo5JaRXrgUBeZPEDHg-nSn6zVj3xgMCHbNxO-4HSm6pbCfOxCnXeXLpCQX82nYDe2Oi17UVOA1yweQIsH-We5b
nV2tGJTyt-s6lzMwuM_ERlWeTyEFkMxu_QaR7fFfnkDtqTtOZTsOCcOshkSfOyEtf-kfQem7Dt8GDFG2XO-6ZSP2EHWBOQkX3usrO8E3knxYjR56hcjqurgn
OCEAXUyUo_ZyCPdF7rlw_34o1srOG1W6cg3GS8UHQUCw7fM3aGK_Vv1hct8m44hAmOX2UTPsvTg043P5OwDTEHXLwC_QhbZeY8ckMEYAXQvOw8Y9hbZOQwzd
}

