sprite $External_Toolkit_dark_bg [100x100/16z] {
xTb7SaGn20PXDjp_oCw1HHT2NSMitkye3-XpceJYb2TFCjU5homJsqYMx0cxIaBMYFhvZf2mN1248eIJuedf9Lx8cmkzu1GlS94dfdLUI5NgXNEv84I7-I54
aodsohbmvQy8Dw-ZNRb_VWlU23MtjmomQebQTZJuEyepKQlE1cxH45IaZ9mOUMr4Om3XZ1v9ohqHHoDUOOGqIiv6Q8CHhjK68rmhZHf6-4P76B0ZVa4QFL8V
mIjZZ4JeswiJylMU264mybj4X3Vuvei9Rp02WZPw923QO2IiSIQWqXfCH46MZA8j68numoFUoBn0B3z6_7rKYtW3RfCGiGOJcOXOWua6CGOJFUADYBfr82AC
Ii0I46tKTbW0Oes40JKWmiWIw0F46HN96UADh4QFU2EXhoBE23GGASJCo9mFsEKCu2jJ8-miuokCT2suHQ-GqNKmoKYZT1tX9t50O0C8GcdhGLYVlUxFa8qY
IlTd-ljd4rwnWb24i7hcjNzsvnKX2CKB_anu1n64Lc8bGX0HWaLYEGFXoPDt
}

