sprite $Amazon_Simple_Queue_Service_SQS [150x150/16z] {
xCv70O1G042Xg_GlR0Vd-uC4kEjuWsHBikNJrbvfhZHNcYlDbUPASwMvqbpPgnzQaYt9bcHBiYNPacn9jlpSsYlDbNzN9_FskN0f2eC1M48gzt-_qpIEUi1W
ZblUVrz_DWG4t556XBBi0K2MhrdVYMfPkW4I-qzKIh3SfLJvrrLIbpY5D9cMCftA18ZieQt9F9XKjMzCfNAdsepmfQizPIdi99IfhgE4wY4BborL8ZxvM89a
LFCiAVkus4Hs5oLKqopsEhbfsWK9rIIh-e0aXhp8FwGgssWafomzLyKiNL55xN7mCQjDicJhSik4dxBQdXaKMofUQ7gkQd5FYMMZy8ZL3ebH-MXzmcepBEYW
aYoPLCKiV05bkWrYGjLbSQVHKwmolSgtcDLPEvCiRws4glkSgVP2L6PRgrtJ7RzYhqHfSWnRn0ewFRDiKQmAM9XupeJFY8JgnD8Nng_pNvbG7LarioZ4-w6K
gfrA1VPcUAPOxPQ5erPdHB8WXCYZnrTAvQnXgNmD2wPR6HMB4YfdyR2hmdqf5vydtSugNwZAS0BY_G5CwyqkaU85lWspgUZklDDtAIwZ_RHFeS89bREKYWvd
-1RWqxS8_VsAzODL4jq-lvFt028o8LPO3j7q3MLBi-eIXEmkAPLIXLz1jL4qG1KRHlxySkI7AgsBf_1jiGJBbGF4jwLYM3nL7gXeyTojbk9pNx02_C8L02Jn
TKEdHfwcLVLsBDGyfKFkV44kvzLpwgGADmiHrK-MBkMqb8uwZlRQdCOI_EeIw-QZAPMipR5-nUYo7Ee1AOE1ukFdwr5eUBnhujKbCwe_trelI3qjdiuQF5JG
lsLdq6cHetEFmOHA7ENXKyUh3waJiRzNWSkzny7uCQ0Sg_xmhHq2tZuVB1Yhq7giubwFz1k-Eu3OZl4saJNqbuMzXvsNK6MDNrwvWJ_MYHAh_lJVvwVOv3AZ
nwfr0olBER9DWyxCUAxoybt_2ZnLiK-35rNqFrFvfvwD87-eD3k2NfZQwVPzNyEJtNwPX7BJxJQtCkXrPIZDLPnR6QH_PjAjx5EhA5mt4BWVUtAhg7Xbkgke
cGMg1Yl_E7vUlFt8TMhhYIUEkF7pYUFV6gYsnPkFspzgQv9FPpc1zuEHmF5uTgzgx7CV_6rjRPwfdOnTTZ9odWb-_2YNJML7rMDvmDgUwLqVc4VlTtssvrvr
MPfmSEvHBpzZ1LYhMp7Q8IkC3qBHJH4UDlpjdF0qKQBJH3dySfjJUOGg077d6ruuUI7yIYKP7H9R8fEdLBJd-LObnx808eiGOd2YZpEZKYmwl4NQKX_VVjH2
Ot2WyYrClrf-WaAxkIcgPi71h9CfLMczOD0wU7C1Gi5xXKZ5ljcwnhOpemqZmGsatIHGhJkFqHUgtQRUtjRQNO9knr6nc8Wj22v5XZVRTflsl5WUIqMy7xCg
tvdAcwpYfSggl5YblSSYBrLUvVjZUasbSuj-codMec-nm2TWh8hNh6BliCWNiOIgTxfeWoJUf4f6rHz3Ve6bnLizeUhlboN1wg70agh-erY_PTNvJLUR2MHO
VPJOQoeh2LONHVQQoZi-pt8KsvkgfYkBiwhox7pHdh4mnPAdXvusc_t_p7pE8h-2pAhYbb_e8KiXHkLL-ximq2Sit2-sSweul9-ePbbSEaV3X2fghZMeComt
BMIlg_glMQj4B78JgELKyp5mLq4TixWUh__JglbS_ZN79qiGqZSphagxF834ieNynMtEb5VvtNASmfPCoyRu7bPGBPtsHKomz4cLEgI4AYyZX8CDAh6Byca_
svs30e00A81YP__rxwi3C5Y2dM0XLsEknboDkPf_TLLho5PaAx8LsOfiHROwkMMkPiSgRKMs8bkHhSXMP2ko5TdggfQvcXsha1NPMW4
}

