sprite $Amazon_Simple_Queue_Service_SQS_light_bg [150x150/16z] {
xC6n00000C2WV_x04wa200009jSwj1K6OMYJS4du_mz-EnwA4Yi5tyfPQWlSx87_a8eYCMqNOe7QDoCInzEGmBu9KfOj8ahF1sOEAIBAvPcObBUAE46TWBrI
KRu14yajqrRmit4PNo313bbTNWyAVfReFNS0kOfjiQ3ye6EUdo-lhmILNKxby0fgLimdSOKCg9mMQR7Gc3QC5ngzqJ3FM0RBFdTEOn7EOQq1bSzfFo-nAHlV
G1pMzu9gQJuiTb3dOTaqKCdtcm5hJZXr3z99Ti2JZCfZv_Vlr0fU9iONcwK_AXFh89ubTPlgpNaETvYS8yg4NLhzVJ-Nua5X6j5vOPbRvppIyy9AFL5buExE
0BHdyEMi0tBlWSHhtq-ddh3osUv1EwZYkbHfSrGjaJyOe7XzyiOuBASsxRgXdKE5m3axk2nzFKnTkw0pVcqWYpkURPDipH9_qdDUh1iYQJEMWMP0U7EA7Mrb
pneJvfzf47uZM11XOw9WyvoO6Lg6HtcaeR3SZ2fYL24fdd-93Oo3uic5VPrT5C9CsqRC2UfneuHTW5CUj9YsPh3BD-e4-EQ1tVRT87e4p100kOPbNz_ynK28
pcCj3_O9C-IXQOhMuw22XY5paFwcTNPmwB9J4sfpqWUQNzfdNjslf5fsdQI2oWEninvhR4cELahQbWDvzuEvIeEC9BvWF_TmdMEWgfGh_s4tdojOV8sg-Rc1
HQrex61RHwrVkFaK7_Gxh4_MkPVK_VrgU6NNaf5ZPOqlR7-g4vypY0PLzFvcN_pTC9W1LCvxSme_YahT3Vucgk_NO3UDjC4o7xJsTb1uszhJCMkNgt3BkuLv
B3BOHOhSQPP2qdObTYadZqLHgrZE8xqvxwkNlCyuDQXoEEDOb77e-DY4Sbt-uLnsjYOxfrBVfUX3DrlCJEvl3rKofQbaQk2-8m0A2gm0bXElhFfaeAjgc0ag
v4_f2hJ45NAHuKQefCr9ucv24sqD4JGyJodg9cBw403oWixBspg1_UukTSZsY86i2YHkCjyIihHY-Y7akfizAV8EwkQa20wuFq74ogdQ7Hz6DnpQiWaa1rlR
q0Ho_RHMecajLasszVuCXOB9zX-v1LX_Os8pRfTc_rCAV_4cRlwjvIGcy_GRNfh6tclxTea0C0n0CNGCzp_mU6RCYyZpLQrhFkqtVBZ3xB6m9GLN5lmYXL_l
y4kd_HV_K1L6BEXIL6qu74wHPIQoOWKMlq41hAEZyekIF06KvE3gVhvGI20BXVcQ8zjVSn2NBy2La8kgKPadk-ipbth_aYH9aYH9DG
}

