sprite $Amazon_Simple_Notification_Service_SNS_light_bg [150x150/16z] {
xC4n0G000CAWt_w13J9WGG000C2PDxSroK4G20SK4T__VVVONVQ1BtIMfDswsft9c3ybOYHgAfLvWuYhgAqbghIvehA8p5hPTbNQry4KI7ig-asczjHnN4KX
gVpKbMq14vNMnvkwLleobnBk9o1oo6HUTta_TaRCzF3QWcklZNlPRfAFxcEu_aAxh3XC4TVLLFt6LEtmevJBeDejTllnyK4synpz6RadXvICux9-TtkEotuA
L45yvDo6scbGPFcuX3GFTKRQ-TjzLRNY4LEgVw6oemKeHYVqOKj1zKU_RGnWSGggfw1uUv0yZUWCbEMSyYDSirIS2ys0AfKzRIIeI7uB0OvGpGQLZWmL8p7G
OmTGilzad40b3-5PSgtgXeTAKM7KiDfGHbGayd7FKo6MfYINF-l8Kw7Ve9ASkkmigY5ffs2L-DM5mhnDCHTHjwUVuh9NyfOYUQlGj5zUSBFeys8Hz8a1ACxQ
QqVS0wgqYcDLVxM7NutJQwdC6ofyzqHK9x2fIhdZfQdYM5Tligr-P7I1MTTH5I-jtoeCkbDQw9TIkHcq8AoBYDxLf30YxT8ULFTbGRT8xL8gyTlZ08gkpGpi
l_1hPDL7LAgPr_MDn9o4Jxr9OPe6CKl3Mqz0PK9eET2E9HedZDdb6b8rpzTyIG39rJ6NHqJLFdt72eD7tptfeLK-bUv7OHnJr9hUwiNszjiQMELJeUNUqVAn
f51iLXqbcBLXLK2LMb8GrgLkIQ33-zYgIJLRTlyJwtr1EJLdIDygsVQKMQg-Bxwdy2FrhOgfPildKJbv7rPTImMVdTjCxxiRLJ6LFFLW8jh9kw8uLWNH7hIS
oGoumXohmim0B6EtvJYBgWfodNE5E5O5L7QRc9sMapCEG2YoAfvnD3qxEvaqi2gSdLl-JSPVQy2gW0hIpETCezkwptQAW3gjYgcWndzQRZQEA_g2nlVVmwg8
Agyuno4pmwflKFMep4UJYiRLL105IOud5N-FgiA41LH15owcYhjmFHLcbHLKyIIj2wZYHCeHbHsYCbKx8zvrdqgsJwbGVQRQBp4BL8qmzyTKROFaChCu_Fe1
AkG_g6JD8WkesWYfu1JKiiDGTgcuZvXgldMRfJ_4eG3ZYV7C4LMsmk3Vs-z3nJlX9rJiL1YI0LzozN5cPgV2a97ax7PNpPgZGXIqCwZQYLIM-lWimOQKH6W1
A-buK678OgtVw0IijcvJcAyMpAc9saNUhM8BDXl6MAJZkApgtoPEtp2DDkjXkvGGHAtySRoTlmsPsZ_yLHb9nHcHzNCc2OCxhqxWMh2JF9v0I6p9hlluNitM
dr20T2uZgAgjECqHdyQXvITVe5wNd1AAfMjELCNIoi7firLIaV_hfDxFzk200000WW5O_zPQW6-R0W0001G
}

