sprite $Amazon_Simple_Notification_Service_SNS_Email_Notification_light_bg [100x100/16z] {
xTPNSeG030DGV-l-zqrt664FunHHfPIbwYsT-4qSB14AMWKb0aAE07farQf0IgNCQ2O92BqXHR9jToFkPk2FUO01WO7EY7ysq6y6Bm141ZIGdy2wfIkiB3Ah
TNW009Ms1b28pW2lZO71BIr9McTWOWGesmQeUMv4HmoDc1gCzBEo4OiLENLW52Lc1gP6Sx0hpZt8uipOu9JZGJrQ8wXIPEGWNUD_DJ9av2WRcJqCZ8rwOiLt
Q1Ju6jdO3b7EQjYOnwclQpGOqy5-lRCQDaAItOoRvBB7muQDqyJNu4EVWpOSl-_QyFkkDdxMsh1nWlWwzpkrZM6SLm
}

