sprite $Amazon_Simple_Queue_Service_SQS_Message_light_bg [100x100/16z] {
xTgr0O103030rDb_O2hStIuDpg7liIf4JaMrlPhfhUrlZsgX8gQDd39oniWF6gFlQSVsPnaxuq_6_kqC1aDwvPqp6D8IwHM38IsHblYk60nfYRI4mP2MI4iO
3EcLj8J1O2ZxIA-COLbkN3IcQ7c80W
}

