sprite $Amazon_Simple_Notification_Service_SNS_Topic_light_bg [100x100/16z] {
xTOr0e0m00J1rFp_mPIu-p7Ru6myLvu6G7KfRtLmb4l8St1mS71ml70VvBXU4fbtsstMEIrpfylVlSN14PPtOtX_Vt1mcEVc-K_tMeuihcmhcLhUtOvzKFRX
u33FvLqEUHT03G
}

