sprite $Amazon_Simple_Notification_Service_SNS [150x150/16z] {
pCv10G0G002nh_Klh0DmIp0RnZMIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBSdM9DvEqsHdGIW02og8-z_lDwHpdjH0
qD8Upfyx9s-XGQ_fthw_rCAS4aASYxHTrfweK793MVv6rIgdC5n_NQKWXSdocwfAJqKfHGGf-SbBQmNRCr6kpIcaP5fmxQYKhljfyDSkEybFgngdCrc7_fpE
v9zLrNIcD9j8A-cC_9ogiMkANKkgRjFHm1Iuyi8GzccMf2Ea7wy0H0qHffI8wqWroofdeLQMQcrVUNX-DLPDid8weZixY9eUKaUgFekYjhEnqVGK6Qdw72hl
xRVeN1i57p5KZLa5g1rM1GN06gd6BDb2wSawcbrh5ui3rPYbMoXE3odjJ04nKCMilKhvCrncLJtwi6IhsLNrO46s7HML__CqmUj85RCQckU6Ye-Vq6CtuBWr
z06BiSnig-h3JYjZwWUgW2MOLBigL9sbDU4K3s3hCOimVdig56js8UmXIp1--ogiMqXkKohahLJsNIghKQLYLPyfbPRCdAxmr_62ho93D9zBjBPf5J8ebHPA
VYYhetg-X8fe6wK7BFLArJX5OGrKo98AhEnSKL_Bmw-5ax7ALbHWUQioeoP5zE4kAeN1cr3PcgfZhdi3aegQ5orOdeOgMrFrhm4ayrHKD3XQQ3CgMrDry-Rw
rGavbwf8VJWW8fjIsPfAtSL6qoXrKcLBgkfVZrCSibcLhQWOQyLpPB9KiKeaP0NJwWXLSxOHf58oKqA8kLH5gGQgzhKsK6dsgKhyjkWr3AJWByUg-bZNprGo
wDRvPY_D5gg0GieDAq2vBDIa-QNIK8LA3wiLp2aIKQ6RHQIujsSRg1hEUQ-MEwsgNuDq03CUh9TE6fGgKDM7uSULPrN7OsPdtUYj1WsZwfKgLXrNVlt5fEgu
wyqSmwUacrAL-UPVSRrvbVOp-gxIW-sNQgoIQ-QZZligB3lib6fLPH-FO7rLuNhDATNA21vPcUtK-_koavrIJStsTaAUflvAP-YzloyRNgd6dG6iniyzPxgB
AdhT0Rphf2ZLK8Nw9AeYxnlNGENDSConr-bDNgbYbKLhsOUhSp_ZTjAuLF7gNEqf8rLN1tMnq4dTKiKgauVNcVQIyQwFpZVjvfz1jESEfHCgfFBv3j_UCbBr
umrQS3J2Q0ueLQ2QJwZ2rEhtBCNzKAez5J9G7KFK0XPTAh9z5HAeqE5hlsVnfU9lL5ciEbfIT_B3AeDgSWYH7rPPwyCXzFB3AejK5KFudZzK6NP_Jlv8XKRA
tS-YggcsBLLSh7wgQXghd1E6PHMA5HtQd4kjn2hdX6535HUB4v9jHbNIG_Ag2iKY6wZ41YhtvTAg2iMgeOgRpQXmmd2zY1khudF85gXGg4ZbdZ2K3LNdsp6K
OqzeaofsJXWMLHZ3t6ypes9cTlv_kgp26DPbbZl3TK-5vp39c3LMoJUgZ33ZLrWrNIdx8tZ5qWOBoG_Te6tDTgHz0qlE4mQWKjrKWILRB3fVucb906wgkgI5
9p5yBwMshKAricsmn6aIUogmI5TOHL-_i5fjKuLWOjW7B608vSf7gnSRfCy7Nvufdx5oi9tQLrq7jwpph3AQtFkgtYXstPcIRDHglbo9gerOBO-sm_ignAvx
YTspMfrwuFPLY792gBp9yDr3pZ7ZjYgEvdI5k5JHCr8BpDEcVHNIIff8LbjBNuxc0KbiENqdMjWN4KWRggrehSpFiqnjD_ysEoS5008048J-E_txci4R4h1t
cAkPgvchcQkPgvchcQjTNf6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5Pawm
}

