sprite $Amazon_Simple_Queue_Service_SQS_Queue_light_bg [100x100/16z] {
xTWt4i9040NHYVl-1oR4W-PNhSnkTmOoJzxLOfcPcPani1q8I0oD6jA2nkk1_lhtUneQ6Xe0gG6mrI0pQ1dGDw1hq3K837e6aK7783JORX0RiCs0mAZCg9Rn
WFmn7ebTZBDjAp9Z_sDt_tDm_sj9VatSvTg-rprgntlj_iyC6XeQ6dwJEUjtE8tQWHYOcPcPtG
}

