sprite $Amazon_MQ [150x150/16z] {
pCv10G0G002nh_Klh0DmIp0RnZMIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBPDuCr5sMmS1A4Ai-lyFVfdWbvWaDlBI
zioQpJs3i0Iuzu_mhws42H5U81BhTQrBHeJm4sJzHrRIOO_MzIzOcHAnlbvHWvB6zaQ8I6wsKeIWs_DbMgvEB0jCFItg_m7h4A3SQ4NmHln1UoUGVw7yDcls
WDUUjrdbrM9tPtZGfSuwJbBXUOzLNow74AYx0RBlOzn2GI30DXyjBz5tGabxwhcx-GI2R6Rn6p4pxP43TrXXPDCJmrZ3UMBzq8BbHSdm0eC7_VMg0G3w0J3b
KeS7MbjLMW8Fp8Cbp_q0IyulwDmIZagBbanQq2HPapKYosZ6QfHM-B6Wweawr6zmsceSZPNFO-TYLMbf3au_QELvYvB9l0gAos9oF7mFWgv31LOo5egjlQ-a
GFq00YkjkDQyrTZF36YYhWGvLFF1WYwct1R3ab5h2MJC3w6GOQiP4reCQzGFelDIsMe-McX-64Lu8JR3ABGiGhEaH5S_XM2gcKj6eONGFL0rlu2ABWsP7BKQ
nHvw6JDfCxlelbOxVjFLXIqUjXhVQKv-inN8OQln5Ig_apYoZbkDYL0faNW14ybMiFIurSY7nLOlrkkbQbl1weUiifPjPbMveIwTpPOkdB4QgvRPTffftd9Q
FgVDWuBFM8tNEk5-vygsxGHzinLlSifgl8hRgillOac94HRQvcsWxkUinZ8ic2a46XBh0o9iqnNFEQiHlztfCWh8zpbdDNmVA30lE6CrrRw2V0_z6isUKsUi
Z3iYoNuzp-ucX1W-Y2IsiwC4yGiazSDMYbL-nCPHVs2siN40oa4hIjCvVzDQBkTtWXXe_hrhWpVza5M7HDu1Yuem3qWK86af9Fe1AruYpBtb_H3JguZ9xcJ2
FZl8vOATCBSyjPKlvyLu8D6Pv8vrvKWRvMRksdf-oVx0Oa4ggnogFW9RFB9M_kSpMJPhjVMgzp2Sj6e0qBAZ_TAY2QkifNdHMrngpWeUI5hFBrfEe7hJ3ot-
FSwSjjBn0k47hqffrWe_efikC6jbVzNA3w_WkBo2sGf-MVbSjkFhLLIqki1psTxrHNyV4A4XUHRlGMb5ws35pJp6IBVW_3t8wTHA9nYdhQooCdXhHRF2uy79
NJI9qEeLft5OqjevcnkhT7ZY8xJQrub3vOaJ6karT8x2BF--iF862Hj1FftjpEaiy2BvPgrHQUKTjQvabXZALYKZ7rA9VQiuPmBScftsarKVxZGSPUV5s02G
R2H-57TAXDYYG6Rrka9MGe26RFvDifedTnCnGqyWI_YUex2gj62VvYUPiBBnpUKkLNsNmaexW6zeMLeq8X8X8fnfKmqQxOhjMjbgLyYawKTEsbMYuLvxQxv3
ijexfJFU8Q0paw8mtcFi49NZpcv6nMX4DfyAyNchc42E7wID-HVwDO4iXgsrLMvMVNnpTLfBLwmqgfXlX9czWA3frf3GhbYDbeELyJDm6QhQIYApxjQoqgeC
LjDngvOH-qKh1OvnGu-XXPxJqjxYuFOvHe4_tTgg1JwXrU5_cbwmoWYiiQDQ2clu9Yk1pD5eGOPliVBbOg-6iu_4xF-oKAKbs7TOzKYdLQUe8p6pVhegsViT
Ld6WhO_6FZ9rfcjwG7U3bKPqKkJ60QqSdRZQTIlE6hgyp1HMcb_IFLRuKTtel9P-B1dUPzK-OcMZrDfg-zizLfAsgBIWYRqLv2mfrwqyrLY-KyidyfouxYGo
emJNhKuFntcjF3gJrFjSiTBbd8W7OSVBmEZ2zDraw3Mh_AW9iS6JW_MMm9E6cFgnYrPvc1MBIJgZfKZVlN-xgvBn_Y6b04qgBMa0y3L8wtx5AgCj5NrB6Q3R
MjBN4jOXQE8NhJ8kpAmUZh0QCdnh6NTuuGlnbo_kjrZLAmhOMNH1k2EiwEQd6ATmRb3IsCyopg9zNudCppCke8pm4mobVsCLPfp_Ke_5nl2BZ3-3d-6_PkUG
00001eAG_-lVTtOH805lHRP6jaQsHhP6jaQsHhP6jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQq3
}

