sprite $Amazon_MQ_light_bg [150x150/16z] {
xPlfjkme28K5We3l_xuzfArXTrMMPJJhdi7lpntE2TaYGIIc_48MYyLYiLWi5el5Oh5OM5RcT8TPi_zXHShfBQn_Ifb9GX3Ql5nFcAfQgOHIQa8QvSv-ULpa
6DaDEqoNQBPALe59hGwB--LMvh6b1xlTcwVaNG2vIhf1vH_oiyuoYS3PogKKnO4VEpU3gAfp2bBDySDRaJYtnfBfFmbsc-awE2aJg5R5Iob6jz7wHrToliqs
MId5fOvg0bnduX6skNIGgtyU_-0oZkzM8SQuTr0K40rUXZ6qiyTvwI3zW-8OhGoZUoIXo2Wj3cKGY3oDufH5rs1VHy6WQgglokV4DRuoD2jducfxiJPAmCFi
tNaGdpfgX6MVMOc7g6JzIVXvbPOoJbL2sOjj2HpNaONJPiKpLOKpo0dntb4XkSn1UqKXFbKKnaQ5lNJZZENPE6wr8Xwg9KsWPXw6ayHDdvUJuEKsAuTEn6ZS
7a5yJyf-F2CfR6KYCk3ywGi4fWaUZoejhvYgbGQAlpEl6cLq5VfGsbD5ZOhx57uOLSs4wdIuzvF1g51qDlu49nS9_3bYW-iE7GUcG8FZlQOaXsR9nYOmjtRv
aa6OPsdjtRFwQ2ScFYW4I5Jj7rI5eBYu2c_rQOxHyWU8r23AnHmxopPwxJtQXQvo5MQruv_NUxlTkiZ4idSPjU6gC6MMCp5l_3u-8jg90pE_nq7YI6m3FKVo
vun0qMg416GKJuIfWqxt8oK1yPocAA2nqUZYU4eWonCW_PiQlkKVWkMQ0fj027Ocul_thWP5kJT_L5Fns0nc62d5G-FMA3Vpaomq5zANGFJPa8EpG1RS_g0P
XBAmufOkPz6J3gmSK9OsL84io2Pmem_1LJdI6mW224blaVi80mNtg38O-ojWz1DL_CQxrglAlvugzDNi6UnJXKi9JhvQHJ-BTh4xKg-uop3inNSjDncgphUP
OVieCq2Agt_lsGFZhVFJigK3MHI4Q5rO7ok8TwxDf9O55q8wj-9GO9f9aasfTtqEIe3FMvqj0HJbh2oRMSaOYZhR2sK_gFhaNDNdFB3X26LAYJTlLSXXkZ5J
IiIygTt2CieXld5An1fb6kZDFMWHLgjwl-3EYyfrU2lmZj4ke_Dtz8atLJFLZI6V75vAcr_T_L27Ynw1nXqDgAcTebGb0RurEqM9h-ognO4dgouxx4ldopgG
TAu3oRWaz2FdkxKX1weWcKtlR6jx_idcj_37JHn6bNwrDoOb3umJ-xrJYKtB85QV_hm7Ffr_Qxd7WkIP2w5HkY5HkWb9bPcEpr_nRNWUQmx7t9C3E5IzRpZb
p2aBCJC5Pt-T4oaCene0jhi3ftTW8_ubJZh9WRN1ScRUgR1qoGaw_xedwBpp2VRf9-Wo3FQhdCnqCDj_YfMWdR21wuPF_6ABl0ETU-8Nqw36uqLOz2yuR8-t
NJRp93apfJDMBUqGSzgHoqxTR_QH7jOwXzYocaC8YDg7Jn-TkazHemdginb0sIV-N0OqZypLwNA1ecyUdbNL0fk8xQyvqlE7CzdBXRWqltm1rrvDxrT2N_EB
glNr6IfhVAdtQrWi5el5Oh5OB1QBnMBnDm
}

