sprite $Amazon_Simple_Notification_Service_SNS_HTTP_Notification_light_bg [100x100/16z] {
xTOtaeG044DHnRh_WJVPcUcg1c65rO_m3mzOK-8le-1Ls38GTeI3UOmskbzjapP3J38GFiEAjAqTPU1f1ZVs0eC6WqC6zZNqk-GpH5Qq38w_BOOtsDdF86Sa
3R8Jse14gb7NRMGt0A3xdrdZ1bWp6H34RWQ4K6UkDxg25OQwvk9Yhp2WZTxywz40am6OZHZzlLl7wp09PTYwgX53b_Jl6keWnE2CzQvgn82bmuo7TDlh4IF6
PSep-DBlO8oK_zqO-T_rbczjZ1Zf0cSj_zGnPfR-
}

