sprite $Application_Integration_light_bg [200x200/16z] {
xTtNVkiW48JnWHLUuCRl_xP7IjyqqYGpElDTfIV_NumAE0J_Oqgfw-In4sBCY1Yp8iRCY14pOdCnvBWE6DmEnfFr-HpN2HnoN4aSSlIf-z1nbUCNoI6777B8
8OSSSiWXXnnoo26777B88OSSSiWXXnnksANiXpeCksK7EWmxPeSv7BlcHpaoref_Orpsh-K5QtQKuuxH-_STu-uW1pagrdmVHpt04N-oVHoToY67778qTw_i
ZheaR2MZTXI4I1qjWTaH6VoE1LlPMs-UUHsEhSkBrupIOG-CX-gbD4P76zn3i3WSQvNVKG2aVWv7dieX1uWTyVQTrX7VdKxWU3K9LHASqj6mbMlVgXb08dF4
ULChfTX7Nz7Bci_jw9V1TNirF6Hr8iSOyidDOfdPqMl-s648sNIEA2cMSxPIiVOU8-S0OPk_yXVhPtvFSKP7mbe9GoKHEYvOMrxVFF8v341gh-yU-Hm9mF9w
SYNnEHx7THptltV88KSS7vmEUnZMOU0R__cZtFRyyRfSmnNYA0-Z8tHR1t9_QCW8lv1b5iVu9nke9t6C7oc3H-6D7VxKyjx8TOvrv_6HbCCnFhDnEiPN6dB8
iSET4O5ZSATAuFZEp45rzpQPu_ipEPQmbPOwhMCyinOgiph6CvsnrAPrZ6UU8sHIntWb83xvPvdHCLwPCG0UraLyCaVC_VsLibOkDHwaRLR7k3YK6h-ZOirf
7V6iMKxWo5CvvC0v77wISPwmrXaTZbJYwQDGEb9yyizQetGyF_adXobKFaViqeaTaS7loBKpEsh9QrQg_bxj50uvv9133ZdgFWx_jaFxJ7JRQz-FUiSmxSD2
jo-EzYcAUTv9uTh7Imuvv91ZbkIGGmuvv9133Zdaa4CEEUIGGmuvv92383dq_-Zba8EhypbmEWVac84n4KGEnEIOYW4mCsBCYXYXWfs28rBg7m
}

