sprite $Application_Integration [200x200/16z] {
xTs7ikCe48LX927WD1lU_srtXNq3Sbc87dpw1lqL9i_uAuL6OUgwtzZLrTM_Npm2WHW1GOgW84LWaA8m-91_BuTrH0RVyHs7zSzp_6lik1obR-Au7EWhZIYU
xi7nb0OB2C71X_0TV8ZUmOVm7No8ti67y1ryYDx1X_0TV8ZUmOVm7No8ti67y1ryYDx1Xn0S70Z1mO4G71m8mS6141mS2C71WH0S70Z1mO4G71m8mS6141mS
2C71WH0S70Z1mO5e7VBL85h7buCe7LyFedEq8M5sBsbU3o0AHmEok9Ur740q3camw125em49xgMj1v0-HmDIZWqVSQuoaTAfWY_7I7gImd48AGoWnt4IaWea
FKlXE80azt-npt4M4WuTIUkGWq_MvJWDENOahKF6EJ32aRGE6UV024VIEcIS0oCSIUkGSGwOEaJfI264jFlTfWvHE9AVtDQqrB_Rr27T3k-gy96fG_eSQN9F
7J1rIDDHCmuSC7L8XyExhJaaf30_Ec3gaDEEwBRMJuly1NMc3Zdhc3ypWBJwX5sc3ZddIAviWUDC7NBA4Sj7GIDJXpGTzwDyGZDJXvnqp6Xdwf1n3fWwfEbO
Jo-7JHrowZWF2WZP8SUE6tE20a9sICFXwm7YfuEjyvKTS5jpmbQQZxVELtO4TvDux-TdJxY2ztuD0AmT3KWTwkBYxYqHneukoC75uWfJXnn3qlpSiTJ61QOE
GKEopbjh-d3KZ7ck86OEmRbsZd13X4zFvm9C7Q9oJDLLbhyFJLE7A1phxk79ScUPEgJVKSPYsbqzpW1C7TBjcFRFifQtUM_ga5x7ms8ulF-wgKF6EM3ga74E
c3gas-4V5YcuP-gG7iV3CdwgBkTD7GBz_F3LM0J8ZdrpgbQ8hSBJ5RwnusFNQ3Ag3U8j7RsVhAssTxJtbCPUQEo8x_coEKIg3HB-w2croVcgB914H3wVIPS_
Si32STiSM_l9fdV0o17b4oGESC3K8UCSC7N8E0VOZkbsVDpRFv3IEs1nliBkiS8om06kemm-NxiUvqUACVOwG7N8xKwEt5ltZp_Avhc__EDJbmDKHtHRSopV
dzrkSy1L-Iu7c0vvlDE9fmutTJd0SnH8rI873ZTrES1qoEe-jOh8tZ67Zzkvlii1faFInvEP95lrZRPGBUfZbmCyHod6TLsZb2g83mdu35dw7E0wzXtyrv5E
1omSYfVycmxG7Mr8MOxrEi1sj26poW6D8uzoo3W7D8wiThGXPS8e7D0uSjkXX0JLSLxIE7BJeOHCclFkFOqZZt98T9ElnuTNEg1nv56EgNhvPmjQ1pIEFCZX
Iil7opz1xu36aGSvgWf3xu36aGSwQeRU0OqZ3tVC2N_eWCQH1pbkB_yiQwLWEl8OntwEy1rvb4EC7NcKGumTUPH3Z1rvb4EC7NcKGumTUPH3Z1rvb4EC7VbX
icaSRKXyjIFlFjcgSRGXVgYZ0LaA92aS3KWiZ7cOem69xgM5OOuMnB-IiM2OmnAoO9oZ3OdpYnG134UMKK6Hma6041mK2C71X_0TV8ZUmOVm7No8ti67y1ry
YDx1X_0TV8ZUmOVm7No8ti67y1ryYDx1Xn0SV0ZVmOVe7Nm8ty67w1ry2D_1X-WTV0ZVmOVe7Nm8ty67w1ry2D_1X-WTV0Z1GORe7L-_ot5zFVhBSJc-Lp_F
uNwSmrsEByMmXrmELtSvh1a428L1a30K10b3yTqfZj7LrNy
}

