sprite $AWS_AppSync [150x150/16z] {
pCv10G0G002nh_Klh0DmIp0RnZMIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4koTMGmcRSJ7UbH60Z0uJ3OlF_x
xj5oPvZIXYAEbFrBnnw9Mb-2CGHfcbIFj4vORwXKQZuWgKW7rfkgNjE40Lct_qEbICAasjzMQVbDo1xul-rDbURvbKYpAKrAUknwzfwow7zFodAYNrB9uKcY
gzlovwQcaOpeu9Lk9BqSHxQOwXwhkodhrjsbcOLKjrZLnwxRZSHK-ooluMht4b7jirBWHSLOOv-L5XL54bEDRLIrK68gplBsOy54L9nL28eceA8iuIZEghcs
lgtYh4vH-tqb5w6qiSLAyKB7wG8qhXhBfypsC0T65YhEQf_cQSj8pRaiDn4jh1hNhxvlxMw4tvFIuUaB5MLLMbJbE5FeJLdLzwkwK36Mql6hnvHAYzqtWgqj
L9HLM5DGtx_NjEmV7_BcfdambjBvLy-H4xmNYxtNZvkh6AlIKazE-IwMYsBtP-GgnkAjQXgs3ey0XP2_3qbLXDNuKZDBG0LxZk85KQYAi99FGAAIwHbqSPTF
7gfQivIqnXEkfAvyR1qk5bEDgKQLVVWuIp-eiYZsQNA4LCxAV01DlMVxzwjUgNpI5FV5L0DgXgoxT2LiqdmiVVx4LCD_GM_jdFZTvxeKKmshMBtyNLLZoUTW
nbIZdDLBjtDIgwITbpK_QaoLoCF3JaVeGe1DBQHYZHrtEjcxqZ8w_sf0fJiZac4T99q49_PzLQV5xf1idhBJIlAlkeYfnaPNqDyTLU-exAvA_XsFCUXtH2MR
V4Y5EH5GvJ46wmeNxuwhF37LM7S5CPpt-PxA0ge52-SSTWUkyWHKo481bNALtQvsOE5e5JAgJEMvsnay0AevLwpikJlukGFj36S2Ac39rHu1hyg-ocwjE1rP
ti4zv4oeB5OSpAtLUPnXvmhiEgxEc1ix6Ha_mNC5d8BaElqysz_rvG6iyljSeTmzTv35ch-b4Y_tdypd2WxCa0EkN-oGLwp19w422_TJ67Rki5w_NKNBNVnV
KstsBmlF5J3atA6xUiKQlB0IlBRfLzlYNLqKDlzkuYfnornY2VRf5OBNBuwxhaDLUWxXvwJdHvhqd8qNvmwEmkjzOm-zLZac_Qum8-SAw-jbvmk5gPgtztas
DgWWpEgw-kkZAZuBCtIkHfPVk4wEMU-hdDEzhBxHxADqyViThkCdRKo5zPwzh7wYhLPPbCVdUYVx_81Af9yjwoXULdDi8x5NPUlzGfRkKywduaDM9g-AgavC
ITz_6L4MVfN5LUt0jF6GfR3V2gXwGPMEPonVdoogygYu3CegoFALAAP2MNPL7SzO3SQFg6YwP6zM3rWTlosuYaV7PMwWiWLKmMoZahwe6fkeG-rDrQ25xfN-
degpAg1UK75M1jIBga56BvczfU8izHTLx0MLbRx5gkS--GsL74VkZALVK-hsWihtNabimMfbEi5wHLKEJn455f3yW-8LbHRusus9fQtcwIen4LNKvKaNVw5W
iOnehALZdQ8MpNWGbMjOQVOWurciruoWvAV_hwkGrkIRhZuJtrRn_9cglvkTGm8001W8GlwlVzzrc884p5pDNCrSpLpDNCrSpLpDNEsz8bkHhSXMP2ko5TcA
R4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSZM0G
}

