sprite $AWS_Step_Functions_light_bg [150x150/16z] {
xTg7SSGm34HHK85X--_NEMVp1jQEzLy5_nA9EK7_30000000VIjnesnTFhPuiid4AF526R9GufLYzF4jjRMws7o8FMvLtQbngtkyLNTHprcRnxTgqPF5uvlr
_5OzlrawseWRJK-QJrL_KyKdEFDjzpyPE4MVRvnkTEDe_FnsPfBH-CdKnuJyRExqf8ggFIwo9yqi5pfHbNohD8agggXAEidtcQhyCrDKoRVAPNgXYgfzOZfD
hnhn2wadWt-LVAiclY79jtFSC3ZjgQBAxDkUEFLH9TygVUE06uUgqqnzpEq9tmsg-AU8__ecKKNLkPukKUN_X9Tdz5Int_wxJQV1VllNKKvPxBUptyv-E_lj
xBUptyv-kzXl_mtss_yO0000003N
}

