sprite $AWS_AppSync_light_bg [150x150/16z] {
xPlPikig34IPX13__xztSj9rDaKYwefjyw3rSWOSkoCrGb4bNS5n7CTn7CTn7CTn7CTfNEb5vNQ2e5fI68YvjYSbbHW-44jxHXB5y9L8xNPDEVmWlGW_oFoK
fbZgZsTpBJ60T9ikWQQGgqolu0pH_Hug7WX9C-gLJRudK0cUMSbpwdV0uIAr9V_TOtTwvOxxGRmyJFqW95w1QWUAodAWAEf7SLM4seyYdoYADeWIIhIrAMmx
8bLU1RZKjj7ffTk80K2QsLIf6maZrNxuHUdVg2MbN4MvoovLo1ylTJUadg4X8fEc799ggXn0LYzAlJFbVwMPzryKHJOeYjaHTMQprLaj6x6y-dN-OdRQrJGt
TVyLP8xmjmzcRmJTDefwdtZ9Hbo_fBdBbXgpSfktR0Jaen7IIrpRyec6rrJXxpFIjHC4IROU4r6lsLM95QwwaYmRl4uBmWK12VCRlVMokQglsO3UtRpap-cf
q1ljAKmBzKNU0v1lvmXXqvHBduMbLfsNZbmcHYvj9GlkNU-SPCixrIspFWzPUrws5j8CPwg-gaGK4LhZMzLJGqjF8GGjBzb2Z6RdfKu7MrP_WHZjtbOoaiPp
CDhjhiTwvPe48wvKxlJxgduwNDJgO5T5oCToKqyBwIcsqa3AosUnMQWEzDkg2a8p-EmnLQWAiptvc2eeK9NkLnMrFPgLh2fktraPf9QKSExDTW3bbAlSMgye
059Mjwhwsg1bfPyA0UHVQB2WIfahAElAwMpiPFIvWhwkDxZ_hstCoboXAEkchWytqEOAQI0CwtixP0HRcIlCOENrjEkJLuY5PTm2YYfSEzdOHcF5uMsFSuMH
SRrDRBVZ4pt-DfqhqC2uFh5btZNzIBYPCbTGrXj2kMFG07dAN45PnwJ8FbMhS8WoLz3NxLCrxA8qLAxwvVXLrdUCQt4RsEgYfUaNJlHrGKkuPR8zlkzMYMYq
bBvELgyJyH_77cnbefb2XUEEkCl6B-9aQwWQ-hQ81iu6FfKPg9DJn8W4imyuXu6s9N_5x4s2iXssee03qguieG6tmGZu7fWIYfLnzr3VIjiYAlTpWAWe1ueA
PubYb9Q3e0D5IJfG58VZZ8xsBzyXIZ8lNKRXWkxoRr9rDGhXpkzoolKmagMUeznaAJmmKrCaXTGU-TPz9fO_rvXI096V_8L2dFv28N6_6QanV2UVzpEJpFqv
X6U_4gBMdqUOwGshWXp7SHp7SHp7SHp7SPo_0G
}

