sprite $AWS_Step_Functions [150x150/16z] {
xTg9hgmW40HGPougLVp_zxx56F3kMj2ntb9P9vidq41FqkX83WiiMR1amP85InOiMR1aeJ-UAdYguAc2fmgUAdYguAc2fmgUAdYguAc2fmgUAdYguAc2fmgU
AhYerlIOVkNnikui1rMQQbu4LeWgFwP37bbW1QXsL6MXdpLg-vxpiinFOHDZL7cJpDWoRp_MnhfBbIggibxGonfILK_KF6jb0JUgsbArnK8lQqXPBQXPZYhS
gbe_Ky5m1tKM0wjTPv7ZRuQ4NXR9c5kqHLDnq8kpxYzE0dfPx6RbzwzpDukZMO-CVXP7i5939G3zB8vW8UyTSihu99gA8svJV15DnM0LD1M3LT1K35P1K_74
TQad0OBgMzRK6G2QYi4gQ2e6gw2f-BMg_oneAWQheAaOh8AcOh0Aceh1AcWg1gkWgNZw9a-I2fgAc4v6Ky5J1Kd5Q1LarOLl2V5KmLC5JSLW5JGLhwlIfUvK
K_6gAWlTQTJDeAiGgMfHkzDubT2TdbJDmkkigN11TSo5xoagQ2e6gw2f6Ao2fcAm2bRLtXBPzUagUAfWTOksd5HzzuTin8jpZAPYi0gQYi4gQ2gExVhUHrFn
4zMmQ2e6gn1oC_J7KuLObRpN_QzpX0eydsFzeyL8HKyLFLNqLD5JHHEL7WVLVzNSXqg2IevIp_4gUghegQAdYeVf7HyLZfDEBYgydWepK3LKOrcezcd3PLsN
VThGG9KtoKBMUTyftwzAE-h0IlUhjebVRcaJlxUhwbAHR3FRDwlmMx6oibOVLMu_cyfc1qcs7JIezffMxHutGrkgv7EBDjIKdLwSRFJYa6zVPzAnao5fe29J
GoLkSL2nTSZa21QZugcYfugUAdggwAcYhB9a5KjMiMGLIrQnP1LBLh5a5KjMiMGLIrQnP1LBLh5a5KjMiMGLIrQnP1LBLh5a_GG
}

