sprite $Amazon_Lightsail_light_bg [150x150/16z] {
xC6n00000C2WT_x44wa2000009XTwz1nB8I1xix___2LB1BP32oH3fEYcxljF36CoyE6py1_XAa8NI6Y5Y_0I9a0hCzabfqI4iidoIJq8oIUoudLFBvWAi_Z
bTePUOBtCpN8IJiwDMYiMDineQJDQFaJSpugLxJfbb5cpSPnWjJAaz6EVigbR6et2HpjPqXDXRh_OpBGgZ8Vv_Jlo5c1LZsfp86Kd4YhpkMJOKwpKTZ91Mbb
5Ij18PY100Q30jEDC5nptltCr12u7Akn7qwNUfTChs9UFy6Z9JR41QSrPTZoDXgIKPceic5q2QQix3ea1ifeKNfWi1zOy3f6cmCgXYyN97MO2Rmzco2Z5NY9
M09MmSnWRSpGZQH0h42fC8jsAyb0h88ChvFGphnZxjD5yFum19DCcOF1mRuRyBYlPjEdFs3uTzzkm4V61FXOX-ms8Ozz7TFtdRrGy7sSKFnrbis92MEpM-Lw
Gw4GSa3SDkzXrhmfmHN1iNIlLhBUElj2NzlixYQIIwKKYGR-2fyktQJo8F7QqrW5Zyin7WVX3W78LjyfJMf4mOZxzzH03OllZC2dtfHLlGMJDrYm03xnTa9M
Bv8Pl3Gpc6X55Zt_nh7oDuwXWP0MlftRC-utlvBdxcJwpwgGxG_j-dgnXGKF4UpwAdV8o5m61OyHMLVyT3LXNOhEqRNbVeTgubcLbtzZbJjRQpWZLivOfN8J
jraGGgQoebV7cC0EJgDNq2kAeVmiapAKRnUXseEoegcMG3KnhK6ponqw3vLTDIKQcZ1fKZXRVGSojFL4eU1JN462rXl54ZYURyHMtLghwhX_QrYd2r5FaD3P
XfrLZLHudfNEHEAmqsFim07HVS1J8eEPc1eItznowCWhYGR4GHPOJl7n8EkuCDBBkGD2F9Gqd_16KbPTpVHPy-4JNhrKGXTN5FYEL0gGAgCrDqYI16XNHGeT
MlBnMnPwyEgEvMEbFjd1DXhoGaxW-vL8MTvqCdx23Indk5a8jy8WoTSZZJf4BIB-q8am4-fG4EeCByHvJkWy0DWBFlyIApZRqv1kSajDu5Bayv3nXSllzk1O
0000062Gl_KSTbS700000001
}

