sprite $Amazon_EC2_Rescue_light_bg [100x100/16z] {
xTg5QW1138JXm-VzdxXO9MppDop3r3B8-Nt8QRBFHJOo9q1881Z3X1yfQw_3fpjMs1mWV0WGRiHFdEUT4Sr5Gm43Y9f_PUXjzd4RvSnJe-xrEutswIEN8VM6
v30aC42P6og1zVU6PeQ61XEVNrS7WWOJ_RLR4JQ8uFkZ8cGG0GOWQ5HYSfyV21X0W058DO10Wv5g00468ZC3Li0EO9o4hbVC3Nm9DWWPH0X3IDv0uXAP6_eo
rmPUByt6aQ4pRBHf3VaCcOmru2jqkEc76skiiKR-URL6u5qR-6O8VFi4lk7-mlTkuDyWyOyJ-5TB_7C6_fq3DO10BIDGamdKbW8ria2jBrgppDTUypLa21k1
clxsF_ozektTSIAzr7nFc95y0pq_4829n9Y9oDWFEv8VAHCTKpJFvWK
}

