sprite $Amazon_EC2_Container_Registry_Registry_light_bg [100x100/16z] {
xTe54i9G38JX7S_zBunxxTa6-uD3PZwWjcsV6egAmPL0J96mr8Hm8LDYy9ITl6cOWmp459cyyY4UGfeOfVDNUPVKQeGKVsd4xQaSXgvFfyRwZ5BGz4V6vQ7f
vUyR61YQ5kkIt7LxkO5HYAYyQseOwft6c9oeJvclCCY9v4GC378YEH4ZAVkG4ykxc7Vz1ZcHd8Y1GKua9tBkpcwKTqcfvuJzvxRzv-ZzOmronqmeJ2NPaPIn
E6v43KNj0G
}

