sprite $Amazon_EC2 [150x150/16z] {
xTa7pkGW44HXq6zuTVyBRywfmGFkqegdC7dyEIV6wi-69GjB5fOiB5bOih1aOSd2aeKb2qiMbYmiMLYoi6HXoSAIXIKBInQMB2nPMBAmP679mfB54jPLRdJj
Kn6Wxh5OmIetswZ2KyKdrLiRxFhKstOLvKEjJtKjLXtLKHqLKwhsb0fF5IcgE4yLdYeyLUIfoeV--gn_7zwNPmug_XlLKHrLgsMgsXvGjJ9Tsw-gywgwNrLk
j48LUzhupgVzPjkcWd6MdmfF5MjKSHEgNuuWZ5IuguxggE8jm_olZkgerYxj07HB5REg-FXyXOe5gbRAQXMlg-e65I-hoWuLArHjwPO104yLdYeyLQnJhLhQ
9-zQ7bLyDrm9gX3LfGTKqnV09QMeY5HwUClmfKYb51MHIYag8fLIL4GgFRoqVobIAKL5f5AAYaYb51MHIYag8fLIL4GgFRnb-5AaKegAIAKK5P5A8whES6r8
HQHIkBJFHroaqhzLTHvL8IvIwP-gFgzgZ1Ifz2yLVVeEBsD5Alr3zLKyyMoqIAKK5P5AAIeYbL9KUAhmL36YIiXJHQJgf1IfH4gHIZ1vrCAA8fKyLV9KoLCb
JvKyLV9KoLCb8rNhtsjnrnEg-VQhwZrKtQjgzrHjhqgjpfjgOxagZeUI9KkMB5coPCcI9KkMB5coPCcI9KkMB5coPCcI9KkMB5coPCcI9KkMB5coPCcI9KkM
B5coPCbw3m
}

