sprite $Amazon_Elastic_Container_Service [150x150/16z] {
pD47ZWKn20HHi0Vg_YVUD8dDFzfTIYZofEQoScn8if1a8Sb2aeKa2qaMaYmaMKYoa6GXoKAIXIGBIHQIB2HPIBAGP279GfB58rZDFJuEzpvJLLdTtl8FbBsr
p5MjhB2rV6kzF2QhIBUgscfJLUjuHNNKvwaMio-gKinHXTkQHrKTL8_ngcosjMHMLPwpji6gytDF-ABA8XwfEbPg2S1NLPPrHwcEbnRmNRLsmcE4gim3lwko
ZFnyrMlxzg4pD0m30PXCt_k_C1ikgffUOf5YHZHPrLVdVZjgonYePrLl_dWv0vMwsLH5bxTBk0B5pQFARbJkBk7g1iP5bTselF5oTODxbTsg-b3XNwqQ4c8s
KJ5VboM6a5VL9u4IAd-yTiVBdeehRyNB6IYjciUhQTN6USNCeVB5QtEyQ9LrBdUNs1qlMlN0qaD8gph7YmmULQdDMVgCerM9vnNHDQZYJx-CL_Qf6AY5hb6u
uupDSxpyggAw1b6NmxpUHhzgRGonawqUZO-fEW7tvJkeqcEepll9owgn8a-zjxseOdfoLtFgDLNFGw1qCK-eTA1qy0wfTA14JG-hwcGqYdZLiwh9Q9JnUa5L
zv_Ud5Vjla5_HsMRwvJgl-g_ocAgBARAOgeififYgYococAgBARAOgeififYgYococAgBARAb0g_HMLAXPWgn5JX1LLgsogSL_6XqheAHrLbygRQb0fEbUiz
7g-ZLF2fVEyyUHsbmgfAFuJNh_DuRQN2aYhpbbTMAwL-OuolBSThAnMqYXdHJzKegJVV7V3QIWMj6d-Y9AfSqrJv6yErbGfhoSwyPPLmfka27Q-jL5XHSIzI
Kzs0gp1ULvKf5HQxG4simNsWgEdbmtsy-FUL2bgburN7dIFo6Y_ZKYeigbYFEWzKuvx_GF89Rh9XAHM4IiHh25IzgL_XBJKRbr9XLSMzOBpA9TvSZDVzKYfC
paKYNbJUT5cMSNf9fSBDkKYsW6OjCL2FFQnqnSASbLc7fNXnyzIUPnCip5byiLprDdBbXTggJSG3Ypd98bwPWMeh0tkM2gK2oy0Aw7Y9gbRrjvGAlBcrUAty
5LrEfOBu0aiiRpcL2fFZhSzKLbyCKoLOZ5Tnekh6RIaLrZzQqorjFG9KAPRvuzNpxlrG9LbMHBnaeDONDbYMz-DLEQsTAirgM_7YjkzkElPOLdVYbKLbXKgo
FF4gd5K7L6Jj3A4c0YLK-onhyepJ6QXpAYpz1mgkuWYKL6dM62ynNiweo1Bn4kFbY0hYAtDnNl6hD4l6Yu5wIKNMT0WnK6TLcjNfOg1ULU5ns35GBwlmC5iO
g7TKcjKpC_-QIhEiPH6eiohO2miXMGZ9GaWMGh8GaeMGB8Ha8IGB8La8oK985aAo49A5a2o4P24a2o5P2Cb2I1P2iZu1
}

