sprite $Amazon_EC2_Elastic_IP_Address_light_bg [100x100/16z] {
xTT50eCm00NHBdF_2zST7KX-XNbBR732xhz9aYH9KddIhF2gRO57IW69LsGFKO97vYpRtIIBp5YsTtkeSGNsea7aPNQ3I3VHdOCYe54t0lF3GACx4xugm6P0
enDXZJgH6VSrPcE-m3KFtBk1Pp3mBacy4mFlzi0tAl2j3OmP0cEVm1WkC1ODZQbv9VsF8qcI94aw
}

