sprite $Amazon_EC2_AMI_light_bg [100x100/16z] {
xTh50OGm00NH7DD_m-iEn2Thyq_umo4I6cBYu034ChYmL2AKTMBmbLrC1EuWW5WYYp4E0OXJ5aO0ej5qGI3YlkNvHXoKWOP6wZxFJ_u2GqD3GqD3mty63I8Q
6aDltjdbA0tBKHeQ6XeQ6XeQbfqrFhXTJODl4ruWN0CwIF1z3VW-4tpV3noPqXU7Ha93p1u
}

