sprite $Amazon_Elastic_Container_Service_light_bg [150x150/16z] {
xPg7hkGW34Nfvl-_U5-_aRNHNR8sZ9vyLQPF3d0e2inZYKGYaKWa4eb48X6ffOoF9wKqUH6ebjvIvblAsvFSNu5fvFIH-PRqaJAEDrv9IL6zfSfPeL9IL5zf
vw0wA3HLokEiK6y0Lwh-_NQHaqBrEQzKKzeflN3b9bDHNNNhEw5KAocgjuooMIzzIKs5dh1JBwcgzokgcqRspLNbEohT8NBVA1IXmk3XEmaDLNX2fQlMNoX2
HNxb91IdSjEB6CAeaEwW5oakeNBGYumyXCfHBpvASohxIMXaycUC2h5Puv3Pdr0H5Jo4ubHyLVOmGciSBGEgClxH27b6LI0KAJweqFjfxwdhHBX6e-BXQotn
tq2CXrIyt13lmiWd5od_HyKT0Jj69QwN6vNy7Q03rO-AZngTDEj6gdupaYcznawgmKOow2Mxg8JEirUzckoW4g8D4S-1YdGnKgT-LFt65-9VzwLYGjsK8c-W
QkihD7ygcKkHFLHpCR-DAgY2AgY2AgY2AgY2AgY2AgY2AeyNf7fBaTUYghXdT8AAx-CvKed1dkU1knzaszAUggpTAHgjDT7Rbc9E9HazYaRgrQO1lQofq1PL
UAifcphqigP2MpI-FmUR5AWP5JB87Xs-Wa0lQogat-gbhzr4Mb9wUL7XRdgJEw50BKNfvKE5Iw4Ez9295iPxLIv5AXvKk7mP6XQzGTTVGnCFSogzXIowOV4U
NBCvmgEx6HybEeHIlzDwFO_gPaml27LJ8Kel7hukudfb2CN6-pgVHp8fkZ8PGj6w7JR7YQXUQzyKYwDNt8LHLcgrsvs2RlJG9ZVGxXpTK7ezZQ0wJTAeD3nI
pO__IYLwqNINezA3wCKay3fMtia1Fo8KAO-5NhB2r4ZRs-dLPA6ApOJYUlMLx-j6FwgNL0EXZ2UXwIGKduI42-NGU7mIehErQ_WQXqyl1_Gw81JHos2zugaN
MFS9nISXQGU4OckS3iJ36T3BOBtYC0afzK_d_kx2ORs8KCVqEYzK91A9H2AHI2GIYVm1
}

