sprite $Amazon_EC2_Container_Registry [150x150/16z] {
pTgBhfmm38JX4o2PUVyNxhqMikgTNLomeoigGb-LNu7i2TuRwzc1bYoqPA4b2orPQCb2InPQij2IXPOij6IX9GijMMZ9GaiMMhBGaeMMBBHaeIKB_usr_nYp
MELP-zUliLUgFEluid4KgumrnzTfZ5cfCjRsb_CNjyrY5TPkKtUQoBrMvHmdOvtAWjgMZStogb4504TzM1LFLZulv8C2bXlflD911U_4N5wfrM3Cu9sOpIip
UOTRJgDftEzNpNDGZXMwvhsgDVvEtW8WMNF8lFAgqtzUVDWaLub4K8ALMIKkhWQ2bLqbBhnUu8PcpK-_SH912LOchmzVBzflG-ILLIqNr4NM_22lH50nI-QL
LUt1QY1OoRmklLuqI-IbM8cW14laTLKrWw2Ih3LIgZWeFUGKZeHAh529LNvcL0jNXrgoCYfS7-8Zi4W5iLOLgV1gNP_RB50vrYae2wnA1H_KOTULAlYWxBfK
1H-KNLUgV51sNQdwHr3bgkc3ikjLfbekgFDrYShlYcpoBB0IbTyLkHMhHZM71GGVM9LgRVvt6xjULQhbTqMccgj25M-pRV8ALFvt6_-a8fNVPlidbQXEGGLF
UbAbjzdsf4TKUfljd_IiQbXGuacFgYme-QGdLHQKVjB3gdV_jQSAFLNegO9IiKG5fM9F5Nkgs5F5dYgMgA1KB551gLYYWbAnH0MbOeaAIiNRL3DM0Kh5crHh
UwM2KZ6lYhS-yVrAnQmgtlhiYEzNAYPLyOypB-zNAgPKyOaeSRzICQ4A3x3e-vMA2LMubzRtAnKJgcWlhLLGAYPKqG4MhO9ICQ6AWj8gA1KpgZcYe1mRCOin
osKXLVwdMlNx3M8MOvPR_xJgF7bJ7-j4p6BCsiCwOfKu4IMRCvLcZVcPQaCqT7DAHOl4vQLKyUJfvW2bOl1wLQhaAJobOX22KkcW58kIXKta9LNwMATdKR9S
NbgLFuMtg5aYBwtoGUb1DToJnw5LqISDa5Lvbfz6hTAVD5gbMPZcUbybWageACxOnYgz6cYLPhcNa52feBHAiuAy8fKEAgzYiCUBLRiEAg-YU7aubRiZeTAi
82-l2jRSb4gpV5vU5Nolf5IQvVFoAX_KlIg6V_rsAhFUhV8ilt8xrORSO8fbUPbA1fLNQHQEuLNZG7emoy9-LXqML4wLPwtDjvHNvLZsZJCsbAg8-mTRijYI
nPOijcIn9OijMMp9OaiMMxBOaiMMBBPaiIMBBLbioM9B5bkos9B5bgpl
}

