sprite $Amazon_EC2_light_bg [150x150/16z] {
xTi72iCm34RXNoOIll-9o-fYoqX1XFSOtUtNbUtzi8Y8Y8Y8Y8ZSbCwy6wMZcbccesotfiFwLLUakkvHnKuLg52XGeNgBrIe2dxTgNEeKA6gAvPIhRX15KeN
_QgbTAjVfOCwLVeKHrzujsedwbUXojiAxeyA5IgcLwYOjizMkUdR59LB0rKsKgMngkYOCg12LJuLrQUnAXkfye4gypr4bM--gd_AW0eL_q5K1Q5YUeMgS8z9
_QyzM_sllMXFNBygb2wALMLxUEjLzNl3yw52XQe-LAWuNXPLFbIeKFcyKLA7pHnzDtEauinHdG-BY8Y8Y8Y8w0K
}

