sprite $Amazon_EC2_Auto_Scaling [150x150/16z] {
pTe7ql8w58DXKsnf_ok-cQyTBitHH3_MI-yF7Su4-ngV3P4iHB8GoK8a2v4iHB8GoK8a2v4iHB8GoK8a2v4iHB8GoK8a2v4iHB8GoK8a2v4iHB8GoK8a2oxM
PIj4LQnpsph7g50e7ml7AvID1KE5AjPwLQ5SB0_ApNAXpbzRBfOBDThMSB5CAE1BvMAPKByg4yk3AfM7PK6LgbZBLECNLQfYBLEXVw5AXMBrTIhqBrIf_bXz
xQy-_5-5Z6_dUnKoLSXK8LE5J1KoLSXK8LE585LtiV3FobGXKuL5ghxrRdUDgcszsqMc2fagB5BrhMUx45XMrRMzwNg4TU3TLwZdBEcTgAj6k-AkjZFSiQwj
crIZjJkMgC8DgkrYxK8Lwrw5wjtfXTh7mhpJFKjNuGPr6lEWiggP2hT9g061TKG51JMWi8we2YMeH5RVcgdwbeIgeBBqLxkE6b1Pkaf73QWiNLKe75RrXrgn
zgiArQxzFbtLNjM5zs2XdcPKdLJLwHEgfghQ9rGNzVFgeglqwRhuQgyB2lyJTPIkqbawIbVfBCeeNQMpI1Mb_sRGMIH5bAxIMTmIKA9APvMA6ahvlD9PfQA2
qb_jEejJLdz4rQts5vNgaTNdBCvPrqBf_r8VMLTK4zM4TOP7XNEXth6uXzLVODzstNLLCnNTaw9zpLJqplhsDbDnYGep5PUeC5DnYGep5R6aYIg4nKWMNQo-
PMFHnMfRED9CnIKgp5HSei9CnIKgp5HSei9CnIKgp5HSei9CnIKgp5JKLIuMZx76SzKuoE8XrcZdPwfpEyZY4TQucntzeTf15YT9Ix4MwY2BivIPvDsHLfNE
AfK71LfOfRAWG1FhI-L2WIRMbyg50asiqnV7X08ThCg30XqiDmgqiCmeqCFoea0Joue2NImd2dInBgrTi4H5V2X6iXZ9OYIBaIn6iXZ9OYIBaIn6iXZ9OYIB
aIn6iXZ9OYIBaIn6iXZ9OYIBaIn6iXZ9OYIBaQp_
}

