sprite $Amazon_Elastic_Container_Service_for_Kubernetes_light_bg [150x150/16z] {
xPfXq-8W38G12k7__-9xUszlgklC3dAkuKFsasgiJyCQOflXfb0e50g5Gg5GA1Ioab8x7_HIZbsOZlIZV3uivuE-0rJBwQ_Enx-FYdapzP8IKgLKNRcifWHK
bnpjTLm86QaSxTNp1N3O8vMLv6Ulfoz_f7h2zQW6rq8XrRsqgNqJge6faMfO_RgzUe42W5Id-dVjPHM_3gakDM8lMJLeOt0glRrUptyCIeLvxLyq5AV2ZqY4
9ywfvFRY9a4gKjkQS7iPSrHwU-7Ungcu8oNRom8Ls4jG3QQfTFRYkUTK2dln0t4gefu_OQ_9f1kX8jt6ccoo_hLqKq5McRqMqrMW6l1LEH_3yl0oKzQee1fm
uxN75J-cJcITgirMilT-_Ut_g2OhsTk_VWKLLZB-ifwA98MaK4_5-ngqbvAAzpKyaqegtjTmrucfU5z3x2MdubOczb9IDR8khF9hgLuzt7_qxAXJ1lRIK-N6
edxJqs79zLH6eW3gb7s7Yhs2KAVSgIfusvMAGFbJDO3QWgf1TNMdkg7gs8eAeVof29GhLIV_yRoe29GZ5O7oexfaOqEgFdQaohlbgcxfgq6m7Ad-OMr6DUg6
jPrWEL8HB6SgnFAd0gmT-_PZl4OKs_0_pibg3bG42ousE5015Wut2AawYq8i76wGKQLg6CMmyEwpW2g_UM-e7KTxliIMskUfEbXavcvrwMYl3rBDNwh5q5GD
xVLXgfdnAbYoE_QsrqUfvkTVMdfMlksbeS8An6_bNh5WBmKLNkJdmr0Osuk42YiGkSoEiG_Fiu8AxvM_4X1IEtBk6ge1bg4hQmLYLuK7v_O2JDKmmtXP26ul
M5B9CCFT5-NP0GMmFuizPFDD63SLR6jLWLk1nysFFnJDt1ogpKT1uxWagxDPAANQGkPrzj8VPhbtGUa78QUFgPZg4qo_wGPiyT3o4z8lWy9GwvRbNPZANbf3
QUo51LWex4VMDYkvlRgWyWft3mpG2rF1aoaKjusW4VvaZyFx5GTx-HcAbsui_gwwESX6wMYlKdmCnJSXiaEwsilVK5WtRzFl92ka6ZZA79Zy50g5Gg5GA1GA
XVu
}

