sprite $Amazon_EC2_Auto_Scaling_light_bg [100x100/16z] {
xTa5aiD044FHBfxxNpXC7PVzGr98sWtF-9cfQpb9CdOn459ad68WPCXeCH0IP4mY8df4HBSqH7L9GHmD0N8nm9EbCUhIACdCgcwKOA7NjL7Q7KezcXWnOYIE
XJ3p4gCJ2z4GZF3m0426tDRb4OCNK-_3ndnxD0PUEN5pHXuoc9Xlj6nGRqRO008GwiTD6M63MZB21ZTav7Q3YT7pi34D6hUkLsys7FFAiCmDwwvX6pJiImpx
HCE-tN2CCXnh7USCXdCVppcS_roK8o1oZMDEObWACMB4CDpJjzKckCRYhXNvQrx-sfs_1ic8ls1hgMtBaTAa4tAaT6c45Ybn188toHe
}

