sprite $Amazon_Elastic_Container_Service_Task_light_bg [100x100/16z] {
xTYr4S0m00D0bzf_uhHXPh-wu3S6dSlEI4xAYGQZ7Ch31eEHRgumyZw3qRsNvVp4O5GoFnXzn3x8O33qHCRvdK4NPPY3UgAzbi7G4rUprdOzKRzYEBDaz1Lx
BOEnrM0SptQ3iJtI
}

