sprite $Amazon_EC2_Container_Registry_Image_light_bg [100x100/16z] {
xTW5RiL0303H5Vl-9wwWu8B7bcRB7i77v8Nfj6tR5lVx2YESiSRTJMYDDTPOOuqrugbFCo9b3IG0yKQywIkCk6_a4N-kyUx3VOE6zKPybN5-_tmSP_ZjAd_X
ZI0YuXFty_ITCu186UCzKdn_-_p1yyT66H3fdJ1GpU-5mKJ-90mY2WICOcw109ICF10IyDt4YAU0W6ydHhm417pV6v53elYbD-9rG1G86DKUN120W57jmGK1
21ZL7bmGDL8Qi0SZaUiCseEHo3K6xi58vDZ0FPY971hptxZ1U73sHv7Hxy736eEdR1eQtUnxez-3ZJ7UWwrniFltpenumoDiU8GDZtY34MymuWr6lC68DnXn
XaUySQGnHuurUkGVFwU-dZVMk4zmsxOz
}

