sprite $Amazon_Elastic_Container_Service_Container2_light_bg [100x100/16z] {
xTZ50S905431Vzp-A-Q2MtHz1jS7yIGc1m0feriYgpqDZSYY-OR6-xGM6xn_jhd6xS7jzltXPqFZqvcDzDVnHbf5uxaHNxNVUB_xVm6YqUeurp1_6ESQbkt6
kMsu3DlKxUyRs5SRPV_SCHcDR3IQE-0UGm00BW
}

