sprite $Amazon_EC2_Container_Registry_light_bg [150x150/16z] {
xPk7RZCn38FF-zx_XV_PgWK1TX4-PeXOpVxYqgA5KyxdKIgLIgLIgLGgbLhzZzQDCRNZdzejSOqZD6w5QPRZdSgy1QPLNt1g_B7y9dzTed6UutNHpBP_uq16
ew7g4LiFDkDH3VO208PwlVW_A-f4TnaAZUsqryGYmCl5lDnGPNu0NgwrL_zYkFGBxJN1KCAQReYN9JnzLxnCQQ_gudL8jw4klgaCzXBoRNS8yMBjiHU-vwxl
vLX_z835KFj321P-GsrncXJjrRV4Y_gcHLtkCdT4wVb3bIr1qGzjhMAxx8YjgL0jupc8KndEGHgL7bj-AeojMQUL2cCh3EQZmjWAWpcfCBRYjf4A3HMtZLHu
Pe_RHYhiRy1W7Yfiiz5W7YgC5xpje493uMq75Hw5qM0EAcmRq606Ad9UWTkNKl5sD0nbeEBdbRXje89umNSoKB4ssqy5Xh9IyJRRJxN0KBT1LKdtugKYRRQP
2WnbfSBd2bH9bLH9bLH9bLH9bLJp5gbMTLBnriTCnLkVRgJYlVJffkBZ5KOgFehYe-8JKKugVYNGIuLN0irKV6h1IVNr2OzHDAewlqcr6Z4KU4wWOj-OKusF
1bW0-sTKZRg3Ky5BTipJqTBCgVZoekTspnyWrHJUJfrPvLGxnXcu4JGgB6BxPw6HQlyK97zBJgLFuUapQqYbJk7f5nuubJuVeyz28fLkADrUIAKRIX-iH2er
NlGBfPmAAx3Xnm10fSUBFhUBLDfCknv2dL3fyQA745BnyygLzaAgImt5ppX0vVi58LQZe38OYeTGK1aCnKCeg21UJ1e5g0o6OY4KL0FZnMslPWFWzYe6WpkL
IgLIgLGgbKgbVWC
}

