sprite $Amazon_Elastic_Container_Service_Service_light_bg [100x100/16z] {
xTc53SH030LHYt__5P_WEBIsP8Wqqy0BPy4YaU9b6HZchS30K327eNXP1ePvAp0m5CjXA5wMWM7UqWqClKipz5sE8OU1SMHkcsjWy7xSzdlrY_2Fmc3Cm9XX
mM3CWC6OWJ43_oWC3COCLyQdVaCdnOrZiz_ObcTiIpOIdjr6urMXOHM6ROW4OzDmWorrZ5091iOcUW
}

