sprite $Amazon_Lightsail [150x150/16z] {
pCun4G00202XJVetjeAJzoJ0pVoIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIhINF
Fh0Zns4WW0f48Ez_uGqQuL4gIbjBcHDirmiJtE6RW22oUu76JKMsFIAg_ljLhh8D4VNVg0hT7gE_IUK5813nNwzoERr_KVCVKHLm_K9Lb5ug2xWIlSlAhrHP
lclnXm6X7-klZooKnd_CBKluhr6ve6baNTRBVu7AivFvbCz5jJKgtbBw-6Fn4yjUijwX7XSgVnWPUSLwKpw9vvyFh0AizQeOKF02rXy0B5-cugXgLi_HOnhK
aVNJL6KidmW-Oe-EB5cgml84hDuLkHtn2qjcf_ni_HodV0cu17U2r0jhjeQJzTCJoN83Qd6-18-LkR1yiePpGq7giogRlVgfqd6--zXwbK1JOGNpCUN0bRe7
QhXOvVsTeDkXy-nehyqlB9jQhCcbmeZWHHfOxVDrk5WLkLGGCv1B_nryt6_vMbKPbYhV4OfiD_NkdLNMgl9Tk1mA3flcfIg70KgBRBbk9zP4lqyKa3tc8eVf
bhV3ibA51UHJLg4HizyNg60GyT7XpqyvIkZhL8vN8ARFy-Vb_Q7IAHL_oybTplWSqbZJAYDjrVVhuw07g2piTfN2rEZsT68ZB5Fn0kVr1urblqtbs_rnR3pC
nciL7bUK_QqWAYE72g3-8TLsXFpD-bdhcwdcAnWoMy7wIxhTUBTdZi7w1qw6IbZhfgYJAGegpcfBxZZn_-yuTGzJSLQ-75-jm4tWzSHHJhySKxKbEnbxticK
SjV_JDKMx_hmm9CRchW-WgWeAu_gN2ut1nvBdS6EYwdQYjE4xWuuy5WvPh_LMh0xYOgoxEt9gwlkse2fsgj3JZmkrawf2JGO5PJLCczEz6ftrqGAjAOGJuWz
JDNuRD0AWUNhZNEPNgN0HSbPhOTV-6CdZTqNm_0oWqyUEAjnrgKcq4XsTqCE6FJmV0XJjQcFrVAppd6iAGe02c6gnXPBEacs8s9mClL1050CKpMsM5eJML9L
7EwNsz3N0EMi1fdO5fZWbvVuBK06e9pLC6pBUIsgZ-jvion2FsbYgaPgA3WPS6ADor80obbjWXKRiAJSBYSELzoeSbQROHcmpEbthOcooa9KdCMl24ILoWEg
2LQ1nS08r2gaesY8Yh6U2nBNMU7GPoHCrIe_AjC4D3yFKN7MffN4O4nCiDeyAoHTt0HjnWEg2LRjzy1uhXrKUehLNh6yxnZKAoHCjepLwJ1L8-UiBbDthpNS
JMNhqQWlmbIjSjSOKbuUK14MncHxZjRtOQh69j88uwNZQPJ5uYfoQJ83qYeLidZ2zn3FGbMhlpv_Dpl70W000023tlaJJwC8Ycn5jY9RaQt8LcGhiXNPYcn5
jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9R0m
}

