sprite $Amazon_Elastic_Container_Service_Container3_light_bg [100x100/16z] {
xTYr0SCm5431Nsh_XSFCOF5TbnYUcI8x021bT4nazKj38x9elg5nUwnzVCmzcBRlXaQyq7X3GqD3GyDzKEE15_zhfBT6R6Z4KpaRQQllnkDjvRZIy4r68nkD
vZwuHtO0m1e
}

