sprite $AWS_Elastic_Beanstalk_Application_light_bg [100x100/16z] {
xT4t4aCn549HIlQ_OlS_w7e6vFWe5JWAaZJnAVlQ-uXNQG5x4NFgWiwJJU5kjYMifYi4p1S4N10JGi8X0Gj41XCY0WqcSYCdm2WHP401hgWOl20aSYCdKaDC
e95_Hcmm0KQLw1ikN4DF4lbJ8P4RkiiDuVurr328g3uL4u41HFvKG7IVYed08A9lz0a3qJRwX83OPfY8m60YDPWG4Mmm4Hdx2MybL2ROS42GmOJTCU0IJB0H
NeADCt4MhCmuzPm5ApBk23iYkCQ1S6_SrAF01aTXSe4J0RcXLg2_PqZOd1kTZC4POumnnXXZZ37666ECCNupamS
}

