sprite $AWS_Fargate [150x150/16z] {
pTg9agKg30PW8MHv_nU-gwN-frCcw1awgTrXkh-Ia02jvaBMXfPaQKcMbcHfIPQMP6b9bfPaQKcMbcHfIPQMP6b9bfPaQKcMbcHfIPQMP6b9bfPaQKcMbcHf
IPP-YJLwQtrKK9siiUqn2gXs5csNe0eg1LFWMgMIVc9ENkVVL7775nIubgYuRP3aaFPRuzzGZSFKOE71yyMgwplvBAVm3jUfhlaZRfNlBnVaUnEmlkHwKmha
fYU-Mv2Fysd8f_V6DVwiwlWruGu22yKILHkQOyc-7dc1AdXRaFChLPXPFejtqneLha8ChF4hLLYnVDOveer5AhrpVPXOP8tAwuJ-zgQBo5eLxXeK7aAhMQp2
7HQyG2ZdYrKuNGDIN6Ivoc_Nq8r_LtKkI2XYlwX25nRy0gezpw5f5r1v_r9JfJLLMbEbVrWbH4zK-g4YIkhIHwr7AZrKXoy5Izyco2ELNbMSFkcdJrhqJAMx
QkuabhrrwVnGfQTgzFZ69bRHGHfpQn3ZK06CdgcauPdXlGgtz8qVg0JowKigTF6yQfyxrQ-gyFGwhVf_-bY_hC8BY3QfuhD6VLzrrYwUKtL4lLUfo-fpAinp
VCvpAjx_nRtTcbTne4sgZYug6FnK5SzihE9pAJigVZM3k0f6NZMkQ_dX3CRlf46zJvx9ckxnCjl75h2sDkHU9UCOUev4r3RULr5a_T-rnLVnqOLF5B1uiefY
6oHtKLsZDQB1_7_kCZDHEztEZxXsmgzqPxmEYiE_R8wwy_nE1fCc9idDwR_nsrqVgnDCxKP47abnr_T-XppK2s7ghG6dTM9snmwuwdwimWngnFeuyCKEkG_J
f6kNzS7JeD7Rvmg8L25BXThFf659S7XS_YkkdKY5h1Y6AKJ4Fu88aitFWKXbcWc1UPWCR0Gnoq8MhhXGbYyJaGfPCOrQtaCCe1pBW3M5u__IfpcK_nAEWJF7
Cc2jZa1LZ6KFMADjhVF4s37BicaMjRD4fp_863B5iZcMT2X1eZV1kR6HAjKJCHfFZ1rfbasmclTTMbClP6AiHYhBR0BRW7T14sD7acLvrkUazVt1pTZD7Hkp
BC_23T8vBy4t8W9ZSopBio1pjpEcnyOioxFmDyIg7ep5Y5HsesAXwuP0xbJufryO6x7CY_lRez7EvNMhKfLnMI61IYELtQfK_R_hgFnG-MDZblaHgyvdrrv4
ugaqfz98PPCgRd3EVgZII6KJgi-UDnwhD59PeBgj0FHKfP7AFDN0dy_u8Ge3a9snccDPdlLP3t3YI7v-dJ9a7tkK2CsnBC_gK0-5_9FwFieVspN7iWbMT3Zc
y19GDCUo2PRuUUs7DrOq5v7Axk-DzXhWlQBzTXoIB1qsoLBkJht4lvlxjNKcR9hbzvRzQQERFlHE5JSVPbLDTZncqTcmPooDLM_2Cb5JPJLLLbDbjoeIM8sq
J6N1rnYyg_PwjafbuJaVgZmjKbbm9mBHT9NAPkwFrgaiVzUsKcN9Uyd5AWik0c7grgbCbuILP5b9bfLaMKcMbMHPIPQLP5b9bfLaMKcMbMHPIPQLP5b9bfLa
MKcMbMHPIPQLP5b9bfLaMKdMtm
}

