sprite $AWS_Serverless_Application_Repository [150x150/16z] {
pCun4G00202XJVetjeAJzoJ0pVoIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScM
P4ko9TcIR4csbXVxG79aXS40Z3Btl_0BwounrXW9t6p_bIT-HY22VHiXXFOA84l2Uap5s6980-jXbLBx61HdFQ_YDWsgivvLAGm3iVoVjpewwqcL4sZCx_PV
6Dw7wqcLLu_j5LUPALuBKWwmTb5UfgWoasky3h2-G8bzLfbHoJglqbU5r6OgdtPwbtKVvQh1Wkit7b2HenALoP46iTaJr5AL_vmah9Cgy7-MgNnDN2eHEQwA
_mjjGMLuTJJVBr7-bihhLwlqzRFOHc3JjJEhQ0ukzsy-hVAgsABAsbtMHW6nLCN10bOpmNtMHW4rKuc8ni6IzzFFSHKb1Hpr0ldvyw1X0k1f5IG5j3Q2WuNw
QrcULlaAB5GDqpNy5rIoecgSZ3OygSBNlUjgvPhCp2TL2YIZ8N1o3f87LFjTZKwg66hLQ0Z9n5g6hVsh0ohqPNf0DUwWkbF1_7fxLuMXR-_FTe_ISCaj5Lma
jX4X0EJmGwIcM0wfCgoT81PG81-lz4aNpM2umghBHt4-Nu5anyaY2wportbsodHMWig6wqiL_4BfzRy9VeA7INPEjb2hwbkDrm_7e0sLgOZQQXIAXTZpeVgm
yVymwr3jHOgsrNlsh43pxT1BcAdo6cQgdXJGvYfmz3SgpPTXdx7mgbOsLfAgwZDtgkhJNvFtn7arNclbofZoaWVJLTXdh3OBNnMOXDHV8yiKghwXGbz44vR_
zcrLNrT1s7bYnDTO6QjKVLK5QZbBVThLAgjKFLblMyizDDoiZvfPfUgtLH9VarT-DbT55iJMldTi7wggILUgddRHEfoCLV89AbMFGyotvbLRl7XagiXg-uFb
NLOnVI-9dxbIzN2OelqIDY0ixshu_lr45LbjluQmUB7GM8XADLXyZqLRX-zADLYupnezNyfpkxsbKlNmoT6smWX0cKdn8pkeIbPZEnYP5JYeQXQG7Z8np6-E
bQh_dYT0B7T3c5zdXwfY2RIJoQT4gehjz71GRHPNrInZF6ZAf-XGrInJnWCoG18h4bGvwzzcvvm80206W52x_WtV4n4PKC2UMP6jo5PaAx8LsOfiHROYMv6j
o5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6joDO5
}

