sprite $AWS_Lambda [150x150/16z] {
pD97aa8n0CHGPzt_n3D0KzwHathxWr-fp7rRtnrA5aeMIXPA5aeMIXPA5aeMIXPA5aeMIXPA5aeMIXPA5aeMIXPA5aeMIXPA5aeMIXRthvSRgxzGbTjpgiRN
LRFSiT-ehbpvaLWIrMObbaSLLayiZueTgvfKx5ZJf6B74gd2QebbKh5ZgLISOybK95QJgKWicoelDPkAcbWkLTxgDbLYwLI9PLCbbaurtX3hdrWpov4TXc4W
iZZa_I_yjlwAyDGLoV24lxCLgcDP36PkGnxfVl_gtdvbiiuVehh-HxM3hELKEdzEbY1ukwHMNwBIbicQxXMQbNLaiZQzGCMoXjwWObbwXKhfCTm_ilGArVbL
rYvf5HNBKYRhwc89mxBEN5OJIyjbQI4Loyed_neglhDXc2scIcyN66RBg68R7M5WPh9QMFsFRTnk5v1LnEe_ubkG1PD_FTLzQT-3h6JoJrEnge8iDR1wgYgo
pWPMMrMKjOEi4bPNrUT22RSBo7gErLtrFdw2B9xyCrIy5WS_q2lAM4rLDpzKmZPLiReDeYHhLB5wrJJuuLx1M7sgkw4DPAN3R98gNtoBidRLi5ggeXykOLSD
oprLqG-Ni1AMNLOrmkXwrYjAM0Qix415MTmhGe0gn-BXmxBoymbKpx62AkbaMVdv92gtL4K_Lr6MYCeTLL4MzueOedAd-KLPt2jYYChFxkKjsUioMJJCYCgD
Dmei2yydKRcXAi9ohr0CKRcXQbwMYCguxQM7GDGhZbIMYCgWwW2gXxqYXgWCgk2pGLaZmG8gGuVWViozGepbPrWxgohq2iGoO46pYgguX2KXAiFY1iyRzeea
HELaoQNdZNl5BV5RYCfDLIph5eKGbTkgk5VaL28gzrHH2HlVgKHKVgvgpyzbdcJG49Nnx4I9KHPJvLXch2Y49R8is22CM0Ug0babAX6L6wfeRs4g4PN37-1P
pRAOIaJbKBUWY4LPeqSbed9uSFaFCp9JYQYyDLG1CrC9e4PKnGyqGpFL0bLm5kQfQ376TrrBgF8EaKZa6JjFTVqJOgEgVCWkeFfq2Dkmme2i3XMhiWtR7iZg
KB6gYAMzyF_R7IfITOGDWbLn2MCgKfNdabXMbZxLTwXTdB60QaDLVLbzgl7bTsv3d5W1avOAL1pzK7utEyS2000008FU-HDFemYAR4Ms8bkHhSXMP2ko5TcA
R4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TaQ
}

