sprite $AWS_Batch [150x150/16z] {
pTZRcjiW30HWSnoz_mltvDseYUmCnMuONUlR_0OM964i-cS3aYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGB
jx1QITllIAKjLZchRdz7LL2Xv-qvie2gRJ7QQbN_Ng3QMglPMKjL-oal_JlAVkhNgafOckRCLQg-eu30MgJofQh04wlwOgrH_Jb3uPPFbnVh-grGiSVBOhLb
gZy_3mJMvIsyVAmI8YifgQ2fWgOA0Ye_xHv-sWLkXbXlDOLRrCDlqTKlJjpN8l0wnp9GeP89gA9HzM4Fh_e4A-JrtKJQNYCrGB3p0e35Ak2bIyKUgrL0yuuU
ZrYhyZkYu2aqLT1KGLC5JHKqLT1KGLC5JHNkL_N7hTsdLRXPrTFcaVfvNlsor_wEvLz8Ok3PzQXdwxbvb7x2UiwQL-NjDVB8lBOTiaBMfAeSL9c5e9p5iwPK
pGyJ_8Yran8v_R7lELl7MLPfhPMlh2dLlb1XG_4IZeL_2awodaQdQK9L7EMiUEAhBwWlQMnSNnLxreWgVbqwMhwO5ll1XCEibq5p6b75Wr0VIvJzatj8At6H
Emwp-YFshBFWGw3aHmLXTzmPlYTcFR7URY4Tc5M_GNTXYBXT9rbqTZgkAjiUvHuLD5K8Ae4T3BDJWTFkh3rBusPmrfvroosQJcxHFdYBFeBTelQv5oTcdQli
trxdDFmwywp-HcMVh6GggMHSPTUglZvRzH6LNQkGUq2DrT5CPTUw2OHkOgpdO2gxi_CQps8gkxDB7SzYAflvlUjPJ6LBL60gMw82KzaI5PZAbgZ0LBP41QQo
9IembIrHWQbiYGfCPKjKO2fReW9JsVZltVbQCfMDgqXbCJjfDiBgDNzLfFtYJ9VNEqnbX_NSSCKwEsbcAlEjYPl3g_lPIJDJsM6Vq4Sx8O9YB3iDz8DLw3Cp
NTwVUJ2L7NMMUQh3vhsi1r65WK7erVbCb_VzCTwhmboZEtDuSiCdpJ7UgK1cG7JADJvFYgpt6uYuDtLi8bZ6PsynpbNrzm-QXOqeT7fwdXR_racyLMLxPkLn
LVw_AYCgjeFtgv8vA_mbVjhdLUIqEoly7BaPPauxL-q4SrRuRoOptVcR0M2tgBF2BKfUdF59SmpwuZWhl1BaTUOlpeJAykQhPU5rvfKCVvrdLFYkP7hlePBX
LH-lPAPKHge-KY7pIVESodY5FDvDT88QLndl9dZdnIVDCOm47fqNp2QwLDPvSHKFV2XCacMIB9DacIJB95acoJ99bacoJ99baYoJP9aaooHP9iaoIPP9iaoI
PP8iasIP9CiaMIR9CacMIR9-0W
}

