sprite $AWS_Lambda_Lambda_Function_light_bg [100x100/16z] {
xTetSWHH30DHXhZ_YHLFeVYhHospZeaSCKzOx-R7vpD9psyS7peUwD426WrWnXFWxqv0IqOGcomejc7ezmCHnU7wUk4LLNet0W7433Swouc9G1Z13OxqIjBx
5hai4ACdyEzbUAJ_oWsEzD_Qy4X7kS4NWerXHbOS6GnXlyvb5XiZ0KRk5Wc0iM5E-KW4rF15MZsDBX9XW00rPebW0n3sn0eoJ95UvqMu0MfN1gI0KRlVAh8i
GsEG4LX357aS8m78uni9G1xJQ6Ako0346l564tExY3SYZIOktmOK4SPQn1ipnoBII1cy23VwOChOQ-0YtXXjG2A3aJPY3NAHeGH6-d69Dqfg8uJe-8v46A38
keE9Sv7poYrZHL1Y_mLwSimFWOkUZKw06jZ84c4rs47MnAa6Dyw9W1hW6VZvfP4AAsEM2Aon_o_dnFuA-9xegLEg8u1ef8rpmXkLK6yr0e8tcQ48Vg5Q37sz
FPg8M364Hphj4PKDLq1GxEfOmBhFYC03l2Vitzj-WFVezMSD7lSp4vmPELhmpAD_fgZdCry
}

