sprite $AWS_Batch_light_bg [150x150/16z] {
xPhRRYGX34Iv6lx_X_VIx4CF3D9HYvMJJ9rdfrGnZB6jxZyC8OGGGWWXX132SWn_YTdwLw4EIuDO-rUWfV1AQjqTYs4ccdkcmY1NCwiv3BopDJ9LMX-qChBL
NHacx7wYmwR_-Lc_O-vdUDsZEXUAwvvrFwv2q6UkKj7Ti5kgvcIPxrtVfB2ukafz9ScLNFtdswxAmAkeNXp-EgkJuLsVEcG-JMZoubEg9lgLSgi7SYLNSYLN
ShLKxVPbN5cwlxhMTxIIHaXPlDCeJWatzhbe-HQpv9H5SNAOoQ33YjPnr7DJwUeoqzQMXHdhBEe9TNXghyrTtRJ8gPXPIMk3pADuGvxdtCLPAxtyunQMmHL4
SSfwOFdDZQ-JrHQNZ88eJ5mICxJY6hREWx6ZgEUBZV6BpktzMgEjwIlZph0eoFfN_shxU_MwiL0xYdgyCAjXKCUbNTWS5uegJufLkfVIidMLbjyRYlh-hlnF
qF-sV-lAu5z5_L-SR_yw-tSo_btVz--G_QS9FdarfybhfHsOKa4KW2d9bLnnv8eZLt8bL_YrT725ThgdNB7k0tTXH0l1EZNQiI8j0kjgQNUFj0Xi0g2J4D8Y
i6c9JOsX8Iq0copfX8sq26mAXzi8fWLW6mkwkK5Q1BRTWLikfWLWcp2m4NomUuCKiZKis-rfGLf7lWLDt5K6MYTTmHCyvmfb7Tvsf7NkjiFAWBJELGPMHPdM
iIeANnoaTUx5WQypqZhsEiDE1ccTwsHOryUqZdLzh4DcMiSwP3PDCArZqmIRl9ZMgScBVNa4jRuBGWWXX1122274Rm
}

