sprite $AWS_Elastic_Beanstalk_Deployment_light_bg [100x100/16z] {
xTU5ZiHG24PXuhp_2wzRsPxc32KsWTMvfVzNbtZUoaFTcZbJz7WbeMoZoCVohTU0DqGh0bpG3eDIA1DF-od77a8y7oJn97tqOCxN1qO8O0D8_Cm0Dr14d3Um
m6jvAZB2Giax64JKmGQHJ322WZUkpwb7YD14tQ2Uw1jXYV_6iUVmkvwNbc0ZVXUsn9M-EyRrM7eYYkODHtW31YLHZV269zg69E3qk6aa68tZIXDzmsofUOE9
QgGq157QZG5jG524Cpf4NYqXpQC8Dj8RJ722C5f4NhP1Xo3823X7vmY-ddd2666UgTk4VyrWGXfXtwuyeHwsnLkCjVrxBHF-HZD4iC7Avt23q0gSzePGpc5W
Zc3K4tr3dPDCUCCJVKC8G6X3haJVu9nCGHW3YHI4CJ0dlU0Df8KWZV9vHC1CBtZ30_D639N8dpTYlYPor_2rnXfhhB766ckiiSOQQpn7RRq2
}

