sprite $AWS_Lambda_light_bg [150x150/16z] {
xPi7ZXmn30H7UVx_OKSa0YvB05TD1pRofIdKILpsXVTlJ2QJoMGocKmcaybaCltPfAvNdsUVFvDgoA7ciq-9eNev0sJ5KYsGfQFYEpe2gLXMZQHYMJESYcNf
gJWDPUcfM9QUYcMjG2gMrVHK3bbnL1DaIQWubMNfgLYMdefb1LBnX_KWAau1MR5K0sJ9DkGoKLRethwYL-NrAwf6iafKIusNnGDJt2iS0xE7o-gkxKylQmPH
ZJzJLW5Pq2jILWbUbNbWSgz8MVk1EIDbyQjB_NDbTQcXMYRCW31PFqaclBg4oHe__O0iHQ_0npqJNbq4lG9KdSigIbNdiePEbPKbxXMigXfPubKPBxpnixIz
WeUZyQFj5QpA-DcLiAfIPVm4zWfhnVeHbp1Uva2Me5VWuckqnVSAk7dx4hQkgwhsEe8iGQ-0Gs9aYNe5gm9Psbx1mwTiP1cb0bNcC0bx1Qi2MUeI1a-DbGKF
jRBqlO9FixrvNTShxFE1LT4hM1N1wdi5VnFYPPNVxdMlfbUmAgRIzmeUXEPn6rdpJeVWSope5QoAZx6iLu01KAMHnGBuQkvxXKnLF_rDc4d_Q8TWYNjP9f-g
MtmrsH_B-cY7s6if96iM1nLS7Zvl98i3L0vLSDveXZ6LNnMVDnnYLwdwLXN8Sb1vLTNjYk-duWVmUUCwT8UAlpwhsii2AeSgE6-4V8sg7AXYvWjKSCTH8aCp
bLyLByPy5wvGZRF5c6LTeIgdSv9dB5DTwX3zPFzXAi5YZBAOIgoAznocyglYz_17CPM_Gx14_W98vL35MTwlSEC_yzg9xGjKnQ6APFcfHdamvQm3By1oj5Hn
CfbC9fF9P3APJ2QJ-Ge
}

