sprite $AWS_Outposts [150x150/16z] {
pCun4G00202XJVetjeAJzoJ0pVoIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR5dcwqCvTXY40YXLvFz_-9MzhyWAuo55
o3UzxXc1MVmTB5DbLbL_ZaffYjWZ-afeZHrNAINXVbL-KCoYpFzSVb0r60R-LpDNGkoSIc3oou1GiFoK2e-lwznodE0XbQDKoJXziUICYYVKma8DJwZiTI0H
6SlHR_BweDweGlD4pXAQesqgdpezOT4bqgLI7DMQ_B38cbHBLwqimncv6wFrMrHZlG1N5lyx8K5hTQWS1RnZYKz0wb1XBXItK_z42J_Vx1n5rYTA-FcZuYYn
K4BPhd92eiWoPjRTAYM4DzxvV6QhGlo_mVGklb-b8EbOLjBRw6OLUah6_9r2P9igtwg2gHBRgV9tpt-6phy9M1jLQFNnhi_yzah4hsnIvQi2Oy-wPNMelAwA
5fMZW7LLjAcYg4AUgOh7LH1vNhU3TNeovDcjKfGmLp7DSIVY5XMAmJKLezeDAZooF4qrbatcQ0NN7O4iKVabO-dsdWrPiFsMhy5ekPj0jAwAZZilH6ygEFog
YcqgH1TLskr6nEEYYdqgn9LViUfam6SxLRKfAeagZgiSFxYgebLLtpIUgOfdgg9NPJfdXFj8LN6osmshMAAAGwfyNjLPRutpgivwU_isbV8S7y8MaQj-DciN
jXB400n4jUZfl-7F3EUZh3tYY5v8b3WMSFGTb6S1H5HoAY8gEHKHbPoAY4fEHKGbfoAYabCHKScfYAZaL4HKSYeYAZaL4PMSYeXAJaL49QSYef9J4L79gOYe
v5H4L78g8Yev5H6Ld8g8Iav5H2Md8gAIKn5HoQc8gEHKH5HoAY8gEHKHbPoAY4fEHKGbN9qg_1FOPFPZX0h_fBEi7stlVOmihnz6xwt2BeHlrjrLkCNoxGDK
c9DbMtLdbMUjVgKqHEKtSLgU-dBPfhUnbvNKA1L6zT67wgEHAZfLcEVnj_wu0_CGbMVDqrkVlqBMwRr5GrNegAXaKScYaaKbYqeMbImgMLIog6HHoQAIHIMB
IXQLB2fPLBAeP579ef959OjA5fKiAbbKigXaFG8
}

