sprite $AWS_Fargate_light_bg [150x150/16z] {
xPk9ZeCu343Zk___mtkYEamTTcXCO2K_NIDmuPKaZeqwh_y9HL4KHL4KHL4KXI0YoiESeFq3FCVB6DeRO7k6K_l1_Lv6BkDwTAkNKZzm_L2ItkQ4RoVfflq6
tk8bRoUKuV75nCyaVeRhKm5P643B4uN5QssyDcrjAh09-LHaD3J70otNMlb-Tsv_lDRgxAAtRJtQnLOR8ASceIwmYcPMdFlNMKMhCCxzAwsYHJzUVY1hh8Bi
7amdtuyMMHtlX4gjDrvd5LS7Vj1dtMAhk3eGs1rOR1LNezo2XxVGAfxQGNcyr2gk3doAtstbNfxmxxPonAVuKwpyJ5cLrGcKECEAAS_E25fhirRRNq2MsRdh
l9NwTfJLkTEy5ULq-WhTVZjjrLSveFDjCehbh44Jd6oe3OBFJrhrtnM-qLAlA9FpbV7NZOzjOsU9MNI-eqP_Qv5jvMzHyAlnq-js7Frc3D4_as_bMdX-5-RH
7SvPwU0C-_4pLZeuJkUiQ716ywp8JyHMmv6AJrZA26gyD6ChNsoQCu8ukXP6hSou9mFF0FEpVVmL3O8UAxGoVeVQ-A6V0u-qDe14OoiLyh2n57wvuv354y81
P1RLVswZgiACq7fuN8rOpkxizSWlGJdej7Mcv6EBhlmBCM0xS0AThlgYqq87PaWIZKzGzSrKo2GMHWWJuau7YKLVyTUOgf0TWNv09Ywbt5z9CZel1uZrl111
j0BckzIFPA3w2ntzI1FUfIQWBjQ1YCmi-WDXPaIC5YNfAnSJWZO1-7f9DsDiNu3iHXTXoeJGVWKWiTfh7QR2J8WOpZTY5jTv68LWGvICsFmVVW3RH6mgIgs3
B2CsQqzqKEPYvp68VfS6_n4BNIo-yY6lG_eQXsTYv_62RN_dYTZSttrOLpwtkTXvAmURCnixRmNDERJgRIwtKgDTPtLazOfYqzaQInFmz7De5SHUPhNzPNxt
3TCFAuzTPFNpxaQ-hyGHwwryVq5zXfMN1fwYxhUYzW6jjPBzzNMdeegjGuFOAwosuTdkP08VzPEdg3WstmhVz_zdjLFu7m3-kA9OohUoTWofbom3x9MFXVCw
8ZvnKV4-oW7xemr6-U8wudpfHnjfd5il9DvR_2YmnVlG0anyE0xofSSkvweiNbPbnTQx63_1QajIcvLIQ_TRyUvtx8FUVJtG0k1Uf_YTa2uLMFN-RFrxoVK3
YV9w71Oyfg8eYg8eYg8eYk9F
}

