sprite $AWS_Outposts_light_bg [150x150/16z] {
xTW7ZjuW48RXOVhzJnnIBEn5ifqsy4lVevfiUqMPHPl_7G0000000024gJAhgk-J98q6jZsQw8kslak9PXoRB5HZ4MOw-CgeTfobo9_yoBHSXdys-QLKnsej
F5EQNtWZwYANyFDMpHlBkKGRApLbBTj3kraGfuwTgMiQMQVT7HwXCyqgVllZWYuaYyZzFHEwiC8Db8TJH-9kbNCYgBE7iMzZsQJkM4NUPOcVxqNTNCXtl6nw
wUzCxwhfOErtgfY8kAQfovUCcQLaL7Kjzp6YF0zXUiUZAafZD34zqP9NbSJbVvv9mQlOfiV38_llIyNpRpo-qQXhjKy5eSwVlyXBdmhyV6hYVrVDHuHVNB5H
LV1KsAegFxSAEnZRdVOn6VQfcgVeNCLqvax4DLL17R-hOYBoagfawcItgXWlcVKxEEZnX-AvoYzYEkqLBsHHxNpv7HnPW-vIbKQ3tknWU6LLXivLysateXOL
LOC9_s0xJ8RPfrLv8ycbLJS-fmfLfcUHxf7RdNObelYaoO0guJCFOSCTN5-5AbIX2bMeGXMgK8KgLA4ALQX25QfGXIhEMr5VfTJfu0VJGwCkibBGAvorXDxm
t33BifpHayW5b8YQTjJvwMwggb2NQwg6KJMWQd0wYVaEI2vXV13FdqB7_qN-Mm000000003m3G
}

