sprite $AWS_Serverless_Application_Repository_light_bg [150x150/16z] {
xTe7ShGm30LWowhtlt0AOVPDGXo8C315tvI_fBrrbPP4LYcbb59AAQMKKaeffPHIIZ7frBvq5ejudlRs0x77erpQhxh5SwGDTOzdU4S6KVlK6aWymLxB2DFL
FcX_SBXqpQInGAe8vxOWUoWKfWcfFXYrXTqT2eEnJOMDOFUlAV8OfCAoyxYDqnfgc0h9upQCK8DKYCNtpf_7JggmMvVMCdyQerIWcCDmC_Ehzr-FSIhew-dX
J6t1TkbG-Q5KtZuvNtzns-YIGohGjgMNRK0_c2hefbZOxlkfC5XTFSBugbY6tJv8zNspuMeAL3z-IQKN0x-iQVbnuFBaenMRlGzJ0IC6--QsyWlE1Hcd0axi
uJGigvrKJVvuNNHFAaolU3XZJGzMvfsfl8lX9-lWa_0jxaa5j7EgiSSqBdGm5V-nLNlxHEBpEkLPgMOD66vQFpU3JcrQBcwhhf5QxU22jjiY3Q-FrED5kNSM
FtuoW6kVK47GjW5KmZGSFqN1-MmitbuYt5x81pVE3gDJiNJxrT8QqE1ste72Pb9NurzfM0YpjQbaZav2pmyLRxyREzghGTLtR1VPfAw6y185tpTnxrfsi6pm
df06_Yv8bUfEaaMnZo_fdas55QhfedWyLlaPnEMK-pBxZf1KbncqJqk-brZPtpXNcxOHMMTWW1r7vPw9gJfEs75gQZUdel6Z05m6_UPKPEibE-98VKqgInnn
YYrCCMRvL9guepP_JwIQUg083ewTduhKYJk1BXihD1w97w6PgnFhQkfKO65HhY9RjoZlRepazIoP1pt2RU7pQuRmH7dT3pOMdYz6vV-nd12AzwSwfVyx5Wvr
qjr7Gf7Zb7XewqiNg_ijePtjdIKcCZH89sEH-EJVp-0vRtyGgvsaUF-39mpuT1gdIPkCVTPYc8QcPC9-dv2eYyKHfPHIIYcbb59AAQMKKaefvHq
}

