sprite $AWS_Elastic_Beanstalk_light_bg [150x150/16z] {
xPg9agCw34LjhVF_N_pe6cudmHX4OY1JJwUMcTvFX2HBhlpvTqYI94cI94cI94cI94bCg9Q_48jzWv9IML3PxrLogMKDkZDWKhgGtnKeAe14xGVbMe3S8cLb
Xkt5LUd6SEcSsheIH9w_PZT9IIUEyuEqEwIgxHM2NPzJrVVJpY-ilWgfVVFhh1XI0Is-zlbvyFli8gjQ9ZHO4tY6RXDdrn_zYK1pzt3qVD9JG-MniYW_E9z_
SDkHGqvBYvvMW1uEx4LQU-MkJ1Eihy4YzIdCV9QMRLUx8ZWujt4qlKm_Viga5nYvCCh8ek7oyDQAOgUjamZ0XWjxypr-Gb-GxTHc4KnOWHeUbkosDRr8-q7h
JXTPeMNQzca9tykiT14SGHC8Ll5uAzH1ZJogCi4-V2krM1q8D5lzYIe-oAdynG9HnAFgMOqAc1RWdrbvBSEyk9Jj6Qb9RkqLcmiLO1yl41DLFT3r0yU0qe09
ekvlmxnuwRPpuZb_giM1VSLnz8KFFAiVQMdefmbQ3oaANUlucLkDuux67VETXnu2lHygVcDAr-0BjbEt6ZqeXG3J-At6PCBc_zFX7OlVp2pP-3ddHPisRcu0
0y7ISKCnX84yDVc3-S4ZXs8kB_1nAumM0qSgI151wx0LIcISbI6f7sbkArQc8ceRnJJMgY8yZy3LfPLBcH4_swhjhT1IMAqqC3tVgcqq3iioqQc6mLQwKz5m
gCzMigm66MM5Fn-UFHzMzdGBeXNLC6G_H0o2SpgiUjNG-VNqviXWns85ILgCNpQejoEDZ-LLjnhMqqhVdO_jK0rshTSdsBVlzweVwLU1JIomSuJds7Xlxs-j
WoxPl6s2_SgFnmfI_D6IGnwO6U9v1QdY7ruoQ62-YjUWVBpKQxFHTqvVM7MgeNqlX0wvaY6n7_2x5tFxihVB8p1uW6OcN0yiGe7z6xGtYaihNKo5K1ZyRWnP
jO95-p7kjudgQpM0geDk8EDM_MgO8HtxjgRMofue4pkRMIL6sPn5MQ6pnJRSODLKmzTO8SykHo9Mj_F_iaghjB8dliIguP-tIYlvaXgybxHAgxHAgxHAg-yd
IP8aIP8aIP8aIP8a-Gy
}

