sprite $Compute [200x200/16z] {
xTr9kgCu54HXcMU8g97tlzfgg2uxuwVyT09yKsV4z1zSUb3x5PlDPe-BHnBoKOXyb28VnSWNOUGXZ-auko0ZxtZ7WtKPnx4jt7GytiGn7JfiOrjVzTJnE7Ba
8QGZ3-4TF8Hqv26yWuUGZZo4T_0Gqf67y0uUGZho4Dx1GqX77i8xU0Zfo4Du1myX7Na8x-0Xf2CFuHqyX7Ja8Ro3Xv2EF8Hty13IaOVm3Xv2El8Gti53I4SU
mZjuICBH_knVIFkpRVl4TcynXrZ75dE8TMmnXrZ75dEeYaDL73h5CHtRqeQrhASvxcreTz9npE0Xl6DhmrlFSEopSLkt4IUDw_sspyWPZfqnxkntXvpbM3KC
SZ_JiMaSv4o7NbR5eIeELN6eYaDL7AhYK1M7BkXeNwI1aFP5rtNeFHpzruVBTHtRhNLqwt1avtnfNIrNtL-rpgxiM3utxClL7TBd80c7EOUY3dCEHHtc78ew
p3aKTRZZEDZfq7F7lmrqc7CewZ3dKDHXpg6emyoSxyNcVA-AmrKShk9m5OSvXw8ESmv57UOSYZhSSHpiT8Wz3duRvr3KOSwXgCESGr67cJdVYytv7kTGr67E
eQZ3d4DHXpc7eWvp3aKTvXoAEbp5ORL_0np_5d2OS4p7TDZ6vboApVaUvr3KOSwXgCESGr67EOUY3XyyTtxTSkJGsOwE3Xqwrx7qCPRd3frw75JdUp97puTE
TQZhlIKTEHHrMCFwrg6emvn3mJctFTIXhuewp3aKTPXpAEemvr3KOSwXgCESGr67EOUY3dCE1HmQ1zcUEiGxLW-3hCyTmXsBXq5k1mwHZeyTice4P5jlnnUJ
e4DjUDk157Du7Ssuwo3EuJN8a3Y7zJ5EiMnw4U0uE2v-UqmxtkugwZ3dKDHXpg6emvn3KOSvXw8ESmvLSMWwVYeXvHskud0LXwiuNCNXAWvNSRYAmrKShk9m
5OUhE5p5uIeELt6uYiDL7AxYS1M7gpXSnU4g3bTnk8h3LHokud3CyPlP4exhDnrpFVhfc8xtgfwZbNEqwRWEOsywpcTS238TxTjACFPAAFOAADwDqXBDPdy
}

