sprite $Compute_light_bg [200x200/16z] {
xTr7aZCX381HsHH5xxZ_QVyS9aVL8DhlMtdxdEq65BUOf5cy749zpToi14LToTop14P5oEIe19bdS-puONq-nopWu9YRE3YEqZthcFixE3WuE3WuE3WuE3Wu
E3WuE3WuE3WuEE97xxrzamuE3WuEZj4YhJQMENgarXSvUYJNbpX6f3TME5hywDh7aT3er_XHM-7unJZI-WLPvUXvZhxICV8SOwNZIEpS3WuE3WwE-5Ewuquf
3exHuisrKTOnBl6EBYF7aVywR_6kMjNtgtXdbHtjU5EjkkDuOvKT71mSyQTqnvtsT71mUB_YuE3WuF1vpi7XTSx1mS71uViL1uVlLnmS7AuxMmUmO5s6TJBM
BIN4ORqe1mS71uTzNfNstTa7QL_gYFI6VTlsqTSury0v4nmS71mSphdZuE3WuE3WuE3WuE3WuE3WuE3WuE2e7uTvz1mSUtK-HvpE4Hob614Swnc581pni7qP
-qlYcJPKx4w9hqZw3W
}

