sprite $Elastic_Load_Balancing_ELB_light_bg [150x150/16z] {
xC4n0G000CAWr_w93J9WCG00071sh4FNOH06ujt__-6t7AcqvjKAWT9rcY2XNEppL8Bo2nHx74vGpk078KNb0c2FHigX3qEAH5KP7iHQufniExABVZ4f-sCX
bV8Vm8Tk6wflz06C1RyoQWZDbZjGcdSBeMwNQ3zU7e6jN86hnOx9vGFRwgChZpT-j1WyGJGM-jLoOL6uMLq8uOgMF48TjAqpjkr8VqTwbDuOMLLeKZTgGbWs
0B9cYI5WF2bZ29yWoJg-GfSlS2WfnT84iDtiZVLarKkGkPoIQSgmSfVntmb9X_hkx0KWrZy8u_bIa-2R64fnzbMgpHLrJhCJj4yg4G91nFvYShMJ97Ou13pF
dqOv-UzQsBK8GQTR2YnXNiKRL8Vvis-UnS4ZOtgfi_eJEIqwoJtsGH2weOJMtE1py0w5oBrMGRRh6tIdjHdjaeX1Y8nffiATyGetfCVCB7hKL3lybuulHg7r
wKFBL7aSyarEXsDK_7tdkYfAhWOTSY1q_8ZzJmeHZzBgU6nj5u9JqhhruGER2-se1TYktNALsAnVLZt50B9SxBIeVoFM-IlnZlit8E4bZN0xHljPjxAmws63
LM0Gz3UVLHiwQZVgSJE8LH8L3yIgl8u7lzktImE0WI0Aee7-UuwCEr9FpBHmk1-0tGxS3CejIhuuvkjC_cJ8Nn_vGoQd2NBo0gTKOAAdr0zKAK9LDLM1HDLQ
LDb6NG3KCO7T9T-9KrrBok6zVuSNTSFHv82Pij0JAQLtvacdKc50WevB6vRuBV5BxgktrFrnGw4snxpvKajetgYgVNRSrAlLE6-0-aH4H4H4H4Hy
}

