sprite $Elastic_Load_Balancing_ELB [150x150/16z] {
pCun4G00202XJVetjeAJzoJ0pVoIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TconDlhGiCW30NWGXAIztzXxs4TIpq81SyV
tVqJKafXRc59FhwIUOzAUqp7ARH5XLdvU4hQebA8QYCxLDg3oYmYzCF2giKi_ZRvJVARGBMOzQNWjl8PgTQowALffAVYTIqhlPPHxYXuNSiAkaiwkb2NiYHg
buJ7KbtAucWSoBYmT2cB8W3jLUcIjfhFbhgQPnqkM7aCudIELsMlIeF2oi4zcrKQd0TpWpfakqfVk_18piZhvmoO9QdEG4c4CvYDZgeAq-E3CidlB3cYf9lt
9ZWTRJ9Vi_ZdASqhofqgoKSSAZ6BwYpz_4g-TNym7TVXY9NFtKNffxZkl1uiL0Kfito77j0a5tz5BaFvMqCbBdgEL2qrtOrgQ5x5jKv_UJ2Lrpkvh5DnDSNX
5rQjytKg_mYzJ2tivvkYwrJSD0HyKacF6sjKNhQvxsd9VwklMACg3GgmIBaPmPQeKeD2hEoecWKgydxfFLI38sD8XVklQ5zoCt9DiF3di7QcN8rhzwfAqtye
N9yViuG-mZAfegP6OD9LXp-lHDAK2ZLLV1moc7HChgf9r5IuiLBFx2mFgtBu4RYooZKgfGHOK1LCcr1At8NVb2pdsJoDgKhGWJ0fEXLGKqiPBc-3tb2G412E
OwBQhE4EgGYKLVUVmhKKWaMHEAWpOF1ncnxIPWLfK4NwrmIgyn5mRgoyKHMdGi7QA5Gr1_cSIcjEzJwgaljL2bIxUz03Ud1tjNj0jUyU6Jm-CkmQHULg5ELN
QBcERJpZrC0pZjcsixDwyDdPpFRDPCvNQ0HKzY-pFaKg-uSPigeYbUszcl3d89KjlF9oLtvTT4Ogk-CgLS3pVwvIzH6aiXLNz3X8PIjMFt2GokvRAPfcsIbJ
gshblAecaomx1wn0OXIf-A7V7wIo-TNQMlDJB7lEtCgsDYlRmop3B5mgsL4-NiwohCtuZidrTWOEKjdexb9m9u-o3B3QdJZjs8aRglb0XLZQxbgMxbtB8PPX
bfVmTHXjX1Ns7Tu-bW4MtWrF1BRm70Xh3Qci_vi30i-C9nFeLAIogMzPU2HkNCmom9fB2R-HWbcsW-KEdxwJ0fOjPhN35gDHtrKhMUoew9vhbjtCmbSz6SrM
aMgUTNKoOlsLPKjP4hKBNgv3AhkXh0RMBsmfYo80tQ2oVsahdFrrfRQMvSSRE0P7L3OvNYaOhmPLDbTO11PkHbKsTnxawmLbh9fdmMjlzfj0jPgLVSvw_eyg
h5hFQe9HQkjP12R8GBMqjZoa7R4TB3tz1wZUhZBTbFTcvrW00000OD0xV-9f546HhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms
8bi3
}

