sprite $VMware_Cloud_On_AWS_light_bg [150x150/16z] {
xC6n00000C2WT_x44wa20000063cp4JPKXM6eZip___3x_LWoXnA-fI8NbUFTy9bI0BePK8P04kq7y7_q7-IaUZZGig4XCLQeYZ8eqe2zCWMCqFoRBICS0Z_
3HW3O7LZ_2OUYXDZ27jhBR2bkJutXug4rUElfmdL6OksmGy5Ap9GOeDCes8H063tIz4MaJZuMaQnT0e2m0z9SVmxa5sNU4PAsn3hekKF91Rd9SSuVNnFv0Vt
eVi5mm-8Z6U9p-rMlaif3j7KsbFyzYAaFQSmO9yrw3xfUlVySVjgbK6D9wmYB_NLAbUQ9woqzeGqIFhF4V8EQFifjjkoYjfNgpA7vAK6i_MknMenZQqIIPlo
BotMoijq1bxehBAdHxNZjfhCtsg5GhNAB4-x_1TwHmUr4rO6K4xyla363HNOJbWr1My_nwLRh4yhFcNLFBQ9bBAqjuNKqR_NOFz9hKcmt4hFMcK9beudRx2o
JF7C0hhHwdk_EXAnnOaLbilPYMpl9Yrx5bkiSL80KrRHTRaDYIMjQj8gqoeHhF9omWR5QQi-lsNHGn5F9VNMJjMW7_O2rxnBdW-NbMSQPwp223RecoubzZDu
YVO9gpp8ow0L15_H2ieVFcML5HBZXmoA-RLQKkgSLRO4pWaSpe9TEDLCM3N6HZHZ6cKinMIeh4rPMLQQqk18hrF1ogtsd5KZ56HuQ9eyrSnQAIen6j_dJZMp
Lb53vSEqrQdjvvnLNLt8eYNUNm0yarOwR-Lzc488a3xVPwnytgePiSN73gqRqH-swZ568c-nSbJUOXMes5jcK53WwrQsnCf0ucLbh5OFzwkARmhqSQSAW6Pw
ErssIWYvuwAkYpwp3eu7awRz2m9TlMVmZc8rtAf5tccA-jBzrO3XK1aN9eioWRHoBnedhVnWuwafUXRDmQvQPUtreeYbPnp58VhbNKi_j5uu3vAtASPXoO6l
dPqrbhmhIqAGehDQbxqavwz_cUzNmhz1QdwI-7pGxkwkGi22l0Z6BFvnI7PKEDerZ6QbijOa_vUmj-iONvAYRfCbtjOGAdHQAbLYBnjYjVR3IFgz2SbCVn71
BvHoUeMKVImiYXT8TViLvvT8PV6BkHBmdkfZV43Hta0G2lgYPf18jFVWGW2nhN7wlpqu4000000Gv6yzoDK8000004
}

