sprite $VMware_Cloud_On_AWS [150x150/16z] {
pCv70O1G042Xc_HlR0J7Nuy4UEVQIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iMT6w
cRNNTKTP60h02Jd0_T_mTsZPBihOs33OcVLh7_KL34IV2XCHonzIsICJovX-8jzMcJ0TOT639JIaV5DbXNv9iITBQOnyJQLCfs5ziFX_ebZ_go-fZEbjsFvd
_SoRO0xlLWccJCsVJiM4IdNayUClg9mFqfixZNq8_HUzMGMKdFpRKNpcHtXr2XTGxB4PeoEhKvX7QL2TqsZP5rHFbDKWDh7mpLqg0Shj93wCvzTK1fJGQGGi
hb3fdQhXdg8tgG_Mk6xnugQJchzIBrGOLAytgp027gkc2xXV9UEQ004o_epx5RXJLx7Uei9ONAjG64SDPfVuH07gfwfQkgf2HRnLXTDC0XiogUnd2g42QvyA
1GWL3O4ATzQXSxTiN_fv1Lf2fS_ljAjwsxnPfJXdg4A4k5SketkGdQf-z9IgclU9B5ZbQQ-A-oxtMGqYVNSycXhz2rIu7RsNOVaRL7hiKltEuZjLyNg527xO
ot2dIWcgwxiTuM6LwsjMqKqg8LfJ-SisvPbt3v-PyYhSLZZIvwxhnveUJwkmUSuiadKLHftLQqtLe67pH1olbygwohh9AlA9ofL8qVqWxcwb7tHLvKJJWHEz
A6DTGB3vW9LLCHxVKwgdnp61Cqik9_6Y-hZMlEe1ulDnnfC-QLw5fvgygXOKhXQQMUYtaYhqtaigFMeN1pcPHCshC7yP5Rv3ojaaneCLhWgsgX8QuoUivoWc
LQZh9PLFhxnFME4I7oqBPLbLoyckO2-i4grPBJYphgji7YQNbykyU3lPslipsxggwZXChaoF34gBLMstQewMitAyKhLRLKPZ4gfsfyffZ2PKxHOLoX4f6LNR
MuDpeop6rECPLJkxGjcYglOaJ5s4nAgU-DN2kWgjclDupFBuvahLDko3uGDbmKFFz0uYKhNWHTf99Kpfgh1L6nyGZnudLiqiYVkhEP5A-hZKWlMUZt-uKhMe
5rrN6Ovq-fBWIjNYlZslmh1e00rLCujd5hodaO-VIfnV_pvMWOKvPA_vnFDdD4CZrSmoZ44gyVovqA_GMHMnbBhB4unu_goRvlAULV5ezR1ODexhylv97ob4
G0Mi5hEyq6hyk3MrNnzIJWO_KdKMeloxgFAiEeIjdYLGWGLNMKLXRP7mIQmdK865k1REesh1JJLyK2i8L35hFK0bSgLgcr1QKu7g7XO3bMUrUrWEr0ghRMBP
ozwa1DGAg-rYCHZ6GAsnsYwMziN8XB6fhBBQDbOXv3Sx86_xM1oqWCcqZQpftSizgZpB2kFpaVUgMlr-_crsZWK000001htp9vv64HJPYcn5jY9RaQt8LcGh
iXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jWO
}

