sprite $Auto_Scaling_dark_bg [70x70/16z] {
xTV50GCn44FHapp6_jiDurmC2gv-c5wM0L-OKZ4oaDOY0TaN2SY-k8hK_NMDiRsmlzcUCKmNIZMq1gibO849s2l7nyNsobHIf4WnN4hfuSsHOijmvHOnL6wE
SUyDCFwTSMOSQRxyWBXUfzXZnOzHiSS8KvSxf_bB7NyDqFR59qKA-UYGVwJAFshc7y5xXdPI4ZbdMUl5Y2zCgHq
}

