sprite $AWS_Cloud_alt_dark_bg [70x70/16z] {
xPL7kkiW34P5iK30sVzoNv4nWyJnvychr-VMWCelqUIFyV3myF2GQuDX9OX8L4rpL3Mi_-G7oGoivlCOWyd88WhuS0IQk3UGH8n9bHECnGYI0S-sSSGhC4Gg
WBcnd51xII8IAb14Xl-UNbvSW-hIp3MM8bSqjxDPI0VmVhYwpGNTGA6Bv5ro00EJEU2_myqepDJkbJliRR5zk2Mv8AgPwLQ1lR3Ylg52yjBoiGYzHFc0mM9V
d2RIw99Xam1ugexJjqzD1JERKQORLE-DP31njlPvlsGEi-BkUmakGpf3gl-t4pON5C_h2QkxCrfLjwqGEuINfEKqIbl_CNTyDyRU8eNsQc_dMbQM_R_1h392
drjlCKwr5A16IHM0l3R_vYwh3JPgFiv9bZS21tM0BLNf4DfVjuDTtGn5b94FrMDLgSjgfyefmRTk494Sn8afHN5IIYkRshHxE6bXXsxRom9j8lSn3iBBUCzo
bsYcFsZl1xAmujocmTcc6xTtGQecqcZlEXk0tH2qNozHeCWxEl10MxnIKJnRYvBXr30OEyCqXNUrMGrdg1zv-vJ9OD6ig6fEMLMBDHRLCy1dpR5ooLg2J9Oh
jiP7RBc6wo1kOPqtMbcEjmb9YzdnIkcMvFVpyF3my1q
}

