sprite $AWS_Step_Function_dark_bg [70x70/16z] {
xPR50SGm30H_eTNqN-xHDspjiIOC5Xlw7wKefe2OaaA21v6p13GCWYbdYkuNvOo1uNuPm2_5xv4_klvC-wlkJYAoUIbY4nrLlet3XI-IecE1XDD1RP5oiC6R
fOW5T3OkB78sHv09ynka63rYWHOfwszOn5ml_jfTm3BSoZDA_OoKRJopsbldwHzOxzPwjzQxFqPHN04
}

