sprite $AWS_Cloud_dark_bg [70x70/16z] {
xT175jim34NHpo9G4F7slzpq7bWMdPEHTMSig7fhjzljrinyMDS_A7lmZJUzQ03uCFC0lEWL1yokhxf3jDUIc7xg0Lsh_C-WSa3L6aig7qoj2OR-LC6aRbPr
ZH7fBIC0PjCL4rCY0FpWsg8h52KCTadr88gUsfXAkQLhonc-jBUSOJfLeEg9vkmw5nnRqOdYmAPp1Z3qK0tmhcVQc33huoJHTCaMH55gCdLL3LoP3bMNTMXA
EBiMEAv4qBMW4qf0qO8AIe2M_DyiJGiQA74mj63ZoAz32oP3cS1rsO2YJ8TT5ncCn_bdrmNDpmfkGBWziKzWwB6oSuatdUjvVVzfzA8tTBlTRXy1
}

