sprite $Corporate_data_center_dark_bg [70x70/16z] {
xPL50eH030HFfAS9-VzpLt5tJPtG6ej4jyDna5Y517Cij1gSPz7ohLOjRY5b1OiP1YnkkKUy0CV5Y_2FrYtAFpB64bj6d5dgZmUe3PfPwbCSfhu1cIM3yoo0
pBJKc6qHPgxyKC0mrGAp-hxGT0sBMseS7Iz0FNO5y3CwsZ9yHbUEEgXczvgkBIZzfETQrky1NLpLCi0eIx01GdGR7ESD
}

