sprite $EC2_instance_contents_dark_bg [70x70/16z] {
xTT50i9G40FGJMsQoVslIs27rRrvQEsxbf_CZApr3OQ-Q_BZr1r3gUE9RFMTXBvRykEKr6Mdu23H5qgYL_Q7Wh8NpX8A98U5af1_hKI6XV9I_XI2OQ4Wv0Pr
j42vB5172xINSzVHyg4iNKVBX-8wyeZf4TCZvlAXBByY6oGMMgdsyJx0p1u
}

