sprite $Elastic_Beanstalk_container_dark_bg [70x70/16z] {
xPO73kKW30NLue8zzp_k5X1IK3wfspVpUs52UIPPVY8lBo_gtr5veYXqmcuwf3eolb4zUgiZ2MdIX1QGTa_Ygy-MS5aZ0RRvvkgW76mhJhdM5V1FWooBUeIV
b9MFXpK8AdxAalYOFTVsDQINFATHa76v8BLsnbgIpaoqauEI26f3QuqbAMSiiNGaQsnrM263QnQZzLxNQozW9uemjiPOJocGBlk10psmMB9RMG5fCeH4FWr2
FQ7CUpB-94b8p_z1hNLawpV8KZwMT04vZhweIktU9FMI-57qjUznOc0oZSGMq37uBVemBPK3Iv9MbpIxHKj4qKiM1UslpLAebFEMCMtLuf3k2Nve2Sh48b0s
gslaP4-G_eVsJX9ROFpScUmGahqBmx5XxDjOxriCIklDQXuc5eEORToj6iSrWN7D-WQIihipH4JxNyi7ZFbP8X88ERnKwAtRwvZb1OvFt6Bktbf71LPrLJli
fijPaivmXhc8UcCriWVyMPQeFBHqyfd56_fmNYQybkUuBx-2bvUNhm
}

