sprite $Region_dark_bg [70x70/16z] {
xTL74aCn20JHBOZf-r_NIsV_C7Bc7Q1BfKJyZjOAb7u4K9Y42jAl2C8q06h6xbRu83-eebeGorYYM05gt0UalIy5mzxT0HLk9K5XLuJ2hWYbKLdOsONAmgOu
Q_7tXOmtd96nDVFlxi8EUszwxGwpHA_yw_ARPa1NkjALhdI54pcfylDQEm
}

