sprite $Spot_Fleet_dark_bg [70x70/16z] {
xPU7pjmm38EngittVzoEnCW9J2DtpvyODwnya6bOntltp-fDRmB-18fQ90vbc7xvS_wg5I-WgrnUV9yWA5sCE1uCLmLKFGvaB8uM1epMmdXzGcZtHJ-1oblP
3cEzVzM-HoF8W95SlPCaKWWoOfwM2J9ZjilVYOalWkpSaz2ZQ9GZ6MDeEfvF-0WH87XJGDUvAyX42PImDu1UEYbIYBaLlraCtEwtZytusSh2n2D5ndlK5pNa
UTOuwX6YWFRFLhXKrYXSoHkYrfggKthNh23hxwS3SEbi2_jAbC4OGB-Kei3FfE1GkpjCQUiujAFWYM8xYYfWsaw7AQhN25O3L6TVs0L-FxjRy2rbVzA98ChL
jD8j3kHm0uZInMrFjx5HU5PovMXCdoDwILOKeAw7ASM-KXJOJIbPZJE5XwW1if_UJ6aOcjxJ-ERJ8Om3iljL6qvdOP9TOOd94RUqwPueR6g5ujRFYmpV7r_s
1UoVVpwHUH9cbmxjlcgS3kTknLjA1bgATcbbsxWbUQPcErEpdQavfKU18MwrzvpWGnwYm2prh4L8rp_a_z4_gpUzwGC
}

