sprite $Virtual_private_cloud_VPC_dark_bg [70x70/16z] {
xPK5SiKm30M7BNXx_-EMsqmKKfcyGn-I5Hd6RsKocKpidlSfF7aa_SsE40jweqT0-f9JlgKVWbn_rPioMTSGRz1aaTpXhoxAYwJys4JaRe8Q5fdftLHix03Y
0LchA_iT240HsTCSDS0WdkQkIub1_SMUIlNQwBub0QAqFngMAgcQG5UIX4qpOcssg_sPG6x3bk5hbLx5LAC4kMCP7YSRLCLXAPHtWD96RuCcic9b8NiRr3Rh
0EAPdHKTfSwZ0OAL1bsl6-5zImrRt-bR3BxIulR4komBNSksvSx2xbcingJVTa13lE6kg0HuNs8Y3rBiP-D2Deuq2kivYgGKrINFgWtHe96nNJD-5vF9P78B
}

