sprite $VPC_subnet_private_dark_bg [70x70/16z] {
xPHLbiL020L_Sst_ottk4cDygBXqdHPW-7oQfi6EeeBA0R7G3UU2KP28vouPQoN6_SCA7EFUkKB217TTIxYcAxf_eHMTGOA9DpDW_DmxBhVeyPL-YgKjFA2O
3pZYWJaMPGBDirWZUAw5qnFM5f2eMk3iC6eM9tRYaeNPFo1HnQBeU779Shn7ylrzOSBZkRf6IMsDZayxLC-01CFFjhH5EbgwxaxmXHPCCdm2JTDi0G
}

