sprite $VPC_subnet_public_dark_bg [70x70/16z] {
xTJ5eOL044JHPLjL_k4-Dnn6llRPu1SVwI-bf1TInuAy2fDY2hv0Ao9Xpqk2baPWyc0ep83GORCWugGEBetqaalnKRRWOfJKhJNRZ90HqEGWPyX8q7z69Ilc
Lq7u21X-PR93S4Figo1MO6_5jnzOLjHTQoiANa3hAY014bKL9qt4I2-eZEUTQ50nylklnKYlVou2NbMzeoldXTV_0QH9YufsgsGbGkKgnzqDNrZHJT91IkaC
}

