sprite $Amazon_EC2_X1_Instance_light_bg [100x100/16z] {
xTa53iCm44HHY_V-5outz8MhSV6FAFmACO-VJbs3RUpmghwXeQ5HqNoDeP6fjJKqQadKMF9PXeRbGqF3Ed6UmSkni-m6Z443UgzEvFNOVARzxXBXLjwePIDe
45cUcJA8uCyVamrStpQ8Z2KXWyZe6hKaQYpvBwEMT8p6knjyh-OR90QHl3721ebbeoOOV05d6TXE6aMZqlKLdWh3FbmZZcirD1pNQbWd_fwXuTgTnlorRGqD
ZT_E6G
}

