sprite $Amazon_EC2_Instances_light_bg [100x100/16z] {
xTed0i0W50JHB_V-9uvEpn8wCvRoD2MiI5uL26brmvhhPoqhO61WO61Wc678AScGMGr3lg6PZFZO10O61WO6Xb5bGwMDOu-6l58CkTKpeePnxDM8R_qnucjb
30mC30mCZ7FZ6J6OuIbSr69WO61WO9JxOC675x-Y16q
}

