sprite $Amazon_EC2_M5_Instance_light_bg [100x100/16z] {
xTa53iGm44FHY7t_2oy8hN8pONqBodcBmRHqzCzk_-J0zWC61WQ6YcOQ0wDChOs18KifmpEQWS7_0mE3Eh6-OUUsn_9qDppdT-yFxmqx7iQG7JKtaYLgo0wc
DcJx1bOsBB4wKPPpGpl3KyXGsF1FwUGfLJ1svKNhA__pxU-vBMWOmmggQUnFgBRXds9LmvFg6wcg4Q-lpWr_Z3vS88nhCJ0Ors9G9wvYOB1sXr5_RHi30sFj
V04
}

