sprite $Amazon_EC2_H1_Instance_light_bg [100x100/16z] {
xTcr0GCn00J12w__XWtHCugbtSJiUKPrdVzjdf-yc9w_DJ0mC1orPWmCHSZ6mF1KH6EgBWE3zGC3WsrYQkFy07VwPKh3lcrCFJBi2qDJBmq_CZ2Ksf2Ksb1a
O-gruQc8njGJ0oFzSjMgWO6HzxY4uqJEQp4mEA_5O9lOhu71lJkCzFUsCJ0m-kuB
}

