sprite $Amazon_EC2_DB_on_Instance_light_bg [100x100/16z] {
xTb50W8134FHBdF_2-DEMoGPpz_Wl76DYSAnucd-zjeD6pQWQMc63T6sr8ODtEEDU_CoR7ZziE5jYGrlIsnuMx8SmziIlZaODd1g80D9IWDrelK3VGe37qiC
ZiZU8utcbshZsqy98wfKHiq0AkDU_Zvl5AtKu9VTaehG6UUI2IGqijPetDgWOUFN5chOeEuFyeOD6pQ8vcdO0CgFXGRGViOZz-gtUQGl-5Y2Lq9M3-m1
}

