sprite $Amazon_EC2_R4_Instance_light_bg [100x100/16z] {
xTb50eD004FHMUR-5wuiKoyawC-cWZnqT1mwkiU-l_tXtwSR61WOYcOt1aQcrCR0a2LYMBPbOF1-O61G9YvaV5sMDLxVoK2PAC_pai2pgtU8zcZODoEYXYCw
Xg6IyQpzPFpv3heHVy-TA1fEb0mdHhQyyZtB4tkk-ePzQHlg6VRjQOkqeQen-iOpCg6y2XhqEL-7VYq61lrQ3Ch4uneOpDrXzEUsCJ0mZfqh
}

