sprite $Amazon_EC2_Optimized_Instance_light_bg [100x100/16z] {
xTe5hWDX409Wujp_ma_gzfDCALCRukqktxhZqy87Hn0vX9488e8iw69qdUWtdG9X80N2H384S6KWa37kMY6Ay15yeJ7666ECCGPFeoygYyQop3A443IODvWt
5cjQNNDM3J5nWYWPGX14pN08tz24Daf4oj14tN08RUXHDU4Rcd0Caz16WTYbmo0x37OOx33eRLSw0KCWGGCT1ke6-Wn-Yi6SKKVe60mQu6s5kp-D_LoS7avx
pYfRhwcHlpS00lSuYl3lrQ05RMXcoR_AlVCOOumnnXWl_Lvj38O8zhtRreXFQCGdUh-P04C1uaZBjpXf1A-QoIy
}

