sprite $Amazon_EC2_D2_Instance_light_bg [100x100/16z] {
xTa53iDG38DXYtF_2m-4yw0GEQF-5WmAN_6X_ZfrZNrV-67VsmO61aP5ypC6XWB1mB17DcLOlip0uFt0mA1Cd3TywVC52SEoHFVBnF8y-xVnx2uQzUpVj55Z
nlrDDYjewDQG9Wp__hE6_x3VrImJburbGcL969eqQj9m8bLUBHFvPtU1YBxdJkJBAoDIXkVPds53yuRc3JMCHhjaqQ3FkHpwjHWOz6inA1F_ry1WxWvZVcuR
0mFZltC6
}

