sprite $Amazon_EC2_T3a_Instance_light_bg [100x100/16z] {
xTb50W9100D1Zld_Xt5hN39evxHUwsEJdquMmVJP6Ku_RcXeQAIQhp4qEdzj3OqW5GFvB4F3xqD3mt_YK2F7uR9ybh6Vhe4blsnm4JFU895TYiRvrwzbaA2H
af47ZI0t67WUcyKmaCSDRZZ4u6Dl6tWcHCyQjpzpBatrlJflf6zmyVxgcf73wqZVmEyNHde6WYNVQs19ytzrvd2tVkVM4stNQcZOhjNmd_YxXePZTnhZnxOr
D3H-EpC
}

