sprite $Amazon_EC2_C5_Instance_light_bg [100x100/16z] {
xTd50GCn44DH7zL_mu6JmWlMJEWhZ6_HE7uwEkVg-S8BFzzhO61WA9glCJ0ofJO6XfoWuNoMWS7vWO51cTXhFFz9oD1b5eoTPQ8MZC2ngtf3ZSR2DmF668M6
sepHRpY1Cd7HM3xO0uOw31KOpch3MJ2U8YNdXzDW-ADuUQKomvOVKeOH6wcotUamnYiZruPxTjhIXjiH-hKO6FHhCIWJVyl0OEuEesjk6mC3uxTp1
}

