sprite $Amazon_EC2_T2_Instance_light_bg [100x100/16z] {
xTb50iCm44DHBtN_2vV3PD2KyhKf15xGcFuwkcVwVVz7zxtUmC30a3K_Os1uIcqC37Nn6PDydu71-u61GPaORsYHoTznnkHdRPcuRoZ7I5qCXdx1c4hTh-vh
h942ZIv_PIZVq2J5Hi5xNcuet5WIVgEiJ2o_vql2_rmj2R-n9Fn6HmGQciLgOAYBmQ3FkH_wjHWOz6inA1F_ry1WxWuZVcuR0mFZltC5
}

