sprite $Amazon_EC2_G3_Instance_light_bg [100x100/16z] {
xTar0iGm44DHbxh_XPSfQ99dwQi9vpLcfv-EpfcSPoucvqq61WQ6hFaQ0yFJQcDWQ1ABCSbd6HZK3mmCsiHGO_POaxGOpT-qjudA6VrbL-CDnHdFg-MZNYDV
59B3o1D-OqeOZ0mXGvkuKfIcN-LBkyDGXA61HdArLzfTJ33KywoHZ8OY34tUUBmsiDszdGpjFpH9X64Pm-qRhZ7Sud7J68Dn8lDQ30pcjHYqYRzeOB1tXn6r
jus1WV7REG8
}

