sprite $Amazon_EC2_A1_Instance_light_bg [100x100/16z] {
xTbL0i9054FHzvdzRnXtWZQrcHlSSh3gLDFHFkQwkM6k_sLWO60ecjKO69cvDWQ6hWaQropBm63wmC1WdZYbeKFidM735YNcYRxFLlYYVmsjoJ2DKnkLDCoV
P7-PDqnZtgWNHcIUg5j3qUbyUgEYXd-1wypDh_IGoFzgUaDFMRDXIdE6czssOeJdLtxnbvlEMKzaknO3W-rQ3EQ9wpSm6Bl3c6fi6mC3e-ri0G
}

