sprite $Amazon_EC2_R5_Instance_light_bg [100x100/16z] {
xTa53iC034FHY7t_2mz49OyYTwLlKVcDub6TEdh6B9iLizmoC30m5CrX38nCQsDWQ4ZG6B8l0uFvmC2W4_zak7sQ96CCwHb3lZb1NnjbygMXOnjcAJZdYwS1
uxVdOqYZ4nklgqhFkNRH9Nt3xytsLTKFYDcu5sDOMDSObWmHC8nMw_MktCZa-yeG8MDODaIYh_ppB_4PZk-rV8_2u7ijVKKdCeCO_7U7iOF_pp4mC8wVEm
}

