sprite $Amazon_EC2_High_Memory_Instance_light_bg [100x100/16z] {
xTa53iD044DHYtt_2nT4AvTNdQaorRUWcBpGiluwlYRUF_qGxxymC30mN9en1eOAWY5XE59YH8vbO50-C32e4pkDz9n_rOhpfneZ4NzehDGQYcmOYNYi4OZd
6vRaASRBeYJl68xi6Teevpj6IFs6sWo5qL9VHVbkUdOb_SvGex4orC1mfC1WpCcuTew1WS6u5eFoWL4GrkumZh1-Ze61CJzd
}

