sprite $Amazon_EC2_M4_Instance_light_bg [100x100/16z] {
xTarWiHG30HHXtt_2ozaBZD8WzMHzUaD6eUFJlw3xTM2szSD3GsDbEPj38sQlRQ6Hf0I0tarGyF_XuQ6-yH-0sseqT9ciE7wFZ51OuuQyxRhHkgCp2eql8-H
MO66FYF5HkPBviMC82i6Ckeg-f_FCoAgZF6dn5b3gv6PSNr_nQyR3SpwGYzXyAFfCz3GRwmtL1aQGGeChpbNutMjXeRNjHhk4p_NqF3PdKR_isqD3OtFpYy
}

