sprite $Amazon_EC2_P2_Instance_light_bg [100x100/16z] {
xTb50iCm44FHB7N_2vUhGZZM5BysOR-YiVlfw9Y1_U43xxSO61WOYkPh38nChOs18ITgE9zbOF3_mC2WJdoHCNZDPuE6qp-Ng1Er_jFjdLvfw2s6KeRtZhi-
aJUywxiA3QVUyF7xZTN_mJwXtF_SwH5neq_aZJwHhgy6wztixsg0g3UwEiD4eQ6d90qCEJc3CUTm6DTYO32knQ1E_5q3WxKxZFgrRGmCZD_E7W
}

