sprite $Amazon_EC2_T3_Instance_light_bg [100x100/16z] {
xTbL0WDH24DHFhF_3TSTwcJqfgvdz6aiEjedFIzVfES_6XWO66hDR0oCdb8R0qFdz1btcPw1mVc1WK6Pw3UKadun3UEQNYDI5cnagTJ3RuJFg8bEeoQw3HtJ
LoPce_v-_O__6nh2aD68jl8g6_c_NCVLCJCtT7vq6ahxt6DeG2FyXgsyqZcquRuB_LeC3Fgr69I9opKmcBl3yCzjOs1WB3jR
}

