sprite $Amazon_EC2_X1e_Instance_light_bg [100x100/16z] {
xTar0a8n48JXb7l_2oDLxCTMi3VJu7p8njjVnww1wt03hhiC6J9aM6f-nf2HqslBa64zYKRFTnaor3vao52VM6hG3RWLDVgj_RfPg4_S4VmyhjfbWuYuiI7z
FVEC6MbMQsnlEQ3xqnm6VMg3ikvn65H5XKO30rg2gq-4-y30kky96XOt6CPQZXiMDMxNhilmjy5Iepqsqlh4GgDZOApz_Yi6Vrf_EsU3UdGoMiX04BxMY_sL
o-3nGsjEZjQrCcHeNIj3VUB_6Z9qTYUZ_cnRXWmP_vqp
}

