sprite $Amazon_EC2_C4_Instance_light_bg [100x100/16z] {
xTa53eHG48DXuht_XLVYJGRle7yZEDyAF1qU7VrZwxOnVjPs0mC3Gz7Sni38bDeO6B943Ckr30pU3mmCoiHZZUe4_PCo_0pV6oeJDMLadbtLXeA6QaCTniZk
e34YPuonRv4twdDR3QqqP1anwdsPzzmDttLdm_S4ogjnmvDwFsvdZ25gDSRlcAm_-etX26FOO6nemnKdvDvpsedqQp4mwDTYK2RUty1WxWwZVsuR0mFZsVa2
}

