sprite $Amazon_EC2_P3_Instance_light_bg [100x100/16z] {
xTa53iD044FH4Vl-5ow8B0Z7KnXz2yBxYeirEdfdON_nmFjt30mC34NpDmP6fjR6m90JD9pVCZ3uVs1WK2T-o92pN4R8SAuPpX53XmqVdZRqtuRtj70bPtXt
uIXl-A3Dy7wdeHF6kV-WR_1njYvPDfGtgj_mML_9rbVBrwA_gnfcgDlmZLApuTG88rXVhVrfwCET2kDQ30p6jHZKYNCD3DRkCFhNjZ4mC6Rd2G
}

