sprite $Amazon_EC2_F1_Instance_light_bg [100x100/16z] {
xTa35i0030JHFEV-5wvjPClPch-cVJgUfzU-qb6t7pSmC30yDAynC2mW61YzGpRAwELP1WRd1mO6ryJB3E-btrTfr5t7hudR5oles1qR_c9ZZEeDKnjPfJPC
OzGvQ7YT0qRqUOwXFwxUR61WU9quWtTEtcinC0w4zreChedlDZ3uTuUX_xUDWO7nxQG
}

