sprite $Amazon_EC2_M5a_Instance_light_bg [100x100/16z] {
xTa53iCm44JH5V_xdxZYaRKoswNCbCAlb9ZYhmD0cgxEQ7hTi6731aVpCuQDE12mOGFbeA5ybs73vuSD6xucNZGILwvJjWsqqwQX31bh5RMwWLRyja752EMG
GTj0MJAOCrWrc31OCKY6Cc5GsKZFfP4tRbuAQ1jA3FntbumODW2s34r6_oevUhtILDKGilQ_oaQq33QD63OYOj78woW9jEQWKVwjqvfZHkLISyU8-yQ1wrNT
BzV3mddkUgBRjJPik5rhmzV4_p9iUEpEnlsnRHisRFntNW
}

