sprite $Amazon_EC2_C5n_Instance_light_bg [100x100/16z] {
xTdL0OLG30FGV6R_XPyBHQwsQ8BhmHMd3fynxOaEqzvio90XWwuvZ2433Y5boA29Ys6oDqE6pWyPCdHDZ3TiRmxZP2J7zBaciiie6iHuWnE3KSRYS0V34CdJ
5_oaqQYwHF0enY2LHl6oJCUZFUGgptFc3De5sQanHQPMiJ5CgO4Y0oOR6umr9iYldLu6I1kO1eauWvu6qWPS321XeDneV2u1aeRUESkZzrePClHUAqFNnECR
ClJlJiOU_f_Ba27Z-Ba3
}

