sprite $Amazon_EC2_R5a_Instance_light_bg [100x100/16z] {
xTb5eW9138JXBEl-5twocawWFOt-jS7vnYh8s4T7_mdNApV2zMK30mD3gNaR0oDdQcDWo2N5S7aj0uD-O60m4myRdVkaN4FQCie4msVQi90NCNJCABJQYyyR
kh9bMDrGcRJrE6zScJFw7On6mJjhh-VrVYGQZLMMb6AOI-t5Q_FAROM8tBpRud5LHVADkCPn9NUCK8-xXgKPYhj82jQoqTx3yjcUYNg2KMd2_Boo6XBhkD1p
lYVoknO3Wz-r6Cp4Jp8mE7U7SVxSDWO6ncVd5m
}

