sprite $Amazon_EC2_z1d_Instance_light_bg [100x100/16z] {
xTa54W8n44JHbFVzBuphTgt7ymU78G_PUEWwT0-xRmyywxY1WO6XgD6CWH6drSR0q3kY6j-eoy2WVc1Wq2RkAJIQOKdH3Uc0CPSvBymRCOvTcO4nzySzRhw6
vKGnxDXLRCFhXoeol327NVvzty5wxiIy4OuPJgGq5CFm4cU9UUDu7NGYlk54VCE9UQEtUXxV2FKOyvdpXYSTh-VCEPdNOc0mhyMWJMpVm63l3gE6_NCC38ps
ume
}

