sprite $Amazon_EC2_Spot_Instance_light_bg [100x100/16z] {
xTf7TiD030HHBFl-9_RAkOp2CyYdnDufz7nbYHYLvCgL9BaCJRxbnENNK0GOCt_Zs8Y65-9G8HukjGz98tnzNJLAeWWBzDfbXGc-5FgV1Z1240A2lEg0KCG5
AVdrPy9d2mb7Qfmv8TTRLVU85_U8r_R8lBH7PjTS8PzBDF4NUlFP-z4KmX3xWCSQ6upC3ISGSOCHDW1P6qmmWWl0JHC3a9N112DkED8ynHDZ_hl4uB6HkL5m
tj8e_WIRl5vrAN-cE8sH6nfrZ56tCz8ON54ZDpFgAACsncNaCtHkPr0pypDVqwZpZH93NXgRL-Bp6ZdAoCsC4WDYHjtEo356RcXKOzJ-eM9yFFg0ytO6tTcv
KVymT6Of_C1W90SPZB11Y1kCCA5pKKxJ0XCHDpg42K3SOCI9kS486epuGQ0XanbghIPzi-wDnect7ulknxkt7rDpzVoP_ctt9lXJmRFTnaa60Y9ELEPxNjHJ
eb4crrZiGNut5dkGv7fa8Vizfk7IBVQsFJDWdpFMl_xxSUNA6m
}

