sprite $Amazon_EC2_Instance_with_CloudWatch_light_bg [100x100/16z] {
xTc7RiH028JXLP_tV-7qWkH_5NO2ANUCYXlekuejUzrqz1nOXmrOjumnnXX3fVatnXWrKtkCCHHIPSJyCMEC632ehVgtoyEomT0rrOOejOOuLKOaBcI10GJi
AZJGVLsnPY8JgGu-RXZGOXjCx95cGzyna8XwoeWvDW9c_7OpatYj0YCnDRWgR-Z8a0n3fuRIHexWtsNM0881KYnZMyRAqKn4WGafxAQISqCGszWJZ9GPSemO
mtZVaUZE6l3wkurGscEi4aCRWqPdcn7RT6Ri4UtVY6reRo1nU0qd21fVzXe64iim687pBx0vWvLWuDdSClQZGr3WNCDnu4qProKPX6CO1c8O1c8Od3Q3Qn7n
3Ovh-4X-9lf8s_shOeDZ63woAWrMZ9bePEwtZp7FxiReVROznXXZt7OU0G
}

