sprite $Amazon_EC2_I3_Instance_light_bg [100x100/16z] {
xTcr0SGm04DHbzf_uMC8iunVpK7W1OsXwkYPtlUL7xtlXmmC30nTcc8CZ6jARGmCzNA9qKjU1WRl1mO6PM9COsRjd8n_hZL2B-qPlrYDFc4n-eJ5w1D6GmSC
zRBTa4nbIN_z68QCncyRJtdL_yVtVhnIjY6PhzN_YsGt5D48ViDMNgq9z3bNGhyM0uD-BGPbOfq61dDt6FwvRGmCZBfp1m
}

