sprite $Amazon_EMR_HDFS_Cluster_light_bg [100x100/16z] {
xTb9OaCn309Grjp_m3s0570RFftCMl7Bz3t8U30tt58Whh5c3Fa3ZMkmOR1Xa0s33OCDWsmOVD104k4U8AVmbH53I65a42eZez0PGlyaiSvI0MCGmAcXnz8J
trBcZSFVKY36uEkOp-Qc04TCRHeyCtXAA4GRwr2McDyMXI56sOGT8UaD_LpOHpzcQEJhtrNIqB-v0xpXum40MMCfo1fSumq0PwzyFPl9tsSROvyXvApiZP5X
s4dxFMD6b6GCZ8GDNxCMd1idHNZ7W4h2W8aYlA68YQ1hzB-h_6_U_-_sdy7yNDAV4_jpUtMDog-rCxazWpSqWuoXcPYXcOWnywCCZHJEEA6pcXWcU-QS5Scp
CyZ7Um0UIVGoj9BeoMWbsbkQLR4UMR_Nb-zPDdkl_HvolnVUx-dxkud27SkVk2lw6tTtV-8kzI_VdrzZvXeUoHit7m
}

