sprite $Amazon_Kinesis_Data_Streams_light_bg [150x150/16z] {
xPlP5kii28KPH2Jl_xx_q9KULnRAIHDJp-2-pDLNm2qgtNvzBIqjBIqjBIqjBIqjBIq10AZxAW10awdABqcrBQh1TRMe2034VSqriLEK003TrxA7S89gLAoP
M9v7PT1C8LVOAU9c2hN2Jf4206Jt6IS72m40hLblDBdUaxUCoJd4fWqOrDHEgopmEPoCbQ1PMZmNox1jcWnJpRH0X8Mp3483h8bBCNUY8l0IbQbOfHr50BQ9
M7x96UrSOXEnk975cV4gy19wcsVOHNcERxLZKWZUIcMAoxUjG2iNVXrCzt2XJvKnL76shsOnGPzB4AhmgsIAFxZChmY6WqZqYNHQsoDs9MjGCy9Ho38OZfke
0g4N525eY8X5H5-wbrot9Jiku6OOr95rTO7AkvClRKpQzjsSw16gg7_ATCOBJ2KH3gS2aDWdQiYYSb4L4IOY74HLzpulPJYIvVArJW6epsMPuIXAMP_5AkYv
OfEgR58TOBW4Tc7Os9cm0tCsDJ24ncTttP8PuMCDu09s4NDEmFGubUVo5X2xr7YgAijut7BFM82zN8ee1Box7XFwPMRRV1NfMC1iC5F6jWCayGvbEL75p_Oi
MTWDaFh6mflUUCMDIgxhjY6smu497ecQ224SL6e_uLKxw_mSbJScV44fL7SJVKdg4ePNYkq9ghQ9ezNqk3AgXPOgrXYQUCEpUlPlzXbAbVwUV3_bXSHlOp0C
UqN5qLYQqEF8qU4D8RuuCXw9fGndZiPOtI5kSV4cZtT4wkw0ATg5vUWG8yE4ej5zSq1bS9JUOgBJbq06fwdkFUPPPM8zSV4MPT2v_DqRAw0mIgRv7Goq4rCR
ju9Lq5rozDgk_wdOLqjCnNUENMm_FmpQ7YhQJb7T2DQUEzkStEqUlt-4VaGbLwdqb8VbtK1nEqs55wtK1QhdOIpl1CfvAhcOmduvPeIAjFjy3ht0EuDTV8q5
3fYSXwKFgJQyPbaSCFdhRVgKAW40ZRrnznu64PNVdMMJKRse4NHV13_US7KGbRY6V3vLmSZxR0wLT7ENKIzJsP2A8clLlyx8OCsUjcXdKMdu6bwfGYVuJ-1q
_-9TklMlpaKzGvEARaELkFxJ5QeqV2A5ZsdDLwZovK9lhpqxrh_hP5pduY9znnZCTzZjaxll-c8gl7E0nbgK7ahSZzU8oa-TFZz1PvK_fggDZzqfgevDbHQg
Tgbyg7ZePAPsVBx6DQAg5M13frYniwZJPywGxeJA76il-lOPbNrfEbe_eTAXa-GvCELqVdTEGwVkFUlv6qZzN-nl80SqY_w7VlMsDlN_2b2sfhvniqsj1CR7
k26l0EF_9NJsnUJBL6TUboRy--p4IzmaglZLyZwLNQIANtWdrDNOr_3vMbfQMbfQMbfQMbfQMbhw5m
}

