sprite $Amazon_Elasticsearch_Service_light_bg [150x150/16z] {
xPg9agmm24KXCGly___EOddjiPCnis6izpYrETMBPu0cn8fUX-CuZkCuZkCuZkCuaZg8JeQf0-jSXBhePEvhbGxSnKeF_5zMRkLMWwu_oMhGzUTP2NMP7Qlx
MgK3iwrENZ6VecPOZQUesLRKnQs-CqNDjz83_ugLMt48uLPMZElRM0ajLUzc1UojngjTYvIqKKGtqi3AQBK3PU736v5JYNzf9TzPLoGnDV0sbwU1bT5g9ua-
8GswYU5gLvXsmWhjS1bO6NLmMM0Gi-Y6v4WRommhOLhXh01YsojXTUKhhIh3gKFUXD-rweLMicL9j8l4XrQvoWhfo_ef-Q6rN6KLw9sg9nHw9wx_WhbLn6fo
aEfHzt0MSolPY-fmhv9JAhMNH55WPnNt_2NTUVIeU71Oa4DhAq75XBR3jrxhAzNSwX6g3nFBaUMvugEvLKOLHxmKOHCO4m_0gs9j9QWMEKOghMagyLb1K86M
LX5_85JrgPPAqIC1uJEqIX0fk2aKJrkys5eLvEnZgC9miCssLh8LS3WKyt0JiDXQuJO9r-VvGoSDjbQuBirr7oJyKgioJg2MELRw5IkFbU3wFbQuNcvcXNur
_0tojVsg85Yp-bNRsw58UMPlRzT1R6Jon7MmdHbGMNNkp12RnK-OA0qIo9VFeYeXZFf2kc9kbwT9JxHFk_6mt-DK7O8VGxrkFyWwHfYWTS7UEQ9Q1aJQgDSz
PyWw8DDElSap6KWbQ9a_lq9kobXgqGgjIvxr3Meh4NPbqBAtWbOKxI813o0RBKChQFN39ObsgKRBr0hX84xISK8W6or3AvJEHanLDqgAlNO0BLkhzYaVXpVm
zxaMMrc1J7tuJ4lOp0fafeQGjGwqpAn0JU6Wj5R_IClK2jIILWeiHbgsLg8znbgsLXIBWPR56RsnbXXPZS_9o8bMc7PoYC-qyYmhEjEAqwowMbW-vraHTqk-
JBOYxMdDj-ffvVbMhPOmSliNvsH-zCfHgq2Aqi-iMdxsob6BSRv7xc05BL3-x6Js3ry1bMad_zqfzX--qXwC2bNlXEHtrLyvEOxZE8xZE8xZE8xp2W
}

