sprite $Amazon_EMR_light_bg [150x150/16z] {
xC6n00000C2WV_x04wa20020sRKIvTPX40X62F7_7_mE3zC86okPaMlqZdr7svpR1SE2yZT22E4NiBHrEBKDla2w2AaA3cqLKklHQXOv-GM27PhFQiyfLAE8
EyDqKcAa38fBY4N6mh4isQoCXAUv9PDI-0KvNP8hf9M_vJ-hkGZ-p_PnPVXVHSSTHrp7oRSCL4NgCjrP4JvoCb8s02H-Xd41ZrYgYW-QLKjsw1nob5PAq4CU
AQ9GNzE4NOBZ8DS7Ba2dZGHYaKd8NF093yrM5OuyzHpaebtfmE-txEsKQBxZe0kQugqnLDcXntpXAAZYQBe7wMrYDUxdKDOkNxP0G7ThEOQKRocqoWW7O5Kh
wg1nlnQd7GNcPv8JXE1sLNlKYxMTeZpFIc28ScbkwfWLpmX5hsGItM-HFiNmkhJYjscbsALHb6Wow8srcwRn97-RtI1WlRGlg6EnfE2P_ZPbxDLIHmUnHRsk
-OMwKElXlidmoTZjRQDV209QFESBAMWd0Ir-M-1CihtsoWPJLw2yR-ur4hCLJwcgvMS7caig-SGokAMj3vlqzAVTQ9oJutgfbU08ZLmqprr_-Fd3b9r9tbXt
VKhtA9ElwAITao3JeiVnAPM-R9LsxTfyq0HSGHujMy03IRnNFdJhUPDPFs75FQNI8gziKisZ10HYLWe6P8qUJ_Rbhj65ObP7O9TAeLSsoQPX3YXa5SgAetMD
asewhIHc5TuwA6SJRM_Y_MNmhkhgvhsi109yvYnltHpLkrYfaogVbP-RrueWnpD7VhRV9vRUL1au6D3IgwXsbYgZut2x7WkjDgHqPopjOjzGJQma9uCauMx6
xD-3ha_1WqGFKbdr8thQ8HC51hapUmWvquGA7OQ9tkm9v4rUdXXsY_VaARKL3DvTyoVwndWSUIXv-n4lFn8sHVHkKvI_LVECEyLIDv1UPhNBSfLjBR-OjFAM
rVsRRHtKrhnJ0BgKgkQScEZmn0IJJfTCHhqmUqadSVRsMspsLZgrz0x6zu3C4rwJQh7JS9CgzvC357zoOBLFMLnizdwsRzy608C00CF6vF-BMUbiLEaEUuSY
PTDwPxrQwRJUfzbEQROrs-fepRPcMxEztDzfjjrdurFFrRZW05qA00000W
}

