sprite $Amazon_Redshift_light_bg [150x150/16z] {
xTi7ZgKm381XbpYEVVy3BxFM0AyYa1AYaJ_rhR_If_dVa59AAQMKKaefcLOfHF20YAMgtHGaXF05aWnEQoM23c5fFeQjIVE4wVCgOf6gErM4d_-CZcj25hKl
ouvnJ9SL-CNL_91LXb_5UaKX1DOJeyiGqFf4GH2xEC9TiZ36oVmqY_723b4LVgXVel2ZTXggvXUrJeC52_7B11PzgjGlqtvLrI-h_QhG_2B3VbM0TZcgKrMe
5wUlRnMGNhZIkrO5h7PYxYe2zAt2Jq-6uqS3zgioWHMMsloBLXbX9TQlAYxQ7MGHLVCTKnNPWjOhlMFLmWJXBI9u2yNSkrQ5jeOTGcaU-bO5qq9mW4hCxR2g
q5IO45uWiMZpCBnggrlK-0XigxctwbXM7JDLcwsgOboQCrLjbm1FLCMmuccg57PqbYg6XPW9B7YMAbZ8-d7WH5KnSPfLHzRbn1DLHGohKkJboV2Dm4eckWTb
YvgeAkOGsNocgdNppLHbi2ZtL7r-fmiix8ugMPVpAmG0yl5LXW01xVrQhpTK4QpeOAsFgwgmKm_M-h0gZ2KLYmlVVJsftL3r-guB1NxvJLNR2uf4ROiAvUQg
WAMQmexUKqMn5v-nnjhYyLKC2nJ1rwZrjyTN6Um8mwR5lDvpuzJ7uyfgmTroQkF7Ak0kAfZUFOFU8ed4NZwAQBUjzWWmVtJtoM0lep73AIen6f-pYjzqE-Fd
x_PWzT5LJOGFluGvkCe88FWyLGrMRPegGrYXpL8b-o-xoInL65CN4ucpLArxhy9Yfghj3Tfoh0xM5LhiHS2vzY3pN7lGOCVyappR8ukYYGwYnhyPc4JpwyvP
TK5M_S7l5oM_ZFfLGRq-L7sg2lmeO__oCVWFs_KVRV0E30ATx6e4mRo71X2md9Wxt1uOVHZ15jRE_U0LcNSZi8CivX-OCCAEU5S5dY1HaHzL_Yj424-ATrS9
Jg7gOrIQBYcOq66HcD_1f1322wGIGNz0IYcbb59AAQNq3m
}

