sprite $Amazon_EMR_EMR_Engine_light_bg [100x100/16z] {
xTYr0SKm54FHLsl_WLEQ5P33kgNfV8R4atBEEOTnJpTiwEa7sz2xzMM5AmnSG00lCpPCg0QTqHyVRgH4WHkf_jGcORE1mKmQXMga8xZ12MwCp-WRHryc5K4C
xKLUtCepZM8KCurKCHpFDspeVScmOIFrESE6tnysRDYmyS_VkxZ067U5WKF_1sjjaW5wuMQImPzUrGZXGjfb1hRC4cAJ0KeCFbO4X4nHWHkyc91iwCW3Bhxh
IZmfvvnp2m
}

