sprite $Amazon_Redshift [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kJMVjARbw7mJ0CiA6S_U_tZ4p_6BemDB-C
5Rttc3oHG7VxJIgrb9JeePHogKr_nS919J7z4AVI5CqDI0hJHt4MJBNDqY1z3-QRB7dPeb9g6tgtQGrGEMRYN4LjahQQ6NVv3glGlt9LMoOrKmpigJPO7F-v
VLnBr6FPKNtEebvHsqeozVPL_kcLIc7QtaRULgrPZOwQGVNXkg_oJowL69ZiNIptQBrLnQ3Y-28gNwh4u1giyfMg6Lp5LRvGiQ4f8werwtwu3KgO4DMQHRq6
tZvC5IrKbCGsQudk6QpocIhYja7IoXIPmIgVg-8FvAQVaU8oSLSPhFAfoWf5N9eiNiOmHKNlAeDLFbMPvkUt35L4RKX5wlCRZIpt-IDOvJFLKMLwMqhqDgxw
C6-moYUgdWHi6HTvdOTLFb55hIHQb4hJz_EmokUgI5h9YUabJhaq-MaULlbI5SbHBQNAaGrDvs6LBrNhvlEmoh-fCbZblrIfD9tFmog7LV6undKw3wiSLccc
Utaw3wiSLMMAydGULZccQZJKflEmoY5LwYyKj10HfVayh794TKF5-y0Vvc6LWoenCvE5oc2LVrDbiCeHLL-dj5GPh79esrDhQRRjOx3ADrL2Gx9G6QpoFPKL
Yihwj9oZ6bd5rYexIzNeYBFQ9oexIPMU1bRpfwWqRjv25S4gV_UA_OUrqXsLmIf_jz1bzk5kiYsLmQgHnNIF9xjUDrK6gaPMeYYzVz5dkog3LJvvNJVPzJsL
mIeVxbyrgy_tK3Br150PhFB9wxhdfnf3L0Qh_FKLL2hoZA82gGnH1IlMgGsV_gdGa40gWrN-yBhkkInzjpAcCbZb_UnphVoAYeS6K6MmofM6IgPes3O5LGQh
l3q-N6ah_AooyrNE8wedapjudaexALKRofDjFqsLOtEcxoBELrbSZVcxYFDLDQx6X5NiN5NiEhlFVbMHnSvMQQstFztStMQThD94z_pe6YgbI8FrrofZYhYF
Nq1Lnw_Tgj_wUnNtMzTl97llprN_pfwtyLHUGINkxXBxVdIjQnNz_LwnkYltlOekS0PpZZCO_QNAQCXyx4AFxMDNU1vCWPgmJd_Da5CLVzEVgDPTK-NNLFar
LNvDbP-iQZYhVK-L76QbxwceeQn6tr4LEYeOgmzdM3MFRh7iivHwzWMLKI_97aiIzVGRAbUwn-LpLc6w9_OLbLiY2fZuCib18bO3LUig3N6kqt6jDr5KRIlV
hD1Jd5AfHwtUoYanFLLiCz-k9TgAcsttdpiAmqbh5SHojxgKfQhkZgc21T7Av5UiDr0FKcsmm43L_ytEWG000020883zVTSeWhnMP2ko5TcAR4Ms8bkHhSXM
P2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhG4
}

