sprite $Amazon_Kinesis_Video_Streams_light_bg [150x150/16z] {
xPk9alGe280vWaZU_u4tDULU3SraqYRi_hzVtNtv5IAZnDd_-omMYyLYiLWi5el5OW47wbub0A3TiwpiVswrPh2vLnaEzY96L3Rtgeo9hM8307IlwWXX5IsC
Yi41xqMCySMzZCLJ62TsAmwMZc058OI-bn5Fbi01Mcs-Rx4i5mTBmva5gSqiC5_9QelM5kSGmPZR6WpXWEANWQjIliD8xL0BUsbgiNcjqfnl4ESMmnUefLez
gAQLsTKWhWGTIxtQky451gn5Ap4iyqOmm6ObTIiEbn8K1cmRGulpQWHrOeemfig_nV0tFBmVmZPmNkwzBv2bFnykGB4yO0UqDTtdOt6DU5-Zh36yWBI9JfL3
YrG5O41HBT0D8G29v41VkE0BGyjxvKlEMcGMSy5gQ0LU-6qjK66ynSeNyxX60Ryhwrs5QRALI-gi5cmwFXZAgGWJqHGhjw_BQm5oUw1AzRYOvxM0Db7RxyJO
5qsF1cbDB4tjzc8Et3DzOGWXOX5fEfZbQGBW0XRINIaummGlm4tppwemFc3bYYQuxK3ajX5Ej_AyB3K-iyvCLKI82ETR-O0DSAXLOy992IWYtwYmY6el39aA
mNleG5xsKa_fzYO44xWbQaq8_tjMKcvLFuFNins9Q9E3vhBzySf0zALX-uFanxtIAjMYet4TVeUEMxFat7CEQf-62KySPWpXXw1zu2Jku1TXS87BMkrammpX
0dZryEMwdfcyg9skUTSVKCcPCFM_7ZVr7pU0QLQ7rXy6zuCB3q_aanCzlOz0PnY_R66d94S_i99lDlB3wiAAiijMQ2VAwdvmPOIhLhp7j9UkcXz14KZliUBK
QIZ58-1eviotujnfrB1u1DURIAocDsaogu7OtLP6RgpCQi1sgvMugKkj1610UfjLHzSepQt-dOFtM4cM9x7LWP9hoYLMLpEApEV_EojNRyNcMdLCdl2cLWV6
Bl6dM6doD3oryiqldMRLeYmV4SojVF55csGrf7eGgDDMbbhDlv72TcO6OV8CzdZjsT_vNv3jbjnq6gCKL8RqLfXyMqMRkniomshBSghjkPK9klExivftsr3S
eip_EdFortdopKojsSdajrZRNhFh6yDRwChv26u3CyzAVKoyQpm2kitUD2iEsoRDk_eHTAJuV2j_wpvsVVQKgl4nFLm13vtey__cwCxgiUu7kGcC6ppFTueq
_35ohpxKLSkj2ZkGBiBEgg1RQubLOMSR3YosgdiAaETLmHEJ8XQBnMAnM2mMYyLYiVW3
}

