sprite $Amazon_Kinesis_Data_Firehose_light_bg [150x150/16z] {
xTlPbjis381XB0GXuFqVkDAfAzIYcUFG8mykyDsqsVz3SGazYlzVAQMKKaeffPIYE_DiOATLLLKVgQggggfi4034iw6KLGm0vDa8x3mRXPrvCWOxIRa8CUV4
qfIFa5BkMA0fLo5Qoi5gdim6X-x9ICuiIfbb20T9ERM0B6KMICg72DWzWTZK6pown7omwMdp-q7C9KLuO1t_nXhuAtUSzb-N2PnODW_mnEwlEiZPnG21HBTN
LVgDgWF7U24ymT-e8dYWxW_AJmrnbut_kvqYZ9DS6ywg3XYpxZOTuSHwFaeLmfTLCUlCxwGC0PjQ_8ZAfEeRWsODBtzQfCshOj1k7x20rAJhMCMDu09PNfTP
P_1LCSa7OvMukmeZFDkkGIeC1_-OTSPtgWwcZI2W7RK74I62qqA5Zom6ObOLD7wk3lDkjIgMt9MgDA8_LyMWpQjG5aySvBxvtBmgHDLbAViAE54JjP-f8Y8H
LLy65__-VhPSDTeMwfGHNY9YsQd-NPKSkghi6ZtEh1NM6yBSwhmAlanxerHLiKbHfYfJeLnFC4wO4Ur4LjRWuzZXrTaEy7flqCMTGLNj-Y0-gaAIhlOpUpiI
Ysw-Qduqh5S5v6vBLTFZsRGB4y6aQbWjqzEP5wuIvgDD6hsv1hTOBJ-_NuNO9UPLhpSKYh5J4QQVgZBXz_Qh6AA0Diw1XXzMnLq-48leM4K45_FLOiheopez
zxIkRzwygAdTT1kStZnD9rKnHFSmXXF9ThrJJAfYY6vkucx3wJXKnH3TgCLLn5vD-wWIFNprKpNIwSN-rpxhustur2YkFRzKHKFJS4M49tuxGFM7ZSwajlcJ
3X2wtqxY_-21rPE83K8itvTns3nT5AhdYsBpJFZDjLLV3RUCKKwmuteZvTsfhfvmLd6z5VRn6tJvtpQiDpCb7c2oVO7hxUX4RvBNlmMeggggggggAZN_hb9A
AQMKKaefvHy
}

