sprite $Amazon_EMR_EMR_Engine_MapR_M7_light_bg [100x100/16z] {
xTXNji9030DGVsl_-tszZ8vHSA81KYmwDjpq5djAfzFfTA1pAgCDpOMJDloyTB72CmmyWG0EPXGAhb6esDEdq6KAsk3SBfM4iW5H6Rxr3L116dKYPAUakRvr
CKc4DBo5d8RoaGQFtpI3Gb_7wOmsTDhWj46lYnlQr8tV50tSCR3EGAgXOD2WmJ50hp_lykZpc4N90FY_5mqUCT_0V8DcPv0Mqf3BhZA0LGQgHl14OOC8wjve
W0pw-gP1kZRopvL1tPwXbolVAAqVkJjM6p4OOzqmP4HLf8spxy-lURoB9nWwpp2mwNmmQNCC96FC96Dvzhf661VIdcQWKXL4sK1b019X8BeaXAgX4nDY6pvo
e8llMeazfTFfT3hl
}

