sprite $Amazon_QuickSight_light_bg [150x150/16z] {
xTk7ZbmX38LX31TypVk_Rugdd3HBJZah5FbFJopb4ynjkplx_wggggggggggggggggjHct-4iaRkZrHQgjzJRKvQgdHsTJb9XOokuiTNtNFqQzbHghlZv7wC
QhLt_HZLtHeQfwZwWtE9_wfdg7ofnFRUqtLdgDnY_jlHldI6gcE15C0JLFCqbM-RR6yTiOEWpFUjhfoXSaiRgivhymYLIVisCRfADOb2z-Qgblz_idu79K1H
LBUazgJxoDBXazCsLMMvbyfueEXtVLW3r6aegDA3RPfD_ysTGQckmLKDjxpl2AuCYl_a9RZYZcWBHmFuOrIuVTiJgXzHeFDLk0-0AaPzf6gyJmY6pOnHV1NE
sCDUlriHYgEAKLxl_eiaK5mLK4WZ55yLerO2HLK1jLIQrpM1ugg0UjtwtZk1ugg0mdG2nLK15KvFe4Yg61LEBw2OgXY5wHZ5Lm4LJ0D5LiKeJCSelWgeO1ee
kYf6OJf6yLLtyrOm3HHBbKHX6YWncYg3mdI0Ogk0qcWQA9ugGjtHD514LGw5QQ2OgXGAqq1HLKcKZUODe9YgxFOXe7Yg5EgEK7nLZDhoq4ZpRDDL6THwhP2w
I_cg01KzqUFoHrV5A6pWn9VMTBugG8KVAUAhP4nDe7ojBjPQnSKeFFLHNbTvL7GCAlKOH7hr9cDgZC8M8jbCbOtqfrpk7mPvAfCC2YmCCbKzZ_hsdi4sJOMd
b3Kb-LenNKitegZwUuL6VbysMuLFlvh_zWYLKnGdoL4gwWxoN-rwW0fdXXcS6HBnpw9wYie4gBLFKMqRVxnI_3kPFcspLDnAfJBchAyaBrMfIbMgUkyINMK7
g4v_fzxvLLLLLLLLLLLLLLNr6G
}

