sprite $Amazon_Managed_Streaming_for_Kafka [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4csJXKcQ_QXMp4CGc4uqvZp_k_ROTGwI4ZX7apt
_ke_yLsjhMGj8LtxzZFxpRFMg-J7P7FqHIpKKTkSVH4BLLRVddEiYOWgwx93giirM6q92rNM33TIdhg2XI9B7Wjq_W9r1GjZYYgrQVFz8WjP5gzIMeNIANZ7
1NaMggonXOh-p1qSxIGBLPPj29V86UmCB0jLLj-3NRJAGfKbcvk-X8Nda4kLMYobLI0Fg-COhmUmhM313zUl1ny4Gwl0z6j-uRJE0icA6IyDbLQ1xHStv5XW
MNvfiWsLLe7e5nveF0lH4FtI3PLMWUZd5l3I6Wln4FrSGwcnmB8irNXFP22wlIFpcZpD0ilQ_w_k_UaEMxj4GwLLoFMRgjiEyrH3fLN8dd-cwfEIQAYq2eb-
KtK-iftl3PLMuRNVLCbpUVhstb1f5TxwJTNk62tHK6aLtlkPwlR9zB26B0i4w_RxPt0lKQwXSggOrQsVKysLSGsLPE5prc7zdCevymsLLY7kvrMd-ro-eT8g
XFsyQhngH4EbLGZxUTNDDbHQ1T_FLi2hT1y4eg7IAaH_oQlayGN_7n0iv5aYhefN-NklVCCkac0HAht7VcwlD53PCeODtGCNyN0gTnz7ZrLwHGtd73tFog6s
EOcpoZMSi-TPgNo9-uA81oxyVAooS-cRMJDHSbo5eQX0e2t__xyl6vqGWPzCsva-jK_TAPzi4hTeKgbmWvSlBZYgPG7WIjAVZn8rJ78N5p6jwBUAx0x2Jlp5
nPnTLWnNx071NlmLmPo_QQNV-GJTnKLGom8ak28_RnKUTt7XsJaPe3BZqcI0ikT_XgqqmHjejdnn4M7_ncc3Q_MgFCJ2TaQr6uj_LX3LiY2KxqviJpHCpNSd
rZXYg-YPs39_oqgvNg709yArb59PJhUIcg2HgcxG1ULCAqM_JSOKw2bocXM3Opo363nyabM5HiuP6gGE6WRh4LPa7o3SoIJTDym_xHbC97f3w1b4zp7ljm8S
xSB4x-B3fsN_7j9ekWl2WbLdKDj-7IsYH4uWQOz_Nsk25QihgR2OCM5RWhCVPIeagaAb1NNoiK8XLcKg2M39oaFcAJ2W16R5GLQ9RGGDWZg2qm5MMlj7rQrW
hF6Ny6IrEKgOsjU6ROjN44ctY0R_VnUpMW0LZgtXKD0MK6QE7MoO-Iid6QcvRPCgMrfIteBdMd66Tv1dMX_1pETPQHvCfg4MkY2UPIKm88dNaZGAyX5MCXkN
M5bDkRP7Eor-2wfonTa9YnTcEmzFLwZM4FIBwBMVKRJn4zIEkhHnglglLAzA_iirDXYSUQIixi4YTeVnrUOxvEF7I2qeaoNOHZhZhxPpoldLoNLOzNqmgSS5
rwmSPL9x72MmcnUjE457vd1Gnt0EpmgRmmYDX69p23_6lKxWzo0jJr7XUeNrez7xVnIgLwYvTus-5wDoXVZGxQnzev_df0z-kT7R4D_ezRkDFXWylz6dhj5l
5OmkU6wZr_uRLbtmp4PVuer-T0WZCxy6EtxTwBLhz4wLd6dI_XYOtAT8tsZqpAFWlshq20EgDHOR_UMtZPwtWskD_ZBLMchqVh9kD7gTMysrZCh-Hk-3Aut-
uhHSJxOGmYmsPA7HNvhMYUXk_cjs3WG00000107ixxj64HJPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcHh
}

