sprite $Amazon_CloudSearch_light_bg [150x150/16z] {
xPg9akGW2415Wa3-_t_t9DJQffFHqRHRvQjpfgydueNP_tyMYyLYiLWi5el5Oh4GvaJ4p3gB4264Vm1CdrPZ36V09XzJKWhlWSz4J37an1XoI1ztse8JYMKt
E6qGdFIi58U3ZKlZX2ui7-Yyo6zJxeWOFIKbSEba97iNwfEz1xpVGFR69xIIvPFkjwYDIdbAYlSlGSzefSfEuIUq-4QgN9vbV6xfnK_m5e_bcRJK6cW59dMx
92A_Qct3fBPtKXGAehveyT2aalDPjOJo8G8wiF-ub0e69jQTsHSRt0zmN1-I_r86bykFuekM_X7LOUDFtqIAJcTrpDHnLAYeS7qtBBTyWnK7pQNdimwQL4co
s0hzLjCZM4BQUwb9vqcb5_C8s0Z1uussiFSXdeOgNir448nuv1_zrODUMdgQLNAPn18Es1p1mXjxvheMdNGzuD525TEH0ce9caPs85oFTt41ZxP_LHVEfuMx
zKqYQTQmU8HTkYs1SlfVhKg28u90sYcjJlyBzIs3NaThjEYNUwfObGKsTNKw_CGohGH2vU86zYKCmT3UoPv2zJaXUYCunGxHik2NKf0gapFcQnLrjHAlkRHQ
sLTeJokm-BTRMRIeenMPLBELDorsjFBWDrjvsxfPvNkjTYlkQuK-fpTRURxpDwrIbX1RsmA1FMFbSxixSkENzCmhQsQxbGUyvnWapwHsApcRNkZR-ojjjtAB
ucJsxSD4AhkYVJT43KlMvGxT5__sVKUoRL37CuuTRLetsKIzjdtvSKLQseb-7Zp0FiKho8_CzPcvMQ2xtQMGYtXxfJPKGNkU9RojCJyLfuQFI_m5STTIBMTb
gn2vAbGqgDO7cci5GBf3intrs6AVQTs3DbPCQqnXb3FBUq3jhQEq-6NcK_oQb0rP7AI5hqTuvIrUWkf1fdsGbZPDoGhsgL5QKgsLrxvXZ5OohLefMmTqa1PL
thkBIutKijm0gHYsRZ5SAr35Ooky6mErabzBti3W9QxHMjOjzzd5CTjmZjTIkFCo9mlfS2s3BX_-alnff-UqD0ONsrXsXnEQqkDQtaSEn3zaEYZmf9R162xO
r7xyOIr_-Ai4xUSUrpAqoAEuiUx6PxGCPZ9SgAjMVvPMpj9QMZodbawf5VSfjMGsBR4wu5nQLZETJClkcMRJ4hEQIikiPjDYivfAox9zCYrx574oBRILS2Oj
jSBcPydl43HvXMiIhH0WEs3FeZMFL7c70BpFWc9Mrfa7OKgSAKtEOh5OB1QBnMAnM2mMFm4
}

