sprite $Amazon_Elasticsearch_Service [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIhScidQsvZi9006Q7gdd_vvqbiTmcZS5H
h9ofcxEGh_bR446MUnbfaAfG4JV6kq6yHdKZgxbXDAexMNUgUAigTVb0nJjLwFA9YlzF5IrLKAjegO9QHKiLr2fQgb3Vw_hyYPLAqVLvY9sgkc4kgMYcmYSg
cgWKNPzzB5LenxoZelOMrIwee5PHUukwee9QHULzvP8AQXKjLL2hgBX5NLP1hQBccNPvHAsYfGfg5IrLKAkeKlaGmXMlMiKtLHwI2ogeLRokQYvLlAM2MiM5
QfAr2afLovBLQITfTNjehWrRqfaAEjN5qqvIa-yUA6lQmfsgziwv0Y5riFoiMBvHnJTKoPqaGNAdAk-Pd7RbKAVmoA5UrK15agldKn91p0rRMevxkMOgg5MS
g_nMb0A9mBQHyB3wiGfg5IUgwiKqIDx03K0zKK6jugcgoIgDqy8Fgvoee5Pnh9BbApXD_c6b4nNKAevLpr9Kd4PUD4S0pP-ee5RnHHMb489Qi3A0SgQ2MiLU
rG2qtwXQKYfrj8XjUiQhLJoguhv-6NjAt3jN-zNvurG5jOe7LPEb2K3N8uQknqYTgg1MSLVzbAgT7ONfTMl5kGgVgmg0raqLHHEyt7WaCjhcAdoiselJ-YwU
gkoldj0UWmiLFbH5-Q7nfIb9QaMV8EMRgV2PAiklNsHIGKrRV5kfe5OHG9K5F9OgB3yCoqiLr2hA1XQ8RERbMrvfhO9QnL_J-CNwRQKD5rHGgZQMRAlkxukD
TKK5jOe03kswhXSGzR8AQXL_gt2R2ceLBLLGgtXGYV0s5MvJfJjL-4HLZlrgtHdyTHMKAdzeraMADLS5MnL8nkCqNYgtwEscgagoQul52Mjn3bggCidMEQ9i
_iMTmL8LPMD57bOeBnRGmrRbGF9v5zrP8QpwGhPM5Ld2I68PUU5XhOea-PngpP8BT3LMFJ1ypELvWUMTi6nLaLlBSddDYcvBDLQv9ZlBbHMhk3tLM1KfdVG1
NAAIi0nLCXAVKv5SeL25PQ-2TukzzQnH07QMlKfO4UJiVL6WOrcgX2Nb6XLAK1tBNaK4-T06VTfcSX4Oi6nLP1vyDb5p7BM3dMMlOlLkZm__HluzPtbR5LdS
E7x6QjvE9Ix_snGAwe9bh29R3XqfDm0hbgrAP2K_KXiaSvQj2iDFzjSiMvMBHS4oL_sRzrdjIoeVGhZE2kQgVWHx_8nLlgiY96x6YbzMSLSDMNAX-BQAeZfZ
rU-gnfzLxwm_h6AlUcMLFwHYf-fOyeQ8JfMxk7-Z6JcvnZYN5AfXD2DuOVaGPE3FguIrfoXKtWtYDICuiFmb5FxYIP07mUb88yas71b-WonKp5J2iWfUKr9A
kG9JbJrBaN-QdGC100000440-_kkKGH5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jWO
}

