sprite $Amazon_Kinesis_Data_Analytics_light_bg [150x150/16z] {
xPk7SlGw24OH227q_WzyqvcxiDgCVpkaSDAtM6SG_kAwlZz5KHH5KHH5KHH50K-8UnG109UdhFI7MzKC3lSemHCh0wjATu-oJMmA7G2QUrIiX2cCi2eAJz3A
mCPdzt1BdiAuiKTUiMny3ai8SwKHJnR34qrpYzLZMKekbeJX0Boo40Zdi4DkQFMuXn1iRXFG1azW_32GhXmcM6jxhJPJMulKQwNs_82ujmXUQ9AgDOCqpUok
0N4Ip9RgDMpmk5n0ahGcXZ6l26-qeIcv5PTB6YGMhCChxBm6GfgO5MNufmWCSjwNelsZXSBdZ4Oy4yhLMEyKpC0-v8hQn1bnFwDq4DpGiBESAaUXAbineYoG
tY2W8V8JSiC1Nw0LUprOvNH4PZ47h83qZbTxc0N2r2wnybiASKO1tOlrAKnujbMy_HHdGHSpytB2J8XubbMy_HHdGQCnlsnB0J3sYhC0EukkAvdDUtaaQ6ia
7jV9CRWmZr0c244aPXwMJkUWvDUqc1b4mMDEy7guEQ1YQfTQcLSS0R5RntQLbQ6ZnH6mbnDcnYVEjZ9cRpu2rZTWiebzApUDmcaPcMOTGwjyvZ2rzRrG6OoO
RXK7q_es2DFtci4vgBbkPpW4hpFGGN4-mq7MCVOxLOruIAALk8rEbhbUoB9IRZT2klxFaH6EMrcPp6WPQLQ2RiSltKhHxIIdMsbtHptphUp8zLptcTTQ7JdA
BzJWyoEmjIWVjO8NyBxJ97ZYeLMSQlza9TiCox52tMLOaXMjcE6EgdtUoduUjAATaobzhHLjd2p3ljOgHXgu3Cksily_h7wyVJvTPiL-wlPM0CP5LhEvZUry
AxQvIxRo7ONg-zzPETTBh6ps9BBDifBDsN0RnwrprreD6yXLy6OSur8havf1ePAi7b-HGffXDUDrJwt__JYNM-dsIYVIbMArlIgCrqgnwhkU6Yl7Ik3-5QCm
LuhL_ifCMIbM-wjOnqgmik4rTAMLPILM4--QPaNXpG33N3Eir2B9kwPPYStKhK1FijhVpJ7phD0cq6tevLd14n9QOLb58ttMwW2_pKg_fPLaM-LJ54LH54LH
54LH5Fy1
}

