sprite $Amazon_EMR_EMR_Engine_MapR_M5_light_bg [100x100/16z] {
xTT7LWCm48DXhNN_0xEXo4_uAPDn-lnqjmz8npCrJTCqSTzx6cDe_OF7wFVGgnNlOV0E1FbY1hpJHfxf_t_oAhQ4RFYgi9Uysk1cHaQxXX_XHY2YiJ_ZVmF5
T1ylCdfNSkePjpIMKPupj6KORscCuOtXZQ5VmnsjhTOvPeF1OCNG18i6eQix1lNhptV0ti1FqI3Ni_U6TCfWCaXMZP_5woVVNxvUgK7Une3yKznGGbRhYIM3
Qgp37SEt1qDNou458rolR7NToBSFke6YWSNGOJVaa61OigxG66_zUFwPptTv1sFVFGnUzNhGj3C6pT1E6F7YxHhORihTpU0biu681ZC1ED57V4g4KapXG6sZ
Z-1C7QAlu9cQfccQlW
}

