sprite $Amazon_Athena_light_bg [150x150/16z] {
xPk9jlCg28K3YCXz__UzKtjepOuv4wPT_tAlwGnDyuc0QCXVVugMbfQMbfQMbfQMbfQMbjnKU0iH5xKN4wbiXw9YBqEYxKpo0h3AW84g_ZepaQZQXxHqk78T
bsuXFd9jht8vbuMTf8xlsCgLy-WVPY3rp_1ZBcssatymrMyDGVmAGm7JICxtKRHfKEtkKUe_SCCwoyr_Dco_-xtCTAdou-7852WCfszw5tawrE-SLgPWrTz-
gqwOH3lBEiy55d4P9FoQZjLkQzxXpUIekcf3B4s3SXfCdoFIoNfKSrSV0IXaGgaVkxndEbN3v1ZYAB1KAFwAQoNdkPOV6jw69RgR1AqVkO8cpHzcz0z3iHqE
fDAZXi6myQJv8nXpRmlKZGiCeqbpI7Udmjg1xBosFrpzA2KEAyvVEwla45xGz9nYAZ-0gbyg4X5B4epblFSD9qWKOoaMFvvYB1E2d0DGGrMqgyJrULA0-kxd
FRzuQ9Y5cgdoNQ9gVhHSmLyyasgNd5rv0v5KXqls8wlPyoTm0e8ItwrOUqvAuS4RUCS4qd4-rzmfrAVRENNdUpT9a3vpy8x2KwVGdnrN1eSoReMsFl1iRopA
ZCBwF4O-g-J3mz5OOVFC0AG-cug6HS1O-g3SJPdzCf6EdLXsRcLc_plMmzri77L1cKJbSE0tL8EewoWrZuhW96kiVPpKFhrp4XNwYl8XZt17XL6dlykZzf3s
lkBtNvjfOVxVdHuBeUvjKNeCImf2_AQTGxjvN-u899KyAh0wUcnuIkse58RaOEZVgpnc1UsXNO12v8Db4wXW_4Z9KIg0AIwZmXcDxJrRn2Ui2vf1jQ5qvFsj
EuunhDRvIgeMMCzh3HncNqU5tsooXM0bl99AJu-q232ICmFaQtH_V7J8G3KxY-8IYnCfa4MdhpXel7r0KeCL9sDrndiPh6r3VdT8kM3c11sc1X_EDIJH0X6P
8Ubk1e44KmiVdLqXdtytXs6WGfwxcy1vmB-FIz4I7fb4HL3Be33fXrK1CYc_rv5NenF1BXNs5jdRrF0MqdQKGy5KPVRf1vGlpFg_IjGDX2U-qq-AOFyCCZo4
H2zBFV_WtGrHP32Km9fw0Za-WYGnk2Imff_MXgogy4r5pM552BMtETakjyzJNERX19cI7pq5yC0IC7Q2ulk_CGHzkip0L5bOFtYw59THdgcQ-2-Vn0LMNW3g
_h7LpvvQ1fPdG34OtNdqr1cE0XL7evcT0zzv6gu4K10fcLqMs0bPRD2N2GI0bT-Huhg5k42NnHLOK9t0zXr4scPZjMXVWAuKL7IZpCOQTuNPiDFfKYnKUwv1
EQg61ApSRiFhiJGHAxMBDGtBNzVn6taBMJcpEngxqCwxoSTOTcadEJ8XLkQcmldBNVSrFbgtqG9_rHiAc5tLmULJpqPnRqfgIDOKtkO0BA1AV_E5LUskge9l
lW0MK5tobX2u7c21Nrt_HXLYOGpEV_iC-rGGgy4MBFzDFNhmi5OxNtp4p0Ho--lKe7f-2xLtWu9MCWQe5ye48lIzjRIqjBIqjBIqjBIqjBJq3m
}

