sprite $Amazon_Managed_Streaming_for_Kafka_light_bg [150x150/16z] {
x9T7SiDG3CL-Bxh_WMDAoO3ftUI2IDqPyw1w_9mW288W288W288Ws7EwK-evtSZ3azJAwP6o_KWbo5wqTj8K9rRzEgJswabmSj0JxanPdHnL35H5q8NL52lz
VrXzV0eE9mKXYzQI_mP7kpaz2NtEwkdAi7C2fl9mkCDsCvM_iPgeb78APIy7rjJPbdr3-Z5Fzz6mlT2mRqYorq5DUJrDisx8OVJwG7FKJpTqr8-6pLC_-uRq
cpTEd-kVQVGAHh_-z3uXVujiHqEpVkLGLkFQZePs_R3QgD3Gg1zMLMMhDBJeXzNKy-naq91-M6KqQ6ZJ3wjECfk6zCEAQSmQRlfXnNQwuHsj2WvOuQaRTej-
M5NvUMFHPT0FAwwXDWtffwsERjgmiu2skguMpQGXd_JQQhvkEExGyA5Tyzgk70QXACKIvly_UBhhiUxYQi9Kzcksid2J82Tk1i_lt3CeREURxMQvySD-zLYL
Oy5EnwAU6J_Wcx9tVGr_sEX0F2j-UFkh4WWkikA7-PMfyKFkolpuWM5bKlpm5X1S9FwXFyvzvJzT5SOFRm71HMByaBaoFtx0bOdnG-RA_C0RLwQTpkhvA-Fq
x_63PQ_Cft1hN-ZcCR61cDCfRt3pk9Y8ArrfFX2NcxXuOkm6y1eKoT86r0qHEHs-G0-8ay0lKVg6TB--E6qWyYPs7Xmu4zF-Osn4R7XFr2-Yu1EpHr5ffbbd
WwSd_bXgXqhvKQIpo4IJ8yHYNzvcwte-zF6ZtCJLbf6ujukBsJUHvrfJGleWumNQuxS2V4HLR8-UXKN-WAgyqHbkGP6QnyK9l2llhyrByn3rjMWWpk5cdY0c
u6OMCq5COcsodIQltmi7CGqJEgCM52NnbhaGXJeKLn3Ly_8tX7qurunxdddMKN-YNtjUjxtN1D5keeuwh8awoHvF37LuJXsg3ufJ9qxpn_u42rZEeeButChu
CdiEBkks9GzUedN_66_YYgyQYlEdCulS_jKV6YSKEI1ELWKiiKq0HUnv9gl2naFifqM1ZcS2KzfWNMCYgSN5MLOxPd8Sr55Su-ADckXhekU_RgAlYTx_redU
leYciOdUiYTw_QCd-fheQw8lYg8eYg8eYg8eYiy
}

