sprite $Amazon_Athena [150x150/16z] {
pCv90G0W082mh-jVs0wUK83PRvnFaYN9acH9iYHPaYn9bYHBaYN9acH9iYHPaYn9bYHBaYN9acH9iYHPaYn9bYHhzpo9jRCrQraS2i0x1192t__rzb2bHfVH
ncoV-jTPVUChX823r58-MwZK9Y-mlX6rnOEXAb-oHfPKwNCNbczO8yM2KOh3QfPMZSmmGIcjgRM0AwbwpAgVBQLgL6wyT-LK3rb26wbrkuewdREgULOlsp93
4aQskPIKQfubgwdPH9JNKKsevbdh_z9iChgC5sb2DSVIfQ9gJvHXIwXcMBfUjZrAvqpH3yzCILLx74cm1h3k_sanpFp2fQJgcYMPsSDbGadLk4TPEktX98vZ
RWgTBOmsBliziR_16f1BL9azEr3LIrRBg68MmVJ1eWz2hL-m9AaQOQdIl0bwBPHyLZMYIjVRyqpJtrIctNWPfCplYGE3hB1FoMKHTU5D2yFLQRgqHXGSzten
K4NZkunrn2HQDWaLiZGgAeAnE6TrrU1gEAqQ1u32sM6YqVTbE3cu7icfd2Nd2rRuxo28vtCz5akhXbzRX9BfCmoVsuDOMZNMtRu5DQKsatgkBLssYOpAHqkP
eETCe72REGsMcYLKpe9KGCsn50UBpIoZYbbwHgdMMjRKfZtShl1NkfcbLIDgLEt-eGnnsyi8IqktVoEj6kVvOBWDZSBTvJ-_0CvbzDAgSTeIlUxlKl5IFCsh
8AqQKEhDhzWFe4lOfJj7WS7ItJ-JK25hNxXyyL2cIrsy2glEGxkJRLBbBDdtzB8h7un2XUDWrNqXf5K3gjIhYfiQf6ibg2o5LYg7eNok-a3yt-PZMJLL_Iai
BpV5LUSvAhzNTP-5cw2gmHJIiOLzgo8u8j_5F1scaE56xajLWrefeQSKK1aTLs75NUYPIZtjE2jz-L7bPnka7qpXMhMRLHWBP0YgRLQ5mNy9ZdvTuRZ3fwtg
JcL9LODHFrOi7umbFEl1tYZ0IgbyLc0y_1ZLSULxO546AakfyAnyK1O_Ae1XNcLfrS02nkvL57ivplUrocPKdtCQthxw3rkecNnEh3AZigpAMNey5-pt6eBc
Dgsoj6gSIiLbkETCp20ahHgmqAuVQH5KEtQ6A8b-LSPFzfE2gUIg0Yheed4INNGuoxTOY30Sag6Buah1FDznnexLK8KBaXHt7EmgSPweVhTZPy4qeCfwZrik
3dFC6hDPodt9pJJ0ZWbB47uCyq35Is4jWGgE1mRN72pVopmz8UzOyVB6nOadP6p0SPwfsl0GN37C3_nAmJkl5rK4-pKR1XitxDQ0JAemWkT0J51l9JZpjRGA
GyV1QhitDjX3JqDLiSfUKxLZPNM_fwc_sSuDX5M5TuDahwaCbY5_hY8N3o6nol8gt7KA3DuvfDYhdELF8FCg345ti5PE91Re2XlBbMnlglgs3ZqgZSjlQXKS
17Ql-Y_e6ogSivjNwF6JSDfO7GvUEHM67x5ahVsDLLRUgogZ1opsnsiBIs6elbGXIv1rYU9zrHCELLxLsKuL_s435WRVn14Sd1CggF0QZ1R9BQiw0LZz3TLl
VHu0PRrz1nQKEVPmWb_wHgL1UMzlmoLaDN9KxjtYP3CWErAtAgaEWoy7GF28DRdga6Kj-Cf26Y_QRrdJPmKwhSpFJQZrRrZpsryn_ELwQH8p-uOrVuJnIVGS
YWW-SFs6DN8iJs-xCsXfOfuyQyopi6_5iJTOunch_Grhp4QNIUgliNf6XUdRyyu7B86-1LyA9bGOutNTpxAqBAYOfLaL5jUa2qqnYvCgZ1L_hFv_M5AsIt0M
d7HUKE6-p6834dNN6fUylgV2UrDgQa5RPVWA15Zlg33B-SdxUTCbub__kWbOBwemKZwtWSSrm4hKLMB0eh1SjDFtro32E1QLfZTTtc-0v2qLnhHn8VUK9dg_
-R2eSgAtlnbaGL-zoh_-6HQYKFMdhE9p3IXG_IdBbDTz0GAgFsRzfzav6000060W173-lbFOimZwHBOYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROY
Mv6jo5PaAx8LsOfi3G
}

