sprite $Amazon_Kinesis_light_bg [150x150/16z] {
xPlNUZOh24Of8iBztszwuYwCNygCp07hxA-p7iNN6hy_HL4KHL4KHL4KHG4lgFyNWHTkPzK0W6vdHT-sAYi60FGy400akzh3lkBOoZmD2VjAuONk6SplZw3S
aiizx49ExiBu-ttAvdMXX6CJrDF0uyP2osqiZcNPqw0m1WRaQWq8qq6IjIIk8KxMmb3B45uXynmCLbeuqaehrc9uGpo73glQ0jHCBHZ1xsTMLp_eh87m3gTu
wT771JvWzTtCLb6FY_u5xEQxCJgg8IL8Qx3PMH9vvOafmb54ASE4PVX6h1sNa0d2lypKjp48PZ_63JQXTebQr14TuGCUVYWsmLUtK-NGugfVPe4sX00aQYAY
_yNyfq2iPV9Wo5be5gF-KmuNAjRnOHQeC5vYjTgwAy64Zs9zg32TRBMUUAqXJB0jIiHKHPY8ph0AGdCvv91bx9kIiViZiGcng6qAyo0quooORlqwESLlJRlM
6KA8M4IwVk1d8J0BUlY2qOCeE3aPuj34fhv4XUbYgtWzy7YWcKeZlD8g7ceKZBCufMPCdMyrPva9pWX891vfE2CWX_L2XKLKXwTXAWJ7q0loYavienh2tr4_
7-t2T3Shqow4gLRhuigtMWeX4R6yq7LozU1KmNZWlMbOUehExTwuKR1Jw-evnBCpjZuyVNRk66ncabSoWi76BtdLrp5GIbuX3rhlSXxl9kYV4xMTkfKWzL_i
lCQr9xHZsKYRbwZXZSXwHwy-kT9ALXlh2Qx6mZZvz0F7jqwAPEj94TlZ3IAhxJrLOx_X2IG_S4Bv_Mcjdq0OzVgzfSwhofvBa_WM86UfOorqYdDYRBzTicKp
pUJQG8Dtclb_w1GSS6t1SCw9XtdQXczb79ro6yqncNH9JulRSBlVom4npvBIwFVZ-iz_aKBccLBne5JFOC0D7s0PhgIQvy2hckgUWwvU6tPF0iElZrofldZ5
AdTyyKkUsbIoS4s1mizhRlzP74cSsrJz-2SKsDFWWv_co7zpt-8Mz3pYg9JPWcd5hg4LUHfwNokxczMuPLjvWjKTAOgYA8gYA8gYA8fd
}

