sprite $Analytics_light_bg [200x200/16z] {
xTrLUkGm44NXacMIXlQ_sd1oXr6kzlMSyveq_AtFJF4_HaIVJfulGIbtX79NA7U6CcUeKp1mg4H6liDnONqznwVREN0e4mUEVkf-wFXq8GSE73XmuC210mSE
73XmuC210mSE73XmuC210mSE73XmuC210yTUOqXrlwbZYM4j2Ou4XY3vZXP3QxTor7YeRgt_OsrxVgTREKf4J7r8KqIKV8VUSHlZs7xrkJXmuC210qUenTkX
SE0OEPrNUuSO_euQzWunghL3Z6xi46FfnWunrcxj4CFQ8OPoTBH936D7As8uETeF62OEJGdp3nWc3atGfVs0uU0GG_yWXfD3Z8ZvAuQBGumfdYgjYs7Z4AFs
lSHJcnW-3Z5wRpMU4iF88SP3QpmbXeb3Z9Vs8eQJGuoNMXN3no66MiiqYM7W4CDw_wuOrWunh1rYM3l4i7Q8OUwOnR1sJ69uEyHmTypz0ew-Deuxuy21uoVX
mD6sb-AXPHlI4WzjBxKKnng7jsOuIXnUoN1CSNXJXcE9mriI7DhIEAAguJZSqVIRZKnZtOvtQ6OV-tZ6hYDO6Ow-wD3Vo5hHG2SuD8aaJ1m37AcJY2QEJ4VV
ug2sdkheIyAI8yFHfuG5UOQZrHXURLoNYaCf73XmuC210mSE73XmuC210mSE73XmuC210mSE73XmuC21mo0SF8yU1mwVhkU8opa2noaO2iSf60h7AHZAdQ7S
5SfGuKw9Z8Zk0G
}

