sprite $AWS_Lake_Formation_light_bg [150x150/16z] {
xC6n00000C2WV_x04wa20000PjzCzvndGIWUC8Zq_kztbYHdi8zD9zESoRkUJtRvsR-0YD6orMHQDF-jg6JQrFvEL1Fa_rCTeRB_RVL4KNIH_wse2bZQtubA
mU9rQqXqblH5yTTHtPelMjztApfrqc9-BPMEVYlJ8wcrwwW4L5KNbRZLQKTYSQq7RuvskSMqh-ANKXdQ-fczT3R4kRkPJYdzRQuPlnJtL0_yrAnSmnLkHJwq
MkkJIdIXgjuUVhygkERu7QAQGq-gIHQgXMtsXui1FzkEdQSyFOXYInvo6Sn5XvBfATK4sRCX2TcBbd6hirdr3qKaIaBV7iebwrR-rDDFeCutgznjtgM2kVXO
O-xMJKCk_wwBogrWZkb9vBHVi9OUWchFfmmP2oCjEt2YYhd_FLQmfs51QMURglkIrXqp_m2M17jRwYzyE60L6jDpSzZH7slqYJZlXaux7Y_E3gtOTPF204V7
fdGVxlXFVnYV74LikTI6JrQdO0d24Coi0lj3SUTkeMK6Y_pzmN_sPSoMgu5qs7PlMkEOAeiNVUnNy9NEW9uO4lVn6RGaMc6NmN-jMoojAyWyr-NonL5fnfBL
88CFCzQqMt_wjaoGjhupLYbJktmvvjRfUtdVcvCgcM5YPmu3LId9KBCfbbJuRk74-ZpcyTvqssx2qbq1H8kRIqyrK-BTq4k238YpvVCPiuOQUhQwVjviRdUZ
h0m7ok2q4tbQ62xCgPm1dcPxrVYC1R2bvM3_rzV_DXZvzCYmWlY9R4X8fFg7exIZEX6foWihKAbPEK5bvzCxWY2fKcT2zNomn_r08JbLWvocsjbADuBzQJ7W
itweM9mgGkmaLSwNB7zH0xyc9LFXdNoxL-kEJ3pRuUwj_ygrLFB7skrTbT0xZqtbPWegCRDuk645IHcMT5-QLAeicjIG77mukPV8UjtwHtt9pQH2fqdLBqPU
9gYOP27QlRsrPtQquzTgeENvnOEIE4a5LtICC93Z9-u_wjYaPBj7RciMhRpSZdYPc-G-BwbqhT4HKXby6P4b6Bcz8L3pTQhqHbLhIFr8_56BuZ2bML6rbdrI
QuQG2Qe4-vFMh7I6CzPMKk68m9R6AczPEnANgGIjl2NjI7YxfdCZc-d7LPozCq7KlRCpNCZl3_cIUOH6wYPOK44QPCDCfiXO9t9AD5RGZYSgqLZ6Es4Ich62
U3ZXkn4Q-g66MaOLwRQeQjsRESuyUVOztZhCrRs9vhIesZy4p6FR_8ubu3ZJWdWald-ovvBxhveNYABib8LANbD3XdduenE9uQI9wSDwXgh2VqJPsESAMYT8
uBhS1ILLnXrLOmHl6wcDHJv_qFNhrboOW2gX2ejc_rA9UxQyTNTi0oGU2OMWucEzd0CTK7p5ozj0orj7V0tx-6D2uC79V2U-q7y-r_ejXNwTHHuKha5gN733
LWv6Lxtehpl-WvkyFZny-qqlmbxnz7jLyg7L1V83LyNpEQdu1KW8OQXOsx-oZObnAHSanQpwfymA_7On4xXa-aPoDHDYX_7t1BwQAUKl9dorQaLrmz5YbK34
qtjxS2030000CCZV-XvVzGG00001
}

