sprite $AWS_Lake_Formation [150x150/16z] {
pCv10K1G040nJgn_O101_BS4yzpwFicMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBOtMyzKoJvUTLZjHRro5eG2CMBJTzt_V
ctXmZfkO6bJdpERf-dz868XRlyToMmwb7laQozTPQLvbOPL_KsLXbGTKRLPbOPM7n-fRB9zcbRo5LrKMLla4wcMPLiLPFilABqlh5wJsYWe_epUnVC-yokHV
R8kqajCXkLJ-CyjVcL1br0s5FKkkyYUM8zSgsbKjRobgBGr2Fs5XbSzMq2Jr5DCqJkOeou-PLTNKaysUvMeYQiymjve7he3gaWM9_bIfVKHQFdD5LMEMIYlq
I7f6dYhAcwg9d7uyO5NNMJx1Oamqg19jgirM-GnMKWyli_oI1H9Kg23r6NVgsZ-khhByYaNfLrNQKqyBcT-MWR3ApviyvLnhPNd451IWxJHCFzVCiChFLFa9
EjHcInEkTQ12UmLOVi7Yz9RSazv2DafBMze2owzO9Sr5RHXP7Ys_PEKfbDWlKLfa-ILBU-7EDPG9C_0sbe_orl1bAyKZjOVx5aimywzOypS8ds3Hk4HuvnIh
M4zK1LOVZbyMxMpNaJuHUy8giEgmTGJpxohySrQ4LNvTfepLTv3Xi4PLOF6WXcrKlt4ByWpBvrZbj8RQwzUNeBsgZylMh-iZEkhFW0gibfeP-kUzVkqrc8At
qe5TX_qPLla_4B_N2dM5htG9X0rtATmUz9hbbscR2kE2uDiNBC2wRrsmBkUd0yfcI5X5_mO4FVJHQ_cm_XolAUt9ScXuiaE2AjudJaEHtdetNOUFWyLsI4or
ZSZdnCOzhAjAWQ7XabfNzNosPqI5MTHh-BbcMpzDD9HB2uvTGbs5JzChrbIlgvkzrL0EnBgVlBYMsgGV26kjJVSR61OQzFilh9a2ahk_5GtbN0sTh0RBglH8
yqVGu8Vw1T8mniYYQdFW9TtIHmYt-fMWz7p1ccchmvhOUr_G7SivtnKjgVApK0vMFgWibep66hBcsggdVybQonzKTR2nNLI9WvKJOh7mw7CLcMfsf0555eiE
xobBgiy523Cm4gY6hEifIFuZNFCZfQb5G-DJxRmg-p7IMkFjBuicZrMshi9RskdabaVqyrhbaUERVrFPxIfwMxlbi4iu5kzNbQshkBMygwYrTd9WXQGBjI_f
mFwkiaLLtvrtrJCa1nJXVi7OnkEbljsD2Wwofj84LKzvcN37A9NmB0TlplsXHRKhbQrLa5wRS5nX6PaBwRNATE8eyNvZB-w2s_jHTR1HmVMHB6OJ-usbUpll
ct52_Q3AQa8x1CD7R9hJuMJOSN6LOXt4_z5K2E_FARdcN5f_OydxmnIfEVSFaQ1gl6TmexI7_OOzGqn5s5yTRm_TUiF-AgGgc8G_UfxKFSZAAFumq_jsX2aL
Sm-oC0NZAkt56YRMLX9MeTshtyV2OXrNuUmSPurt5d6Le8IZH0wfSHLAMFmsrjoPRVBrgxjOYaNXJoh5GNMSjLwNi0h96AmuQ_1INrp5CuFb2qFLxb0vpGoM
JtSLsIqg6Kv3ouze7zASSpty222F9Y3_NONEab5n-JXNqJrbiDXakqcbwRE6s6oHuMCQXkHafk7DTwYy9cnea7qxJEBEU2LRIx_cisTHrMvJ6PtCmzKV9wXe
zHjKg0-7LNZ0UviAXoxzK36dFRIN3gSW6JmClqlb1IoeYhft2pLtbumdN9Ls5L35RbOPlRD4S2NxsrNaHT5t5DczAh34BsCVOQ1kLhdr-RxEQccBVKFbhtFy
8gitddn3XIAIhh2KKBvlgF0GeDaqgwOjsUvN8VsR4C-ncF03abzKkRmUurwnO4fitrMXYedO_9V0L6mvlXv9Uuhu85mIyDzK8TOIO4tzBTew2IlVjrLm8LHQ
Otc4MokK49Y-h8ABqaMeMJGUZvIH1prdiVpdVucsV2RAQBQW2gnWb5l9kNDoQQn-J4m5rfSILFtVx1m8000000W2sDztZI88R4Ms8bkHhSXMP2ko5TcAR4Ms
8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR0q
}

