sprite $AWS_Glue_Data_Catalog_light_bg [100x100/16z] {
xTf55WCn40DHhNN_-uOPDD1jFuDg5VuPHbpY8m1WOhZ7yWR7Cl3w70bz6S0G1iA63UugODZmlElbOqJ3ouSD_YpD87LXWwkA65pTReCRoZ3meqG3ZnGKCoY9
98ChPkhcfla-1CqPkn24ZNyQ08ICTqJFkcZNq8Xujuo1eA4HfXgAY1aQIJSK4JV0IvKDJQmm199dQ4GJ3HaAqKHRXa84qPmX4K6qPcX44EqP6j54-mRU3NHh
uDN0B8QDI_KD6refVHwEmvnFjE5p-hvkOCFphfSFZcAGwSQ8zosXXe6onX4
}

