sprite $AWS_Data_Pipeline_light_bg [150x150/16z] {
xTe7ZYGX38LX4mpOzp_mgXYsXUI9MA8hl6_Z9EklN1tqgW0000000000G3Z6c8hecHJw4AgUHwQNecTHQTBq78GEWJdqV_KS-8X9HrxFgdeAuRM6PFIzIqiz
eA-NQIVFFN3--avCGwwr_r-c_RuUdnlIxgZlxS-gz0T5DuaV-qm9z1skUT-POZxIlkbY-R-bwyODAB_kPzs2VxzTudchdhW5xTxEz2L-VRtkFJFKHD-8rPmP
pdGMVUWLnsRbSS-Wm_W_kwFyTpAsIcNw-blOAkC9LLAuA-AkiXCNIQIN9BugEp6kTJMQXUQhiXEfBLvNPi5PPIUIh9wIuY7GeNYhyZnnyReTfitMmZ7EMqNp
nCLBvBZSJrS-PvNOYMjLCarqLrKpSR5g_iZFJ7nY5QeCTIBZ6LMesh-temfLwdJ5AbIX2bMeGXMgK8KgLA4ALQX2bH-gK8LZ4C-BeWhF8T-r2bNDl4hiqEn4
MQfAEYJlcyxinBNbx3yMkOlZhLQ6Rs9olqtEhcx_nBem97___Zp_HDOLRAAys1dLIOu3YnhkYQS200000000003_
}

