sprite $AWS_Glue [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kJ7JjHSXI6WG0AHhvw__zxzuBQTQlY8kv0
cJrwpjnlHa9ASfd1bbynOarLBKtgfopSgD9Pm9sgAgjmdQhzUKHMuKvLbLMuKrLb5UvKLLc5YxkT8wjmfwhAAdmoopigdGMLnGglz95L-41r7bc5ErLLLa6U
15UpGBbJLMKLxbHLMOKxLLLMGUtspdJWo2e8glUFIrc5ErLLLa7OE1sLoeB8qey0MOLhL3eB8YldQ1P2M9SZBrIbg2mCiqgomtAagqhB4eAbCix262iRWrZb
JiTbpxgbGHP6M8b8fofhJbePOM60jR5Z3PkPfRp7g_prrymiLOKUQjqivJTcM4bj2wwL8glmOfglbkfOIjfUpbLPXJjLLLRXTGK3LR3loMq5G_LHLSnQVRS7
Cuiv-qGp2y5VkmoCKmomol91oiYKnmWhwgXONqPMmTVGR0llOi9cHatb8wlWQtYiPwFrp0qNp6oVhCNLpqTMmSt9hGua73Er6ra5LyFyFYeTOtsCXK5MfaSv
JNddhv1Lu1hQ2MRmsfAAMSj03JFDptva5GOwPRmB5HMpjhThIADgX0M1nHEedqnN7651OCKt_mM1LirPP1M67exnvv5LeCNJ3wqQWGM95NdnwFNZo2eqXtmI
Lqq_iWfdDUHXgx4m7bebsghfHrQ1nxQ-QleiA3bvya1cYGKf_SN3JmvL5hJGukcicgf6Lg5pxDFSq5bGqvcJD6FbG8xVANxLp571xL-_QYQfyBg1qa6TfG8j
7bur4rLmZKrZR9uADCHfvCzKmIb8EKy5euhHgOcgIWtlwpTBXUHLwGagU5Nz0rN_LN5_jp4-I4LvYig_tVyCLM5LUOOA9ORbI8YbpbMnB7yFYIQgEFMHAanN
-Tb0y_GFLlrNuPagF5E5oQhIh43UqskPfrgQ-DFpL5jVjSrJnT-Aw4_FKo4rf3rfRxM4YIhaeruuOllf362AYW_3jG90tVOJ1G0mIzL8bWBKLWXWZeghbegh
9Z1JXRGqYMWoJyMl9n9m0UiBhaXT3rI1YwYwYBKrVKuHLPwbptchU159DS0I8hA-DJi70W0000220FRtNQC8Ycn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGh
iXNPYcn5jY9RaQt8LcGhiXNP6W
}

