sprite $AWS_Data_Pipeline [150x150/16z] {
xDU5bkGW58HXac1Lx_--8tJ7nxZ0RgtyuzBtV8SusilzWoGBaYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGBaYn8iY39WYGB
aYnAiYZ9eYIBVLWvp6-5t8d5BgpW7asn3uizMDvjXIuiTc15ToZrOB6TbOjcydugNt7Fh6BZJhK0o8KLEx3Opfgs5SghhvL56olDxu0v0S1X9_ShC2tbxz78
uY73GUTJAXim7_Rx66FvtNdXp2fMexxEpgA1bLn5mSAYWVNSfyBq9ST7VpbJLAZgMRcW0E0Bby_hbeu65kjPQTszV-Rtg6UndhKT_jytNrGmgpXI1REA0xPW
9OlLhFMwylLvo-EmjrUpQ63DXPNIuhveZkkPuPfPnH5dqIspYXslE0OMsrZ-US-0qlPzEA0iBDfOQNdiM_XOXRpToPXODB6EtLK_oQpYI1NCAkOOtlCnzrAb
u4iXmQZAy-LGQbOT9yx9fChks9JRLScTIWOLtBcfMPNT9OCgFDRvlQby6rjL_ZhHererbSr6Sdtyd5jLPSNJOMDEGAsgB0_VMv-e6bNvjE3hH8CgSsMrgbP7
FXa1e5v5hYpNAU3cDwiuKWMpYYDLq5IXHdKDZNqnKLC5JHNCAevKGMzlBscgeAc2fWeM5KimzxqAPXL7gc1MSQGAPXL7gc1MSQGAPXL7gc1MSQGAPXL7gc1M
SQGAPXKrLTHKKLD5JHKrLTHKKLD5JHKrLTHKKLD5JHKrLTHKyRUfslklklTVnMyJEmRNngjkiP7bBlqw5JLLr5InGlN_VAMZ-g_AV9OsetsNBpFIwQTiKYry
jZZd9ZQooaGyMqnhLI1k3gNv_NlFHjPZeY_DXLYlIkuIsCYwJKprAdftAfAjhCj43uEAyO9gPmLtAC2a8lpyB83imShxn0oZgZqOuskpSo00000080XWVzyr
YY2o5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bi3
}

