sprite $AWS_Glue_Crawlers_light_bg [100x100/16z] {
xTT7SaCn30DGh77_-wPtG0ujKAd4vXTovgM879ldWnzeZ040JtUz6METCSQOVQMPlPkVjVzeZ3766FtvMSOO-RdYOowyYGsAmMC6tPlS6AF_V_uppwv7p9kZ
1WyP19yZncCY0tJ13p0kvySOQ33SP2_79J1e3okbz5t6-bpvEVk0IwdJ844Q0vi6hC431Zyns67G41yhkDPGXElaXl-nfO9DGv5tVQdXaVKa8pBym4bXor34
z0a1LcD_N5X3sjeDz1gm1Z93xzHmRVi6QiREzsqQmpzoto1OCcYCEcADPLU0G0pRTTx0Lguoi9ah30Gf61uOWuyvQF0bPmm_r6mpA8Aisnm1wD9Y-C_gfBmF
1Csoq4OKQY5HA8T4eMEJa1bmvpepFjpMM-g6t2iXBT4EiGIJlULsuPf0rxmhIZI6FcXDG4G8sdDQK0Osjm
}

