sprite $AWS_Glue_light_bg [150x150/16z] {
xPg9RZCn28HziHZU_tt_mxqfbRogA4urNvjxZr46CqvY_Nq000000000001KNY4zXlAEHrK5LUiMgg0AOp2bb-UhiYeybQWZz7AeGY_tUrY-AlyvgB9kFM0F
Wwh9HDHQg-KPHvM8_XZ2jBGO75LSIkl4yThcgCN7gVQhF54xQo2y96shel86YSOWlNoWjav4_8oZgd_OUce4RoUfdPWtUfWmKw-lUsa4ydJimN9pF-vbSQQg
Q0SRNHlQZ8DDGv1ggxsDLUuMMWtMRXqs2CitaFXvmdr8urYk3EgjRD8wZNMhWSnNCuIPQBp5iocujWhkpNQ9d-jrlK4t_iLvoBeDXxHr_onohvjCZMQiWl_6
re5DQtxZdGtqCAGABJ6ZoexOU0zblxlz3BJPhLS2N1gAFHtT5v_leRzHGl0aH8qtvDEZnXzUDvjjUl2C0FzsOvUpeyO_xntD2S6J5ZL-FMT7pRw7MVxPuCdt
psPATjJu-RkTtPd1SpbIKu8dEshymlRRMBg7MLE5ZS3BZ1f_yc0UfIEVVekhelcmLSLw0bQLFg0ggA9LJ9CEKcNG8x1Vz-iHpFA1gMSWrCepZKGFGlWVKny8
W3KVK0LLwSpwrOgKEi-OBJYFa-XVg-g7h2QtZ_EuFacudahjqapO-3NAWZKNgU_McqZF7e1shTWq2hCmhbtJk9dCPHV47FTvuj9K_ALPKqz2-Z5rRlly4Frr
000000000000Vm4
}

