sprite $Amazon_Kinesis [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kJLZl0cbE5mJ1C01AI_I_uSgTdgjelE7Z8
ku5vZa8AzbUlD1AzLzFe1IjUbJMSPMkg35G1BBD8bRvMsQgAD9nb7ejIIirPxU4i-xBGKobOrSDPvh4gV5UIHasZMUQn62-iDCeQpJANbU0hp6dKerdciWfS
s0ompxrM6Ln25UxD9C4iEuA_t-73eXxBibFuPK5irb2MdKChc-6RJIMKPHEM9BY6QZpBPgoQu2WjuIoRiWYpwCFAFOnbKrPFCnP95ClcB4cpbvXg4CiUM3nd
aOImx3TM4Z1DNwskjohCQdfBAFsfzEqi-vc5Zu2Vicnc6Guy5J3cU_cwgFMTBFk5fTbRGvBJjyBxMEQ5NrPLu5g7lLOPMDlFhfIRR62PdxEsYVLUhvGMPQzL
Xfy97kbSqgLS7sZlLEXMpVHt1OaFEw9SAxFYNgb80KlhyOlerwHI0b4UlDhuthegOPRMXotN6SbmlAvAr25BcHvdWRH2CQeHOvPoJcTOLvXmBJb0bOeUhCai
eChgrfdhu6K0P7sZ6ZN0WbkEIXDTRr7LwRlN80lFWZneVGFBt8vXtjGFxRXSwW8Eg_m434rGvv9W-S-OaX6F5bWshPqMTDT9meNISkonR9wsT8A9JfDMyXkL
OjNSHUceF9uvkzIQQKsbM3NljcuoU6O09stmHdCLPjbFALEwHALorur1rNDWftriqWDOjf9xK2crYiW-bYtrsMWv-ULH_JyvwkiiM-ixDz4sMuyzbYq6JYhR
LFfQPHTLfWqgmB8thCvWSUrGwLkLp42KSovrn79kUISkYWXll0z3jxIcSgvx4lBNRYz9kR9eK3-gv4AYojtqCP5sN2ASs6FPOqmNaTgdJISPtAEgqVdYPqUR
JdsuNvzJORLh-8GSh-hvkENOlwtS9aOhk_M7gqGMm_atBpo-DgYEBxGB8upAdW7sSACdCI_tHX-kQkRKwrN4VJAutAyVyaP5tN2SvvSnVFxQeofgA6qhNzLs
gufZEfDiv7qF2L6L1zCnmvv5T1rSydArFuzwiQFfbsrasAcIlwRMx-DqTjI9L6dzQzAdEG50CIeXroG5Vr6ELnt_4mTc5_p05QzIylvDbCDKkuBYLFtxyi1H
vnXT2WfKSVgKrVrgMhgDubGOXH_KF-i_KeLHOhSOhFyGbOyYjLi5hlyu5KRXJSdWq1olwbDKLZ14ubLACrGrLBogpDOK6ovQ9Ud_EXvJR5x1AeA_tWzK6Ejf
_nLiRMQHhAT7fT2QRLwSYi4p0LPSc2h3dnTWHGMf58-a0gom61N3gM1W1mImfcTYmYDCB9ertO4LFq7xiG0L7fKDF46_69L0LRPmbZdrcIgSzL-pyr708000
GEpPGlpxnG1xNXJ4sceujxhUOcNrFxUwthBKkh2wteBnMMTMoPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMv8joPPaIx8bsP9iIROaMvAj2G
}

