sprite $Amazon_Redshift_dark_bg [150x150/16z] {
xPlPZXqX34GVATl5_tzkLcGHAqDwa4oJaS_hBFTSkzXwQL-4eYYAeYYAeYYAee2ech5FqCnKy9QG6li2ckAq4ViZg3YjT94OBFJ9L0LmF6aJ9kUSQAjCGsOr
Gyj3LqPhCsrPSACZOlqtHAOK5NkZWubIjfN6D2tfFw2qBOJz1v9Jglri8AbOOI1j3TySAxHja6SbRHl9isBRXcbM-t47Uw9LfsnE35bM0yFE99fcvL0swfHe
HI-Oe3q0ucLYdbLJz-hKOBRSO6bBj6g81neL8EX0DFuMMgBL79G8mxuun33Hofl3JvqbqgqSKUl_m5IQasxbGFIlRQEVdb-mSl0J6ISmjpbejKzPhG7kil9v
ZNALbVM1NMHbtR5hhAHFo0rMNYeT1owxnMf83QsRhE3dmB9QuN6oMwnSnaJighIZJ-0MgwRTqOjM79saxh4IFzxSjZhpjlqLl7ddhG1W4IkyO3NEzzIFhg9P
Uy6AVS0FiYulM5btR97rarPnNxV8-b4h3Xk9FOGDLPotYliwHqFQpbl1kqL5a7gdWnudcQ_-nRt2-LpvlYvYWFNpyvNBK8GzCBcUjqAVK6De75vQSUJFwGgY
Z5PlhZYKgO1lTj0DI9CsOM-ctGMmFaMSjuhLk68MLQ_6-XHnVXRbnpVU3Esq5SOz0BdeQYtCTmNtM85zGDnZnUxm3YiVOsO-pgwmucWTV11UO1LsUxTOXRtA
VrUhofNEjxwrvgkykJr_7JJSTIyLQgQe-yvbjK5PVS7dHQrjOpbMz69jbufPRoTepX_lm-sdQv7uCW0srkHmfJi3tonGssEKuSkaQBaO7hx7aIqLdyga2TRF
i3gKbeXtn27DL2RKZF5tjAKZx9-2qiuWv4EZKqenE94Ok_D0r4W66z8qIUWyHL4KHL4KHL4KHV4T
}

