sprite $Amazon_CloudSearch_Search_Documents_dark_bg [100x100/16z] {
xTT5biH03C1GxtJ_4mysXrr-GMdRy8C5aSuegDZGY7JR6neQBEx8XeRln_O6K6a0iuwW-dJuhs7IxVvsmA32OCA0LWEc3TeCPXcq6Cmq89B1f14vf4l4YD51
aiIe4T5kHAnlh7-jEjzQrAnx_YpxVW0hleFhZoNhZubHq8GH9OqQ4PN8gci6rt3kezpZQ6WubcWuNcaubcWubXp9q70iqN0iqT1eAs5evB9l
}

