sprite $Amazon_Kinesis_Data_Streams [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kJE7jTZbo5WG2Ck0afx_--vqmgNJCkX0pA
kj8_zyQtWDiGoohf__3qgpMbb4EivrMFizHJYQDwbANwf4h2Adra1P6mIfUgxgWUPUcAbLDATVhLXeLzbgLWMRD2qwyo5lPPbgvOFVsVOIviaQTP2fOvVfj-
jG3xA4kNhB9UmYeFitJ9wlPJI979ah1AhV59J6oMPrcwPdLxiJ9--K6MEYmoQs2aLzgZB7LOdCpExC-pr6FLP6wjyZXBNHQXD2rMUOwbBekJnwBn54jzLdTP
gJt4qYqMMI_lLp8_mj9D5bjFuYjbFC3I7PRvxXdvnrNFN56LpIh64J0qNn6L_IJQgoW5hjpYB5_bzvOzNPmJKldViNIFLJ6qvw9jM41bifX-Hkxp42MzKzhu
1onTnsmeszKelKCxie3APZ6jNS8bNP9hvpXhJR8FpKv7zG8sGhcs9IwaAkOLeoOaTvd3DISZEPTQQ__E42IYIc0jNQcmUBBx15IfYCcIHhTTmAtcXrI9XisI
_ZbawM9dl6pagUHSzKfRi6JKowwkNTRflTMQSvw58Y5L8WPhIY_fAciivpbKeGKoW-N0a7nEErFfe6ISD_sIWgrs7hzXgPE6OQY9az4mPMPDyIkz7x7KooXt
Jnh2cBEZWBMlWklWEC2jv8XAV9NlGWNu6LnhfZEL7AWGwPT1gE1TvkFukwLSeAnOkfLHwQ028ZbL0TRC2c1-WgK7aSM3bdEjZT5Go6Wrl_bjdB3qA2AZkwU1
t46Q_7G72wjKNd5e7VSBCsLSRv5Bbfwp4EEWmZWOsi79kjig2QlKAIPY3Fa-HdodLRhEvh1L4bRfiiG94uLjP5_EwfibKuAgiNxXVIjeVSx0BPl6xPO_55aQ
oWL75o4ifHccUzQPYYlDdDfU60IeiXwoxB4sITEXi-5bEAEwE6dOWYxhx5q3aCeKhn7ctwm-wsoQgF7SMqXFZcfCTUknxapvSl5Jn6Ab4vN_CK-zIFuWEIr_
r-YMkGPLxt5o5w_bUyTaa2ppRisDoTguUPMnOgEpErwvVA0g4LLpJ0Xw7cDbEL2b4L3zh9riN3CAUeYFL2sgugqEwzP7Qb-5FnvGPTdfiDAmrzk-gc49ZrL5
xNIQVtZLZIxmcW7_YsDLkJ6Xmr1MHwhl5Q_dgd9ZeYuV1P5FLTLzPFKaJCdg2upfgkgrs1j-_RUgaT_Fj5uYWbxO3eTLTgqIJ1_vAzN0uZL5_bxLfhL3Ed5O
DNwbmYEMXxN_MLN_OAwmUcpj_xzICTx1YsNjFogt2Ops-9MgOvTRCmXLlZbxcgeSLW4r_FrV8weQL055qvyhruxl4LMBgePzzXF2udt-kQQwEhcObzKHL4bw
fUY4clR_wrT8LJTLmLFVUwoK3TIq_niwOal5aHCoKhqzrQzI-7L7bGzk4_QcMjJKiAWCbg_YoCqB8RFGUT7pxtczLL7qbegdlThMRYptGJD4R_GONanhiPzN
H3TK4bCnvkJU2Y-YUglg0HMsBzb3z-KZ2vLASz_ELO8gL99XzTOSPfd2hnJy13AcOdkbh2V0xdonieSIjq79jWwzOH7RB2QWeggC1PmRLDTvVmK0o_WA874L
gd9MPVNoySL45rzC_a2bjr-NVglIY4hTBt6obQ-Ooe_prN9JzUMev5Y5YFM5LxRp1PQb6X4LylaPEDS-v21VO3qNES_NVytEWG000020883zVTSeWiXMP2ko
5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhSXMP2ko5TcAR4Ms8bkHhG4
}

