sprite $Amazon_EMR_dark_bg [150x150/16z] {
xC4n3G0000AWK_idjeS3yWW0000wzimpkN8G2C9_9t7_uswqkv2QDoKNI8m3cr_yjYSruD7-h32fnDIml0gNHkjMrC1I01N2ahV8gOZwVwm2LDxh8_6Fi4Jy
UdN-OKa5gK9E0RNTL0683jChvBfGI2jGqIC_L1CH_Cdsf3EKxw8_4mTBIqxdQ9USZ9f72zTdWckDgL9ZwF9Kili1oyUv1sgzbGZPhTXD64em2x8-KO1-xlK-
KYhSpDxuvFwa2aOGBbBhnOtxBRlmOqxnK_hdAeP_Q_HzgLXw7a6nIYmnL15w3YVLM2mxGzWQKs7SA9Kc88b57eBCppmJSPcW2UHYENc8UIgDbYrxsIuqfz8P
AAIJcxobl7cdsElIZFkq2gGH2PXrG-lK42evdQEIO2PmiLQ3uXSqyxDxdLNAijX68fPvKAZHl-QWGdEtvnyrNGhjvfnlZcM3oEi1gZ-SL6zJKca2bVotaKeO
1CZFZdCkVdg5l7_0O-JlT1MKaT1flsIa7jWE3zfS_SNrbudwGGsLzr93LyMachHpCZxeO4avbR1TxSOrZD1AgPWAtyr86DBuoogJgLUexEWZsD7Wpvd5JYsd
4Y2f31tDl5Jir78gXD2XAuirBnKx8ARAPML7iqGgzh0vbVAZxCva6TNLHvDl5JZMzLJI1kkQirnwSgIhg0HI5QB2ZAyLGKC4QsGxf89OPJg3aMlVsaKX5Lh3
XeaJAY-bKjYF3TCvR1nnnqvhavC9ry5mXbVRv_e01gdUwy7zQOVi9y_UIyNaxRdTX7eSmAGtUzesxRm8BBepDsbRTwbYCVhsJJlwV4Fl9Ku_H8zWTK-Azf-g
8Vn0gtG2YR8iSreB4Z7KCbFDdsnhVhBDKcsy1V3aO7lBZGdrMP9gu-sI95BTVnCNV1DdoKtSxbjBIoxYzjpmHdB3k-ysNA_SXlzktwuD08PXA0gstd_XO1Dc
CDoD8BNlHrSEV5zPzAQLHN-gpIBbcu9kNgH4Lk_qGkobK_nLc88kQBOrsvfj7zHiQxOZM5HPdrrUwbarZXUW-G00080Q
}

