sprite $Amazon_Redshift_Dense_Storage_Node_dark_bg [100x100/16z] {
xTa5ZiL038FX27t_6w_uqTz8YLmlZOKFsgyuaAaRSo9AW3W6vcENFz0uXXA64eQKC9Gmb32aXA4RZN8YuZYVBrqPDaINAHUYpl0eQdBzXnM1hPJ7UD_6OR0W
R6xt1XE0M0p-FnXmOaE2ltOO0W8HDhO4Norj3H0GaTGPceMVLf_1o6yt94sCUKSB-_OQ4X1EWxCowCTki02_ea4_FIjyVxS6lxm0FBvT6Res1Zqz6O-RHxqf
txo5KGy3dztUA4Xh28mUgO6XgnwxA5lZWGoC6XhyVbI7rDYeWF5uNFtNYe_TVy_XT-Up2_V0-GvoUoL3Mv9j4xbfzxJjVV_jxACuaxxMR-J7FeanN7WiUiRj
FH6PgoNcdCcvSxu6aAzbv6ioZ22Hhv7bQts9ccMWzfgj8UThuVcQVdvjWer7_iHQqTzOk_iJQwb_UVty69HZSEuqJhu
}

