sprite $Amazon_Redshift_Dense_Compute_Node_dark_bg [100x100/16z] {
xTatSi0m44DHTBZ_ZLqw_LdDoX2SY4xnAOjSwi6Sc18cTiOnOCPFCexXXk66OJSCDmmt3BjX-453ISGSAQVO7CKGUp0oY2SZe_ZACEKMWL-fZF5ncuJ1WZ_E
2HX0098mU7qmuCIM1CzE60O24JRk4dorVDS00H7Ra-5T-6dD6OpyTiFsnjZ_Q67VMSC68cbmlcJCT-1r9Yn50twUD8bpzmQt0W1udPisfjjqRRpUl4L_veQX
qT258SXi28mHqSAmR3OeLKFF6Hg8jj6_Lf9ozxp_xF9xxk0x-1gOp7rBkDUI_IRQD2FsRHzkL-8VDMRnhyqR_RPFemrNRekUTljCLFfgZJvdi-_Shm7qQndz
cWmZIFHhPFrQNwDcMQYzTcl8_LfulwRV7vjWupL_OgpeRupT_OcnrByyVduCoZ4uJnedBm
}

