sprite $Amazon_Kinesis_Video_Streams_dark_bg [150x150/16z] {
xPlNUkKm28Glpm2Zzt_TJQzZV3ul4LluxrBrHs2CIcv_FiCm3CCm3CCm3CEm7i2tpyPQAyPAMDt-yhaQAvDMt2SXn_TldtMHRZjnEIicfd0dfXDhTIUM3265
x4xYE8JH74BxuoQBSh9yzHO7IpAhCOQKCSJQMnta-8I8OOzMdaFnfEMzCGpnwTRSGgf5j3s7cTRoDgqijnRHgWNv-GS2dLecSgxJozP1Sldgz0AFfYjUlMXj
MYkGUCK6CHqi-lVunkeJ0mz3XLZlXA5XkhINSxt3hMQWy1A1V2ByHzJKxxGthu0Iu_eCmnsbSjHXv7i2AMtd4Z32tGsVkUAxU3lneXI3DDDSi3fyynfFQm4y
-2DMMS6skEU9Wta4gwrqkobhWIVb4p3tU805LkBTbzO2Xg6pc6inNQNg2L4qXHXL7J1KskL5KmFJEStuLAOkUkR5oN6xO9PJu2N5T9Mgjz9UzpzeW0kvGYlz
g35Sc-aonGeh3OpVkW7WrWyirbSYtBhTyaO5GAjPh6FY0Ny47zaLpVjhG4Q3srZzeH549iJNPBUDsGxdKM6mfi9WyLr7o3GgCVgBEZufqGs9zts4LNIaxqPv
bty_H4rt5POkFVPf6OMIWEi2BDiQqbZIG2SLndvd6ormjg4KIK2IFpWgTcZrOb0Sd0kgBaRmp0d1rzzyuIWQrwn4Fib6Njy_EkUo5P6LrIQhE2-h35CZ65VW
PwpYr2diO0IAyDTOnOaJxNW4yIr5LhbJ81iXsPeejq8iUPgZhQH_lPMBk2HMJk5LRGMAUSgiH0wMM_aIX_AvrGCMmglEAevY0IPMd-ej7ObLzGblQlK0GYHO
WPKnEGrFh4G_Yp8hMq-OcC7CIXOwPbQ5joounqfB9VdV444SfDJd_C-pVLLdEyulODrV6ShgLIfbJLNKavoYtV_6YUIDKthRaEXvE-StCz7GoUXRhDerx_hA
Ur6UN8zkw93Jsz4y6O4YnPLLxKroEnd1H3eLMOciKguRLwdvVoXudvNB04Auxjpz21b04xzivqwHVW9Tl1VhTzLoAsYhXXr8aOt2gcct5ebLryvs7i6-Ku3S
gk74f8bX68PX68PX68PX-0K
}

