sprite $Amazon_Kinesis_dark_bg [150x150/16z] {
xPi7YYqx34J9BgNzR_U_ISs46dqQsbC6T3Pm3v9TxNJN-Gp3C0p3C0p3C0n3_GFhErvLUQHL76SLjwp6AfUEh2gZuwgM3juhlqgeWMS0wYgX1EDLAV5mJ_hx
8MuXdsucBXRg7qvBMD2sC46BbKj0swmKzp1e3A2qMYZQGnThEHz38TPAhfLQBRHQ2PLMTKqiNngirqh8j7YQPhqIK6dntCfIUjblKyw5NbTLycUvejv94tZ5
vvfmhmhJfFm_V3LU6QRfOYNtkWY3e5nq2C7parXkDUCruVLQ5bcV2T-Y1feHLpdGY5rakEDHkLmCppOBu5c4Z71tmtVMRIfNuzLCEMDc7DotgaIJzNqMm2At
M7M1RK5c757pY7pQYYytQHPu4v-0kSS_yW6h9250fjmVfnIIphK-2sA_cZUXsSsuZ703TfQhNq3r4ou-nzG3cYIS7Ek6sOQy8bv4ZAh51YkAvQs91hX7xh3Y
eNcPaPerCVMm5I_OfMPOUl1QCU8cbkiNAf3geHtByGz_0P_uisuojVjWariSQPL2g_CxY4ueun_-O-SWIOO8b-LMlzqJAHNP6aj1r2VIxO2lioNPp2XMCjmf
JBZguqvXIxX2vaT3jXxOJU3HdLVWtiwhTkwyWZhr4PQnDS3u1P9-Hy_7KtyIkl_qWnIA9_qVdnJ5El1KBVvtCoquWOnRfxMzKMu8BXhrE6MfWoJ78CAb3Zza
wtD2Vxj4ZCGtSHRyW6i_oFxMaYlfRtZ3H9VqWL_7Vs29fBmP_mUziYXYAvNYQqBzCvbh_2l0aG-mMYbV6g9xvMGdlZQq9IARbvbsuYjMqxxuRLnrfNBkYXDV
ahlw8JbtrJOGpJy43ceW3dXpxxo2ImT9fVbF70UFM8tLZ2irmp0Cmp0Cmp0Cm_0V
}

