sprite $Amazon_QuickSight_dark_bg [150x150/16z] {
xTk7Yjr034PXkgMH_FwFcsBXROU1sVAR8T6Xf2dBTztBxl5lrNLTrtLTrtLTrtNTEAMDBw7i5FU4gbM79clLSZOYTr0nawlqwLKs8eRlfR8uht9ifF8yxs87
5O_DiOlgMdqPevQOxQ6o2tMjoLfOMwX6eUwbbZkeYXBu-ZkenfklRzkeidxhsoohejHXFGkupJvuXfbd-RPGvVcsFEGgiq-ZJAog5PB-1PHCPRcqJk8QSOl4
9r2eNb1W4GMCIXMu3X2We5ePJ3Uh2m5RGPbvQ5NnOZ4yFm1AUEV5hIfmyWMgm8-ftYo4KQe9AWwnYjS1L17rj2gnCYUeHxUhCrv-vpEKL4LK5O73A51Q5L4l
-GGbL7qT9LSHvPvb2fkWz2gYxalV5nDGSXLHc0PAhY9gEZs0Kgc8cauxK2eLKPW6IgyYYjD4wLL4SPeelOeeJXEbLzaB2jD4wLL4SPeelOeeJZik7cGgeZWD
b5H5LDfa6YYjYYXE0oLN4SLfeFGgeZXDb5urHrcK9e0IgeY2jW9Ahrf7wLL4eInDbkhGgrPGNlzmZxXU1TJ27RrUHHHBF9DHguXYTS_rb2fZE52JPJMaAaRK
VBkorAdMKVfzaDc8p72W40wYGbKilzsmnA1AbK2ji3WuLwcM5AyP16-kU9Ff8vTFkEvb5whYPGd55rvQgrJddmOEai-h-ByCRq5Q9Lg3-gtT5IhzaO7fZwA-
Y-h8xw3qP-Vy0af-9GEJG2MfLPOnHdydUQjQrQfM_GS_kzIg_NzIR_-whkkwhkkwhkkwhliD
}

