sprite $Amazon_EMR_Cluster_dark_bg [100x100/16z] {
xTb9aiKW38DXxtJ_6_UU4YxQKVuU7jfb_387JBsO6xa0nDwuHZlZvurhY314619XY314619Xw4MZaeXygdAATaOCqJQLGjGP6KLDzYkC2FkLoXZhDWd32rhd
10n362HX-FMziQun8jRP2KE6i8WtfeI_MfeQHh28fCxGGOvV_RbHk-ICGeqUw8t-I4-0gieQaY6IXco2nhwnOF29qVnX0uO55lgPqG267nWdhqlOA9TcZMyR
9slL4wEw98pnhspqdlT88GPnhP1xpZ-xn3i8V4kmRoB_RUV_KVo_rZDysuTlm_5jqPzlKuimT49GVJM-pydtdVaQ05_Bw6ioL6s9hv7njJwYPWdKNjaQCbyB
vslw_DW4FyR2ZnNfVupT_OknrFyyVduDbslul6dSV04
}

