sprite $Amazon_Athena_dark_bg [150x150/16z] {
xPk9RgKm34Mrzthf_t_kRBJHuvtd2bG7gb6kjfcsX1FRSOm9R_-BbfQMbfQMbfQMbfQMbfPa7f7ldyfmqzr46m-KRdSX-GCHbN43c0KueFHhVJdCD4BfG-Q-
Sshe3gPm5U5sCPUDEuOTYZgVpwIeWgOElRIB39LsQWen5Ih0T90hDSzxYK0vVf5DXJe_RP_fHOEXJaudfa6bVICUin-AthiVoxuxgarmehuQKnR1yce-bh8S
qI8FrWhMdI2oS9y64i2imb9hHiyYRrTAByRfZ7IkFdzLO7datbx4YaR_6RPf117Br50nL9F_l31Kw5HfeGOVrWCbc2ekVp6RQFAVJcpJt9GvN4ke-zdDjlux
jHWhuJ_buMqwNc15Wx4KM3HPUA_selSRIv6OQmLLRpCqLgiSK6TJi6OK3vYfv1wVSjFBRGO_QQ5XSgwRCXc6I_nvPjPT_0Ms5YgqNxCfhEiMSRmT4-IOof3r
nhi_sdxNtzkqw_e5LXrSs6-gg9eovXzaAbTTTgv2UvnZF8KFqx_lZ9LFDi-9KHMciadafSlqpS124DkWseULINeABDMhRepKH2KKoANqvFidgtiVLUvkzBMO
E7U15brKZ9LutTGUuOrLrnBkqj2M-n2nClVOmYaYmbtQxhf146DSt9SNweYLtk0XNDnDHQldSqfAsr6nrjD-IkgY2jW3J-l5ok-culn9EVOVuQOtK2MoLuY9
OFYxWwekJnYnshKNYcfzDXK3M14vkD3ClewA8olgFIUleifXZeehWJ4xCp3y-UemW34zYpA1it-589oquz1ub3uTA5pSMOnokhmJSePKpo1QEv5C3PLLixWM
_-r8xbcc1Xe6LT_S2fbZ4zyPanEV9XnkgLmzhnGbLPQfWJQa0mdPbD-jc3BZZH4v_ub-TDXChrutmLG-l_inxhOfmZT5mj7ePa_g5Ed1CvMCJSXhkcfZAwPI
nJk3sHt8kj-NORXaOCtirXhFq6toebixi3exsmoIivtm79UrcQhZBS30wZFLgJScT9y_NDPgAeRlkRTB0olxJALeU1EtOVMPoba277WPvq38aVSR57HO77x3
QxNl-vE1uy0Xc420bT9_oa9P7UwL1VQUDYoEXRWP2dVzausguG8i0Ul0YHHJpiPwlQBbNvxUcOrLdmghJpfTWrMEzHXD6IFuxyMYhiTwzqQicQTOxySwRouR
S-5GSUVfw1fBDvuahx7YrbFtMMpmUTKN2iokZf3lxOtosJIFVSr1B5BrV_dYqYWQ0YTJW0Mg6xuI0XRYweOlgeZLlmOPG1JFgH1Bw5XC_58lUJ2CZs8cuHpY
ZL8MrVFjM8IwNmeaZH_2bLYXFrfBIqjBIqjBIqjBIqjBIxy1
}

