sprite $Amazon_EMR_EMR_Engine_MapR_M3_dark_bg [100x100/16z] {
xTU5SiH038DX3UhzdxXC6jUpsjY7yLzUw7Ty2SxMD4tJnBodDCQ872gDKU-c3ojUm-0L2FB13CIw3MEcVFiOguf2RcZ_Jrc2RJ2P-JDQDoWJgU4JI5UcjCvZ
Azr7owWzoELINjAGKROPaWpZAOqnOcF4nj2VCNcCwcf-vHfS6Dmmf5ziRH2okc1GVdxz5g--x8PdaFg_SqDtiyFWsi2c8NTdl6EZOJ-kugv-0tgZg264hdvl
tw0OCfmOS0tTdXfnDS1zmtXSnTM-OJu_wWR4a64ab-ZmQxlC6etntE_dvppUvHMCl6iOF7G-6BGUWz1HhSDOthrL0t6JtTKCEhD72DdfN818r94ufO8VLw6X
QnWe4dK4RPM5QPgcwHK
}

