sprite $Amazon_Elasticsearch_Service_dark_bg [150x150/16z] {
xPf7kkim24Q7edd_ottT_trSsQHyGQHmHka-GHZLiOwcQPgcQPgcQPgcQKWEe56CRGVOg8MsGqOnpsibZcUn6exFicghjWggVg5LKFKBhOAgNnohvxKIHxLL
y4xwAAhIAhYVYgssGzhgbb5KlTLml8jLMvcgFfML3V0iLYOqdimAt6wLsTi1Ola3qzWHYwooUZj0uhw0DYLzf1LTsQyW91F6umySMANrTd2QCRbGJH9xEpPe
cFxXlnSejCghu08ZHf8JmqnAhCmdqHn2nSUMMP5DJfENxHzSOmKf6IVebnQlip84wWJ-qf9LLehRx1Gov9QbMoa20QbGYty_IhSYL7zo2enE433QCDjAqNuy
02ig5yHGq7I15KAblgM0JlqyPLiXLBWMAZoG0U2VRCNJfHH1GkK4-0F9LWWE-R8az2-_ZEPHaIHRwPuiYgj-op4wgF6MR2Mx2EEYa0fAFELQqTw0KJRFN-LK
AuH7VJ97618hrGgNGOg523wIPON7F3qE4ylMM17I2e_36TDwgn7JLkxnCrdXVdmIAr_QxN9biBNrYj7v5jShr7OeRbnSsscFZvzVSMK_E8yPufuGshHmV8KM
uWiDQ0l7eZkgb-e2Bnwtnw212-Ou5qkeqRhve5s_xckqRkuirxKVjFBN6IuLJrG5Q3t7cWoanF3P-lKhI0s2rfArlhWH1VDNQALQGIieMuHrKQULRZMYDMGn
I3cjN2larf4NYLjlTreBzoOslpUnxT2Oj7AjS2rWsCO1Tg9bILQ0uU4n2xMIh68lvK6nLg8LiblXWoIxf9LivVUT2HONj9AiOcAjTAjDUONMxMTUx7QjFAlu
d4oifMKdXopIuYghxKmBmIgnEj92zrbcTQP5nLQRI_bdifgrkDngqiA2o0FFoTp-ZjV2GtdecQBRt_4dHHIpZ78hQ05-vCdiszyvrkB7dMA_yvrvyg4qdWh6
USHxQPgcQPgcQPgcQPhc9m
}

