sprite $Amazon_QuickSight [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBSdMPCvETFI4WHW0auGas7t_zwr-MEHU
4mqZJHUtUoFbut8u23FxbffzfJ9PnvQSbSfapUzLyPqgsggaGtvuLCnK8QoYgSfXpLQBGyM0AiQIpA6YeKfaULGqL0cikTVQka_5W2h2cbNbxb0nKILMLs5L
buffAh5-w-RcKZ5B9LOzERMLy-jmgPYfmhsfocVW_TJvL4nHYRMhr9k-jLHAfWf7rT4qdgYOgK8z6q6gwLKnKzNEmqeLSRXLJ5ITbAlMDm5TAkQfvjLJOtJL
krV5BDLHDaMRogbYG3Md4wNCXoe-LFLplDAVe8fGNXMVg6RHFbdMmYTzj7F9BeHVHR_gk4rhLhjGcXEJLDe6IlMWW7JLl8RxckIswK6DqMkkgbsMsxTxKEhr
B5NvzAB6hYPAu7mLFiiDFSQf5kgYIuMmYjxhW9LAgDzL2Alel0vGJKfbeAH2LELWbMlC2wKZsaP9XR2A3jGdjLurwa19XR2A3fGo39IXGbZ51wXke4mLmYfY
ZHhZ2rUdXR9L2AkuHjtZJDWeMuMmYckKhiPibAr2MCK5obBjGgrL2AjeeYnL5yfGAM4LRPHKDcgjGbX56oMLZLgh45RHHabbezOgX5KqK58PA8yACPLOnuso
L4CelmfX5NLF8vHKlw4g7geGLX52MQeBLOx7AeHL5CfG2VLOXP1Ag0b3TQE0Y0e1bL0739LGCHK2Ag4CbL1H5TogDKeg5qfB6tcc4eh4xpdQTgO95LVXcKee
qdf5BLHSXISgeVvW7GOgh89V9TIVh79fohK0ybKsIgnnb-OyNIDVPQF4QjfjcfEJLJQAr0xinjEF79MD4aiJqFzGbTRd6aNUsshFLoaBb5XDZp8IZgi8YhpF
mPbw3YfphzjdBmfbi8fHeWagD8sqGf6_T_lCLA5Og3NhGAQg-b6ahXc0JDMu1XbVxxB8TG3CCIQGgwht5cAxlrkpb4JL-J3n6a_VhfAi4cMIzyPg3B3UeEAR
zg3DoZ_Q9mEij6ReQeO0Axb59mEix1bda05MykmyoG0hzKgcTl1HKbNnl5F5zBk97cBbttc5yauLtwdYErLyfuhlLF6TAhvJnHnLOiAguvKgVAFgXytQSr7x
IYLMJX39psRdG00000104C3-lciKGP6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfiHROYMv6joDO
}

