sprite $Amazon_Kinesis_Data_Analytics [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kJ7JlBZLs7WJ1SrCpQ_uAlS8pSRYkKO3bc
plW_P_ZGaWjET1PwLSS2W72BvQzoPt6bqeNAbKKkL6sXScMHt3z1TnPxKrNHiOYUkhCuOmK0ISSIUisTnHah0H0TA-XbzMPnnYhcfzBG2-hDufG5ymZbm3gp
-D75YrtGY-hCei5QNY6WLvrPV6KUblqKIlDbSSugYviLrPN51KlC9Qr0Bxkok61Lc0zSycVnd7M7hDdl9KSMXump3FRLGcnkB8uPPnWdBAbUBAvPPSb2ScBn
4alCvUz9TM7n8glgKCPHQ0uiNc7PkoKuYkrn5Y-pejh3rOlrOHOli2ec7rSBm97azYIBLrXDPcTL1H_5yXoBLlRAsrEG0_PXjrMSV2X5nsh0gv3R0opEcznj
-Ung2Mz9pFMBB2wQtI79-gaIS2gaDKtlgTH-QPvlLCi1Gn9IAaNjRgaYU_E9Gh1-Mqa28mcTbt8PsrV1PdNN-f5hsPBPtL0XgidIB6jOhwOeJYf86rZcrOwb
gLajAGQiqXkgNZPOrXQaejDgAQdpWW5KlQM2L5BjIeInKhjjgWgEGZLODknOgVO0YzEQ_E_IUSMurY7ku7QtFMCOSxkM8yp2CLErLteRBAvgyUhhGCrHiDsK
HLvr8UQcHiPARQhKLgrTnWGiQZMb87igDLNhj0ZU4cCsBLpDdTTRgsmMBzMI62ygJxPGhMhPc82KgWkB6vdZf1uiRgNQIWe-AhsjelREDFLWSRFpcqe8K0yM
Tnk7IJrOlCEgENgSOE-cgetFeVOIRfMch4sHlS-ucHhjgMeI34bCfJwjqkkg6d4kvDBqw6cLNbErB2E8Uchxrg-_vuAgnfEeyiXJfOthwlc_KtpbgLAkql16
uj1FKhrcI8hoSpz5rGH7iStOlVQzgZoOh4eKN5UbqwhVK-57GTT_Pc13XRU-fAhB3Vivgg2h3Vj9gaYx8gSDsr9fxqkgk3IzDknRLN5XEc-OlsfT5LXxyLDL
BG17MNaAlVK-kQdowUWkgF2Mawe9ZZA7Vg8g6sVt4rJc6qre7AgoLcdFHVKwlMhT_myLlrbL3rDKwrXVAcRZcNDJbSajRuAp2cyvg2nKi--_isgD4kLGV6ty
zwkQ_UwdWXyLygpIdhjAWLwaZOhAKSNlK0bwOOBAv6SL_LLfTQSAJHMzLHNesJE5necApYf1hzhMof-aAkWbsrhuirI2dfhMo9-bgkYLXVMdg280uLWnh8QA
NYhqyiAwLj57LT5JqvgkgEYYIW34jhPBAdgeWdc06Jt-F1LwrLI5VohhDsse_cjsFWeO1000Y3rRY7-_663FYu8SjRhIN5bP3T-jBA_-7wwCpngEasn9jYHR
aYt9bcHBiYNPacn9jYHRaYt9bcHBiYNPacn9jYHRaYt9bcHBiYNPcW
}

