sprite $Amazon_Kinesis_Data_Firehose_dark_bg [150x150/16z] {
xPl9TkGm24MNUV3G__zkPtAEZChTEbPROV7kDaDTOq1ZlVK88OGGGWWXX11ufvvLUmUoajKIifALhAeHxrPUpefbhLZEoj-jefoLrIr2AsSLUeNJe9MiGjOD
LjGCbjSBLidku3MrM5ChMiNSmfSMKL8hhDnBBEHbgH8llD2nmQhB9Ols3RCOMmUtJAyyX-kTeA7_hHDRh5hyUA4FIj0DsMhFK7u8u2TUqKx4RrXnp2NZIUom
miu9DNuKeXFpkB1AMVSS5kqiTfWnNbaTq1-DMKxo_jDWVc6r8sZmE7-Q8tM6RBKbQ4UI9pStZ5PqjZOPD1XZLSoJs7KDOdY8G1P2bvbhm1WJLaVICNSsVE3k
vCfOWDSnOqnOvST0ohlxLbt99M3kv9LL_jLhg_0RLbC5dgr6Nbe5_KRZo5qH-3zMv56zDsa9qXsuRpK2B7IfH91qFy8tRsMV0ERlSA4p8BMfn9pLOWrUgp5g
M6Kjbh9ASIfWPTT2VCVzJWtY7Ll8zbSkdZlNlDLuvW_OWbM_fbdlxK6kjD5nUhHkjJvNRNyTdabEZSxEtYgRtKXsNFXCr62Qo3pGhz9ppytwpWs5NGMUcj-g
aN6oNs5iA74vbAqf3Pz3kjjeHKQRpkgbrKIA4jrcLrvqm-EhmVpSI5OvH3jMpiV7TCcSh5A8ddUYZQDZjdeuH7bxBmmfxPELuODDksevJ4Dp-BMzldx7DW_N
-2MhqIddplxTsi2Oz-6TKTBTSaxWfsFnSgSvFC9Ky1Y7R_Ma0WMbg1FUVs8LfH19gixxeswaBDpUqKsdXLjXka4ttHNq0htiHJNgTdIXc-JwBe2iP2KhMSaA
kvM444888OGGGeW_
}

