sprite $Amazon_Kinesis_Data_Analytics_dark_bg [150x150/16z] {
xTi5ikHW20JWyg3tF-xwyYGzJ2hMJ-Xr_Ry2mlZoyJEPJ2QJoMGocKmcaqd-Ygn-rpFJHmLKooUlrQWKge83glDjzRjMuyQ9mQfebP0JnOELxC62BOp2SkAF
M-Za5kg7ArR0ObbobuCsa-N4Oi4UIlAsGvqV0dh8OVKpv7zOnksXWz-cpfQqh13QTTYnqcYiRhOoXCeI_FkPBaoMWfdZkQeg3XO7qoNng5oU_nBAOU6QI9JB
xuPLiyBM_VNamIIgLQYF5LSXb0kxBF8bSQjCug6h6bbnkuscvN91iCYt2JUJKt6EsrW7koAsHOA4kvcflCqUR_hon1KG9b26iqELtlMntmLY7fUekZi4wbkk
E55pZvDL-6B3ky2QzIcYPluhSOwgojKKxEOjfU2s3y3kt5BRxp-f1ze3AfVf32np42dPIlTcJPt54a-uD7lPzfpW0dS7m9QwMbMksB82AYAs6NV2vTYiW7PD
dQ_2IxDM03-YO0MO2L-c-5Q37r7pHiMcHQDYsvokmelf8rN9_ODDkyTgsYrtnIuHbIftvWIIeIsgGbI91_1K62gnU78JkEU4OohnDw82CLK2dfrYgyG1YQqo
yAmdKxNzaPVSgz8D9lN8xITOLcol2fZW3jkkobSveWhjxozJLDvUcoJLzcVLjglgnxqgVshwGxfNvOsfPkvkLM-gQvElgXaF0-Vr--aobO7MjQfybOjK4g1E
R9LLAofybJz-rR9LbGAhhdk5bwNIQ5uDhtF0DNUbIlDF55HmTKvbX-hCTra4GLMePlu9AdamKY_plpxdSfKyUmCMHTMYTE6eh9cfq8MXwjzj6B9GLFqxCsKX
gRIsDBAoLD6zFPgbqge9iD9K_hXKobFLL04hHzL_Gi5uAeCDbB9oL0uRgFMVSLJvAmehw6ILV4ZLibMr8rzD9QFwc9bC9fF9P3APJ2QJoUGd
}

