sprite $Amazon_EMR [150x150/16z] {
pCu10KG0002nVy3w5oO3S4imrsttasn9jYHRaYt9bcHBiYNPacn9jYHRaYt9bcHBikL-pPNcIdEbkT9SQQuqLvehZTKo_d-7_xG20gkTNJDTUrE7WJ36s59q
xlzwJrkNOPaW33RfFl--DUyp4jeI6OT5etHYsKDGQTYf4yliUQX-B7i4IuQYcByg3aNQWsMFO9MS2ZE8X4BOa_Bs15QUeG1IiAG3ougUi4g9SkgeM_O4Le5W
pB6ZdDe3MFgDAhyzaXrLtXx04Z0iolITPYhx21NKJ6Lz4PJZ24BDLFQHR8UQgUmZbG5gfh8dgwY-ICrKzaJ7oUWuxLX6wXePOX998xfp1vPrOY5aB3cULhyY
Xp59bUe9h8cGZgrAAtkKkrJMbkp3E427QQNxd-UxLDPIH8Vq4cmJU0HFWvmgLBrO8tiZ1sRDJetJ56S-kKjbjvCgw5bLHP1Z-PxcmXLkKzdTaLteUznn2aTQ
2aIenD3kOKdHMxwaew1cjmMfLiooorWoZSEYcEO0HTXoQjP48TNoZGOgmfh2G0eP9l3p1jYyyow-OUS6AlFB93I9LySLPe6APuXcAbkpmXMDB6HMEgTAJLI6
5vWLvskBxb8i-AKrFEyLi0BIoEbgufSnc2M1wVDv7RKAbgvCh4nUEMPbF2ZvhSusKvsa3c8RJioQuYRKkf_7ugkHQWvVhamBdbaGOoM4leqgSZbYPSzANV9k
E-PC-krlnlMFMgWoe6fOmcq0I4iZa84qdWtDzQJALX_PmvOpSWieIWIbCFKkLIf6cp6MtrmqZTwiF7cLzmuLh0hrmGPc4TAOD040XM8emktRnwfP9LRa7pfG
0gP0I4i5resZ-QlqHRf55M0Li9WAuW8GCytAtArPDwZqUwf33XMb3A93ipAFWQphLEMrR9LFfGjIGdJ8B66hM9UfogHc6pbKI9-OtGL8O9clgrIbvzjMBjL4
9OlDedD87UiyhSHs8YewE1uhKjroTOcglBwH72evULMbkkdhFfKC1zhN1l7D0dH55wZoKrGAg-hwD9MpDzVquo8uqS1wgdjKK7ksfnjOrSf0kbyP9bhGQhfT
HK5bDwgeqaXLrusEGt4zp6VnrqAg3UUgTsU7oiWFdXVute3nxvekJZ9CHLWJpLPSGcKT_-IhwfvLfpwFolofBsQo2hl4ECBJ6bXrGlQeR6zLZ0osMeNKW-hH
h6yJhdYRo94dToc4XzUcKHkfi7cvuisBmSAwJ3XRggVwbYfdMBobyjuCgzJPwEzJeVlf6HPlz02Znp8UN3-qaSfY3UixLAeTFm05rUhNfKkHd4D5PwSc2IyP
3LHqLRC3dL_L2Z4SExv0jbBPSe5qZ68eQexBOya1wwEopRNMDhfohGM9u7Bx79LjBjj9ok-h9F-o3LKksvrKA12-edbMPVST4-sdCXpgM0dNm5EhmFW6hNrK
I2C-BIBZrHohl0-3AA2RgI1D-tVYDhFXQ7OqxF43cUbDnLug2EzQyYEQp0w6FUy2Bg6sNbYl54t9imgSHN5QJfNoIIgRXmOptoeQ--hxeVMhC4G-wSRZAmYK
Nn-cGdbOFcNXNFRoQbVKrwUfJ6gVI87oD-0G4vW-IcNEftVQPOye_99K6GkN22QNNu1g_WITVTDSkUDFfnAKh2Bixp-RAXOAkZHFFvkgGF2WEFvSAfm5EVj_
4fL_GfLVcUfV1ElPRiZsNwao62h3BrH5CJMh_KeTnoHW3Fp9L7hGdQq3ovvH7aXgre7rtsUmr6OrKZs5fTiTLcrH6zLZMEiseRPL4nLZFQz6gY_Dpe400000
W220_NtNA8AyLcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQt8LcGhiXNPYcn5jY9RaQq1
}

