sprite $Amazon_Kinesis_Data_Streams_dark_bg [150x150/16z] {
x9Ev3a8n30JB-Dh__rmkYoeExGPffuDtZJpEkXyXX11222644080RFit0EJQaTNwSoiLzEki4a1i_tg7fH40QllNEYmDdxzVLovMzWXfv3bXa1FwcB1iiUZl
px997DOSAyaDQpo6LfsMXU7GaAiLirQIjMfUxGHrvUsdLXdp79wrdAfLyye1QLGjs_ulgfSVObcsLeMHjERbyW9nNbQd8vT0auozhtbSdP4NChwVdhnuOa_Y
pIizRXW6mez16Tt_k4bCLyv7pLA4QE7DMt-Z30kmXezlTiLr8DqUS1TnKTu_G6OGN9OuEhBuDJI7oY3_02EsM-5o74P8BR38Os2P6H7Mh4RLP41oeOcd9jEs
G7MaYgFM0lF8BLHg_-Iz5fnLXtaaxgNI-oUBJWk2NyXqaPc9MwZ8NS9XZMoh5EZzazQ2t8vcj4zHOAnIE-62nNnizad6T3zbga0frjqKO89CsmrSn-UYgz1o
6nLpWIH0crd4hD-gvQWsAbgbeAXgPY4au4ap7qg0FGztKcZP18hvp2EnVG-eTmEyL0yywzkWs0tZRpO6xrU9e6pVp0RwLhRF-rI_bqeB4woF7SAjcGTwRnfk
fD8Y3ZgWsRY4unEhHAKNFFQKsFzO_gJVJOGFPMXGSgze45WLUTV7FRownas1LLkYMHOPoXTkDCjU6W9fHQ0dgnqNLaI4AJSeAdh8QqoqcWZ35IgKcHX9nqzJ
rMCOavjsTsf5oQcDJpwhdxnqAVXdpTi5gYpSPy-SKfk7w8iKLM5j9YQbOKc31fDKlaW5dzel-wX9hQdevLUeSah3yYlNVPvAkBPmgyQ2uGCjKCfWYo4yKZ6n
OCH5gZzOawoKJ9npUP6gC38bcBWseQdOcz52ZbjlQ11oicr-Ac5Bn-HvAiF0JqzJnUbAxx1bAgj1PPVZv49xnbS6qH1_YihEJYxHBuDI2Hev6UejUfVTrNon
znnIvOOfYwucOuKggb2lyjzNg7mLoavSpVblz2sySn7Jg0jGK519Zs2U2fLabr0k_db1HQwzTuAErOluDLKMrCh6rHV3XvESfQYieWiOwzJuZ6cDLL29aS_2
52kpiiKrPOXVclZ55Ific8uMWZj9vPL9SidA5lEhSrIcxaEpia4UkEtDiX0_aaN9MhgjtVzhZjqts_gNBvYP0FpNlfrJ0Gm2K13qxne9Mt7F64Y0Sj-F2h1w
9TJ5PCEYgklIZlLPbxWjVzNLSiSBHk7Ty5THmsy400000m
}

