sprite $Amazon_Kinesis_Video_Streams [150x150/16z] {
pCv10G0G002nh_Klh0DmIp3xndcIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kIBScMP4ko9TcIR4cs95kJDpjDSYJ4mJ0iiMYh-zztS5JGKUdv8186
vltRIpvjP1Lj-oXggN-NY2XjiUwhhhDYflA9wYehOgAoRLLlMnLNJh2thOgXIloxJ2s_peeHAn5HyUyAjUmwApeBFP_zEw5MzTki6B44lYf6hUItMJ5a4Jn2
xjYhhEZXmSOlOVR5jbNnSeJearvcnPZ5rCBlGhQxh1YpP39PsQ-oOi9Yk4cLFjMhh7Y4dc_W36-puXcQ8RJsM-KYAxu2PvZmQ56sQwpu3fnX7h1ORx5Ypf8f
YyebLhnYCTZyUo_NXWgpyDCh_PRi0YlUiF3UOgATgTzHOHOUhaBTfOTPyOAbD7YvB7KNLpl9YZSiuz5PQQ9UbdEiGE4jZrT1JRGEsrO5dcqMXwzNBrKxm8fn
QBQnomhzYNFL_v4LaqQhWC5zGH8zIcLEypsLuKlpU4TPJVGLfr947BUbOWSiBzHBw6bIc42S6gzK-MvTHPq5NBEtd5KamsseY0solF8GrjEI-Owg9Pqr6-qi
vZ2LaXFDyYqLPGSii0kA-30LAOsN0D1zHzMg4OwJJ61BhRQeid_B7B0Gh6yfEy2AOPx1qWGmfkzINi51rIHXi3JHBiW4IxzhIblIilUicEMLNbwWj6QcvOQi
064NSL7lRMufh7AaclTOcfIh-JpJKXAlgHohvdszrJ9upG1EQ-EbAT17h7YLLQP7t6Zc1rjMTLX6Aq3q1YjM6bvKSYcgUeuLIxcxr4JZKgjyqhyjisAPrJ8f
YGuqPCLYpvjAuWCgm8fzbjRJAjzITPP9lN62hKsLwmp4VTXbTTfx6oh5cw59FWm_qfhA9TDN32vvPrYRfDIN-eLUglH1uY8MyFyz2wKwPRrucVWXSlWPX34j
nkR3LcvzMNpuiHjjD675DFb3YXvWCMt4Uohh3sFnwPR_nHVrTvdsBwWsLFtmiWREM-QjjFpzgb8hhQlwgMIRNPsPXb-SpolKMbVzcjBOP9a-TPNwKahxgZgz
o3zKlfPjgzXVhDLDbU-gSk3ayQaQUe8m9RsZoaFJSuU19p2rM2weyiJqt67__OJ-M-fX5KwP2EmBeEeLkwsor9zLFHvXLVTVLTNlevkh2lMINbCP4u4LDbQv
FsRmYgg2ivkhdZT1hkTLdaO_VvGdgfPcCFYxAdnwYkQ_gsBmHCjWy0-ej7yR3e_rdog6JopSNNfC9OCfDwQdAiPFx8FFsogCCZp_3rNSKM4Kl3taFYf_LJ4u
GJfyWaQVaWykgXBnKCN_PTgTFkN0gEpnhOh9PZYshvXQ2QFw_3zLCTYYScwBbjbCIK1L_7jYPV0TzOOABYgyfiW2g_fzgr8ld_tfpDHIRDKOgkBgJKQeLR1L
Og8A0YE-gSAFTsZDCLM14J-bKch9m3fNSH_nywfCH8oFLMAkaZxYvrNKgZChLlNyYahXL0Ly1y3VUaLLY8YnrP1AOucbUwe43x1Iw-LXnwLFYXIg4lmNaAsm
b5hfhaheKrL_oT92dsHF5IzLSVhJsf_0-PBgz2VRFoCMjVojAevz2z1LFsEL3LIenMzCn6VzjE9kljv_cfq30G0000110Flxhb44HROYMv6jo5PaAx8LsOfi
HROYMv6jo5PaAx8LsOfiHROYMv6jo5PaAx8LsOfi3G
}

