sprite $Amazon_CloudSearch_dark_bg [150x150/16z] {
xPg9RiGW34Hrx_Ze_tzkxuxMBPi4P5WgUNJjIHvcmC7azlzLAfLAfLAfL2gLIgKI054L0Bi0gVdBdTpasMX2eY1NF35A0IdAvJbCzWl3Vd-Www7q3aS5P1Nr
fyLB_CX1mgWP5aBPpqNb57jPkE0N0a4kMpfwZbFhyOVp9LyXq4lJT1MMT5r8-UiTe2Zu0YnyGHrbwJPMAaN79KGjfETrMBp0W_b66NvZwTmiusTCv8h3Zfcc
ShJ6jIM9KyHdZf-qeEWdt006pcA6qdcBWhK_ZYaHHgpx3c5MgFpHj2HJuB8m-3RBwj9WRPjDexUCmLeHAdjePFd6XSXzi238TfMqf-NHEkBVCMAmFDFszZXK
E9gpZD5FhonnaK2OszTC32vTk7E09FfUca5HVdfq8sqczotG2hC6q8_x3UUQGHesbQ6sry-w3LE4ZXc3bcOhD3_jCm7dhIGjeTx-jBTdd9kQOYjhthzOjmku
ctGaKEbVA_TH-NSZy2Gi_sDhOSC30OTOt02CJq6qeAJJd1RtkffA1J8DKT41dahbZFyW5VDz8fKIQfIAcI6HYi4VfcAmqgXYxCUfa4Z5_9f3XRJax6Dpsh9Z
PUGWut0Zb6HGMQ32OC0pvw3IIUDKQ2qlad1_DKRL7Z19IeJIU3Fi0iseUzC3R7-e2OrrQClOpuSt6DqbAO_kFEN6NKPh6LnwmoxHaiiCHiR-RQxow2bxcuhE
sz1OPuZ7T9b-x-qjVluECpF5dFgLznsqvTSWstUqpYFBC-56YykaOfy6h2io_ZWLAt8WK9xB-TDqh7RcWbs1ufIrILZ64I6esh7eo7USMLXEh95_pS82_Jjs
9ELpiAGRYmNvcLZQYGL2JSNgE-0MKgp1akkHvM_dUkjY3eGphibOuqzrm5u8jGGBF9V48HFHvsF57EY2ayV5P1LMp86kzsGG8z9YB79HRX-AG0PVZnMvsWyS
hiIY8Du0ujduQgmZ7vdoKa_1eW3zae36tm0hwFzX5LPX5PPZIooxROc5lR1O1zmAYpNJhR1uGB0R5aYr3HQfTiCIKcs3HRTlXSMg-LPOF27O2ek5pJsmJ5Yr
U7QeOh7UGo5-6wojeE8PWkEsYs3EWyAj18HjxVugbKgbKgbKAfLAfLBf3G
}

