sprite $Amazon_Managed_Streaming_for_Kafka_dark_bg [150x150/16z] {
xPc7Zjmm34JHToXI__-vAOl1GJ4jH2kVGYBWIxassftJSvFzUa1H54LH54LH54LH0EagDUk_C4arJTQ99Yj5B4qhbierMusR5Dgx7j9C5SKXosIn2dS-PS4a
hVYvyFFihSgWtzhnDLMQwSZG0Es_GHr5vw2FMBAf8ffdizBttgVlWfB5dxalClYJFoSkYJzNCek_gSDeV_4EVGLVDDwV_sQyFp-1BOC_NnRX_W207m7dCCfV
vnMeSkxeCDWVMmcdACuXDM5iPQmIw93-XbOwQ5CwZFF7LXYdXmu3_R4L_H6XmoX_R2M3iY27Gdz3A-FKn3c4qT_GQfYP88TAVvTMTfDgGVxOIYVND8ZnD-w3
4kNG-sCh2NNePu37TcE528VWE_bMu0_-jKF0MHdFpZft29nz_C3V_guLV64CW-IKE8BxLgysSKZqQAdsyHvBBCkDCpyo_l637vdXyOCVUUpczQUC8-taZVvr
hYDpjifhCFxnWnyP__Z1Zynw58r_uEr7dggb1qRk8-zzIF5uP3m5fBKcs0YU0iqw-Sj5hxZW6Vm9nzhyy3bmTbaerg_OhHzCWYTedPYg3YTVXun1Sy4doCIU
2hWfsoZ71-qQr6jmGwkxnK8HtgZUbJ9P26wq6XhCNXV61Yve_YpjWpkjVc7lemr4BmwyBGRR9y6jLXwPx0AEjX3SQsMB-xQi1k63U_Sx1anMWsqzk8MeVMqD
Yq7T26u0O3c8vy5ZLNtmF6ZwvG1BmSxWEQ1zHB4UF8Vw8zDgK0_UF_OODeBxm1yknyq4OhDtmoMei-16p-kBDBU5G6-Fhp8BTXVSEGysl_KQV04NT5NlBpdQ
vjdP6ajC9L2MwMAmAzj2xSarWwbEr-HyDn-qbyS5zrej7WLqDTXyyFc2Hl4q2FsEOuKCIXJV4SGOb6UBzmRSBjHzKDQ3CIjw95_HruhUigteN__lYhvMz9fa
HQ-fL_IregyLVL4KHL4KHL4KHL7y1
}

