sprite $Analytics_dark_bg [200x200/16z] {
xTj5ZWD144JHsNLcmVsFEzYXOIvmoF_l3K-gCFlc8YCY8Y8Y8YAYuwAx2WSE73XmuC210mSE73XmuC210mSE73XmuC210mSE73XmuC210qVKrWVKQcnrb3wi
ij6HVM2vpH5zQB7BKVjzDOv_5q_NjClHpXiVq0EaxNByx5J_V6ax7J764VCSE73Wm86ZFrVS7Mg40mSELTqTOhWxnF1tY57D7M8SrWunyZ1tY67k4CFS8OOo
TOXXxcXYU3dY2uQ5GqUeVC6mS6W9BTuph1nw1TNo7SF48OOgxnWk3Z5gqzbwPZWvn3ZYXEGpmyaXnlFv4iFA8SPZ-KWGmyaXnbcqPuQJGupthwbC7EyPAbkj
OfWun7YVbKCCSuSOvWunp1rYc3l4C7SKCSmTLGntXnZ-Zd8uErG6tplZ-2eSE73WYBD-NyQGijyNPsiSsVhaMgvmj3wzji9Hvplg2aUPxoWh77gdCILTzto7
5f8p6AbrB7547_7CyVKLptTe8csyesaSmnmx9g9h7UdOC16DOwaZ-gHYk6FBiqXP_dgtpc3K3Q_Rwm86_ql5WGC73XmuSE30WGC73XmuSE30WGC73XmuSE30
WGC73XmuS10H4H4H4H4HqHq
}

