sprite $AWS_Glue_Data_Catalog_dark_bg [100x100/16z] {
xTe53WCn44DH2tt_4vSPl32JAE0lAhyk8oxn4G0mCTnZUODZ6NXzZeI-36080s731dSLC6nutlNoCQBXvSC6VvPcaBgmmLL53Avkjy4DPHZuKQA1HmgA6PH4
ai4LCtLpqtmVWkQCNGZ2nZyD04B6Ew9dNRHhQ4IyMyP0qD08Kmr5n0oDf1kAY1lWfSg69bOO0iapDAA9XWo5QA8jGo62QCwGY21QCpGYYFOCZMYYVGFl1her
y6fW5iF6fVg63QsKFW_7OSudsl0vVLytiE5vryi7Hp78T6F4-vPGmq1PumW
}

