sprite $AWS_Lake_Formation_dark_bg [150x150/16z] {
xC6n00000C2WS_x64wa20000Pj-w4YFNOTXdG8Aw_t5VSHbecQ8T1_5MV75S98Y0MkIuWHeRygTYLUC0VYPMuobMVrd5trnz1Ew8dueL7rpgfsGLHr3pRMpu
WQnUC5D0a3KUA39nBojAjqQsWOdxMDN9AhZZlsYyWqhSg-0BpfWAtm1nAwiKgvSgPZnCXaZMRRp4f1ghD-f5y1vUGB2gzZGWjywsiJhJr25Y-KMKGg9Ch6fZ
jN7BUAiXB6NN3euEJ0gUDST7gllJLUD3LkD3eS23jD_a1yZCZ6rGHvrKHBe-N4uNleGLS_OrSWSY7xJVTu2VLem67f2oAv6Yv3ohsTUezQO8jz9QLucoYuX3
k7TonFgUlYzQLiFpNDhbWJYMM91-Qrhs8Glhc-j2wDQm5eaKFl9Mk3NCDU7r65EuGqC-aO1qQnZlf2IUgiYk8QLXzqhXd8AcwUYiEpCJJMuFib8QlgDVJBSv
rQt6o9ysKrKqhRgkr6qCCTGJqh1y7J2Kbzu7fbafvgMBfdQg7GvdgNtoq1jUOsd-uL1S2k5DbfgdZjszEzQ0DrdohZfsrwzFtnKrnIShlKNFR9CjEMrCFDPq
9nVYORJAGtfyyvf7G3GYZU9ZU8fa1lRxeL4BVSmAcu0IxTeuRPLGbIj1IjlLv3jiXJwO7pqSXX8l3w7Lyf_NtQ4YFWKseJYnSXJfQDXHPEQcf27z5z5Dm25y
ngesi_UjT1dATBLBoO8X_pOFHF9_10nUlSvA_KNBNws1hu1MLhgYopFcCvCvxF6zh4fNqURqciLpiufCdgnA8avCggqkDAMBh9ML-X_dlxttFpLEuqVefSBv
I9bzXT5OpVUeDNhM8qwMNjeVIRVRpnf2aHxyJfIX3yRar7aZXI6vnAecRaN5MRgClN5X7DkZzbfGqa-iYFbFtYyv7H1mLjmputHBorH2CA6XFywBPEunacH2
PVeMoFAMBXkMo8uvYpA8OMwrBHn3f0n5sj8TDUWmnNMWbs7TzleNGp_0LW8DXVZtpc6Gq689VzlykQVSwKeLJUMazPG3vfp_F7u8OxBIrtVAa7NZuSJwi8Oa
CIrRfiknE8loTCDO36QSPamrOzqyV-9BDp1aFsun35QuSBA7qb8hZZYXhr1YSMvcCNmlyDdF2LA9TMeuuZEiGbVCXwdeh2f2Mz9JEks2u3uCxw1eYHNns3LN
QWUz3HPPCokKhEb4TLg08a2XBdTICfMVrWM4dLGV2EAAAJifForUiQIox4Uf_6VRKb__WMq-_GKUx_Z2jk8Pc_Tc-34VuwwVLHk-6E1GNIjEVlNMrHNV9HOi
aRy9MKF4qEyYgFjor5syHEtup2yoHUXUJj9n0Mbt9y3wW98wwUr0ql8l9duWakH1XqpP_sV0l-t1WGm0003087_hUtpL4m0000G
}

