sprite $AWS_Glue_Crawlers_dark_bg [100x100/16z] {
xTS7RaCn30DGOlB-9-xUf5F5b3j5Z3yau7LOGiBpmGyqnW20fxlUZB7E66FCljBCtitFsdyqnXXZZFxyB6EC_5pnCHVUn0R5u363xarkZD7_F_-PPzSZvirH
WuSCWiyHup6H0RhW1nYNysCCD1XkifVZ4XYqXvLI-YvZVQxyd7t0fTHfa22DWKq3rk01WvyOx31eY8yLN6iemdLom__OKi6ceSYxljJmo7gI4Hb-uAImPIXY
-eG0gx4_BgmXRUq6UWrO0vcXTsgujdq3DMFd-pQDuH-vRn0i6JH67R76iYj088RjEczWArSPsCmL1e8K30-CmSSSDFYICuOVQhOP547MROu0T6an_6TrKju7
WcPPQ2CAjP0eb4EYqB59o0ouSvqP7sxhBNL3xfMGbcY7M8B9tdAxS4sWQzuL9Hf37xGc8284xJajA0ERMm
}

