sprite $AWS_Data_Pipeline_dark_bg [150x150/16z] {
xTi5TYGn303HnnRv_iTTS0y-1Qs1XleBOQKQXzjc0G000000GFqVNLbJz26ahOVr2srheVs6j9M8iV7CbhThMbL-oTFrhAgulkljRSJ72XexqSqAidEW-0YK
znnq9g8t-_Zo_lZSmjyHzRdNPqd_ePVk_ATzIgD_8KpibMSAkMoPpxl2BbjQNbWbFpvfM7i9-_bsyVLM7N4BvhtTthwtvpE3UF-2IpephEaiUj1Bd9nbf-iC
RRYyhyMe-ZMPN5M_9bENgv8ZL8dQe5AjoXCB-yw5LwloH9cBYduZf5oL9qw8VYUgLNdYz2d9_rkcQR4gJxIvLHLoi-gzM9KdnjpnhdStZujLaYVELKdwpTMg
TZ5NbMVqEggeIbfHJuvHHTNhztQgg6f5MwoYYYgggAAAAggeeeegggYYgeuggZW6kL-KAkv3tciLLP8UdIsGF56cglpssMdHakB4FliqEHl6-zQIuaIlFqqk
vE5Fl9Fwq-Iq9SM9LdwHHgIejqqKyvDoKvueRLK00000003m5m
}

