sprite $AWS_Glue_dark_bg [150x150/16z] {
xPe7Rbmn34JHMNN_uwOdX0TB82u2kOjvQEv-NqEDN2Il1o6444888OGGukSVBciuftXMArh93sX5A-x1WIvVOeKMQCavOfVJYbtUTDYmLVysMc5QJzXXj59r
zuZ8yuTXApMFF4LlfUT4kEbz9S_pc0VJRkSt6IONiKQfiV9wBLrk4USD6U7kfhz1A_purCjI2SFIT1YCO5viytHxT-v_p7PQZII8O88XTyX7q-wgYFyW0ZzQ
Bg5vFapADVny69VYIeRk4US_YN2leRg4LXXmFCF0nQ-1goTHkSdx7pmkv_UX9pSOzRiPllyfxcVex__eHHdgxVnmKkRpU_-kmXqxds6VttHfrQAQ0CCPeloA
qjA4dzR7C-mNzFx0spiAP3p3VgEE7ppu_k7ImhNSb24w3vSMxj7X3EVpmxtVzyPmXlFvzMTA_-R1WwTVml63nq1rjBJcgmepN9GVhinyLVKMPJcVeSDhyoJ-
Bovb0OPM9Xj0Atb2ArgvoW_K5ra1ieBsp_tpzLwex40zpX_2LHQXlv0dWl3E1wreDOvcToCbTScDGtnzZEYjOibjSdnz3Yk5jvUXRC6yLruEipwhbJLeur9e
KeR3L6fMQHRpCvym-NiwFaqMaUr1Cp_pATlmF2wl1o6444888OGGyXq
}

